#!/bin/sh

rm -f testbdb.dat

./testbdb testbdb.dat foo bar
./testbdb testbdb.dat foo baz
./testbdb testbdb.dat bar foo
./testbdb testbdb.dat foo
./testbdb testbdb.dat bar
./testbdb testbdb.dat
./testbdb testbdb.dat -foo
./testbdb testbdb.dat

rm -f testbdb.dat
