
// Autogenerated buildcode file - this will change on every make
#define BUILD_CODE "1245473076"
#define BUILD_DATE "Sat Jun 20 10:14:36 IST 2009"
#define BUILD_BOX "Darwin mac 9.7.0 Darwin Kernel Version 9.7.0: Tue Mar 31 22:52:17 PDT 2009; root:xnu-1228.12.14~1/RELEASE_I386 i386"

