
// Autogenerated buildcode file - this will change on every make
#define BUILD_CODE "1492008747"
#define BUILD_DATE "Wed Apr 12 20:22:27 IST 2017"
#define BUILD_BOX "Linux indimail.in 4.10.8-200.fc25.x86_64 #1 SMP Fri Mar 31 13:20:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"

