.LL 8i
.TH hostsync 8
.SH NAME
hostsync \- Synchronize user additions/deletions across cluster

.SH SYNOPSYS
.B hostsync
[
.I options
]
\fB\-d\fR \fIvirtual_domain\fR

.SH DESCRIPTION
.PP
\fBhostsync\fR is a utility which synchronizes user additions and deletions between the
\fBmailstore\fR and the \fBcontrol host\fR in a clustered domain setup. It synchronizes the
table \fBindimail\fR and the \fBhostcntrl\fR table on the control Host. This utility
should be setup in cron(1) to be run every 30 minutes by the system administrator. Only
one instance of \fBhostsync\fR can be run at a time.
.PP
Normally the tables \fBindimail\fR and \fBhostcntrl\fR should be synchronized. But in case
of problems like the control host being down, or the database on the control Host being down,
the tables can get out of sync. \fBhostsync\fR corrects all records that have changed on
the mailstore, but have not got applied on \fBhostcntrl\fR by looking at the pw_uid field
of the table \fBindimail\fR or \fBindibak\fR. Records which are synchronized have the
value 1. Value of pw_uid other than 1 indicate the following

.RS
.nf
.ta 5c 10c
pw_uid Value	Description
------------	-----------

2	User not added to hostcntrl
4	User not deleted from hostcntrl
.fi
.RE

.SH OPTIONS
.PP
.TP
\fB\-v\fR
Sets verbose option
.TP
\fB\-d\fR
Name of the clustered virtual domain.

.SH RETURN VALUES
0 for success, 1 for any failure.

.SH "SEE ALSO"
vadduser(1), vdeluser(1)
