.LL 8i
.TH resetquota 8
.SH NAME
resetquota \- resets/corrects maildirquota for a Maildir

.SH SYNOPSYS
.B resetquota
[
.I options
]
.I Maildir

.SH DESCRIPTION
\fBresetquota\fR sets/corrects maildir quota for a Maildir. Without the \fB\-q\fR option,
resetquota calculates the disk usage for Maildir. It is usually used in two situations.

.nr step 1 1
.IP \n[step] 3
For correcting the disk usage used by a Maildir. 
.IP \n+[step]
For setting maildir quota specification for a Maildir

.SH OPTIONS
.PP
.TP
\fB\-v\fR
Sets verbose operation
.TP
\fB\-u\fR \fIusername\fR
Use username for setting the ownership of the file.
.TP
\fB\-g\fR \fIgroup\fR
Use group for setting group permission on the file.
.TP
\fB\-q\fR \fIquota_spec\fR
Sets Maildir specification for the Maildir (See maildirquota(1)).
.TP
\fB\-p\fR \fIperm\fR
Sets permission given by perm on the file.
.TP
\fIMaildir\fR
The full path of a Maildir.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
vsetuserquota(1), vmoduser(1)
