.LL 8i
.TH vrenamedomain 1
.SH NAME
vrenamedomain \- rename a virtual domain or an alias_domain to a new name

.SH SYNOPSYS
.B vrenamedomain
.I old_domain_name
.I new_domain_name

.SH DESCRIPTION
.B vrenamedomain
renames a virtual_domain or an alias domain to a new name. In case of an alias domain,
it adds \fInew_domain_name\fR as a new alias domain and deletes the old alias
domain \fIold_domain_name\fR. \fBvrenamedomain\fR has setuid bit set and runs as root.
In case of a real domain, it does the following

.nr step 1 1
.IP \n[step] 3
renames the domain directory.
.IP \n+[step]
renames entries having \fIold_domain_name\fR to \fInew_domain_name\fR in the following tables.
\fIindimail\fR, \fIindibak\fR, \fIvalias\fR \fIdir_control\fR, and filesystem specific
\fIdir_control\fR tables, \fIlastauth\fR, \fIsmtp_port\fR, \fIuserquota\fR
.IP \n+[step]
adds the entry for \fInew_domain_name\fR in qmail's assign file.
.IP \n+[step]
deletes the entry for \fIold_domain_name\fR in qmail's assign file.
.IP \n+[step]
creates domain directories in the BASE_PATH for A2E, F2K, L2P, Q2S, T2Zsym.
.IP \n+[step]
runs \fBqmail-newu\fR to recreate the assign cdb file.
.IP \n+[step]
relinks all alias domains aliased to \fIold_domain_name\fR to \fInew_domain_name\fR.
.IP \n+[step]
creates a file .domain_rename in the new_domain_name's domain directory. If this file is
present and a user logs in through IMAP4 or POP3, the file .domain is recreated during the
login process also. This ensures that when a user logs in, the .domain file contains the
correct domain name.
.IP \n+[step]
recreates .domain file in user's Maildir to with new_domain_name as the entry. 
.IP \n+[step]
deletes the file .domain_rename when .domain file has been recreated for all the users.

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvrenamedomain\fR executes the program defined by
the POST_HANDLE environment variable, passing \fIold_domain_name\fR and \fInew_domain_name\fR as
parameters. If POST_HANDLE is not defined, the program/script INDIMAIL/libexec/vrenamedomain
will be executed with \fIold_domain_name\fR and \fInew_domain_name\fR as parameters.

.SH OPTIONS
.PP
.TP
\fIold_domain_name\fR
Name of an existing domain which is to be renamed.
.TP
\fInew_domain_name\fR
Name of a non-existing domain which needs to be given to old_domain_name

.SH RETURN VALUES
0 for success, 1 for any failure.

.SH "SEE ALSO"
vadddomain(1), vdeldomain(1), vdominfo(1), vaddaliasdomain(1),
valias(1), vgroup(1), vadduser(1), vdelivermail(8), vreorg(8)
