#!/bin/sh
#
# This script prepares artifacts that can be downloaded for openSUSE build service
# It creates name.tar.gz, debian.tar.gz and name.spec
#
set -e
if [ $# -lt 1 ] ; then
	echo "USAGE: prepare_obs name" 1>&2
	exit 1
fi
name=$1
if [ $# -eq 2 ] ; then
	type=$2
else
	type=0
fi
ver=$(cat conf-version)
if [ -z "$ver" ] ; then
	exit 1
fi
if [ $type -eq 1 ] ; then
	/bin/rm -f ../$name.spec ../$name-$ver.tar.gz ../debian.tar.gz
fi
if [ ! -f ./configure -o ! -f ./Makefile ] ; then
  ./default.configure
fi

# Create spec file
if [ ! -f ./$name.spec ] ; then
  make $name.spec
fi
mkdir -p $HOME/stage

# Create debian.tar.gz
make debian/Makefile
make -C debian
cp debian/debian.tar.gz $HOME/stage
cp $name.spec $HOME/stage
cp debian/*.dsc $HOME/stage
if [ -f $name-rpmlintrc ] ; then
	cp $name-rpmlintrc $HOME/stage
fi

make -C debian clean
make clean
cp -rpf . $HOME/stage/$name-$ver

# change cwd to staging directory
cd $HOME/stage

#remove debian directory
/bin/rm -rf $name-$ver/debian
tar cfz $name-$ver.tar.gz $name-$ver
status=$?
cd $HOME/stage
echo STAGE=$HOME/stage
/bin/ls -l 
exit $?
