.TH dbinfo 8
.SH NAME
dbinfo \- Dbinfo Structure Administration

.SH SYNOPSYS
.PP
\fBdbinfo \fB\-i\fR \fB\-S\fR \fIMySQL_server\fR  \fB\-p\fR \fIport\fR \fB\-D\fR \fIdatabase\fR \fB\-U\fR \fIuser\fR \fB\-P\fR \fIpassword\fR  [\fB\-c\fR] \fB\-d\fR \fIdomain\fR \fB\-m\fR \fImdahost\fR \fIfilename\fR
.PP
\fBdbinfo \fB\-u\fR \fB\-S\fR \fIMySQL_server\fR [\fB\-p\fR \fIport\fR \fB\-D\fR \fIdatabase\fR \fB\-U\fR \fIuser\fR \fB\-P\fR \fIpassword\fR] [\fB\-c\fR] \fB\-d\fR \fIdomain\fR \fB\-m\fR \fImdahost\fR \fIfilename\fR
.PP
\fBdbinfo \fB\-r\fR \fB\-d\fR \fIdomain\fR \fB\-m\fR \fImdahost\fR \fIfilename\fR
.PP
\fBdbinfo \fB\-s\fR [\fB\-m\fR \fImdahost\fR] \fIfilename\fR
.PP
\fBdbinfo \fB\-e\fR

.SH DESCRIPTION
\fBdbinfo(8)\fR is a utility for administering the \fIdbinfo\fR structure maintained in MySQL(1). This
structure holds information about all MySQL databases corresponding to all mailstores comprising
a clustered domain. A clustered domain allows IndiMail to distribute users in a domain across
multiple servers called mailstores. These mailstores can be located anywhere geographically on
the network. Each mailstore requires its own local MySQL database to store its local users. The
\fIdbinfo\fR structure helps IndiMail to connect to the MySQL database of any given mailstore.

.PP
The above five different forms of usage allows you to add, modify, delete and display the
\fIdbinfo\fR structure. With the '-e' option, the \fBEDITOR\fR environment variable is used to edit the
Mail Cluster Definition file. For reliability, this structure is maintained in MySQL as well
as a file defined by the MCDFILE environment variable (defaults to \fICONTROLDIR/mcdinfo\fR). On
updation of the \fIdbinfo\fR structure, the entries in the file is synchronized with the entries in
MySQL table \fIdbinfo\fR. In addition to the MySQL table \fIdbinfo\fR, \fBdbinfo(8)\fR also uses
the  qmail assign file (\fIINDIMAIL/users/assign\fR) to find domains not listed in the \fIdbinfo\fR
table. Domains not listed in \Idbinfo\fR table are assumed to be non-clustered domains. The
\fIdbinfo\fR structure for this domains is created automatically using the environment variables
\fBMYSQL_HOST\fR, \fBMYSQL_USER\fR, \fBMYSQL_PASSWD\fR, \fBMYSQL_DATABASE\fR, \fBMYSQL_VPORT\fR
(If \fBMYSQL_HOST\fR is not defined, the control file \fImysql\.host\fR is used).
.PP
The \fIdbinfo\fR structure holds the following parameters

 - MySQL Server IP addresses
 - MySQL TCP/IP port
 - MySQL database which will contain IndiMail's database.
 - Username to access the MySQL database
 - Password for the Username
 - Domain Name which will be served by the MySQL database
 - Mail Store IP address.
 - Optional Cluster flag indicating that the mail setup is part
   of a mail cluster. A clustered domain is a domain extended across multiple servers.
 - Filename pointing to the path of the Mail Cluster Definition File.

The option '-s' in \fBdbinfo(8)\fR displays the status of all MySQL servers used by IndiMail, listed
in the MCD file. If MCD filename is not given on the command line, the environment variable
\fBMCDFILE\fR is used. If environment variable is not set, the static definition of MCDFILE in
indimail.h is used. The information displayed is as follows.

.SH OPTIONS
.TP
\fB\-v\fR
Sets Verbose operation
.TP
\fB\-i\fR
Insert \fIdbinfo\fR Entry. All \fBdbinfo(8)\fR parameters are mandatory for this operation
.TP
\fB\-u\fR
Update \fIdbinfo\fR Entry. With this option the MySQL parameters pertaining to a mdahost serving a domain can be modified.
.TP
\fB\-r\fR
Remove \fIdbinfo\fR Entry
.TP
\fB\-s\fR
Select \fIdbinfo\fR Entries
.TP
\fB\-d\fR \fIdomain\fR
Domain Name
.TP
\fB\-c\fR
Sets the Domain for Clustered operation.
.TP
\fB\-S\fR \fIIP\fR
MySQL Server IP
.TP
\fB\-p\fR \fIport\fR
MySQL TCP/IP Port
.TP
\fB\-D\fR \fIdatabase\fR
MySQL Database Name
.TP
\fB\-U\fR \fIuser\fR
MySQL User Name
.TP
\fB\-P\fR \fIpassword\fR
MySQL Password
.TP
\fB\-m\fR \fImailstoreIP\fR
Mail Store IP
.TP
\fB\-e\fR
Edit Dbinfo using vi
.TP
\fIfilename\fR
Name of a file containing MySQL, MDA configuration for IndiMail

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
vhostid(8), vsmtp(8), ipchange(8), hostcntrl(8)
