.TH vdelivermail 8
.SH NAME
vdelivermail \- deliver mails to users in a virtual domain

.SH SYNOPSYS
\fBvdelivermail\fR [\fB""\fR] [\fIdefault account\fR]

.SH DESCRIPTION
.PP
\fBvdelivermail\fR delivers mails to users created (by \fBvadddomain(1)\fR) in a virtual domain.
\fBvdelivermail\fR is called by \fBqmail-local\fR through an instruction in the
file .\fIqmail\fR-\fIdefault\fR present in INDIMAIL/domains directory.
\fBvdelivermail\fR is the MDA for IndiMail. Along with a wrapper postdel, \fBvdelivermail\fR
can also be used as the MDA for postfix. \fBqmail-local\fR sets the environment variables
\fBEXT\fR and \fBHOST\fR. This is used by \fBvdelivermail\fR to set the
user and the domain component of the email address. For postfix, these two environment
variables are set by postdel. If the username is quoted, the quotes are removed. The
user@domain is then searched in the authentication database. If there are any system problems
due to which \fBvdelivermail\fR is unable to locate the user, it exits 111 and the mail gets
deferred. \fBvdelivermail\fR will exit 100 in case the user is not found, locked/overquota,
address is looping, or if vdelivermail is not called correctly. Bounces can be discarded if
you set the environment variable \fBDISCARD_BOUNCE\fR.
If the domain is a clustered domain, \fBvdelivermail\fR attempts
to find the mailstore for the user. If the mailstore is local, it delivers the mail locally.
If the mailstore is a remote server, it invokes \fBqmail-remote(8)\fR to deliver the mail.
If the environment variable QMAIL_EXT is defined, \fBvdelivermail\fR attempts to locate the
username based on qmail Extensions.
.PP
If the user is not found or user is found but is inactive, action taken is as per delivery
instruction (third argument to \fBvdelivermail\fR). If the user is active, \fBvdelivermail\fR
checks for any forward delivery (including aliases) and delivers appropriately. While
delivering, \fBvdelivermail\fR creates the inbox (Maildir format) if the directories do not
exist. \fBvdelivermail\fR defers the mail if stick bit is set on the Maildir to which the mail
is being delivered.
.PP
\fBvdelivermail\fR adds the following headers on delivery of the mail to a Maildir
.nr step 1 1
.IP \n[step] 3
Delivered-To: specifying the address to which the mail has been delivered
.sp -1
.IP \n+[step]
Return-Path: specifying the sender's email address.
.sp -1
.IP \n+[step]
X-Filter: specifying if the mail has been filtered through vfilter.
.sp -1
.IP \n+[step]
Received: specifying the date and time, the mail was received and delivered.
.PP
\fBvdelivermail\fR looks up the qmail control files blackholedsenders and blackholedpatterns.
If the sender's email address matches an entry in these control files, \fBvdelivermail\fR
discards the mail without bouncing the mail to the sender. A line in these files may be of
the form @host, meaning every address at host. These files are also used by \fBqmail-smtpd\fR
causing SMTP sessions to get blackholed.

blackholedpatterns gives qmail-smtpd the ability to blackhole E-Mails by comparing the sender
address with a REGEX pattern in blackholedpatterns.
Example:

*@earthlink.net
!fred@earthlink.net
[0-9][0-9][0-9][0-9][0-9]@[0-9][0-9][0-9].com
answerme@save*
*%*

blackholedpatterns  file  with  this contents stops all mail from earthlink except from
fred@earthlink.net. It also stops all  mail  with  addresses  like:  12345@123.com  and
answerme@savetrees.com.  Further, any E-Mail with a sender address containing a percent sign (%) is rejected.

.SH Quota Checking
.PP
\fBvdelivermail\fR uses Maildir++ specification. Maildir++ quota relies on maildirsize file
having correct information, so if your users can modify the file in some way (e.g. shell access),
you're relying on the goodwill of your users for the quota to work. As a trade-off between
accuracy and performance quota recalculation happens when the size of maildirsize file reaches
512 bytes or becomes older 43200 seconds. The command \fBvuserinfo(1)\fR also recalculates
the quota.

The maildirsize file in the Maildir root directory contains both the quota limit information
and the current quota status. It contains a header in format:
.EX
 <storage limit in bytes>S,<message count limit>C
.EE
If the size of the mail is within the quota, or if the size of the mail is less than
OVERQUOTA_MAILSIZE (1000 bytes as defined in indimail.h) but would bring the user
overquota, the mail is delivered and the user's current quota usage updated. Else the mail is
bounced back with Over Quota message. Also if INDIMAIL/libexec/overquota.sh exists, the
command is executed with the following arguments

 maildir_path Message_size Current_disk_usage Current_mailcount quota

.PP
The command overquota.sh can be changed by setting the environment variable \fBOVERQUOTA_CMD\fR.
The default behaviour of bouncing mails on overquota can be changed by setting environment
variable \fBHOLDOVERQUOTA\fR or by having a file \fIholdoverquota\fR in the user's homedir.
In this case, the mail will be deferred till the \fIqueuelifetime\fR gets reached. If
\fBHOLDOVERQUOTA\fR is not defined and neither the file \fIholdoverquota\fR is present
\fBvdelivermail\fR (if the user is already above quota) sets the \fBBOUNCE FLAG\fR for the user.
Subsequent deliveries are bounced without any quota checking. Setting of the \fBBOUNCE_FLAG\fR
reduces the load on the server when multiple mails are being sent to an overquota user.
The \fBBOUNCE FLAG\fR is removed only after the user logs in
and clears the mails to reduce the quota usage. Site administrators can customize
Over Quota Bounce messages, by setting environment variables
\fBQUOTAWARN1\fR, \fBQUOTAWARN2\fR ... upto \fBQUOTAWARN10\fR. These variables should be set to
a percentage quota usage for which warning should be sent. In addition to the \fBEXT\fR and
\fBHOST\fR environment variable, \fBRPLINE\fR and \fBDTLINE\fR variables are also used by
\fBvdelivermail\fR to set the value for \fBReturn-Path\fR, \fBDelivered-To\fR lines in the mail
headers. 
.PP
The quota limit for a user can be set by the administrator either in size, number of mails or
combination of both. e.g. 40000,2000S means quota of 40000 Bytes and 2000 mails. Administrator
can use either \fBvsetuserquota\fR or \fBvmoduser\fR programs.
.PP
Additionally per day limit on deliveries per user can be set by specifying the environment
variable \fBMAILCOUNT_LIMIT\fR. This can be set in the qmail-send run file. If the number of
deliveries for a user exceeds this number, the mail is bounced back to the sender with over
quota message.

.SH Date Folder Delivery
.PP
One can use vmoduser(1) to turn on delivery to a date folder. If this option is turned on, emails
can be delivered to a folder based on the current timestamp. This option is useful if you want
to deliver mails based on the year, month, week, etc. vdelivermail(8) uses strftime(3) to process
the date format for the folder. The file folder.dateformat in user's Maildir is used for storing
the date format for the folder.

.SH dot-qmail processing

.PP
Every virtualdomain get's it's own directory under INDIMAIL/domains. qmail's user/assign file
gets an entry for each domain that points qmail-local deliveries into this directory.
Therefore, all normal .qmail file processing works in each virtual domain. .qmail files
just need the user name extension to work, i.e. .qmail-joe for user joe. ezmlm uses .qmail
files for processing, so it will work under IndiMail.
.PP
If no user matches a .qmail file then the .\fIqmail-default\fR file is processed. This file
contains invokation of \fBvdelivermail\fR program with arguments. \fBvdelivermail\fR reads the
authentication database and delivers the mail into the users directory.
The last parameter of \fBvdelivermail\fR determines what \fBvdelivermail\fR does when it does
not find the user. See the section on \fBOptions\fR below.
.PP
In addition to .qmail files, IndiMail has its dot-qmail processing called valias. valias can
be either the file .qmail in the user's home directory or an entry made in MySQL(1) using the
\fBvalias(1)\fR program. You can have multiple delivery lines in .qmail or valias entries in MySQL(1).
vdelivermail will skip processing valias lines, if a line causes exit code of 99 to be returned.

.SH Mail Alerts
\fBvdelivermail\fR sends alerts in the form of UDP packets to a host and port which can be
specified in the following two ways

.nr step 1 1
.IP \n[step] 3
By defining environment variables MAILHOST_ALERT and MAILHOST_PORT.
.sp -1
.IP \n+[step]
By creating a file mailalert.cfg in the control directory. The first line of this file should have the line host x.x.x.x where x.x.x.x is an IP address. The second line of this file should have the line port port_num where port_num is an integer.

.SH Discarding Duplicate Emails
You can discard duplicate emails received within 15 minutes, by setting \fBELIMINATE_DUPS\fR
environment variable. You can change the default time interval of 900 seconds by setting the
\fBDUPLICATE_INTERVAL\fR environment variable in seconds.

.SH OPTIONS
.TP
[\fB""\fR]
Blank double quote for backward compatibility
.TP
[\fIdefault account for delivery\fR]
If email does not match any virtual domain user (determined by \fBEXT\fR and \fBHOST\fR
environment variable, this is the default delivery instructions. This may be one of the four
values given below.
 
.nr step 1 1
.IP \n[step] 3
Full path to a indimail user directory 
.sp -1
.IP \n+[step]
email address to forward email to
.sp -1
.IP \n+[step]
the string \fBbounce-no-mailbox\fR to bounce the email back to the sender.
.sp -1
.IP \n+[step]
the string \fBdelete\fR to delete the email.
.sp -1
.IP \n+[step]
Address in \fBSMTPROUTE\fR format to which \fBvdelivermail\fR should use SMTP to deliver
the mail. e.g.

.EX
indimail.org:192.168.1.1:25
.EE

where indimail.org is the local domain, 192.168.1.1 is the IP address of an SMTP server for
indimail.org and 25 is the SMTP port.
.PP
If IndiMail is configured for hard quotas (default is yes with 5 Meg quota), then the size
of the user's current usage Maildir/new and Maildir/cur directories and other folders
(excluding Trash) are counted and added to \fImaildirsize\fR. \fBvdelivermail\fR recalculates once
\fImaildirsize\fR reaches 512 bytes. This ensures that quota is as accurate as possible even if files
are deleted externally. If the user is over quota the email is bounced back to the user with a
bounce message that can be customized (See the section '\fBQuota Checking\fR' above. If the
message is 1Kbytes or smaller the email will always be delivered. This allows system
administration programs to always get a message through to the user. 

.SH RETURN VALUE
.TP
.IP \[bu] 2
0
if all steps were successful. 
.TP
.IP \[bu] 2
100
for permanent errors. i.e. if user is over quota or bounce-no-mailbox is set and no matching user is found.
.TP
.IP \[bu] 2
111
for all temporary error occurs during mail delivery and without the error, the mail would have got delivered

.SH "SEE ALSO"
vmoduser(1), vsetuserquota(1), vmoddomlimits(1),
qmail-lspawn(8), spawn-filter(8), qmail-local(8),
qmail-remote(8), maildirdeliver(1), ismaildup(1), strftime(3)
