.LL 8i
.TH vaddaliasdomain 1
.SH NAME
vaddaliasdomain - Create an domain aliased to an existing virtual domain

.SH SYNOPSYS
.B vaddaliasdomain
.I new_domain
.I old_domain

.SH DESCRIPTION
.PP
.B vaddaliasdomain
takes an existing virtual domain and links a new domain to all the accounts on the existing virtual domain.
.B vaddaliasdomain
Has setuid bit set and runs with domain's uid.
Carries out the following steps to create an alias domain.

.nr step 1 1
.IP \n[step] 3
Insert into table aliasdomain on the Control Host (if old_domain is clustered).
.IP \n+[step]
Create a symbolic link new_domain linked to old_domain in the domains directory.
.IP \n+[step]
Add entry to qmail assign file.
.IP \n+[step]
Add entry to virtualdomains control file.
.IP \n+[step]
Send SIGHUP to qmail-send.
.IP \n+[step]
Add entry to .aliasdomains in the domains directory for the domain old_domain.

.SH OPTIONS
.PP
.TP
\fInew_domain\fR
The desired name for the new alias domain. \fInew_domain\fR can contain alphanumeric characters besides '-' and '.' . However the first and the last character cannot be '-'.
.TP
\fIold_domain\fR
The name of an existing real domain to which the domain new_domain needs to be aliased.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic message is printed.

.SH "SEE ALSO"
vadddomain(1), vrenamedomain(1), vadduser(1), vdeldomain(1), vdominfo(1)
