.LL 8i
.TH vpasswd 1
.SH NAME
vpasswd \- change passwd for virtual domain user

.SH SYNOPSYS
.B vpasswd
[
.I options
]
.I email_address
[
.I password
] 

.SH DESCRIPTION
\fBvpasswd\fR changes a virtual domain email users password. The program must be run
as root or as the indimail user. It uses \fBcrypt(3)\fR routine to encrypt the password.
You can set the environment variable \fBPASSWORD_HASH\fR to set the encryption method.

.B PASSWORD_HASH
identifies the encryption method used and this then determines how the rest
of the password string is interpreted.
The following values of
.B PASSWORD_HASH
are supported:
.RS
.TS
l l.
PASSWORD_HASH | Method
_
0             | DES
1             | MD5
2             | SHA-256
3             | SHA-512
.TE

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvpasswd\fR executes the program defined by
the POST_HANDLE environment variable, passing \fIemail_address\fR as a parameter. If POST_HANDLE
is not defined, the program/script INDIMAIL/libexec/vpasswd will be executed with \fIemail_address\fR
as a parameter.

.SH OPTIONS
.TP
\fB\-e\fR
Set the encrypted Password field
This options disables the internal encryption routine which encryptes the password provided
on the command line. This option sets the encrypted password field exactly as given on the
command line without any encryption. It expects you to give a standard encrypted password.
However, you can use this to set plaintext password for CRAM-MD5 authentication.

.TP
\fB\-a\fR
(use apop, pop is default)

.TP
\fB\-r\fR
Generate a random password

.TP
\fB\-v\fR
Set verbose mode.

.TP
\fIemail_address\fR
username including the domain component

.TP
[\fIpassword\fR]
Set the password on the command line. If the password is not supplied on the command line then user is prompted for the password. The password must be entered correctly twice in order to be accepted. 

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic message is printed.

.SH "SEE ALSO"
vmoduser(1), vadduser(1), vmoduser(1)
