.TH proxyimap 8
.SH NAME
.PP
proxyimap \- IMAP Proxy
.PP
proxypop3 \- POP3 Proxy
.PP
vproxy \- Generic Proxy

.SH SYNOPSYS
.PP
\fBproxyimap\fR \fIpath_of_imapd\fR \fIMaildir\fR
.PP
\fBproxypop3\fR \fIpath_of_pop3d\fR \fIMaildir\fR
.PP
\fBvproxy\fR \fIhost\fR \fIport\fR [\fIlogin_sequence\fR]

.SH DESCRIPTION
\fBproxyimap\fR and \fBproxypop3\fR act as proxy for IMAP4 and POP3 protocol in a clustered
domain where users homedir lie on multiple hosts. \fBproxyimap\fR and \fBproxypop3\fR correctly
locates the user's mailstore and make a IMAP4 or POP3 connection to the user's mailstore host.
This facilitates to have a single IP address or DNS entry for all hosts comprising a clustered
domain. The proxy works by passing all data from the file descriptor 0 to the socket connection
(IMAP4 or POP3). All data which comes from the socket is is passed to file descriptor 1.
The recommended method for using \fBproxyimap\fR and \fBproxypop3\fR is through tcpserver(1).
It is recommended to use a cdb files (-x option in tcpserver) tcp.imap for \fBproxyimap\fR and
tcp.pop3 for \fBproxypop3\fR. For enabling unrestricted IMAP from a host, set environment
variable POP3CLIENT and IMAPCLIENT in cdb file used by the respective tcpservers (compiled
by tcprules). e.g. To allow unrestricted IMAP/POP3 access from the host with IP w.x.y.z, use
tcprules to compile the following.

.EX
tcp.imap
w.x.y.z:allow,IMAPCLIENT=""

tcp.pop3
w.x.y.z:allow,POP3CLIENT=""
.EE

If you set the \fBAUTOADDUSER\fR environment variable, users can be automatically added by
using the \fBadminclient(8)\fR protocol to connect to \fBindisrvr(8)\fR. The auto provisioning
happens only if the user does not exist in IndiMail's authentication database. If you set the
\fBADDUSERCMD\fR environment variable to a program, the program will be run with the password
passed as an argument.

Following environment variables are needed by these two proxies to start up

.TP
\fBTCPREMOTEIP\fR
IP address of remote host.
.TP
\fBTCPLOCALPORT\fR
Local TCP/IP Port on which proxyimap, proxypop3 is running.
.TP
\fBDESTPORT\fR
Of the form protocol:port where protocol is either imap or pop3. Port is the TCP/IP port on
the remote host offering the imap or pop3 protocol.
.PP
Currently proxyimap and proxypop3 allow 5 bad login attempts, after which the connection is
terminated.
.PP
It is also possible to set data timeout for the proxies through the environment variable
DATA_TIMEOUT. The two proxies will terminate if it finds no data coming from either the
client or the actual imap/pop3 server within the time in seconds specified by DATA_TIMEOUT.
.PP
vproxy is a generic proxy which passes data from file descriptor 0 to a TCP/IP connection and
data from the TCP/IP connection to file descriptor 1. The TCP/IP connection is specified by
\fIhost\fR and \fIport\fR parameters. login_sequence specifies initial data (if needed), that
needs to be supplied to the application listening on port port on host host.

.SH OPTIONS
.TP
\fIpath_of_imapd\fR
Specifies the full path of IndiMail's imapd executable
.TP
\fIpath_of_pop3d\fR
Specifies the full path of IndiMail's pop3d executable
.TP
\fIhost\fR
Host Name (Host Name or IP address for which the proxy service is needed.
.TP
\fIport\fR
TCP/IP Port on host for which proxy services is needed.
.TP
\fIlogin_sequence\fR
Initial data needed by some servers to start up properly. e.g. POP3 service will require USER
username and PASS passwd sequence to login.

.SH RETURN VALUE
0 for success and 1 for failure in which case all diagnostics are printed on stdout.

.SH "SEE ALSO"
authindi(8), adminclient(8), indisrvr(8)
