.TH vdeloldusers 8
.SH NAME
vdeloldusers \- remove inactive users

.SH SYNOPSYS
.B vdeloldusers [\fIoptions\fR]

.SH DESCRIPTION
.PP
\fBvdeloldusers\fR is a utility to delete inactive users or mark users who have not logged
in for more than a specified number of days. When marking users as inactive, \fBvdeloldusers\fR
moves the user records from the active authentication table indimail to the inactive
authentication table indibak. For active users, it deletes unread mails older than
\fIage_in_days\fR specified by the \fB\-u\fR option. Unread mails are deleted only from
the inbox.

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose mode while vdeloldusers is operating
.TP
\fB\-d\fR \fIdomain_name\fR
virtual domain for which vdeloldusers is to be run.
.TP
\fB\-a\fR \fIage_in_days\fR
Delete accounts older than this date. Default is 2 months or 60 days)
.TP
\fB\-u\fR \fIage_in_days\fR
Delete mails older than this date. Default is 1 months or 30 days. Specifying the age as -1 disables this option.
.TP
\fB\-t\fR \fIage_in_days \fR
Deletes trash for users who have logged in for the last 'age_in_days' days.
.TP
\fB\-f\fR
Make vdeloldusers run faster by skipping stat() system call done on Maildir/cur (for ensuring while deleting a user, if a user becomes active). By specifying this option you run the risk of deleting inactive users who may become active while vdeloldusers is running.
.TP
\fB\-p\fR
Purge entry from Database. The user, home directories and all files pertaining to the user are removed from the system. All records in IndiMail tables are additionally removed.
.TP
\fB\-i\fR
Mark the user as Inactive. The user's authentication records are moved from the active table indimail to to the inactive table indibak. Additionally, INACT record is set for the user in the lastauth table.
.TP
\fB\-r\fR
Report only. This option causes vdeloldusers to display the actions it would take but does not actually take the action.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic message is printed.

.SH "SEE ALSO"
vdeluser(8)
