.TH 822header 1
.SH NAME
822header \- print the header of a mail message
.SH SYNOPSIS
.B 822header
[
-X
.I field
-I
.I field
]
where
.I field
is an email header name
.SH DESCRIPTION
.B 822header
reads an 822-format mail message from its standard input,
and prints the header of the message.

Under 822,
the header is terminated by the end of the message
or by a blank line.
.B 822header
also ends the header
if it sees a line that cannot be part of a valid header field. If neither -X or -I option
are given,
.B 822header
prints all the header fields in the message.

The -X option causes
.B 822header
to exclude the specified field. Multiple -X options
can be given.

The -I option causes
.B 822header
to print only the specified field. Multiple -I options
can be given.

Note that the UUCP-style
.B From_
line placed before a message in an
.B mbox
file is not part of the message.
.SH "SEE ALSO"
822field(1), mbox(5)
