.TH cdbstats 1
.SH NAME
.PP
cdbstats \- read cdb on stdin and print statistics
.PP
cdbtest \- read cdb on stdin and test it.

.SH DESCRIPTION
\fBcdbstats\fR reads a (seekable) constant database from its standard input and prints a
few statistics:

.IP \[bu] 2
records is the number of records in the database,
.sp -1
.IP \[bu]
d0 is the number of records at distance 0 from their hash,
.sp -1
.IP \[bu]
d1 is the number of records at distance 1 from their hash, etc. 

.PP
\fBcdbtest\fR reads a (seekable) constant database from its standard input. For each record in
the database, it double-checks that the record can be found by its key. It prints tallies in
several categories:

.IP \[bu] 2
found is the number of records found correctly by their keys.
.sp -1
.IP \[bu]
different record is the number of records where a different record was found with the same key. This should not happen unless the database has multiple records with the same key.
.sp -1
.IP \[bu]
bad length is the number of records found but with the wrong data length. This should never happen.
.sp -1
.IP \[bu]
not found is the number of records not found. This should never happen.
.sp -1
.IP \[bu]
untested is the number of records with keys longer than 1024 bytes. cdbtest doesn't bother testing these records. 

.SH SEE ALSO
cdbmake(1),
cdbdump(1),
cdbget(1)
