.TH condtmaildir 1
.SH NAME
condtmaildir - Feed message to program and perhaps store message
.SH SYNOPSIS
in
.BR .qmail :
.B |condtmaildir
.I dir
.I program
[
.I arg ...
]
where 
.I dir
is a Maildir-format directory and 
.I program
is one or more arguments specifying a program to run for each message.
.SH DESCRIPTION
.B condtmaildir
feeds each new mail message to
.I program
with the given arguments.
If
.I program
exits 0,
.B condtmaildir
writes the email message to
.IR dir ,
and then exits 99, so further commands in
.B .qmail
are ignored.

If
.I program
exits 111,
.B condtmaildir
exits 111,
so delivery will be retried later.

If
.I program
exits anything else
(or does not exist),
.B condtmaildir
exits 0,
so the rest of
.B .qmail
will be processed as usual.

If it encounters a permanent error in handling a message, 
.B condtomaildir
exits 100. If it encounters a temporary error in handling a message, 
.B condtomaildir
exits 111.

If
.B condtomaildir
encounters a permanent error attempting to run prog, it exits 100.  If 
.B condtomaildir
encounters a temporary error in attempting to run prog, it exits 111. 

Note that
it is not safe for
.I program
to fork a child that
reads the message in the background.

.B WARNING:
If you create a
.B .qmail
file to enable
.BR condtmaildir ,
make sure to also add a line specifying delivery to your normal mailbox.
.SH "SEE ALSO"
bouncesaying(1),
condredirect(1),
filterto(1),
except(1),
dot-qmail(5),
qmail-command(8),
qmail-queue(8)
