.TH dkim 8
.SH NAME
dkim \- exercise the domainkeys library
.SH SYNOPSIS
.B dkim
.I opts

.I opts
is a series of getopt-style options.

.SH DESCRIPTION
.B dkim
exercises the dkim library. Both signing and verification merely print out the DKIM header.
They do not keep a copy of the input file. You will need to do something like this:

.EX
 (./dkim -s QMAILHOME/control/domainkeys/dog </tmp/testmsg; cat /tmp/testmsg)\
 | ./dkim -v
.EE

.SH OPTIONS
.TP
-s \fIkey\fR
.I key
is a path to a file containing a PEM-format private key. The base name of
the file is  used  as  the  selector. Reads the email message on stdin. Prints the
.B DKIM-Signature
header.

.TP
-v
Verifies the email on stdin. Exits with a non-zero exit code and a message to
stderr if there was a problem with the signature. Always prints a
.B DKIM-Status:
header to stdout. This option requires the \fBs\fR._domainkey.\fBd\fR txt record in
dns (public key). Here \fBs\fR is the selector and \fBd\fR is the domain

.EX
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=gamma; h=DomainKey-Status:
To:Subject:Message-Id:Date:From; bh=IarZI4AMTl/vy1jTbPphDcOl4YNS
POk7Vn0tDdgkbV4=; b=VpIS6XNOLU2WWWlsYGeLB3wMbyFQwkg7F0hr7blu1W8f
0RRtuyw9igFwY7q7FNaPVlfZ0cfLPh0mRrlExu4V7uQaTP8nnnHO2cAokYbncGS5
ADU9NbAcpDh+E2YQwzCX
.EE

.TP
-l
include body length tag
.TP
-q
include query method tag
.TP
-t
include a timestamp tag
.TP
-h
include Copied Headers
.TP
-p \fIssp\fR | \fIadsp\fR
0 - disable practice (default), 1- SSP, or 2 - ADSP verification
.TP
-b \fIstandard\fR
1 - allman, 2 - ietf or 3 - both
.TP
-c \fIcanonicalization\fR
r for relaxed [DEFAULT], s - simple, t relaxed/simple, u - simple/relaxed
-d \fIdomain\fR
the domain tag, if not provided, determined from the sender/from header
.TP
-i \fIidentity\fR
the identity, if not provided it will not be included
.TP
-x \fIexpire_time\fR
the expire time in seconds since epoch ( DEFAULT = current time + 604800). If set to - then it will not be included
.TP
-z \fIhash\fR
1 for sha1, 2 for sha256, 3 for both
.TP
-y \fIselector\fR
the selector tag DEFAULT=private
.TP
-s \fIprivkeyfile\fR
sign the message using the private key in privkeyfile
.TP
-H
this help

.SH "SEE ALSO"
dktest(8),
qmail-dk(8),
qmail-dkim(8),
dknewkey(8),
rfc-4870(5),
rfc-4871(5)
