.TH filterto 1
.SH NAME
filterto \- perhaps redirect mail to another address
.SH SYNOPSIS
in
.BR .qmail :
.B | filterto
.I address
.I prog
[
.I arg ...
]
where address is an email address, and prog is one or more arguments specifying a 
program to run for each message.
.SH DESCRIPTION
.B filterto
feeds each new mail message to
.I program
with the given arguments.
If
.I prog
exits 0,
.B filterto
forwards the standard output from
.I prog
to
.IR address ,
and then exits 99,
so further commands in
.B .qmail
are ignored.

If
.I program
exits 111,
.B filterto
exits 111,
so delivery will be retried later.

If
.I program
exits anything else
(or does not exist),
.B filterto
exits 0,
so the rest of
.B .qmail
will be processed as usual.

Note that
it is not safe for
.I program
to fork a child that
reads the message in the background.

.B WARNING:
If you create a
.B .qmail
file to enable
.BR filterto ,
make sure to also add a line specifying delivery to your normal mailbox.

\fBfilterto\fR uses environment modified according to files in 
@controldir@/defaultqueue directory.

.SH "SEE ALSO"
bouncesaying(1),
condredirect(1),
except(1),
dot-qmail(5),
qmail-command(8),
qmail-queue(8)
