.TH mess822 3
.SH NAME
mess822 \- parse a mail message header in RFC 822 format
.SH SYNTAX
.B #include <mess822.h>

int \fBmess822_begin\fP(&\fIh\fR,\fIa\fR);
.br
int \fBmess822_line\fP(&\fIh\fR,&\fIline\fR);
.br
int \fBmess822_end\fP(&\fIh\fR);

int \fBmess822_ok\fP(&\fIline\fR);

stralloc \fIline\fR;
.br
mess822_action \fIa\fR[];
.br
mess822_header \fIh\fR = MESS822_HEADER;
.SH DESCRIPTION
To be filled in.
.SH "SEE ALSO"
mess822_addr(3),
mess822_date(3),
mess822_fold(3),
mess822_quote(3),
mess822_token(3),
mess822_when(3)
