.TH mess822_when 3
.SH NAME
mess822_when \- extract a timestamp from an RFC 822 field
.SH SYNTAX
.B #include <mess822.h>

int \fBmess822_when\fP(&\fIout\fR,\fIin\fR);

mess822_time \fIout\fR;
.br
char *\fIin\fR;
.SH DESCRIPTION
To be filled in.
.SH "SEE ALSO"
mess822(3),
mess822_date(3),
mess822_token(3)
