.TH multitail 1
.SH NAME
multitail \- watch output sent to a file
.SH SYNOPSIS
.B multitail
[
.B \-E
] [
.B \-e
]
.I filename
.SH DESCRIPTION
.B multitail
opens the named file for reading, and outputs data appended to the
file as it grows.
If a new file is put in place of the original filename, the original
file is closed and the file is reopened.
.SH OPTIONS
.TP
.B \-E
Seek to the end of file before producing any output from the original
file.
This is the default.
.TP
.B \-e
Do not seek to the end of file before producing any output.
This will cause the entire file to be output.
.SH SEE ALSO
multilog, tail(1)
.SH NOTES
This program is useful for watching output written to the
.I current
log file produced by
.BR multitail .
.P
.B multitail
is very similar to GNU
.BR tail .
An equivalent command would be:

.EX
tail -n -0 --follow=name FILENAME
.EE
.SH RESTRICTIONS
.B multitail
can't count lines or bytes from the beginning or end of the file.
If you need these features, download and install GNU textutils.
