.TH multipipe 1
.SH NAME
multipipe \- supervise an pipeline of commands
.SH SYNOPSIS
.B multipipe
.I [ directory ]
.SH DESCRIPTION
.B multipipe
starts one supervise process for each subdirectory of the current
directory.
.B multipipe
skips subdirectory names starting with dots.
Each supervised processes is piped a copy of standard input sent to
.BR multipipe .
.P
Every five seconds,
.B multipipe
checks for subdirectories again.
If it sees a new subdirectory, it starts a new supervise process.
If a subdirectory is removed, it closes the pipe to that supervise
process.
Directory named
.I supervise
or with names starting with a period are ignored.
.P
If
.B multipipe
is given a command-line argument, it switches to that directory when it
starts.
.P
If
.B multipipe
is sent either the
.IR INT ,
.IR QUIT ,
or the
.I TERM
signal, or it reaches end of file on standard input, it runs
.B svc -dx
on each command to shut it down, and waits for it to exit.
.SH RETURN VALUE
Exits 0 when all the commands are shut down.
.SH SEE ALSO
supervise, svscan
