#!/usr/bin/perl

($showheader)=@ARGV;
#print $showheader;
$counter="1";
while ($line=<STDIN>){
	chomp ($line);
	$cmd1="grep -i from: < /bin/cat ".$line;
	$cmd2="grep -i to: < /bin/cat ".$line;
	$cmd3="grep -i date: < /bin/cat ".$line;
	$cmd="/bin/cat ".$line." | 822header";
	print "\n";
	print $counter.". Message ".$line." :\n\n";
	print `$cmd1`;
	print `$cmd2`;
	print `$cmd3`;
	if ($showheader eq '-h'){
		print "\nMessage header is :\n\n";
		print `$cmd`;
	}
	$counter=$counter+1;
}
