.TH qmail-queue 8
.SH NAME
qmail-queue \- queue a mail message for delivery
.SH SYNOPSIS
.B qmail-queue
.SH DESCRIPTION
.B qmail-queue
reads a mail message from descriptor 0.
It then reads envelope information from descriptor 1.
It places the message into the outgoing queue
for future delivery by
.BR qmail-send .
The default outgoing queue is QMAILHOME/queue. This can be changed by setting environment variable QUEUEDIR to
point to a path having a valid qmail queue.

The envelope information is an envelope sender address followed by a list of envelope recipient addresses.
The sender address is preceded by the letter F and terminated by a 0 byte.
Each recipient address is preceded by the letter T and terminated by a 0 byte.
The list of recipient addresses is terminated by an extra 0 byte. If
.B qmail-queue
sees end-of-file before the extra 0 byte, it aborts without placing the message into the queue.
If \fBUSE_FSYNC\fR environment variable is defined \fBqmail-queue\fR uses fsync(2) to sync the message file in
\fIqueue/mess\fR and the envelope in \fIqueue/intd\fR file as well. After creating a link
to the envelope in \fIqueue/todo\fR to \fIqueue/intd\fR, qmail-queue syncs the directory
using the following two methods.
.IP \[bu] 2
.I BSD Style Synchronous Directory
This gets enabled if \fBUSE_SYNCDIR\fR environment variable is defined
.IP \[bu]
.I Using FSYNC
\fBqmail-queue\fR opens the file in \fBqueue/todo\fR and uses the fsync(2) call. This
hack forces directory syncing.
.LP

If the control file
.B extraqueue
exists, its content is added to recipient list. The environment variable
.B EXTRAQUEUE
also does the same thing. The value of the environment variable overrides the
value in the control file.

If the control file
.I originipfield
is set or if the environment variable 
.B ORIGINIPFIELD
is set, a "X-Originating-IP" header will be added to every relayed mail.

If the environment variable 
.B ORIGINIPFIELD
is set,  it overrides the control file 
.IR originipfield .

If the control file
.B quarantine
exists, recipient list is replaced with its content. The environment variable
.B QUARANTINE
also does the same thing. The value of the environment variable overrides the
value in the control file. Additionally, the header \fBX-Quarantine-ID\fR containing the
list of original recipient list is added.

If the control file
.B removeheaders
exists, \fBqmail-queue\fR removes all headers listed in the control file from the mail message
on descriptor 0 before writing it to the disk. The environment variable \fBREMOVEHEADERS\fR can
be set to use a different name for this control file.

Every envelope recipient address should contain a username, an @ sign, and a fully qualified domain name.

.B qmail-queue
always adds a
.B Received
line to the top of the message.
.B qmail-queue
keeps a copy of the
.B QQEH
environment variable (if set), and passes it into the queue.
.B qmail-local
and
.B qmail-remote
will prepend it to the headers of the email when it is delivered. If the control file
.B envheaders
exists, \fBqmail-queue\fR passes all headers listed in the control file to the queue along
with the value.
.B qmail-local
and
.B qmail-remote
will set environment variables corresponding to the headers with the values.
An optional length, separated by a ':', can be appended to the name
of the header. If length is specified, the environment variable will be set only if the actual
length of the header value is less than or equal to this value. The environment variable
\fBENVHEADERS\fR can be set to use a different name for this control file. If the control file
.B logheaders
exists, \fBqmail-queue\fR writes all headers (along with values) listed in the control file to
file descriptor defined by \fBLOGHEADERFD\fR environment variable. The file descriptor needs to be
open for write. You can open the file descriptor in the startup scripts for
.BR qmail-smtpd,
for example.
.EX

 touch /tmp/header.log
 exec 45 >/tmp/header.log
 LOGHEADERFD=45
.EE

If the file descriptor is not open, logging of header will be silently ignored. Logging of headers
can be useful for debugging or logging specific headers in log files. The environment
variable \fBLOGHEADERS\fR can be set to use a different name for this control file.

.B qmail-queue
does not inspect the message and does not enforce any restrictions on its contents.
However, the recipients probably expect to see a proper header, as described in
.BR qmail-header(5) .

Programs included with qmail which invoke
.B qmail-queue
will invoke the contents of
.B $QMAILQUEUE
instead, if that environment variable is set.
.SH "FILESYSTEM RESTRICTIONS"
.B qmail-queue
imposes two constraints on the queue structure:
each
.B mess
subdirectory must be in the same filesystem as the
.B pid
directory; and each
.B todo
subdirectory must be in the same filesystem as the
.B intd
directory.

.SH "Qmail High Performance Scanner Interface"
A large fraction of today's emails is infected by a virus
or a worm. It is necessary to recognize those malicious
emails as soon as possible -- already in the DATA phase
of the SMTP conversation and to reject them.

Typically, this is facilitated my means of
.BR AMaViS , 
.BR qmail-scanner ,
or
.B qscanq
which facilitate as "wrapper" of
the original qmail-queue program invoked by means 
of QMAILQUEUE path (
.BR qmail-multi ).

However -- in case of virus attacks -- those umbrella
programs become part of the problem itself due to their
resource requirements.

Today's virus scanner -- in particluar Clam AV -- work in 
resource efficient client/server mode (clamd/clamdscan)
and include the feature to detect virii/worms in the base64
encoded data stream. Thus, there is no necessity to call
additional programs (like reformime or ripmime) except 
for the virus scanner itself.

The QHPSI extension for qmail-queue allows to call an arbitary virus scanner directly,
scanning the incoming data-stream on STDIN or it allows plugins to be loaded from
the QMAILHOME/plugins directory. This directory can be changed by defining
\fBPLUGINDIR\fR environment variable. QHPSI can be advised to pass
multiple arguments to the virus scanner for customization. To run external scanner
or load scanner plugins, \fBqmail-queue\fR calls \fBqhpsi\fR, a program setuid to \fIqscand\fR.
By default, \fBqhpsi\fR looks for the symbol \fIvirusscan\fR to invoke the scanner.
The symbol can be changed by setting the environment variable \fBQUEUE_PLUGIN\fR to the
desired symbol.

In order to use the QHPSI, the virus scanner has to have
the following qualifications:

a) Correct interpretation of the base64 and perhaps the
   uudecoded data in order to detect the virii/worms therein.

b) Results have to be made available on stderr/stdout.

And perhaps:

c) Suppression of 'negative' scan results. 

Details on setting the virus scanner interface is given below.

.B QHPSI
can be set either to the full path of a scanner or to a list of plugins.

.LP
.nr step 1 1
.IP \n[step] 2
is set to full path of the virus scanner, i.e. QHPSI=INDIDIR/bin/clamdscan.
If full path is not specified,
.B qmail-queue
will use execvp(2) to run the scanner. Else it uses execv(2).
Setting QHPSI environment variable turns on the QHPSI interface. 
The Qmail High Performance Scanner interface QHPSI also allows
.B qmail-queue
to read command line arguments taken from the
.B QHPSI
environment to be used as a call-interface for an external virus scanner:

.EX
 QHPSI="clamdscan %s --quiet --no-summary"
.EE

Any \fB'%s'\fR in the \fBQHPSI\fR gets replaced with
the message filename in the queue's '\fImess\fR' directory.

.IP \n+[step]
is set to list of plugins starting with a keyword 'plugin:'.

.EX
 QHPSI="plugin: clamd fsecure symantec"
.EE

Sets \fBqmail-queue\fR to load three plugins clamd, fsecure and symantec from
QMAILHOME/plugins directory.

You can also use the plugin generic.so. generic.so plugin can use any scanner defined
by the \fBSCANCMD\fR environment variable.

.EX
 QHPSI="plugin: generic"
 SCANCMD="clamdscan %s --quiet --no-summary"
.EE

Any \fB'%s'\fR in the \fBSCANCMD\fR gets replaced with
the message filename in the queue's '\fImess\fR' directory.

.LP

.TP
.B QHPSIRC
To specify the return code of the virus scanner in case of an infection; default is 1.
.TP
.B QHPSIRN
To specify the return code of the virus scanner in case of no infection; default is 0.
.TP
.B REJECTVIRUS
If set to 1, infected mails will be bounced to sender. If set to 2, infected mails will
be blackholed. If set to 0, infected mails will be accepted. Blackholing does not work if VIRUSFORWARD or
QUARANTINE is defined. Setting to a value > 2 will bounce infected mails to sender
.TP
.B VIRUSFORWARD
Infected mails will be quarantined to the email defined by VIRUSFORWARD. This will work only if
.B REJECTVIRUS
is not equal to 1. Setting VIRUSFORWARD sets the \fBX-Quarantine-ID\fR containing the
list of original recipient list is added.
.TP
.B QHPSIMINSIZE
The minimal size of the message to invoke the virus scanner; default is 0.
A typical choice would be QHPSIMISIZE=10000 (~10k).
.TP
.B QHPSIMAXSIZE
The maximal size of the message to invoke the virus scanner; default is unrestricted.
A typical choice would be QHPPIMAXSIZE=1000000 (~1M).

When QHPSI is enabled \fBqmail-queue\fR adds the header X-QHPSI, the value of which
is either 'infected' or 'clean' (depending on whether the mail as identifed as infected
or not).

.SH "EXIT CODES"
.B qmail-queue
does not print diagnostics.
It exits
0 if
it has successfully queued the message.
It exits between 1 and 99 if
it has failed to queue the message.

All
.B qmail-queue
error codes between 11 and 40 indicate permanent errors:
.TP 5
.B 11
Address too long.
.TP
.B 31
Mail server permanently refuses to send the message to any recipients. (Not used by
.BR qmail-queue ,
but can be used by programs offering the same interface.)
.TP
.B 32
Spam or Junk Mail threshold exceeded. This is returned when a spam filter like
.B bogofilter
is used (SPAMFILTER is defined) and the mail is identified as spam.
.TP
.B 33
Message contains a virus.
.TP
.B 34
Message contains banned attachments
.TP
.B 88
Custom error (=bounce) messages. You have to write the error message to STDERR
and exit 88, in order to use the custom message. Format of the message:

Dthis is a custom fatal error message

Zthis is a custom temporary failure message

.PP
All other
.B qmail-queue
error codes indicate temporary errors:
.TP 5
.B 51
Out of memory.
.TP
.B 52
Timeout.
.TP
.B 53
Write error; e.g., disk full.
.TP
.B 54
Unable to read the message or envelope.
.TP
.B 55
Unable to read a configuration file.
.TP
.B 56
Problem making a network connection from this host. (Not used by
.BR qmail-queue .)
.TP
.B 61
Problem with the qmail home directory.
.TP
.B 62
Problem with the queue directory.
.TP
.B 63
Problem with queue/pid.
.TP
.B 64
Problem with queue/mess.
.TP
.B 65
Problem with queue/intd.
.TP
.B 66
Problem with queue/todo.
.TP
.B 67
Problem with uids/gids.
.TP
.B 71
Mail server temporarily refuses to send the message to any recipients.
(Not used by
.BR qmail-queue .)
.TP
.B 72
Connection to mail server timed out.
(Not used by
.BR qmail-queue .)
.TP
.B 73
Connection to mail server rejected.
(Not used by
.BR qmail-queue .)
.TP
.B 74
Connection to mail server succeeded, but communication failed. (Not used by
.BR qmail-queue .)
.TP
.B 81
Internal bug; e.g., segmentation fault.
.TP
.B 91
Envelope format error.

.SH Notes

Samples with clamd/clamdscan:

Here is a typical sample how to customize QHPSI together
with Clam AV (clamd/clamdscan) for a tcpserver tcp.smtpd file:

 :allow,QHPSI='INDIDIR/bin/clamdscan %s --quiet --no-summary'

Comments:

 - The path of 'clamdscan' can be omitted, because it is in 
   the standard path (INDIDIR/bin).
 - In the configuration file clamav.conf, the option
  'ScanMail' has to be enabled; clamd has to run as 'root'.
 - The argument QHPSI='INDIDIR/bin/clamdscan %s --quiet --no-summary'
   tells Clam AV to just provide the return status and print nothing
   on the stdout.
 - The argument QHPSIRC is not necessary, because
   'clamdscan' return with 'RC=1' (the default) in 
   case a virus infection is recognized.

Sample with McAfee's uvscan:

 :allow,QHPSI='/usr/bin/uvscan --secure',QHPSIMAXSIZE='9000000',QHPSIRC='13'

Comments:

 - The path of 'uvscan' is '/usr/local/bin' and can be ommitted.
 - 'uvscan' returns with RC=13 in case a virus is found,
   therefore, QHPSIRC has to provide this value.
 - The virus scanning is omitted, if the size of the message
   exceeds 9.000.000 byte, ~ 8.5MB.

You can also set these variables outside tcp.smtp. e.g.
  # echo INDIDIR/bin/clamdscan %s --quiet --no-summary \\
     > /service/qmail.smtpd.25/variables/QHPSI

.SH "SEE ALSO"
addresses(5),
envelopes(5),
qmail-header(5),
qmail-inject(8),
qmail-control(5),
qmail-qmqpc(8),
qmail-send(8),
qmail-smtpd(8),
qmail-internals(8),
qmail-multi(8)
