.TH qmail-qstat 8
.SH NAME
qmail-qstat \- summarize status of mail queue
.SH SYNOPSIS
.B qmail-qstat
.SH DESCRIPTION
.B qmail-qstat
gives a human-readable breakdown
of the number of messages at various spots in the mail queue.

.B qmail-qstat
must be run either as
.B root
or with group id
.BR qmail .
.B qmail-qstat
looks at the control file
.B queue_base
to determine the base directory of the queues. If that is not found
\fBqmail-qstat\fR uses the environment variable QUEUE_BASE or the conrol file \fBqbase\fR if
present to use the queue base. If the environment variables QUEUE_START and QUEUE_COUNT are set,
\fBqmail-qstat\fR will process multiple queues present in the queue base.
.SH "SEE ALSO"
qmail-qread(8),
qmail-send(8)
