.TH relaytest 1

.SH NAME
relaytest \- test if a host is an open relay

.SH SYNOPSIS
in tcpclient \fBrelaytest\fR

.SH DESCRIPTION
.B relaytest
is designed for the purpose of checking if a remote SMTP host is
an open relay
.B relaytest
needs to be invoked by tcpclient

.EX
tcpclient -T2 -RH -l0 127.0.0.1 25 /usr/sbin/relaytest
.EE

.SH RETURN VALUE
Exits 0 when all the commands are shut down.
If a fatal error is encountered, it exits.

.SH SEE ALSO
tcpclient(1), tcpserver(1)
