.TH svscanboot 8
.SH NAME
\fBsvscanboot\fR \- starts
.BR svscan (8)
in the service directories, with output and error messages logged through
.BR multilog (8).

\fBsvscanboot\fR is available in \fBindimail(7)\fR package.

.SH SYNOPSIS
\fBsvscanboot\fR [ \fIservicedir\fR ]

.SH DESCRIPTION

\fBsvscanboot\fR (without any command-line arguments) runs \fBsvscan\fR command

svscan /service 2>&1 

If \fBsvscanboot\fR is given a command-line argument, it startups up svscan for the directory
\fIservicedir\fR given on the command line (instead of just svscan /service).

\fBsvscanboot\fR sets \fBSCANINTERVAL\fR environment variable to 300 seconds. This causes
\fBsvscan\fR to look for new services every 300 seconds. You can change the interval by having
the scan interval specified in the control file QMAIL/control/scaninterval. \fBsvscan\fR also
sets the \fBSCANLOG\fR environment variable to have \fBsvscan\fR log all messages
and errors using \fBmultilog\fR, in the directory \fIservicedir\fR/.svscan/log/current.

\fBsvscanboot\fR sets PATH to

.EX
QMAIL/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin
.EE

(all in one line, no space)

and clears all other environment variables.

The recommended way is to put the following entry in /etc/inittab to invoke svscanboot.

SV:345:respawn:QMAIL/bin/svscanboot <>/dev/console 2<>/dev/console

.SH SEE ALSO
supervise(8),
svc(8),
svok(8),
svstat(8),
svscan(8),
svctool(8),
readproctitle(8),
fghack(8),  
pgrphack(8),
multilog(8),
tai64n(8),
tai64nlocal(8),
setuidgid(8),
envuidgid(8),
envdir(8),
softlimit(8),
setlock(8),
ps(1)

 http://cr.yp.to/daemontools.html
 http://cr.yp.to/slashcommand.html
