.LL 8i
.TH mgmtpass 8
.SH NAME
mgmtpass \- Create, Modify Admin Passwords for IndiMail administration

.SH SYNOPSYS
\fBmgmtpass\fR \fB\-u\fR \fIuser\fR [\fB\-a\fR \fIpasswd\fR] [\fB\-p\fR \fIpasswd\fR] [\fB\-i\fR]

.SH DESCRIPTION
\fBmgmtpass\fR is a passwd program for setting passwords in the table mgmtaccess. This table
is used the the administration server \fBindisrvr(8)\fR. For users other than the superuser,
the old password will be prompted, and only after successful authentication, will the password
be changed. 

.SH OPTIONS
.TP
\fB\-u\fR \fIuser\fR
The user for which the password needs  to be changed.
.TP
\fB\-a\fR \fIpasswd\fR
This option creates a user. The user has to supply the password for the user 'admin' to access
this.
.TP
\fB\-p\fR \fIpasswd\fR
The superuser can use this option to set/reset the password for an existing user.
.TP
\fB\-i\fR
Gives information like last accessed date, last update date, no of unsuccessful attempts and
whether the user is enabled/disabled. Only the superuser can use this option.
.PP
If the user gets disabled, the only way to enable the user is to run the command
.PP
.EX
 mgmtpass -u user -p pass
.EE
.PP
after which mgmtpass will prompt for the current password. Only if the current password is
given successfully will you be able to enable the user.
.PP
The userid 'admin' has superuser privileges (like creating other users, resetting passwords,
etc). The user 'admin' is created if it does not exist. The user will be prompted for setting
password for 'admin' user.

.SH RETURN VALUE
0 for success and 1 for failure in which case all diagnostics are printed on stdout.

.SH "SEE ALSO"
adminclient(8), indisrvr(8), vpriv(8), IndiMail(7)
