.\" ripMIME is a simple program which provides extensive email attachment extraction abilities.
.TH "ripole" "1" "1.4.0.1" "Paul L Daniels" "MIME decoders"

.SH NAME
ripole \- extracts attachments from OLE2 data files (ie, M$ Office docs)

.SH SYNOPSYS
ripole -i
.I ole2_file
-d
.I directory
[
\-\-\fIsave-unknown-streams\fR
\-\-\fIversion\fR|\-\fIV\fR
\-\-\fIverbose\fR|\-\fIv\fR
\-\-\fIdebug\fR
\-\-\fIhelp\fR|\-\fIh\fR
]

.SH DESCRIPTION
\fBripole\fR is a small program designed to pull attachments from OLE2 data files.

It can handle most of Microsoft Office documents like "doc" (Word), "xls" (Excel) or
"ppt" (Powerpoint).

.SH OPTIONS
.TP
.I ole2_file
Input OLE2 file (usually any Microsoft Office Document).

.TP
.I directory
Extract attachments to \fIdirectory\fR

.TP
\-\-\fIsave-unknown-streams\fR
Extract unknown attachments too.

.TP
\-\-\fIversion\fR, \-\fIV\fR
print ripOLE version.

.TP
\-\-\fIverbose\fR, \-\fIv\fR
print verbose output.

.TP
\-\-\fIdebug\fR
print debugging information.

.TP
\-\-\fIhelp\fR, \-\fIh\fR
show this help

.SH EXAMPLES
.EX
ripole -i xam-doc1.doc -v -d tmp
Decoding filename-short-XAMIME.dat
Decoding filename=mp71.exe
Decoding filename=MPSetup.exe
.EE

.SH SEE ALSO
ripmime(1)

.SH AUTHOR
THis manual page was written by Adam Cecile <gandalf@le-vert.net> for
the Debian system (but may be used by others).

Permission is granted to copy, distribute and/or modify this document
under the terms of GNU General Public License, Version 2 or any
later version published by the Free Software Foundation.
