.LL 8i
.TH indisrvr 8
.SH NAME
indisrvr \- IndiMail administration server

.SH SYNOPSYS
\fBindisrvr\fR \fB\-i\fR \fIIP_Address\fR \fB\-p\fR \fIport\fR \fB\-b\fR \fIbacklog\fR [\fB\-n\fR \fIcertfile\fR]

.SH DESCRIPTION
\fBindisrvr\fR is the administration server for administering IndiMail's clustered domains.
It has a simple mechanism by which administrators can connect to this server and issue
commands to execute any of the IndiMail programs given above. These commands are issued by
the \fBadminclient(8)\fR program. e.g. To run \fBvadduser\fR on host phoenix2, run
\fBadminclient\fR on any host on the network. \fBindisrvr\fR implements simple authentication
using crypt(3), MD5, SHA256/SHA512. The userid and passwd are maintained in the table
mgmtaccess. A separate password maintenance tool mgmtpass maintains the passwords in this table.
On successful validation of password, \fBindisrvr\fR executes the specified IndiMail administration
program on the localhost. For security reasons, the list of these administration programs are
hard-coded in the indisrvr executable. On SIGUSR2, verbose option gets toggled (see -v option
below). For a clustered domain, the table mgmtaccess will be on the hostcntrl db. For a
non-clustered domain, the table mgmtaccess will be on the local MySQL database.
.PP
Indisrvr uses a privilege table vpriv in MySQl for allowing access to command and
commandLineSwitches. For a clustered domain, the table vpriv will be on the central database.
For a non-clustered domain, the table vpriv will be on the local MySQL database. The table
vpriv can be maintained using the \fBvpriv(8)\fR program.

.EX
The following command runs the command vadduser with arguments test@indi.com password.
 adminclient -h phoenix2 -p  4000 -u admin -P adminpass -c ''vadduser test@indi.com password''
.EE

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose option.
.TP
\fB\-i\fR \fIIP_Address\fR
The IP address on which indisrvr needs to bind. Useful if a host has multiple IP addresses.
.TP
\fB\-p\fR \fIport\fR
A TCP/IP port or service in /etc/services on which indisrvr needs to bind.
.TP
\fB\-b\fR \fIbacklog\fR
Max backlog to be maintained after which the client should get connection refused
.TP
\fB\-n\fR \fIcertfile\fR
A PEM certificate causes indisrvr to negotiate TLS encryption with clients.

.SH RETURN VALUE
Always returns non-zero status, which means the server died due to some reasons. Most likely
of a bug. Will also return on SIGTERM with exit status=0.

.SH "SEE ALSO"
adminclient(8), mgmtpass(8), vpriv(8)
