.LL 8i
.TH initsvc 1
.SH NAME
initsvc \- Enable / Disable IndiMail services

.SH SYNOPSYS
\fBinitsvc\fR [\fIoptions\fR]

.SH DESCRIPTION
The \fBinitsvc\fR command installs all indimail services to be automatically started up on
system startup. Depending on the OS, \fBinitsvc\fR installs \fBsvscan(8)\fR to be started
up by
\fBinit(8)\fR (entry in /etc/inittab), \fBupstart(8)\fR (job definition in
/etc/init/svscan.conf) or \fBsystemd(1)\fR (job definition in
/lib/systemd/system/indimail.service). \fBinitsvc\fR needs to be run by the
\fIroot\fR user.

.SH OPTIONS
.PP
.TP
\fB-on\fR
Enables all services to be started automatically on boot or reboot
.TP
\fB-off\fR
Disables all services to be started automatically on boot or reboot
.TP
\fB-status\fR
Displays the status of svscan service
.TP
\fB-print\fR
Displays the entry for svscan in /etc/inittab, /etc/event.d or
/lib/systemd/system

.SH RETURN VALUE
0 in case of success, 1 in case of any failure.

.SH "SEE ALSO"
init(8),
initctl(8),
svscan(8),
supervise(8),
indimail(7)
