.TH CRC "1" "May 2016" "IndiMail" "General Commands"

.SH NAME
.PP
crc \- checksum files
.PP
crcdiff \- compare two crc lists and report the difference

.SH SYNOPSYS
.PP
crc file \.\.\.
.PP
crcdiff crclist1 crclist2

.SH DESCRIPTION
For each file, \fBcrc\fR calculates and prints a 32-bit CRC, the byte count, and the file name. It is typically
used to validate files transferred between different systems, and is useful in detecting subtle disk corruption.
\fBcrc\fR uses a checksum compatible with the DOS version of \fBcrc\fR, the 32 bit CRC used by PKZIP version 0.9,
as well as the "crc" command in ZCOMM and Professional-YAM (high reliability communications programs).

The 32-bit CRC used is the frame check sequence in ADCCP (ANSI X3.66, also known as FIPS PUB 71 and FED-STD-1003,
the U.S. version of CCITT's X.25 link-level protocol).

\fBcrcdiff\fR compares two crc lists and reports the differences.
 report:
     corrupt  - crc changed w/o date change 
     replaced - crc + date changed
     perm     - permissions changed
     own/grp  - owner or group changed
     removed  - 
     added    - Print the info for the new file except for deleted.

To generate crclist you can use

.EX
 find / -print | sort | xargs crc -v > crc_file
.EE

to generate a crc list.  Assume that no files have tabs or spaces in the name.

.SH BUGS
Altough extremely unlikely, files with different data may still produce the same crc value.

.SH SEE ALSO
sum(1), md5sum(1), 
