.TH ismaildup 1
.SH NAME
ismaildup \- Duplicate Email eliminator

.SH SYNOPSYS
\fBismaildup\fR \fIdir\fR \fIcmd\fR [\fIargs\fR]

.SH DESCRIPTION
.PP
\fBismaildup\fR takes email on stdin. It exits with status 0 if the email is duplicate
(received previously) in a given time interval (default 15 minutes). It executes the
command \fIcmd\fR with arguments \fIargs\fR if the email is not duplicate.

You can put the following in .qmail file to eliminate duplicates

.EX
   |ismaildup /var/indimail/bin/maildirdeliver /home/manny/Maildir
.EE

You need to set the environment variables \fBMAKESEEKABLE\fR, \fBELIMINATE_DUPS\fR to turn
on the duplicate elimination logic. The time interval in seconds (default 900 seconds) within
which the duplicates are checked can be set by the \fBDUPLICATE_INTERVAL\fR environment
variable.

.SH SEE ALSO
vdelivermail(8)
