.TH login_tasks 3
.SH NAME
login_tasks \- perform set of important tasks on login
.SH SYNTAX
.B #include <indimail.h>

int \fBlogin_tasks\fP(\fIpw\fR, \fIuser\fR, \fIservice_type\fR);

.br
struct passwd *\fIpw\fR;
.br
const char *\fIuser\fR;
.br
char *\fIservice_type\fR;

.SH DESCRIPTION

\fBlogin_tasks(3)\fR api carries out a set of instructions. \fBlogin_tasks(3)\fR is called by
\fBIndiMail(7)\fR authentication modules for POP3 and IMAP. They carry out the following steps
in the order given below

The first step \fBlogin_tasks(3)\fR does is to create user's home directory. It is not neccssary for
a user to have a home directory during user creation (e.g. '-d' option not specified when running
\fBvadduser(1)\fR). The directory gets created automatically when the user logs in successfully
using IMAP or POP3. Also, a user may not have a home directory if inactivated by \fBvmoduser(1)\fR
or \fBvdelolduser(8)\fR programs. If a user is inactive, login_tasks(3) makes the user active on
successful authentication.

\fBlogin_tasks(3)\fR copies any bulletins present in \fIbulk_mail\fR directory to the user's Maildir.
You can change the name of this directory by seting \fBBULK_MAILDIR\fR environment variable.
When a user is being activated, \fBlogin_tasks(3)\fR checks for the bulletin activatemail.txt.
You can change this filename by defining \fBACTIVATEMAIL\fR environment variable. For a new
user, \fBlogin_tasks(3)\fR copies the bulletin welcomemail.txt,all. \fBWELCOMEMAIL\fR
environment variable can be used to use a different filename. \fBACTIVATEMAIL\fR and
\fBWELCOMEMAIL\fR environment variables should refer to a filename in the directory
CONTROLDIR/domain_name/bulk_mail.

If \fBNOLASTAUTH\fR environment variable is defined, \fBlogin_tasks(3)\fR exits after copying
bulletins. If not defined, further actions as described below are performed

An entry is made in the MySQL \fIRELAY\fR table. This enables the POP/IMAP before SMTP
feature, allowing a user to use SMTP relay (from the same IP address) to succeeed for a period
of \fBRELAY_CLEAR_MINUTES\fR minutes after a successful IMAP/POP3 authentication.
(see \fBclearopensmtp(8)\fR).

If \fBMIN_LOGIN_INTERVAL\fR environment variable is defined \fBlogin_tasks(3)\fR exits if
time interval equal to \fBMIN_LOGIN_INTERVAL\fR seconds has not elapsed since the last
successful authentication. You can use \fBMIN_LOGIN_INTERVAL\fR to control brain-dead applications
like MS Outlook and family.

\fBlogin_tasks(3)\fR puts an entry in the \fIlastauth\fR MySQL table, recording the IP address
from which the IMAP/POP3 access has occurred, the timestamp and the service (POP3 or IMAP).

If \fBPOSTAUTH\fR environment variable is defined, \fBlogin_tasks(3)\fR will execuate the
script/program defined by the \fBPOSTAUTH\fR environment variable

If the program/script /usr/local/bin/migrateuser is present, \fBlogin_tasks(3)\fR executes the
program/script just once. If the program/script exits with non-zero status, it will be executed
again till the next successful IMAP/POP3 authentication. You can change the path to the
\fImigrateuser\fR program by defining \fBMIGRATEUSER\fR environment variable. \fBlogin_tasks(3)\fR
uses a filename as a flag to execute the \fImigrateuser\fR program just once. By default this flag
Qmail.txt is created in the user's Maildir after successful execution of the \fImigrateuser\fR program.
If this file already exists, then execution of \fImigrateuser\fR program is skipped. You can
chose A different filename by setting \fBMIGRATEFLAG\fR environment variable.

\fBlogin_tasks(3)\fR also arranges for bulletins to be copied to the user's Maildir. Bulletins
are email messages that can be deposited instantly in the user's home directory without injecting
a mail. You can create bulletins using the \fBvbulletin(1)\fR program. Bulletings is a good
way to communicate with all users or a large number of users instantly. Bulletins are instant
and do not involve any queuing. Bulletins are available to all users (regardless of the number
of users) the instant they are created. See the section on Bulletins below.

If the user is overquota, an overquota warning mail is sent. Site administrators can customize
Over Quota Bounce messages, by setting environment variables
\fBQUOTAWARN1\fR, \fBQUOTAWARN2\fR ... upto \fBQUOTAWARN10\fR. These variables should be set to
a percentage quota usage for which warning should be sent. If BOUNCE flag has been set (by
\fBvdelivermail(8)\fR) for the user and the user currently is not overquota, \fBlogin_tasks(3)\fR
removes the BOUNCE flag (pw_gid field).

.SH Bulletins

You can create a bulletin by creating RFC 822 formated files in the directory
CONTROLDIR/domain_name/bulk_mail where \fIdomain_name\fR is a name for a virtual domain
created by the \fBvadddomain(1)\fR program.

If the filename has the extension ,all then the bulletin gets copied to every user's Maildir
on successful login. To prevent multiple copies of the same bulletin getting copied to user's
Maildir, the copy happens only for the first successful authentication.

If you want bulletins to be sent to specific users, then you should have the filename
without the ,all extension. The specific users need to be inserted into the MySQL table
\fIbulkmail\fR. You need to insert data for the \fIemailid\fR and \fIfilename\fR columns. You
can automate the creation of bulletins by using the \fBvbulletin(1)\fR program.

.SH SEE ALSO
vadddomain(1),
vmoduser(1),
vdeloldusers(1),
imapd(8),
pop3d(8),
proxyimap(8),
proxypop3(8),
vdelivermail(8),
clearopensmtp(8),
authlib(7),
vchkpass(8),
vbulletin(1)
