.TH postdel 8
.SH NAME
postdel \- deliver mail to a user in a virtual domain using postfix

.SH SYNOPSYS
.B postdel
\fB\-u\fR \fIuser\fR \fB\-d\fR \fIdomain\fR \fB\-r\fR \fIrecipient\fR

.SH DESCRIPTION
.PP
\fBpostdel\fR is called from the postfix's master.cf configuration file to deliver email to a
virtual user. \fBpostdel\fR sets the environment variables EXT, HOST and RPLINE which is
used by \fBvdelivermail\fR to set the user and the domain component of the email address.
\fBpostdel\fR forks and calls \fBvdelivermail\fR and gets the exit status. The exit status is
than mapped to postfix/sendmail compatible exit status. Since \fBvdelivermail\fR can handle
only one recipient at at time, the variable \fBdefault_destination_recipient_limit=1\fR should
be set in main.cf. If default_destination_recipient_limit is set to more than 1,  all mails
will bounce with usage error. Hopefully this will be corrected in future versions.

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose option
.TP
\fB\-u\fR
Username to which mail is to be delivered
.TP
\fB\-d\fR
Recipient's fully qualified email address.
.TP
\fB\-r\fR
Sender's email address.

.SH RETURN VALUE

.IP \[bu] 2
0 if all steps were successful. 
.IP \[bu]
67 for permanent errors. i.e. if user is over quota or bounce-no-mailbox is set and no matching user is found.
.IP \[bu]
75 for all temporary error occurs during mail delivery and without the error, the mail would have got delivered
.IP \[bu]
71 for Operating System Errors
.IP \[bu]
70 for Software Bugs
.IP \[bu]
64 for errors due to misconfiguration

.SH "SEE ALSO"
vdelivermail(8)
