.TH printdir 1
.SH NAME
printdir \- display directory structure layout for a virtual domain

.SH SYNOPSYS
.B printdir
.I domain_name

.SH DESCRIPTION
.PP
\fBprintdir\fR displays the Directory Structure Layout's hashed component.
The hashed component is used by
\fBvadduser\fR to construct the home directory. Hashing enables faster directory lookups.
The information for the directory structure is maintained in the \fBdir_control\fR
MySQL tables. \fBprintdir\fR has setuid bit to root and runs as indimail user.

.SH OPTIONS
.PP
.TP
\fIdomain_name\fR
The name of the virtual domain.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
vdominfo(1), vadddomain(1), vadduser(1), vdeluser(1), vmoveuser(1), vrenameuser(1), vreorg(8),
vuserinfo(1)
