.TH vcalias 8
.SH NAME
.PP
vcalias \- convert .qmail to IndiMail \fIvalias\fR database
.PP
vcaliasrev \- convert IndiMail \fIvalias\fR database to .qmail

.SH SYNOPSYS
.PP
\fBvcalias\fR \fIvirtual_domain\fR
.PP
\fBvcaliasrev\fR \fIvirtual_domain\fR

.SH DESCRIPTION
.PP
.B vcalias
converts .qmail files to IndiMail's optimized valias entries. These entries are maintained
in the table \fBvalias\fR. The IndiMail's MDA \fBvdelivermail(8)\fR is capable of working
with both .qmail files as well as valias. Hence, .qmail and valias can coexist. However care
should be taken by the user not have duplicate entries (i.e. Entries maintained as .qmail
file as well as valias.

.PP
.B vcaliasrev
does the reverse of vcalias. It converts from IndiMail's valias entries to .qmail files.
.B vcaliasrev
is a shell script which uses MySQL client to query the valias table and build the .qmail files.

.SH OPTIONS
.PP
.TP
\fIvirtual_domain\fR
Name of a virtual domain for which the .qmail files need to be converted to valias.

.SH RETURN VALUES
0 for success, 1 for any failure.

.SH "SEE ALSO"
valias(1), vgroup(1), vadduser(1), vdelivermail(8), vrenamedomain(1), vreorg(8)
