.TH vdominfo 1
.SH NAME
vdominfo \- Display domain information for virtual domains

.SH SYNOPSYS
.B vdominfo
[
.I domain_name
]

.SH DESCRIPTION
\fBvdominfo\fR displays domain information for all domains (or for a particular domain given
on the command line). The information is given as below

.TP
\fBDomain\fI
The domain name (the real domain in case of an alias domain).
.TP
\fBuid\fI
uid of the virtualdomain
.TP
\fBgid\fI
gid of the virtualdomain
.TP
\fBHost ID\fI
Hostid for the host where the domain is created.
.TP
\fBIP Addr\fI
IP Address of the host.
.TP
\fBDomain Dir\fI
Domain directory for the domain.
.TP
\fBBase Dir\fI
User's base home directory for the domain.
.TP
\fBUsers\fI
No of users in this domain. (Not displayed for an alias domain)
.TP
\fBvlimits\fI
If vlimits is enabled or disabled
.TP
\fBAliasDomains\fI
List of alias domains for this domain.

.SH OPTIONS
.TP
\fB\-a\fR
Display all fields
.TP
\fB\-n\fR
Display domain name
.TP
\fB\-u\fR
Display uid fields.
.TP
\fB\-g\fR
Display gid fields
.TP
\fB\-d\fR
Display domain directory
.TP
\fB\-b\fR
Display user's base home directory
.TP
\fB\-t\fR
Display user count
.TP
\fB\-l\fR
Display alias domains.
.TP
\fB\-p\fR
Display SMTP ports
.TP
\fIdomain_name\fR
The name of the virtual domain.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
printdir(1), vadddomain(1), vaddaliasdomain(1), vmoddomain(1), vdeldomain(1),
vlimit(1), dbinfo(8)
