.TH vfstab 8
.SH NAME
vfstab \- Filesystem balancing Utility

.SH SYNOPSYS
\fBvfstab\fR \fB\-d\fR | \fB\-i\fR | \fB\-l\fR | \fB\-u\fR | \fB\-o\fR | \fB\-n\fR \fIuser_quota\fR \fB\-q\fR \fIsize_quota\fR \fB\-m\fR \fImdaHost\fR \fIFilesystem\fR

\fBvfstab\fR \fB\-s\fR [\fB\-m\fR \fImdaHost\fR]

\fBvfstab\fR \fB\-b\fR

.SH DESCRIPTION
\fBvfstab\fR is a utility for maintaining the FSTAB table. The FSTAB table maintains the
filesystems which can be used for serving the user mailboxes. Normally when creating an user
account (\fBvadduser\fR), the environment variable BASE_PATH is used. This however is not optimal
when having multiple filesystems. In such case, the administrator can use the -b option in
\fBvadduser\fR to distribute the users across multiple filesystems, taking into account the
load of the different filesystems. The load factor is computed by running vfstab with -b
option periodically through cron(1). 

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose option
.TP
\fB\-d \fR
Delete local/remote file system
.TP
\fB\-i\fR
Insert local/remote file system
.TP
\fB\-u\fR
Update local/remote file system
.TP
\fB\-o\fR
Make local/remote file system offline/online
.TP
\fB\-l\fR
Add local file system. If -n and -q options are not given, the values user_quota and size_quota are automatically calculated from the free disk space available and by assuming an average size of the mailbox to be the value of the environment variable AVG_USER_QUOTA
.TP
\fB\-n\fR
Max number of users to be added on this file system.
.TP
\fB\-q\fR
Max size of file system
.TP
\fB\-m\fR
Mailstore. The hostid of mailstore on which the user's mailbox lie.
.TP
\fB\-s\fR
Show filesystems configured in FSTAB table. If -m option is given, displays the file system only for the specified Mail Delivery Host.
.TP
\fB\-b\fR
Balance filesystems by computing load.
.TP
\fIFilesystem\fR
Name of a valid file system.

.SH RETURN VALUE
Returns 0 for success, 1 for any failure.
