.TH vhostid 8
.SH NAME
vhostid \- Add, Modify, Delete, Display IndiMail hostid mapping

.SH SYNOPSYS
\fBvhostid\fR [\fIoptions\fR] [\fIHostId\fR]

.SH DESCRIPTION
\fBvhostid\fR displays the hostid to IP address mapping used by IndiMail for clustered domains.
Each host in a clustered setup is assigned a unique hostid with the help of \fBvhostid\fR.
Subsequently, \fBvhostid\fR can be used to display, insert, update or delete these mappings. This
information is maintained in the MySQL table \fIhost_table\fR.

.PP
When a user is added to a domain in a clustered setup, a hostid is needed to be alloted to the user.
This information is kept in the MySQL table \fIhostcntrl\fR. Thus locating any user's mailstore
involves querying the hostid from the table \fIhostcntrl\fR and susbequently the IP address from
the table \fIhost_table\fR.

.SH OPTIONS
.TP
\fB\-v\fR
Sets Verbose Option
.TP
\fB\-s\fR
Display hostid Mappings for all hosts (if hostid is not given on command line. Else displays
the hostid to IP Address mapping only for the host with id \fIHostId\fR.
.TP
\fB\-d\fR \fIHostId\fR
Delete IP address Mapping for \fIHostId\fR
.TP
\fB\-i\fR \fIIpaddr\fR
Maps IP address \fIIpaddr\fR to hostid \fIHostId\fR
.TP
\fB\-u\fR \fINew_Ipaddr\fR
(Map \fIHostId\fR to \fINew_Ipaddr\fR)
Changes IP address for hostid \fIHostid\fR to IP address \fINew_Ipaddr\fR

.SH RETURN VALUE
0 if successful, 1 for any failure.

.SH "SEE ALSO"
vsmtp(8), hostcntrl(8), dbinfo(8), vadduser(1), vgroup(1), IndiMail(7)
