.TH vmoddomain 1
.SH NAME
vmoddomain - Modify delivery instruction for a virtual domain or set domain limits

.SH SYNOPSYS
.B vmoddomain
[
.I options
]
.I virtual_domain

.SH DESCRIPTION
.PP
\fBvmoddomain\fR modifies delivery instructions for a virtual domain by modifying
\fB.qmail-default\fR. \fBvmoddomain\fR has the setuid bit set and runs with the
\fIvirtual_domain's\fR uid. \fBvmoddomain\fR can also be used to set domain limits when
using the -\fBl\fR option.

.SH OPTIONS
.PP
\fIvirtual_domain\fR is mandatory. Rest are optional.
.TP
\fB\-v\fR
verbose
.TP
\fB\-l\fR \fI0\fR | \fI1\fR
Set domain limit. 0 to turn off, 1 to turn on.
.TP
\fB\-f\fR \fI0\fR | \fI1\fR
Sets the domain with VFILTER capability. 0 to turn off, 1 to turn on.
.TP
\fB\-h\fR \fIhandler\fR
Sets the handler for delivery instruction for non-existing local users. The handler can be one
of the following values
.RS
.nr step 1 1
.IP \n[step] 3
The keyword 'delete' - Any mail addressed to a non-existing user gets deleted.
.IP \n+[step]
The keyword 'bounce-no-mailbox' - Any mail addressed to a non-existing user gets bounced to the sender.
.IP \n+[step]
Maildir – A full path to a Maildir (e.g. /home/manny/Maildir/). - Mails for non-existing users get
stored in a Maildir
.IP \n+[step]
Email Address - Any mail addressed to a non-existing user gets forwarded to an email address.
.IP \n+[step]
IP Address – An IP address in SMTPROUTE specification (e.g. indimail.org:192.168.2.1:25) - The mail
gets redirected to another server which has the user.
.RE

.EX
Example Usage

vmoddomain -f 1 bounce-no-mailbox example.com
.EE

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic
message is printed.

.SH "SEE ALSO"
vadddomain(1), vadduser(1), vdeldomain(1), vdominfo(1), vdelivermail(8)
