.TH vrenameuser 1
.SH NAME
vrenameuser \- change email address of a virtual user to a new email address

.SH SYNOPSYS
\fBvrenameuser\fR [\fIoptions\fR] \fIold_email_address\fR \fInew_email_address\fR

.SH DESCRIPTION
.PP
\fBvrenameuser\fR changes the email address of an existing virtual domain user to a new email
address. This can be used to either change the username or to move the user to a new
virtual domain lying on the same host. vrenameuser changes only the pw_name and pw_domain
component, and doesn't change attributes like pw_gecos, pw_dir, etc. But can be used in
conjunction with vmoveuser, vmoduser it can be used to change the homedir, gecos also.
\fBvrenameuser\fR has setuid bit to root and can be run by the root or indimail user.

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvrenameuser\fR executes the program defined by
the POST_HANDLE environment variable, passing \fIold_email_address\fR and \fInew_email_address\fR as
parameters. If POST_HANDLE is not defined, the program/script LIBEXECDIR/vrenameuser
will be executed with \fIold_email_address\fR and \fInew_email_address\fR as parameters.

.SH OPTIONS
.PP
.TP
\fB\-V\fR
Print Version Numbers
.TP
\fB\-v\fR
Set verbose mode
.TP
\fIold_email_address\fR
Current email address of the user.
.TP
\fInew_email_address\fR
Desired new email address for the user.

.SH RETURN VALUE
0 if successful, 1 in case of any failure.

.SH "SEE ALSO"
vmoveuser(1)
