.TH vreorg 8
.SH NAME
vreorg \- Recreate Directory Structure Layout for a virtual domain

.SH SYNOPSYS
.B vreorg
\fB\-d\fR \fIvirtual_domain\fR
[
\fB\-r\fR
]
[
\fB\-R\fR
]
\fIuser_list\fR

.SH DESCRIPTION
.PP
\fBvreorg\fR deletes the Directory Structure layout and assigns new hashed component
for the home directory of the user. The existing files for the user are moved
to the new path if necessary. indimail, indibak, valias MySQL table entries referring to
the earlier path are updated with the new path.

.SH OPTIONS
.PP
.TP
\fB\-d\fR \fIvirtual_domain\fR
The name of the virtual domain.
.TP
\fB\-r\fR
Reset Dir Structure Layout for virtual_domain
.TP
\fB\-R\fR
Do not decrement Dir Structure Layout in the original filesystem.
.TP
\fB\-l\fR users_per_level
By default, \fBvadduser\fR uses an adaptive directory structure based on a table dir-control
which is automatically managed by \fBvadduser(1)\fR, \fBvdeluser(1)\fR and \fBvreorg(8).
The basic idea is to break up the user Maildir directories across multiple directories and sub
directories so that there are never more than 100 user directories in a single directory. Use
this option to change the default compile time value of 100 users per directory, when doing
a reorg.
.TP
\fIuser_list\fR
Name of a file contain valid users for the virtual domain.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
printdir(1), vadduser(1), vdeluser(1)
