.TH vtable 1
.SH NAME
vtable \- create MySQL table from text file templates

.SH SYNOPSYS
.PP
\fBvtable\fR [\fIoptions\fR] \fItemplate1\fR \fItemplate2\fR ...

.SH DESCRIPTION
\fBvtable\fR can create MySQL tables from simple template specfied in a text file.
A text file containg the following content can be used to create a MySQL table \fIdbinfo\fR
with two indices as given below.

.EX
dbinfo
(filename char(128) not null,
domain   char(64) not null,
distributed int not null,
server   char(28) not null,
mdahost  char(28) not null,
port     int not null,
dbname   char(28) not null,
user     char(28) not null,
passwd   char(28) not null,
timestamp timestamp not null,
unique index (filename, domain, server, mdahost, port, dbname, user, passwd), 
index (domain))
.EE

\fBvtable\fR helps you to maintain your customized MySQL table structures in simple text
files so that they can be recreated easily at any point of time. You can give multiple
filenames on the command line to create multiple tables in a single invocation of
\fBvtable\fR.

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose option
.TP
\fB\-S\fR \fIIP\fR
MySQL Server IP
.TP
\fB\-p\fR \fIport\fR
MySQL TCP/IP Port
.TP
\fB\-s\fR \fIsocket\fR
MySQL Unix Domain Socket. You can specify this instead of \fIport\fR if your MySQL
server is local.
.TP
\fB\-D\fR \fIdatabase\fR
MySQL Database Name
.TP
\fB\-U\fR \fIuser\fR
MySQL User Name
.TP
\fB\-P\fR \fIpassword\fR
MySQL Password

.PP
\fItemplate1\fR, \fItemplate2\fR are filenames each containing a template representing a
MySQL table structure.

.SH RETURN VALUE
Returns 0 for success, 1 for any failure.

.SH "SEE ALSO"
IndiMail(7), install_tables(8)
