.LL 8i
.TH vipmap 1
.SH NAME
vipmap \- maps an ip address to a virtual domain

.SH SYNOPSYS
.B vipmap
[
.I options
]
.I ip_address
.I virtual_domain

.SH DESCRIPTION
.PP
\fBvipmap\fR maps an ip address to a virtual domain. During authentication if any connection
from an mapped ip address gives a user without the domain part, the same will be used from
an existing mapping. In case a host has multiple ip addresses, individual ip addresses can
be mapped to individual virtual domains.  This can be used instead of the environment
variable DEFAULT_DOMAIN or INDIMAIL_DOMAIN. The environment variable INDIMAIL_DOMAIN
takes precedence.

.SH OPTIONS
.PP
.TP
\fB\-v\fR
Sets verbose option.
.TP
\fB\-d\fR \fIipaddr\fR
Deletes mapping for ip address ipaddr and domain \fIvirtual_domain\fR
.TP
\fB\-a\fR \fIipaddr\fR
Adds a mapping between IP address ipaddr and domain \fIvirtual_domain\fR
.TP
\fB\-p\fR
Prints mapping between all IP addresses and virtual domains.
.TP
\fIvirtual_domain\fR
Name of the new virtual domain.

.SH RETURN VALUES
0 for success, 1 for any failure.

.SH "SEE ALSO"
imapd(8)
