.TH maildirsize 1
.SH NAME
maildirsize \- print quota of a Maildir

.SH SYNOPSIS
\fBmaildirsize\fR \fIaccount\fR

.SH DESCRIPTION
\fBmaildirsize\fR scans a Maildir for all emails and calculates the total storage
consumed by the emails. It then prints the quota in Maildir++ specification.
.SH "SEE ALSO"
maildirquota(1), maildirmake(1), deliverquota(8)
