.TH qaes 1
.SH NAME
qaes \- qmail/IndiMail AES Encryption/Decryption Utility
.SH SYNOPSIS
.B qaes
.B \-k \fIkey
[
.B \-i
.B \-d
.B \-e
.B \-s \fIsalt
]
.SH DESCRIPTION
\fBqaes\fR reads strings on stdin and encrypts or decrypts them using AES. The encrypted
output is base64 encoded. For decryption, qaes expects the string to be base64 encoded.
qaes uses 256-bit symmetric key

The Advanced Encryption Standard (AES) is a specification for the encryption of electronic
data established by the U.S. National Institute of Standards and Technology (NIST) in 2001.
It is based on the Rijndael cipher developed by two Belgian cryptographers, Joan Daemen and
Vincent Rijmen, who submitted a proposal to NIST during the AES selection process. Rijndael
is a family of ciphers with different key and block sizes. For AES, NIST selected three
members of the Rijndael family, each with a block size of 128 bits, but three different
key lengths: 128, 192 and 256 bits.

.SH OPTIONS
.PP

.TP
\fB-k\fR \fIkey\fR
Argument is a key to use for encryption. The same key needs to be supplied to decrypt
a previous encrypted data

.TP
\fB-s\fR \fIsalt\fR
salt to use for encryption. The default salt is 12345

.TP
\fB\-i\fR
When encoding, ignore line terminating newline character.

.TP
\fB-d\fR
Decrypt input data

.TP
\fB-e\fR
Encrypt input data. This is the default

.SH "SEE ALSO"
base64(1)
