.TH qmail-cdb 8
.SH NAME
qmail-cdb \- prepare data in cdb format for
.BR qmail .
.SH SYNOPSIS
.B qmail-cdb
.I filename
.SH DESCRIPTION
.B qmail-cdb
does a chdir to @controldir@ and
reads the instructions in
.I filename
and writes them into
.I filename.cdb
in a binary format suited
for quick access by
.B qmail-smtpd
or
.BR spawn-filter .

If there is a problem with
.IR filename ,
.B qmail-cdb
complains and leaves
.I filename.cdb
alone.

.B qmail-cdb
ensures that
.I filename.cdb
is updated atomically,
so
.B qmail-smtpd
or
.B spawn-filter
never has to wait for
.B qmail-cdb
to finish.
However,
.B qmail-cdb
makes no attempt to protect against two simultaneous updates of
.BR filename.cdb .

The binary
.B filename.cdb
format is portable across machines.
.SH "SEE ALSO"
qmail-smtpd(8), spawn-filter(8), qmail-multi(8)
