.TH qmail-greyd 8
.SH NAME
qmail-greyd \- greylisting daemon for \fBIndiMail\fR, \fBqmail\fR and \fBnetqmail\fR
.SH SYNOPSIS
.B qmail-greyd
[\c
.B \-t
.I timeout (days)\c
]\ [\c
.B \-p
.I port\c
]\ [\c
.B -h
.I hash_size
]\ [\c
.B -v
.I verbosity
]\ [\c
.B \-g
.I resend_window (hr)\c
]\ [\c
.B \-m
.I min_resend_time (min)\c
]\ [\c
.B \-f
.I free_interval (min)\c
]\ [\c
.B \-s
.I save_interval (min)\c
]\ [\c
.B \-w
.IR whitelist_file
[.cdb]
]
.I ipaddr contextFile
.SH DESCRIPTION
\fBqmail-greyd\fR is a greylisting daemon responding to UDP query packets, typically
sent by a using \fBgreylist(3)\fR function in \fBqmail-smtpd(8)\fR.
The query packet consists of the sending IP address, the sender address and
one or more recipient addresses. \fBqmail-greyd\fR borrows most of the logic from
\fBgreydaemon\fR written by \fBJohn Levine\fR and the \fBgreycheck()\fR function written by
\fBAndrew Richards\fR.

If the IP address was previously successful for a greylisting check, and
was last queried within \fItimeout_days\fR, the check succeeds. Alternatively if one of
the supplied triplets of IP address / sender / recipient have previously been seen within
\fIresend_window_hours\fR, but at least \fImin_resend_minutes\fR ago, the check succeeds
and future checks within \fIresend_window_hours\fR for the IP address will succeed.
Otherwise the triplet(s) supplied are added to the greylisting database to check against
future queries, and the check fails (meaning \fBqmail-smtpd(8)\fR will reject the message).

Emails that have an envelope sender of the null sender are considered a special case where
\fBqmail-greyd\fR will expire the record immediately in order to avoid whitelisting it,
once we allow the mail to go through. Mails from the null sender are (according to RFC 821)
are to be used for special administrative mails like bounces only. Consequently, they are almost
never used for more than one legitimate email. For that reason, there is no need to maintain
them any longer once an email has been passed.

\fBqmail-greyd\fR maintains its database in memory, thus avoiding complicated schemes to
manage greylisting data on disk, making it faster than disk-based
approaches. Periodic backups of the database are made to \fIcontextFile\fR
on the disk, to enable \fBqmail-greyd\fR to start with existing greylisting data, in case
of restart. To keep the in-memory search as efficient as possible, entries older than
\fItimeout_days\fR are expired during every request. To keep the in-memory database as
small as possible, records older than \fItimeout_days\fR are periodically removed. The
default interval is 5 minutes and can be changed by specifiying the \fB-f\fR option.
You can force removal of expired records by issuing \fISIGUSR2\fR signal to \fBqmail-greyd\fR.
\fBqmail-greyd\fR also backups the in-memory database to \fIcontextFile\fR on receipt
of \fISIGTERM\fR or \fISIGUSR1\fR signal. The \fIcontextFile\fR and its containing directory
should be writeable by the user with which \fBqmail-greyd\fR process runs. At start-up the file
\fIcontextFile\fR is read and all records older than \fItimeout\fR days are expired. \fBqmail-greyd\fR
can maintain an internal hash table for fast IP address lookup using the \fBhsearch(3)\fR function.

A whitelist of IP ranges not subject to greylisting can be specified to \fBqmail-greyd\fR
by the \fB-w\fR \fIfilename\fR option. The range can be specified in CIDR format, wildcard or range
notation. If a file with the name \fIfilename\fR.\fIcdb\fR exists, \fBqmail-greyd\fR will use
\fBcdb(3)\fR lookup in addition to the normal in-memory search in a table of whitelisted IPs.
\fBqmail-greyd\fR re-reads the whitelist on receipt of signal \fISIGHUP\fR.

Examples of whitelisted IPs

.EX
 192.168.2.1/28
 192.168.[3-4].45
 192.168.2.*
.EE

\fBqmail-greyd\fR listens on IP address \fIipaddr\fR, port 1999 for incoming UDP queries.
127.0.0.1 (the loopback address) is recommended for \fIipaddr\fR if \fBqmail-greyd\fR is
to serve queries on the same machine. You can specify :: for \fBqmail-greyd\fR to listen on
wildcard IPV6 address.  Specifiying * for \fIipaddr\fR causes \fBqmail-greyd\fR to listen on all
addresses.

\fBqmail-greyd\fR uses \fIMSG_PEEK\fR flag in \fBrecvfrom(2)\fR to determine the length of the
packet and then reads the entire packet in one operation.

.SH OPTIONS
.TP
.B -v \fIverbosity
Set verbosity. 0 - minimal, 1 - moderate, 2 - maximum, 3 - include debug messages\fR

.TP
.B -h \fIhash_size
specify the memory for creating a hash using \fBhcreate(3)\fR

.TP
.B -w \fIfilename
specify whitelist of IP ranges not subject to greylisting.

.TP
.B -t \fIdays
timeout for known IPs in days; defaults to 7.

.TP
.B -g \fIhours
grey resend window, in hours; defaults to 12.

.TP
.B -m \fIminutes
min resend accept time, in minutes; defaults to 5.

.TP
.B -f \fIminutes
periodic interval, in minutes, after which entries older than \fItimeout\fR days are expired; defaults to 5

.TP
.B -s \fIminutes
save interval for context file, in minutes; defaults to 5

.TP
.B -p \fIport
Alternate port to listen instead of the default 1999

.SH "QUERY FORMAT"
Queries to
\fBqmail-greyd\fR are UDP packets containing the IP address (as a string) preceded by
.BR I ,
the sender address preceded by
\fBF\fR and the recipient address preceded by
.BR T .
Each of these fields is separated by an ASCII 0 (null) character.
Additional recipient addresses may be appended to this structure, each time
preceded with T and with an ASCII 0 as separator. Finally the record is terminated
by a ASCII 0 character.

.EX
 Iip_address\\0Freturn_path\\0Trecipient1\\0Trecipient2\\0\\0
.EE

.SH "SEE ALSO"
qmail-smtpd(8), greylist(3), bogofilter(1), hcreate(3), hsearch(3), hdestroy(3), recvfrom(2).

.SH REFERENCES

.TP
The Next Step in the Spam Control War: Greylisting
by Evan Harris
http://projects.puremagic.com/greylisting/whitepaper.html
.TP
Announce: greydaemon, a new greylisting package for netqmail
http://www.gossamer-threads.com/lists/qmail/users/136740

.SH AUTHORS
.B qmail-greyd
is currenty being maintained by Manvendra Bhangui <mbhangui@gmail.com> and
is part of the IndiMail package at http://www.indimail.org
