.TH replier-config 1
.SH NAME
replier-config \- The replier-config Program
.SH SYNOPSIS
.B replier-config
.I dir
.I dot
.I local
.I host
[
.I outlocal
[
.I outhost
]
]

where
.I dir
is a directory,
.I dot
is a \.qmail file, 
.I local
is the local portion of an email address, and
.I host
is a host name,
.I outlocal
is either the local portion of an email address or the empty string, and 
.I outhost
is a host name. The directory
.I dir
must begin with a slash. If 
.I outlocal
is not present, 
.B replier-config
sets it to local. If 
.I outhost
is not present,
.B replier-config
sets it to host.

If 
.I outlocal
is not empty,
.B replier-config
creates a new email replier at the address 
.B outlocal-help@outhost

If outlocal is empty,
.B replier-config creates a new email replier at the address
.B help@outhost

In either case,
.B replier-config
sets up two 
.B \.qmail
files to control the help-address replier:
.B dot-help
and
.B dot-return-default .
These files should control messages to the addresses
.B outlocal-help@outhost
and
.B outlocal-return-@outhost ,
respectively (or 
.B help@outhost
and
.B return-@outhost
if
.I outlocal
is empty).

Within 
.I dir ,
.B replier-config
creates several configuration files for replier.

The first line of 
.B dir/inlocal
consists of
.I local .

The first line of
.B dir/inhost
consists of 
.I host .

The first line of 
.B dir/outlocal
consists of 
.I outlocal .

The first line of
.B dir/outhost
consists of 
.I outhost.

The first line of 
.B dir/mailinglist
consists of contact helpaddress; run by replier, where helpaddress is the help address created by
replier-config as described above.

The
.B dir/headerremove
file contains

return-path

return-receipt-to

content-length

The 
.B dir/headeradd
file contains 

Precedence: bulk

The 
.B dir/text/help
file contains text sent in response to messages received at the help address.

.B Typical usage

To configure a replier at the address joe-replier-help@example.com, the user joe issues the
command

 replier-config ~/replier ~/\.qmail-replier joe-replier example.com

If email to joe@example.com is delivered to joe@joehost.example.com, the following command may be
appropriate to configure a replier at joe-replier-help@example.com:

 replier-config ~/replier ~/\.qmail-replier joe-replier joehost.example.com joe-replier example.com

If the user replier handles mail for the virtual domain replier.example.com, then the following
command creates a replier at help@replier.example.com:

 replier-config ~/replier ~/\.qmail replier example.com ""

.B Adding replier addresses

To add a new replier address that filters only the body of a message, edit the dir/bodyfilter
shell script and add a new case corresponding to the new address. Then create a symbolic link from
dir/qmail-bodyfilter to the \.qmail file that controls the new address. That's it!

Adding a command to filter the message header is entirely analagous, but use dir/headerfilter and
dir/qmail-headerfilter, while entire-message filters use dir/msgfilter and dir/qmail-msgfilter.

.B Bounce handling

By default, a replier created with replier-config silently throws away bounce messages. The \.qmail
file controlling bounces is a symbolic link pointing to dir/bouncer. Edit dir/bouncer to change the
treatment of bounce messages.

.SH Examples

as \.qmail commands
Save messages to test@example.com:

  | condtomaildir ./Test ifaddr to cc : test@example.com

Save messages to or from @example.com:

  | condtomaildir ./Test ifaddr to cc from : @example.com

Save a message if it was addressed to test@example.com:

  | condtomaildir ./Test iftocc test@example.com

.SH Email-based servers

This section provides several examples of email servers based on qtools. These are
simple-minded servers, designed only to demonstrate methods of providing services, and not
as examples of useful services.

  help: Fetch help information on the available email filters.

  cat: Return a copy of the original message.

  foldlines-20: Fold lines in the message body to 20 characters and
  return the result.

  presubject-OK: Add [OK] to the beginning of the Subject line of
  the message and send back the result.

  revline: Reverse each line of the message body (after folding
  lines to 1024 characters) and send back the result.

  rot13: Apply rot13 encoding to the message body and send back
  the result.

You can download the scripts for this example replier. The qtools package includes the programs
required for the examples above, but does not install them.

Documentation for the programs used in the examples is available here.
