.TH serialsmtp 1
.SH NAME
serialsmtp \- blast files across SMTP
.SH SYNOPSIS
.B serialsmtp
.I prefix
.I helohost
.SH DESCRIPTION
.B serialsmtp
is similar to
.BR serialqmtp ,
except that it transfers messages over SMTP.

.B serialsmtp
uses
.I helohost
as the local host name for saying hello to the remote SMTP server.
.I helohost
must be a fully-qualified domain name.

.B serialsmtp
supports ESMTP PIPELINING.

.B serialsmtp
assumes that all sender and recipient domain names
have already been canonicalized.
.SH REFERENCES
See
.B http://pobox.com/~djb/proto/smtp.html
for further information on SMTP.
.SH "SEE ASO"
tcpclient(1),
serialqmtp(1),
maildirserial(1),
qmail-smtpd(8)
