.TH uacl 1
.SH NAME
uacl \- test qmail-smtpd access list
.SH SYNOPSIS
.B uacl
.I sender recipient
where
.I sender
is the sender's email address and
.I recipient
is the recipient's email address.
.SH DESCRIPTION
.B uacl
tests accesslist and shows if a mail from sender \fIsender\fR will be allowed to be sent
to recipient \fIrecipient\fR.

.SH SEE ALSO
qmail-smtpd(8)
