#!/bin/sh
if [ -f /etc/lsb-release ] ; then
	. /etc/lsb-release
	if [ -f debian/control."$DISTRIB_ID"."$DISTRIB_RELEASE" ] ; then
		echo dh_gencontrol -- -cdebian/control."$DISTRIB_ID"."$DISTRIB_RELEASE"
	else
		echo dh_gencontrol
	fi
elif [ -f /etc/os-release ] ; then
	. /etc/os-release
	if [ -f debian/control."$ID"."$VERSION_ID" ] ; then
		echo dh_gencontrol -- -cdebian/control."$ID"."$VERSION_ID"
	else
		echo dh_gencontrol
	fi
else
	echo dh_gencontrol
fi
