.\" This manpage is Copyright (c) Alexey Mahotkin 2002-2004
.TH CHECKPASSWORD-PAM 8 "05 Oct 2009" GNU/Linux "Authentication"
.SH "NAME"
pam-checkpwd \- PAM-based checkpassword compatible authentication
.SH SYNOPSIS
.PP
pam-checkpwd [-\fBs\fR \fIPAM\fR-\fISERVICE\fR] [-\fBd\fR] [-\fBH\fR] [-\fBe\fR] -- \fIprog\fR \fIargs\fR...
.PP
pam-checkpwd --\fBhelp\fR
.PP
pam-checkpwd --\fBversion\fR
.PP
.I Additional debugging options (see below):
.RS
	[--debug]
.RE
.PP
.I Additional rarely used options (see below):
.RS
	[-H|--no-chdir-home]
.RE

.SH "DESCRIPTION"
.B pam-checkpwd
uses PAM to authenticate the remote user with
.I checkpassword
protocol.

.PP
.IR checkpassword -style
programs are usually run by network server programs that wish to
authenticate remote user.

.PP
.B pam-checkpwd
uses PAM service name specified by
.B PAM_SERVICE
environment variable, or by the -\fBs\fR " or " --\fBservice\fR command-line option.

.PP
After successful authentication, if -\fBe\fR or --\fBnoenv\fR or option is not specified,
\fBpam-checkpwd\fR sets up supplementary groups of authenticated user,
its gid, its uid, and its working directory (those values are taken from the system
user database).

.PP
Normally,
.B pam-checkpwd
switches to user home directory.   If
-\fBH\fR or --\fBno\fR-\fBchdir\fR-\fBhome\fR option is specified, this step is skipped.
This option is useful when you have automounted home directories, but mail is delivered to a
central location.

.PP
Finally,
.B pam-checkpwd
executes
.I prog
with
.I args
as its arguments.

.PP
\fB--\fR is used as usual to separate the \fBpam-checkpwd\fR own options from
\fIprog\fR options.

.PP
\fBpam-checkpwd\fR logs authentication failures (or all actions, if
--\fBdebug\fR option is used) to stderr.

.SH "ENVIRONMENT VARIABLES"
.TP
.B PAM_SERVICE
.B pam-checkpwd
uses contents of
.B PAM_SERVICE
environment variable to specify the PAM service name.  This could be
overriden by -\fBs\fR option, see above.

.PP
Before invoking \fIprog\fR, \fBpam-checkpwd\fR sets environment variables
.BR USER ", " HOME ", and " SHELL
to appropriate values.  If --\fBnoenv\fR option is specified, this step is
skipped and the variables are left alone. This is needed when you have
virtual users which are not listed in your \fI/etc/passwd\fR,
and you need to only do authentication. Setting up process
environment is handled by some other application like \fBsetuidgid\fR.

.SH "DEBUGGING"
.PP
You can turn on debugging using the --\fBdebug\fR option. \fBpam-checkpwd\fR
starts to log all of its actions and the results of those actions to to stderr.

There is a way to manually trace how the \fBpam-checkpwd\fR
authenticates: use the shell redirection option. In this case
\fBpam-checkpwd\fR reads \fIcheckpassword\fR protocol data from stdin,
and logs actions to stderr. You can trace the authentication for the given user
and password with the following command-line

.PP
# printf "%s\\0%s\\0%s\\0" username password timestamp \\
.br
  | pam-checkpwd -s SERVICE -d -- /usr/bin/id 3<&0

.PP
It will trace the PAM authentication process for the user
\fIusername\fR with password \fIpassword\fR, and run the \fBid\fR
program, which will report the user and groups \fBpam-checkpwd\fR
switched to.

.SH "SEE ALSO"
pam-multi(8)
.PP
http://cr.yp.to/checkpwd.html
.PP
"PAM Administrator's Guide" for your operating system.

.SH "AUTHOR"
.PP
This version of pam-checkpwd was written by Manvendra Bhangui <mbhangui@gmail\&.com> by 
hacking checkpassword-pam by Alexey Mahotkin <alexm@hsys\&.msk\&.ru>
.PP
.I checkpassword
interface was designed by Daniel J. Bernstein.
