.TH curvedns-keygen 8 2011-12-15

.SH NAME
curvedns-keygen \- Generate private/public key pair for curvedns(8)

.SH SYNOPSIS
.B curvedns-keygen
[
.I path name
]

.SH DESCRIPTION
.B curvedns-keygen
creates a private/public keypair to be used by
.BR curvedns (8).
When run without arguments, it will simply print the public and private keys
in hex format to STDOUT, and the public key also in uz5 format.
.P
When run with arguments, it will create
.IR path /env/
if necessary, and write the hex private key to
.IR path /env/CURVEDNS_PRIVATE_KEY,
unless the file already exists. It will also print the full nameserver name
constructed from the uz5 public key and the given
.IR name .
.P
.B Invoking curvedns-keygen with arguments is not recommended!

.SH AUTHORS
.B curvedns-keygen
was created by the CurveDNS Project.
.P
This man page was written by Peter Conrad <conrad@quisquis.de>.

.SH SEE ALSO
curvedns(8), http://curvedns.on2it.net/ , http://www.dnscurve.org/

