.TH autoresponder 1
.SH NAME
autoresponder \- Rate and time limited autoresponder for qmail/indimail
.SH SYNOPSIS
\fBautoresponder\fR [\fIOPTIONS\fR]
.I messagefile
.I directory

.SH OPTIONS

  -c       Copy message into response
  -q       Don't show error messages
  -l       Lax Mode. Respond even if recipient is not in To, Cc, Bcc,
           Resent-To, Resent-Cc, Resent-Bcc headers
  -L       Don't try to make links to conserve inodes
  -N       Don't send, just send autoresponse to standard output
  -n NUM   Set the maximum number of replies (defaults to 1)
  -t TIME  Set the time interval, in seconds (defaults to 1 week,
           -1 for no rate limiting)
  -T STR   Added Content-Type field. This option is valid without
           the -c option. \fISTR\fR can be a path to a file having
           the content-type. A newline at the end will be removed
  -s STR   Add the subject to the autoresponse, prefixed by STR
  -S STR   The subject in autoresponse (defaults to the subject in
           received mail)
  -b SDate Date in YYYY-mm-dd HH:MM:SS from  which the autoresponder
           should start functioning
  -e EDate Date in YYYY-mm-dd HH:MM:SS after which the autoresponder
           should stop functioning
  -f addr  Set addr as the From field in autoresponse (defaults to
           recipient)

.SH DESCRIPTION
.B autoresponder
is a RFC 3834 compliant email responder.
.B autoresponder
creates temporary files in \fIdirectory\fR to track sender's rates. If more than NUM messages are
received from the same sender within TIME seconds of each other, no response is sent. This
program must be run by qmail. Put "|autoresponder \fImessagefile\fR \fIdirectory\fR" into
your ".qmail" file before other delivery instructions. \fImessagefile\fR is a pre-formatted
response, including headers, and \fIdirectory\fR is the directory into which rate-limiting
information will be stored. By default
.B autoresponder
will reply with the address of the recipient. This behaviour can be altered by setting the
environment variable SERVICE_RESPONDER. The value of SERVICE_RESPONDER can be set to a friendly
name which will appear in the 'from address'. For a service responder, the address will be
determined by the \fIbouncefrom\fR and \fIbouncehost\fR control files. The Return-Path however in
both the cases will be null to prevent brain damaged MTA like M$Exchange to send bounces/reply to
autoresponder.

.B autoresponder
replaces occurrences of the following special characters in the \fImessagefile\fR.

.IP \[bu] 2
%S - Subject of the original mail
.IP \[bu]
%D - Date header in the original mail
.IP \[bu]
%d - Date of the auto response
.IP \[bu]
%t - Envelope recipient 
.IP \[bu]
%T - Recipient(s) to whom the mail has been addressed
.IP \[bu]
%C - Recipient(s) to whom the mail has been Copied
.IP \[bu]
%B - Recipient(s) to whom the mail has been Blind Copied
.IP \[bu]
%F - Sender of the orignal mail
.IP \[bu]
%R - Return Path of the orignal mail
.IP \[bu]
%r - Bogosity value of the orignal mail (Spam Rating)
.IP \[bu]
%M - Mailer used by the sender
.IP \[bu]
%m - Message ID of the original mail
.IP \[bu]
%% - The % sign itself

.SH Features
 - Limits rate of automatic responses (defaults to a maximum of one
   message every week).
 - Validity period can be specified (Start Date or End Date or
   combination of Start Date and End Date)
 - Will not respond to nearly every type of mailing list or bulk email.
 - Will not respond to spam mails (mails filtered by bogofilter).
   Uses X-Bogosity header and look for 'Yes' in the header.
 - WIll not respond to senders listed in badrcptto, badrcptpatterns, badrcptto.cdb
   and MySQL table listed in badrcptto.sql
 - Will not respond to bounce messages or MAILER-DAEMON.
 - Bounces looping messages.
 - Can insert the original subject into the response.
 - Can copy original message into response as MIME
 - Can use links in the rate-limiting data directory to limit inode
   usage to a single inode.
 - Inserts Auto-Submitted, In-Reply-To and References headers as per
   RFC 3834. The value of Auto-Submitted headers is set to
   'auto-replied'.
   In-Reply-To and References headers are set to the Message ID in the
   original mail (if present).
 - Can insert header fields from the original mail into the
   autoresponse if special characters are inserted in the
   \fImessagefile\fR.
 - RFC 3834 compliant

.SH SEE ALSO
vacation(8), vmoduser(1), vdelivermail(8), dot-qmail(5)
