.TH cdbmake 1
.SH NAME
.PP
cdbmake \- write cdb by reading series of encoded records on input
.PP
cdbdump \- read cdb in stdin and print database in \fBcdbmake\fR format.

.SH SYNOPSIS
\fBcdbmake\fR \fIf\fR \fIftmp\fR
.PP
\fBcdbdump\fR

.SH DESCRIPTION

\fBcdbmake\fR reads a series of encoded records from its standard input and writes a
constant database to \fIf\fR.

\fBcdbmake\fR ensures that \fIf\fR is updated atomically, so programs reading \fIf\fR never
have to wait for \fBcdbmake\fR to finish. It does this by first writing the database to 
\fIftmp\fR and then moving \fIftmp\fR on top of \fIf\fR. If \fIftmp\fR already exists, it is
destroyed. The directories containing \fIftmp\fR and \fIf\fR must be writable to \fBcdbmake\fR;
they must also be on the same filesystem.

\fBcdbdump\fR reads a constant database from its standard input and prints the database
contents, in \fBcdbmake(1)\fR format, on standard output. 

.SH "SEE ALSO"
cdbdump(1)
