.TH checkdomain 1
.SH NAME
checkdomain
.SH SYNOPSIS
.B checkdomain
.I dom ...
where
.I dom
is a domain name.
.SH DESCRIPTION
.B checkdomain
reads email addresses from standard input, and compares the domain portion with each 
.I dom
without regard to case. If no addr appears, 
.B checkdomain
uses the domain part of the environment variable $RECIPIENT as 
.I dom.
If it finds a match,
.B checkdomain
exits 0. Otherwise, it exits 100.

.B checkdomain
reads addresses in the form output by 
.B 822addr.
Each address appears as a null-terminated line with an introductory character.
A + character introduces a delivery address, and a ( character introduces a comment. The
introductory characters are not part of the address. 
.B checkdomain
compares its arguments only with delivery addresses, and ignores comments.

If
.B checkdomain
finds an address matching dom, it exits 0. Otherwise, it exits 100. 
