.TH dktest 8
.SH NAME
dktest \- exercise the domainkeys library
.SH SYNOPSIS
.B dktest
.I opts

.I opts
is a series of getopt-style options.

.SH DESCRIPTION
.B dktest
exercises the domainkeys library. Both signing and verification merely print out the DK header.
They do not keep a copy of the input file. You will need to do something like this:

.EX
 (./dktest -s @controldir@/domainkeys/dog </tmp/testmsg; cat /tmp/testmsg)\
 | ./dktest -v
.EE

Here are the options:
.IP \[bu] 2
-s
\fIkey\fR: Sign. 
.I key
is a path to a file containing a PEM-format private key. The base name of
the file is  used  as  the  selector. Reads the email message on stdin. Prints the
.B DomainKey-Signature
header.

.IP \[bu]
-v: Verify. Verifies the email on stdin. Exits with a non-zero exit code and a message to
stderr if there was a problem with the signature. Always prints a
.B DomainKey-Status:
header to stdout. This option requires the \fBs\fR._domainkey.\fBd\fR txt record in
dns (public key). Here \fBs\fR is the selector and \fBd\fR is the domain
.EX

 Comment: DomainKeys? See http://antispam.yahoo.com/domainkeys
 DomainKey-Signature: a=rsa-sha1; q=dns; c=simple;
  s=dog; d=indimail.org; 
  b=CndyNmOBqXD+d6qLGVjVua/oDJetLzAKAh3JoId93GmWRg1Y40DUdvZZhw8tTIoZ;
.EE

.IP \[bu]
-c \fI[simple|nofws]\fR Canonicalization.
Defaults to simple.

.IP \[bu]
-t \fIn\fR: Test.
.I n
is a number indicating which internal test is being performed. The meanings of the numbers
are documented in the source code.

.IP \[bu]
-d \fIdns\fR Test dns record

.IP \[bu]
-b \fIn\fR: Buffer size.
.I n
is a number which forces the buffer size. Only needed for testing.

.IP \[bu]
-D \fIdkdomain\fR: set d= tag.
.I dkdomain
is set as the value for d= tag

.IP \[bu]
-h:
include h= tag when signing

.IP \[bu]
-r:
only include unique headers in the signature generation, implies -h

.IP \[bu]
-T:
Generate DomainKey-Trace: header, shows Diff header if Verifying.

.SH "SEE ALSO"
dkim(8),
qmail-dk(8),
qmail-dkim(8),
dknewkey(8),
rfc-4870(5),
rfc-4871(5)
