.TH ofmipname 8
.SH NAME
ofmipname \- build a name-address database for ofmipd
.SH SYNTAX
.B ofmipname
.I name.cdb
.I name.tmp
.SH DESCRIPTION
.B ofmipname
reads a name-address table from its standard input.
It converts the table into a database
suited for quick access by
.IR ofmipd .

.B ofmipname
writes the database to
.IR name.tmp ;
it then moves
.I name.tmp
to
.IR name.cdb .
.I name.tmp
and
.I name.cdb
must be on the same filesystem.

If there is a problem creating
.IR name.tmp ,
.B ofmipname
complains and leaves
.I name.cdb
alone.

The database format is portable across machines.
.SH "INPUT FORMAT"
The name-address table is a series of lines of the form
.I key\fB:\fIname\fB:\fIaddress\fB:\fI
(including the final colon).
If
.B ofmipd
is given
.IR key
(after hostname rewriting)
as the return path for a message,
it will replace the return path with
.IR address ,
eliminate any existing
.B From
field in the message, and
insert a new
.B From
field showing
.I name
and
.IR address .

.B ofmipname
ignores any line beginning with #.

For example:

.EX
   # From: "Joe Shmoe" <J.Shmoe@sun.af.mil>
   joe@sun.af.mil:Joe Shmoe:J.Shmoe@sun.af.mil:
.EE
.SH "SEE ALSO"
cdb(3),
ofmipd(8)
