.\" Manpage for rewind, version 0.1.0
.\" (C) Sun Feb  7 18:24:57 EST 1999, Len Budney
.\"
.TH "rewind" 1 "0.1.0"


.SH NAME
rewind \- Reset stdin to start of input, if seekable

.SH SYNOPSIS
.I rewind

.SH DESCRIPTION
.P
.I rewind
returns
.I stdin
to the start of its input, if input is coming from a seekable file. If
stdin is not seekable, then
.I rewind
has no effect.

.P
.I rewind
permits a shell script to perform multiple actions on an input
file. This is particularly handy when input files are email messages,
and a shell script performs multiple actions, such as forwarding and
also filing away.

.SH "SEE ALSO"
maildircmd(1), serialcmd(1).
