.TH incrmesg 1
.SH NAME
incrmesg \- Display incremental messages in log files

.SH SYNOPSYS
.B incrmesg
\fIlogfile1\fR [\fIlogfile2\fR] ...

.SH DESCRIPTION
.PP
\fBincrmesg\fR takes name of logfiles as command line arguments, and for each logfile,
displays, all lines that have incrementally got added into the logfile since the last
time \fBincrmesg\fR was run.

\fBincrmesg\fR(1) maintains the check point against the postion last read for each logfile. It also
maintains the message count for each logfile. Both of these numbers are maintained in the
file \fIlogfile\fR.seek in /var/tmp/incrmesg. This directory where the checkpoint is maintained can
be changed by setting environment variable \fBSEEKDIR\fR.

\fIlogfile1\fR, \fIlogfile2\fR can be any text file. It can be used to show the diff between
the previous version and the current version.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic
message is printed.

.SH "SEE ALSO"
logclient(1), logsrv(8)
