.TH rpclog 8
.SH NAME
rpclog \- RPC based log collector

.SH SYNOPSYS
\fBrpclog\fR [-f]

.SH DESCRIPTION
\fBrpclog\fR(8) provides RPC based communications to clients to push log messages.
\fBrpclog\fR(8) can receive messages from multiple log message monitors like
\fBlogsrv\fR(8).

.SH OPTIONS
.TP
\fB\-f\fR
Run in foreground. This option prevents \fBrpclog\fR to detach from the terminal and run
in the background. This option is required if you want to run under supervise(8).

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic
message is printed.

.SH "SEE ALSO"
logsrv(8), incrmesg(1), logclient(1), supervise(8)

