'\" t
.\"     Title: courier-unicode
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/11/2017
.\"    Manual: Courier Unicode Library
.\"    Source: Courier Unicode Library
.\"  Language: English
.\"
.TH "COURIER\-UNICODE" "7" "03/11/2017" "Courier Unicode Library" "Courier Unicode Library"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
courier-unicode \- Courier Unicode Library
.SH "SYNOPSIS"
.sp
.nf
#include <courier\-unicode\&.h>
.fi
.SH "DESCRIPTION"
.PP
This library implements several algorithms related to the
\m[blue]\fBUnicode Standard\fR\m[]\&\s-2\u[1]\d\s+2\&. This library uses
\m[blue]\fB\fBiconv\fR(3)\fR\m[]\&\s-2\u[2]\d\s+2
to convert text in a given character set to unicode\&. Any character set displayed by
\fBiconv \-\-list\fR
can be specified for the corresponding character set parameter\&. Additionally,
courier\-unicode\&.h
defines a special character string
unicode_x_imap_modutf7
that specifies the pseudo\-character set for the modified\-UTF7 encoding used in IMAP\&. This string can also be appended by a space, and up to fifteen additional US\-ASCII characters\&. The resulting character set also encodes these additional characters, in addition to unicode characters, with modified\-UTF7\&.
.PP
The C++ compiler must have C++11 support\&. Minimum usable version of gcc appears to be gcc 4\&.4 with the
\-std=c++0x
flag\&. Current versions of gcc use C++11, or higher, by default and do not require extra flags\&. Consult the packaging documentation for the Courier Unicode Library for information on any compiler flags that are needed to build software that links with this library\&.
.SH "SEE ALSO"
.PP
\fBunicode_convert\fR(3),
\fBunicode_default_chset\fR(3),
\fBunicode_html40ent_lookup\fR(3),
\fBunicode_category_lookup\fR(3),
\fBunicode_grapheme_break\fR(3),
\fBunicode_line_break\fR(3),
\fBunicode_script\fR(3),
\fBunicode_word_break\fR(3),
\fBunicode_uc\fR(3),
\fBunicode::iconvert::convert\fR(3),
\fBunicode::iconvert::convert_tocase\fR(3),
\fBunicode::iconvert::fromu\fR(3),
\fBunicode::iconvert::tou\fR(3),
\fBunicode::tolower\fR(3),
\fBunicode::linebreak\fR(3),
\fBunicode::wordbreak\fR(3)\&.
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
Author
.RE
.SH "NOTES"
.IP " 1." 4
Unicode Standard
.RS 4
\%http://www.unicode.org/standard/standard.html
.RE
.IP " 2." 4

	      \fBiconv\fR(3)
.RS 4
\%http://manpages.courier-mta.org/htmlman3/iconv.3.html
.RE
