'\" t
.\"     Title: unicode::iconvert::convert_tocase
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/11/2017
.\"    Manual: Courier Unicode Library
.\"    Source: Courier Unicode Library
.\"  Language: English
.\"
.TH "UNICODE::ICONVERT::C" "3" "03/11/2017" "Courier Unicode Library" "Courier Unicode Library"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
unicode::iconvert::convert_tocase \- unicode uppercase, lowercase, and titlecase conversion
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <courier\-unicode\&.h>
.fi
.ft
.HP \w'std::string\ unicode::iconvert::convert_tocase('u
.BI "std::string unicode::iconvert::convert_tocase(const\ std::string\ &" "text" ", const\ std::string\ &" "charset" ", char32_t\ (*" "first_char_func" ")(char32_t), char32_t\ (*" "char_func" ")(char32_t));"
.HP \w'std::string\ unicode::iconvert::convert_tocase('u
.BI "std::string unicode::iconvert::convert_tocase(const\ std::string\ &" "text" ", const\ std::string\ &" "charset" ", bool\ &" "err" ", char32_t\ (*" "first_char_func" ")(char32_t), char32_t\ (*" "char_func" ")(char32_t));"
.SH "DESCRIPTION"
.PP
The overloaded
\fBunicode::convert::convert_tocase\fR() function converts the
\fItext\fR
parameter, in the
\fIcharset\fR
characters to lowercase, uppercase, and titlecase\&.
\fItext\fR
gets converted, internally, into unicode\&.
\fIfirst_char_func\fR
and
\fIchar_func\fR
are either:
\fBunicode_lc\fR,
\fBunicode_uc\fR, or
\fBunicode_tc\fR\&. If the converted text string is not empty,
\fIfirst_char_func\fR
converts the first unicode character in the text string, and
\fIchar_func\fR
converts any remaining characters\&.
\fBunicode_lc\fR
converts its character to lowercase,
\fBunicode_uc\fR
to uppercase, and
\fBunicode_tc\fR
to titlecase\&. Finally, the unicode string gets converted back to
\fIcharset\fR, which gets returned\&.
.PP
The optional
\fIerr\fR
parameter gets set to true if an error was encounted converting the text string to or from unicode\&.
.SH "SEE ALSO"
.PP
\fBcourier-unicode\fR(7),
\fBunicode::convert::convert\fR(3),
\fBunicode_convert\fR(3),
\m[blue]\fB\fBiconv\fR(3)\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
Author
.RE
.SH "NOTES"
.IP " 1." 4

	      \fBiconv\fR(3)
.RS 4
\%http://manpages.courier-mta.org/htmlman3/iconv.3.html
.RE
