'\" t
.\"     Title: unicode_uc
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/11/2017
.\"    Manual: Courier Unicode Library
.\"    Source: Courier Unicode Library
.\"  Language: English
.\"
.TH "UNICODE_UC" "3" "03/11/2017" "Courier Unicode Library" "Courier Unicode Library"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
unicode_uc, unicode_lc, unicode_tc, unicode_convert_tocase \- unicode uppercase, lowercase, and titlecase character lookup
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <courier\-unicode\&.h>
.fi
.ft
.HP \w'char32_t\ unicode_uc('u
.BI "char32_t unicode_uc(char32_t\ " "c" ");"
.HP \w'char32_t\ unicode_lc('u
.BI "char32_t unicode_lc(char32_t\ " "c" ");"
.HP \w'char32_t\ unicode_tc('u
.BI "char32_t unicode_tc(char32_t\ " "c" ");"
.HP \w'char\ *unicode_convert_tocase('u
.BI "char *unicode_convert_tocase(const\ char\ *" "str" ", const\ char\ *" "charset" ", char32_t\ (*" "first_char_func" ")(uncode_char), char32_t\ (*" "char_func" ")(uncode_char));"
.SH "DESCRIPTION"
.PP
\fBunicode_uc\fR(),
\fBunicode_lc\fR(),
\fBunicode_tc\fR() return the uppercase, lowercase, or the titlecase equivalent of the unicode character
\fIc\fR\&. If this character does not have an uppercase, lowercase, or a titlecase equivalent, these functions return
\fIc\fR, the same character\&.
.PP
\fBunicode_convert_tocase\fR() takes the string
\fIstr\fR
in the character set
\fIcharset\fR\&.
\fIfirst_char_func\fR
and
\fIchar_func\fR, each, should be
\fBunicode_uc\fR,
\fBunicode_lc\fR, or
\fBunicode_tc\fR\&.
\fBunicode_convert_tocase\fR() returns a malloc()ed buffer\&. The first unicode character in
\fIstr\fR
gets processed by
\fIfirst_char_func\fR, and all other characters by
\fIchar_func\fR\&.
.SH "SEE ALSO"
.PP
\fBcourier-unicode\fR(7),
\fBunicode_convert\fR(3),
\fBunicode_default_chset\fR(3),
\fBunicode_html40ent_lookup\fR(3),
\fBunicode_category_lookup\fR(3),
\fBunicode_grapheme_break\fR(3),
\fBunicode_word_break\fR(3),
\fBunicode_line_break\fR(3)\&.
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
Author
.RE
