.TH nssd 8
.SH NAME
INDIMAIL/sbin/nssd \- NSS daemon for IndiMail
.SH SYNOPSIS
\fBnssd\fR [-\fBf\fR \fIconfig\fR] [ -\fBd\fR \fIlevel\fR] | [-\fIV\fR]

.SH DESCRIPTION
There are various functions to lookup users and groups in a local environment. Traditionally,
this is done by using files (e.g., /etc/passwd, /etc/hosts, etc), but other nameservices
(like the Network Information Service (NIS) and the Domain Name Service (DNS)) are popular,
and have been hacked into the C library, usually with a fixed search order. The Name Service
Switch (NSS) provides a cleaner solution to extend the lookup to other databases. In Unix-like
operating systems, the Name Service Switch (NSS) allows Unix configuration databases to be
provided by different sources, including local files (for example: /etc/passwd, /etc/shadow,
/etc/group, /etc/hosts), LDAP, and other sources.
.PP
\fBnssd\fR provides \fBIndiMail\'s\fR database as an alternate Unix configuration database for
/etc/passwd, /etc/shadow and /etc/group. The actual implementation of nssd is implemented by
having \fBnssd\fR listening on a UNIX domain socket \fB/tmp/nssd.sock\fR and a library
which extends the functions getpwnam(3), getpwuid(3), getpwent(3), getspnam(3), getspent(3),
getgrnam(3), getgrgid(3), getgrent(3). These functions are implemented as a shared library in
\fB/usr/lib/libnss_nssd.so\fR. All of these functions connect to the \fBnssd\fR daemon to lookup
users and groups in \fBIndiMail\'s\fR MySQL database. In fact one can use any MySQL database by
modifying the relevant SQL query string in the \fBnssd\fR configuration file
\fBINDIMAIL/etc/nssd.conf\fR.
.PP
To enable the \fInssd\fR library, the following entries should be made in /etc/nsswitch.conf
.sp 1n
.PD 0
.TP 16
passwd:
files nssd
.TP
shadow:
files nssd
.TP
group:
files nssd
.PD
.LP
\fBnssd\fR uses \fBsyslog(3)\fR to log all messages. You can improve the NSS performance by
starting \fBnscd(8)\fR name service cache daemon.

.SH OPTIONS
.PP
.TP
\fB\-V\fR
Display Version Numbers
.TP
\fB\-f\fR \fIconfig\fR
nssd config file path
.TP
\fB\-d\fR \fIlevel\fR
Set debug level.  Higher the level, more the verbosity
of messages which get logged. Set \fIlevel\fR to \fIdebug\fR
to log everything. Set \fIlevel\fR to \fIalert\fR to log all
alert messags and above. \fIlevel\fR determines the
importance of the message. The levels are, in order
of decreasing importance:

.RS
.nf
.ta 5c 10c
Level	Description
-----------	------------------------------------
LOG_EMERG	| system is unusable
LOG_ALERT	| action must be taken immediately
LOG_CRIT	| critical conditions
LOG_ERR	| error conditions
LOG_WARNING	| warning conditions
LOG_NOTICE	| normal, but significant, condition
LOG_INFO	| informational message
LOG_DEBUG	| debug-level message
.fi
.RE

.SH SEE ALSO
IndiMail(7),
nssd.conf(5),
nscd(8),
nscd(5),
nsswitch.conf(5),
getpwnam(3), getpwuid(3), getpwent(3), getspnam(3), getspent(3), getgrnam(3), getgrgid(3),
getgrent(3).
