#! /bin/sh
#
# $Id: mkpop3dcert.in,v 1.1 2000/10/06 17:50:37 mrsam Exp $
#
# Copyright 2000 Double Precision, Inc.  See COPYING for
# distribution information.
#
# This is a short script to quickly generate a self-signed X.509 key for
# POP3 over SSL.  Normally this script would get called by an automatic
# package installation routine.

test -x /usr/bin/openssl || exit 0

prefix="/var/indimail"

if test -f /var/indimail/share/pop3d.pem
then
	echo "/var/indimail/share/pop3d.pem already exists."
	exit 1
fi

cp /dev/null /var/indimail/share/pop3d.pem
chmod 600 /var/indimail/share/pop3d.pem
chown root /var/indimail/share/pop3d.pem

cleanup() {
	rm -f /var/indimail/share/pop3d.pem
	rm -f /var/indimail/share/pop3d.rand
	exit 1
}

dd if=/dev/urandom of=/var/indimail/share/pop3d.rand count=1 2>/dev/null
/usr/bin/openssl req -new -x509 -days 365 -nodes \
	-config /var/indimail/etc/pop3d.cnf -out /var/indimail/share/pop3d.pem -keyout /var/indimail/share/pop3d.pem || cleanup
/usr/bin/openssl gendh -rand /var/indimail/share/pop3d.rand 512 >>/var/indimail/share/pop3d.pem || cleanup
/usr/bin/openssl x509 -subject -dates -fingerprint -noout -in /var/indimail/share/pop3d.pem || cleanup
rm -f /var/indimail/share/pop3d.rand
