.TH "alterMIME" "1" "1.4.0.1" "Paul L Daniels" "MIME decoders"
.SH "NAME"
alterMIME \- MIME encoded email pack alteration tool
.SH "SYNTAX"
altermime --input=<input mime pack>   ( --input=- for stdin )
.br 
	[--disclaimer=<disclaimer file>]
.br 
	[--disclaimer-html=<HTML disclaimer file>]
.br 
	[--disclaimer-b64=<BASE64 encoded dislcaimer>]
.br 
	[--htmltoo]
.br 
    [--force-into-b64]
.br 
	[--force-for-bad-html]
.br 
	[--multipart-insert]
.br 
	[--remove=<remove file name (regex)>] (if filename contains a /, matches on mime-type )
.br 
	[--removeall]
.br 
	[--remove-by-regex=<filename regex>] (if the regex contains /, matches on mime-type)
.br 
	[--replace=<filename to replace> --with=<replace with>]
.br 
	[--xheader="..."
.br 
	[--alter-header="..." --alter-with="..." --alter-mode=<prefix|suffix|replace>]
.br 
	[--altersigned]
.br 
	[--no-qmail-bounce]
.br 
	[--verbose]
.br 
	[--log-stdout]
.br 
	[--log-stderr]
.br 
	[--log-syslog]
.br 
	[--debug]
.br 
	[--version]
.SH "DESCRIPTION"

The alterMIME program (and objects) has been written
to facilitate the modification of MIME encoded email packs
when such things as disclaimer additions and attachment
nullification is required.

alterMIME is part of the suite of software which includes
Inflex email scanner, ripMIME attachment extractor and the
XaMime commercial email scanner.

.SH "OPTIONS"
.LP 
.TP 
--input=, Sets the mailpack file to be the filename supplied, if the filename is a
single '-' (hyphen) then the mailpack is sourced via stdin and outputted via stdout.

.TP 
--disclaimer=, Set the plaintext disclaimer source file.

.TP 
--disclaimer-html=, Set the HTML disclaimer source file.

.TP 
--disclaimer-b64=, Set the BASE64 encoded disclaimer source file (implies --force-into-b64).

.TP 
--force-for-bad-html, Force adding of the HTML disclaimer even when HTML is not correctly formatted the HTML portion of the email body ( if there is no explicitly defined HTML dislcaimer, see --disclaimer-html )

.TP 
--htmltoo, Sets alterMIME to insert the plaintext disclaimer into the HTML portion of the email body (if there is no explicitly defined HTML dislcaimer, see --disclaimer-html)

.TP 
--disclaimer-b64=, Set the BASE64 encoded disclaimer source file (implies --force-into-b64).

.TP 
--remove=, Remove any attachments which match the filename supplied, if the filename text contains a forward-slash '/', then the matching will occur based on content-type headers rather than by filename.

.TP 
--removeall, Remove all attachments

.TP 
--replace=, Replace attachments matching the given filename. Requires to be used with --with.

.TP 
--with=, Replace the attachments specified by --replace with the file specified.

.TP 
--xheader=, Insert a header line as specified into the first set of headers.

.TP 
--alter-header="..." --alter-with="..." --alter-mode=(prefix|suffix|replace) Alter an existing header in the mailpack.  This function modifies the value of the header, as apposed to the header name.

.TP 
--altersigned, Force alterMIME to modify 'signed' emails

.TP 
--no-qmail-bounce,  Don't search into email bodies for attachment headers

.TP 
--verbose, Describe details of the process occuring

.TP 
--log-stdout, Send all output messages to stdout

.TP 
--log-stderr, Send all output messages to stderr

.TP 
--log-syslog, Send all output messages to syslog

.TP 
--debug, Provide greater verbosity and debugging information

.TP 
--version, display the alterMIME version string

.SH "EXAMPLES"
.LP 
To add a disclaimer to the content of mail in mailpack and output it
to stdout
.LP 
altermime --input=mailpack --disclaimer=/var/qmail/control/disclaimer
.LP 

.SH "AUTHORS"
Paul L Daniels
.br 
ripMIME WWW site http://www.pldaniels.com/ripmime
.br 
ripMIME mailing list <altermime\-general@pldaniels.com>
.br 
For mailpacks which do not appear to decode correctly \- please email to <mailpacks\-2004@pldaniels.com>
.SH "SEE ALSO"
.BR ripmime (1),
.BR inflex (1),
.BR ripole (1),
.BR opentnef (1)
