.LL 8i
.TH vbulletin 1
.SH NAME
vbulletin - instant bulletin for IndiMail

.SH SYNOPSYS
.B vbulletin
[\fB\-f\fR \fIfilename\fR] [\fB\-e\fR \fIexclude email addresses file\fR]
[\fB\-V\fR] [\fB\-n\fR] [\fB\-c\fR] [\fB\-h\fR] [\fB\-s\fR] [\fB\-a\fR]
[-S subscriber_list_file] [virtual_domain ...]

.SH DESCRIPTION
.PP
.B vbulletin
implements instant bulletin for IndiMail. It does this by copying an email file in the user's
inbox (Maildir). The various options given on the command line decide how this copying is to
be done. vbulletin has setuid set to root and runs as user indimail.

.SH OPTIONS
.PP
.TP
[\fB\-V\fR]
Verbose mode. Prints out each email address it is sending to. 
.TP
[\fB\-f\fR \fIfilename\fR]
File containing the email message to be posted. 
.TP
[\fB\-e\fR \fIexclude email addresses file\fR]
File containing a list of email addresses to exclude from posting. 
.TP
[\fB\-n\fR]
Don't actually mail it. using \fB\-V\fR and \fB\-n\fR can be used to list out all virtual
domain email accounts. 
.TP
[\fB\-c\fR]
Default, copy message to users directory.
.TP
[\fB\-h\fR]
Make a hard link from email file to virtual users directory. Email file must be on the same
physical device as the virtual users directories. This will save disk space. 
.TP
[\fB\-s\fR]
Make a soft link from the email file to the virtual users directory. This will save on disk
space but will not remove the file when all users read it. If the original file is deleted,
users will not be able to read the message.
.TP
\fB\-S\fR \fIsubscriber_list\fR
Take the list of subscriber list from a file and populates the bulkmail table. The IMAP4/POP3
daemon query this table when a user logs in and creates a link in the user's inbox (Maildir)
to the email_file. This causes instant delivery of the bulletin without using any disk space.
For a clustered domain, vbulletin can be safely run on all the hosts giving the same
subscriber_list file. vbulletin takes care of identifying the subscribers listed in
subscriber_list file present on the host and those which are present on some other host.
.TP
\fB\-a\fR
Sends an instant bulletin to the entire domain. The file is copied to the bulk mail directory
with ,all appended.
.TP
[\fIvirtual domain\fR ... ]
List of domains to send the message to. If this is not supplied then the message is sent to all virtual domains. 

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic
message is printed.
