.TH 822headerok 1
.SH NAME
822headerok \- Check if email message header is 822-compliant.
.SH SYNOPSIS
.B 822headerok
.SH DESCRIPTION
.B 822headerok
reads an 822-format email message from standard input. If the message header is
822-compliant, 822headerok exits 0. If the header is not 822-compliant,
822headerok exits 100. If it encounters a read error, 822headerok exits 111.
In any case, 822headerok writes no output.

Under 822, the header is terminated by the end of the message or by a blank
line. If it sees a nonblank line that cannot be part of an 822-format header
field, 822headerok considers the message noncompliant, and exits 100.

Note that the UUCP-style From_ line placed before a message in an mbox file is
not part of the message. 
