.TH columnt 1
.SH NAME
columnt \- align columns in a table 
.SH SYNTAX
.B columnt
.SH DESCRIPTION
.B columnt
reads a table of whitespace-separated lines.

.B columnt
then prints the table,
changing the spacing so that
the first column takes the same amount of space in every line,
the second column takes the same amount of space in every line,
etc.

In the
.B columnt
output,
all columns except the last are right-justified;
the last column is left-justified.
There are two spaces between adjacent columns.

.B columnt
needs enough memory to read the entire input.
Other than this,
it has no limits on line length or on the number of columns.
.SH "SEE ALSO"
column(1)
