.TH tai2tai64n 1
.SH NAME
tai2tai64n \- convert TAI timestamps to TAI64N
.SH SYNOPSIS
.B tai2tai64n
.SH DESCRIPTION
.B tai2tai64n
reads lines from standard input.
If a line does not begin with a TAI label,
.B tai2tai64n
writes it out without change.
Otherwise,
.B tai2tai64n
converts the timestamp to TAI64N format, and writes out the
converted timestamp followed by the rest of the original line.
.SH SEE ALSO
multilog, qmail-analog, tai64n, tai64nlocal, tai64n2tai
