.LL 8i
.TH adminclient 8
.SH NAME
adminclient \- Client for running IndiMail programs remotely

.SH SYNOPSYS
\fBadminclient\fR \fB\-h\fR \fIadminHost\fR \fB\-p\fR \fIport\fR \fB\-u\fR \fIadminUser\fR \fB\-P\fR \fIadminPassword\fR [\fB\-n\fR \fIcertfile\fR] \fB\-c\fR \fICommand\fR

.SH DESCRIPTION
.PP
\fBadminclient\fR is the administration client for administering IndiMail's clustered domains.
It has a simple mechanism by which administrators can connect to the administration server,
\fBindisrvr\fR and issue commands to execute any of the IndiMail programs \fICommand\fR.
On successful validation of password, \fBadminclient\fR executes the specified IndiMail
administration program on the remote host by connecting to \fBindisrvr(8)\fR. For security
reasons, the list of these administration programs are hard-coded in the \fBadminclient\fR
and \fBindisrvr\fR executable. \fBadminclient\Fr uses environment variable \fBADMIN_TIMEOUT\fR
to timeout connections to \fBindisrvr\fR.

\fBadminclient\fR needs to supply credentials of users with administration privileges. These
users can be created using the \fBmgmtpass(8)\fR program. You can furhter use \fBvpriv(8)\fR
to control/restrict access of these admin users to certain programs (and even command line
arguments)

.EX
 e.g. The following command runs the command vadduser with arguments 
 test@example.com password.

 adminclient -h phoenix2 -p  4000 -u admin -P adminpass -c "vadduser test@example.com password"
.EE

.SH OPTIONS
.TP
\fB\-v\fR
Sets Verbose option.
.TP
\fB\-h\fR \fIadminHost\fR
The IP address / hostname of host on which command \fICommand\fR needs to run. 
.TP
\fB\-p\fR \fIadminPort\fR
A TCP/IP port or service in /etc/services on which indisrvr is running on adminHost.
.TP
\fB\-u\fR \fIadminUser\fR
The administration user (maintained using \fBmgmtpass(8)\fR) for which indisrvr will
validate the password.
.TP
\fB\-P\fR \fIadminPass\fR
The password for the user specified by the -u option.
.TP
\fB\-n\fR \fIcertificate\fR
A client certificate which should be provided in case TLS encryption is needed
.TP
\fB\-c\fR \fICommand\fR
The command that needs to executed on the remote host \fIadminHost\fR. Command should be
enclosed in quotes for commands requiring multiple arguments on the command line.

The -h, -p, -u, -P, -v are optional. If not given, the environment variables ADMIN_HOST,
ADMIN_PORT, ADMIN_USER, ADMIN_PASS will be used for these variables.

.SH RETURN VALUE
Returns the return status of the remote command executed. All output printed by the remote
command on stdout/stderr are printed on stdout of adminclient.

.SH PROTOCOL
The adminclient protocol is descibed below. You can connect to port 4000 and execute
the below sequence of commands to execute. Here 's' denotes server and 'c' denotes client.

.EX
.B adminclient Protocol
 s - server
 c - client

 s: "Login: "
 c: "userid\\n"
 s: "Password: "
 c: "password\\n"
 s: "OK\\n"
 c: "index command arg1 arg2 ...\\n"
 s: <output of above command if any>
 c: "\\n"
 s: "RETURNSTATUS[return value of command]\\n"
.EE

The below shows an actual example of vuserinfo getting executed by executing the
\fBtelnet\fR(1) client on port 4000.

.EX
 <lf> - linefeed

 Login: admin<lf>
 Password: xxxxxxxx<lf>
 OK
 7 vuserinfo -n manvendra@indimail.org<lf>
 name          : manvendra@indimail.org
 <lf>
 RETURNSTATUS0
.EE

.SH "SEE ALSO"
indisrvr(8), mgmtpass(8), vpriv(8), IndiMail(7)

