.LL 8i
.TH install_tables 8
.SH NAME
install_tables \- create All IndiMail MySQL tables using builtin templates

.SH DESCRIPTION
\fBinstall_tables\fR can be used to create all MySQL tables used by IndiMail. It can be used
when creating a fresh \fBIndiMail(7)\fR installation. It creates the following tables on the
local MySQL database

.nr step 1 1
.IP \n[step] 3
indimail
.sp -1
.IP \n+[step]
indibak
.sp -1
.IP \n+[step]
relay
.sp -1
.IP \n+[step]
atrn_map
.sp -1
.IP \n+[step]
bulkmail
.sp -1
.IP \n+[step]
fstab
.sp -1
.IP \n+[step]
ip_alias_map
.sp -1
.IP \n+[step]
lastauth
.sp -1
.IP \n+[step]
userquota
.sp -1
.IP \n+[step]
valias
.sp -1
.IP \n+[step]
vfilter
.sp -1
.IP \n+[step]
mailing_list
.sp -1
.IP \n+[step]
vlimits
.sp -1
.IP \n+[step]
vlog

.PP
\fBinstall_tables\fR will use the host.mysql control file to connect to the local
MySQL database.
.PP
If you are using a clustered domain, \fBinstall_tables\fR will additionally create the
following MySQL tables on the \fIclusterinfo\fR (See IndiMail(7)).

.nr step 1 1
.IP \n[step] 3
hostcntrl
.sp -1
.IP \n+[step]
aliasdomain
.sp -1
.IP \n+[step]
dbinfo
.sp -1
.IP \n+[step]
fstab
.sp -1
.IP \n+[step]
host_table
.sp -1
.IP \n+[step]
mgmtaccess
.sp -1
.IP \n+[step]
smtp_port
.sp -1
.IP \n+[step]
vpriv
.sp -1
.IP \n+[step]
spam
.sp -1
.IP \n+[step]
badmailfrom
.sp -1
.IP \n+[step]
badrcptto
.sp -1
.IP \n+[step]
spamdb

.PP
\fBinstall_tables\fR will use the host.master control file to connect to the clusterinfo
MySQL database.

.PP
It may be noted that IndiMail does not require that any of the MySQL tables to be created
prior to use. All tables get created on-the-fly when they get accessed. One can say that
\fBinstall_tables\fR was written by the author because he had nothing better to do with his
time.

.SH RETURN VALUE
Returns 0 for success, 1 for any failure.

.SH "SEE ALSO"
IndiMail(7), vtable(1)
