.LL 8i
.TH vfilter 8
.SH NAME
vfilter \- Filter capable MDA for IndiMail

.SH SYNOPSYS
\fBvfilter ""\fR \fIdefault_account\fR

.SH DESCRIPTION
.PP
\fBvfilter\fR is a MDA which implements IndiMail's powerful \fBvfilter\fR mechanism. These filters
can be set up by the \fBvcfilter(1)\fR program. Filters are run one by one and
action taken the moment the first match is found. Once a match is found, \fBvfilter\fR
ignores other filters (which could also result in a match). Hence care should be taken by
the user to have filters in the proper order in case where multiple matches are possible.
.PP
\fBvfilter\fR can be enabled by replacing \fBvdelivermail(8)\fR in the .qmail-default file.
For optimization, \fBvfilter\fR skips filters if the file .vfilter is not found in the user's
Maildir patch. This file is created by \fBvcfilter\fR when the first filter is added and
removed when the last filter is deleted. If in case, While processing, any fatal error occurs,
\fBvfilter\fR passes the mail to \fBvdelivermail\fR directly (or any other mail delivery agent
defined by the \fBMDA\fR environment variable) without any further processing. In case of
temporary errors, the mail remains in the queue and retried later and hence again passes
through the filter. \fBvfilter\fR can perform various actions on a filter match. These actions
are

.nr step 1 1
.IP \n[step] 3
Delivering to any one specific mailbox (Maildir format – if this is different from Inbox,
the environment variable \fBMAILDIRFOLDER\fR is set, causing \fBvdelivermail\fR to deliver mail
to a different folder).
.IP \n+[step]
Bouncing the mail back to \fIsender\fR
.IP \n+[step]
Forwarding the mail to another \fIaddress\fR
.IP \n+[step]
Running the email through another \fIprogram\fR
.PP
On a successful match, the mail is removed from the queue. If mail passes through the filter
without any match, mail remains in the queue and is handed over to \fBvdelivermail\fR (or the mda
defined by the \fBMDA\fR environment variable) for further processing.
.PP
These actions make \fBvfilter\fR a powerful mechanism to organize your emails, spam control,
automation based on email, taking specific action on receipt of specific emails, etc. In fact
a complex email based system can be developed around \fBvfilter\fR mechanism. However, due to
complexity and current limitations, forwarding are not checked for errors.
.PP
\fBvfilter\fR can also be configured to run global filters. There are two global filters

.TP
\fBPre Filter\fR

This can be set by setting filters for the special user prefilt@virtual_domain by using the
program vcfilter. All filters defined for this user will be applied for all users before
applying the user defined filters. Pre-filters can be turned off for specific users by having
a file named .noglobal in the user's Maildir.

.TP
\fBPost Filter\fR

This can be set by setting filters for the special user postfilt@virtual domain using the
\fBvfilter\fR program. These filters will be applied for all users after applying the user defined
filters. Post-filters can be turned off for specific users by having a file named .nopostfilt
in the user's Maildir.

.PP
\fBvfilter\fR can also be run in test mode by specifying emailid of the user on the command line.
The only other arguments permitted in test mode is the -v option. If the -v option is
specified, all actions performed are shown on screen. This option can be used to test so that
important mails do not get lost due to misconfiguration of filters.
.PP
\fBvfilter\fR uses a sophisticated mechanism called Email Processing System (EPS) to parse the email
(headers, mime and body). EPS is a set of API calls which allow systems to understand the
contents of an email message. The fact that email messages are rather complex, means that EPS
cannot jump around the email randomly like a monkey and be expected to understand its content.
\fBvfilter\fR runs the email through EPS line by line to understand specific things like MIME
attachments.

.SH OPTIONS
.TP
[\fB""\fR]
Blank double quote for backward compatibility (with \fBvdelivermail\fR)
.TP
[\fBdefault account for delivery\fR]
If the email does match any .qmail-user file and also does not match any virtual domain user,
this is the default delivery instructions. There are three values this may contain.

.nr step 1 1
.IP \n[step] 3
Full path to a indimail user directory 
.IP \n+[step]
email address to forward email too 
.IP \n+[step]
the string bounce-no-mailbox to bounce the email back to the sender.

.SH RETURN VALUE
.TP
.IP \[bu] 2
0 if all steps were successful. 
.TP
.IP \[bu] 2
100 for permanent errors. i.e. if user is over quota or bounce-no-mailbox is set and no matching user is found.
.TP
.IP \[bu] 2
111 for all temporary error occurring during mail delivery.

.SH "SEE ALSO"
vdelivermail(8), vcfilter(1)
