.TH 822received 1
.SH NAME
822received \- print the Received fields in a mail message
.SH SYNOPSIS
.B 822received
.SH DESCRIPTION
.B 822received
reads an 822-format mail message from its standard input,
and prints the
.B Received
fields from the message in an easier-to-read format.
.SH "SEE ALSO"
822field(1),
822date(1)
