.TH byte 3
.SH NAME
byte \- The byte library interface
.SH SYNTAX
.B #include <byte.h>

.SH
Copying Strings

void \fBbyte_copy\fP(\fIout\fR, \fIlen\fR, \fIin\fR);
.br
void \fBbyte_copyr\fP(\fIout\fR, \fIlen\fR, \fIin\fR);
.br
void \fBbyte_zero\fP(\fIout\fR, \fIlen\fR);

char *\fIout\fR;
.br
char *\fIin\fR;
.br
unsigned int \fIlen\fR;

.B byte_copy
copies \fIin\fR[0] to \fIout\fR[0], \fIin\fR[1] to \fIout\fR[1], etc., and finally
\fIin\fR[len-1] to \fIout\fR[len-1].

.B byte_copyr
copies \fIin\fR[len-1] to \fIout\fR[len-1], \fIin\fR[len-2] to \fIout\fR[len-2], etc., and
finally \fIin\fR[0] to \fIout\fR[0].

.B byte_zero
sets \fIout\fR[0], \fIout\fR[1], ... \fIout\fR[len-1] to 0.

.SH Comparing strings

result = \fBbyte_equal\fP(\fIone\fR, \fIlen\fR, \fItwo\fR);
.br
result = \fBbyte_diff\fP(\fIone\fR, \fIlen\fR, \fItwo\fR);

char *\fIone\fR;
.br
char *\fItwo\fR;
.br
unsigned int \fIlen\fR;
.br
int \fIresult\fR;

.B byte_diff
returns negative, 0, or positive, depending on whether the string \fIone\fR[0],
\fIone\fR[1], ... \fIone\fR[len-1] is lexicographically smaller than, equal to, or greater
than the string \fItwo\fR[0], \fItwo\fR[1], ... \fItwo\fR[len-1].

.B byte_equal
returns 1 if the strings are equal, 0 otherwise.

When the strings are different,
.B byte_diff
and
.B byte_equal
do not read bytes past the first difference. 

.SH Searching for bytes in strings
result = \fBbyte_chr\fP(\fIone\fR, \fIlen\fR, \fIc\fR);
.br
result = \fBbyte_rchr\fP(\fIone\fR, \fIlen\fR, \fIc\fR);

char *\fIone\fR;
.br
int \fIc\fR;
.br
unsigned int \fIlen\fR;
.br
unsigned int \fIresult\fR;

.B byte_chr
returns the smallest integer i between 0 and len-1 inclusive such that \fIone\fR[i] equals
(char) \fIc\fR. If no such integer exists,
.B byte_chr
returns \fIlen\fR.

.B byte_rchr
returns the largest integer i between 0 and len-1 inclusive such that \fIone\fR[i] equals
(char) \fIc\fR. If no such integer exists,
.B byte_rchr
returns \fIlen\fR.

.B byte_chr
and
.B byte_rchr
may read all the bytes \fIone\fR[0], \fIone\fR[1], ... \fIone\fR[len-1], even if not all the
bytes are relevant to the answer. 
