.TH iftocc 1
.SH NAME
iftocc \- check for blind carbon copies
.SH SYNOPSIS
.B iftocc
[
.I okaddr ...
]
.SH DESCRIPTION
.B iftocc
reads a mail message from its standard input.
It exits 0 if
.B $RECIPIENT
is listed in a
.B To
or
.B Cc
field,
100 if not.
Addresses are compared without regard to case.

If you list some
.IR okaddr s,
.B iftocc
will use them in place of
.BR $RECIPIENT .
It exits 100 if
none of them are listed in
.B To
or
.BR Cc .

For example, with qmail 1.03 and above,
you can put

.EX
   |bouncesaying 'I do not accept Bcc.' except iftocc
.EE

into your
.B .qmail
file to reject blind carbon copies
(including messages from mailing lists),
or

.EX
   |condredirect me-blind except iftocc
.EE

to forward all blind carbon copies to me-blind.

.B WARNING:
If you create a
.B .qmail
file to invoke
.BR iftocc ,
make sure to add a line
specifying delivery to your normal mailbox.
.SH "SEE ALSO"
bouncesaying(1),
condredirect(1),
except(1),
dot-qmail(5)
