.TH SENDMAIL 1 
.ad
.fi
.SH NAME
sendmail
\-
IndiMail to Sendmail compatibility interface
.SH "SYNOPSIS"
.na
.nf
\fBsendmail\fR [\fIoption ...\fR] [\fIrecipient ...\fR]

\fBmailq\fR
\fBsendmail -bp\fR
.SH DESCRIPTION
.ad
.fi
The IndiMail \fBsendmail\fR(1) command implements the IndiMail
to Sendmail compatibility interface.
For the sake of compatibility with existing applications, some
Sendmail command-line options are recognized but silently ignored.

By default, IndiMail \fBsendmail\fR(1) reads a message from
standard input
until EOF or until it reads a line with only a \fB.\fR character,
and arranges for delivery.  IndiMail \fBsendmail\fR(1) relies on the
\fBqmail-inject\fR(1) command to actually send a message.

Specific command aliases are provided for other common modes of
operation:
.IP \fBmailq\fR
List the mail queue. Each entry shows the queue file ID, message
size, arrival time, sender, and the recipients that still need to
be delivered.
.IP \fBnewaliases\fR
Not supported. Use fastfoward(1) / newaliases(1) instead

.PP
These and other features can be selected by specifying the
appropriate combination of command-line options. Some features are
controlled by parameters in the \fBmain.cf\fR configuration file.

The following options are recognized:
.IP "\fB-Am\fR (ignored)"
.IP "\fB-Ac\fR (ignored)"
IndiMail sendmail uses the same configuration file regardless of
whether or not a message is an initial submission.
.IP "\fB-B \fIbody_type\fR (ignored)"
The message body MIME type: \fB7BIT\fR or \fB8BITMIME\fR.
.IP "\fB-bh\fR (ignored)"
.IP "\fB-bH\fR (ignored)"
IndiMail has no persistent host status database.
.IP \fB-bi\fR
Initialize alias database. See the \fBnewaliases\fR
command above.
.IP \fB-bm\fR
Read mail from standard input and arrange for delivery.
This is the default mode of operation.
.IP \fB-bp\fR
List the mail queue. See the \fBmailq\fR command above. This is implemented by running the
\fBqmail-qread(8)\fR command.
.IP \fB-bs\fR
Stand-alone SMTP server mode. Read SMTP commands from
standard input, and write responses to standard output.
.sp
This mode of operation is implemented by running the
\fBqmail-smtpd\fR(8) daemon.
.sp
.IP "\fB-F \fIfull_name\fR
Set the sender full name. This overrides the NAME environment
variable, and is used only with messages that
have no \fBFrom:\fR message header.
.IP "\fB-f \fIsender\fR"
Set the envelope sender address. This is the address where
delivery problems are sent to.
.IP "\fB-h \fIhop_count\fR (ignored)"
Hop count limit. Use the \fImaxhops\fR control file instead.
.IP \fB-I\fR
Initialize alias database. See the \fBnewaliases\fR command above.
.IP "\fB-i\fR"
When reading a message from standard input, don\'t treat a line
with only a \fB.\fR character as the end of input.
.IP "\fB-L \fIlabel\fR (ignored)"
The logging label. Use the \fBsyslog_name\fR configuration
parameter instead.
.IP "\fB-m\fR (ignored)"
Backwards compatibility.
.IP "\fB-N \fIdsn\fR (ignored)"
.IP "\fB-n\fR (ignored)"
Backwards compatibility.
.IP "\fB-o7\fR (ignored)"
.IP "\fB-o8\fR (ignored)"
To send 8-bit or binary content, use an appropriate MIME encapsulation
and specify the appropriate \fB-B\fR command-line option.
.IP "\fB-oi\fR"
When reading a message from standard input, don\'t treat a line
with only a \fB.\fR character as the end of input.
.IP "\fB-om\fR (ignored)"
The sender is never eliminated from alias etc. expansions.
.IP "\fB-o \fIx value\fR (ignored)"
Set option \fIx\fR to \fIvalue\fR.
.IP \fB-t\fR
Extract recipients from message headers. These are added to any
recipients specified on the command line.
.IP "\fB-U\fR (ignored)"
Initial user submission.
.IP "\fB-v\fR (ignored)"

.SH "ENVIRONMENT"
.na
.nf
.ad
.fi
.IP \fBQUEUE_BASE\fR
Base Directory containing IndiMail queues.
.IP "\fBQUEUE_COUNT\fR"
No of queues to use in the queue base directory
.IP "\fBQUEUE_START\fR"
First queue to use in the queue base directory. sendmail will any of the QEUEUE_COUNT queues starting from this queue in
the queue base directory

.SH "SEE ALSO"
.na
.nf
qmail-inject(8), preprocess and send a mail message
qmail-queue(8),
qmail-smtpd(8), SMTP server
