.TH mess822_fold 3
.SH NAME
mess822_fold \- wrap lines in an RFC 822 field
.SH SYNTAX
.B #include <mess822.h>

int \fBmess822_fold\fP(&\fIout\fR,&\fIin\fR,\fIprefix\fR,\fIlinelen\fR);

stralloc \fIout\fR;
.br
stralloc \fIin\fR;
.br
char *\fIprefix\fR;
.br
int \fIlinelen\fR;
.SH DESCRIPTION
To be filled in.
.SH "SEE ALSO"
mess822(3),
mess822_quote(3)
