#!/bin/sh
# $Log: mysql_libs,v $
# Revision 1.4  2018-02-11 21:20:26+05:30  Cprogrammer
# use conf-sql to set mysql libraries
#
# Revision 1.3  2009-02-15 19:34:42+05:30  Cprogrammer
# made finding libs configurable
#
#
if [ $# -ne 1 ] ; then
	exit 0
fi
confsql=`grep -h -v "^#" conf-sql`
if [ -z "$confsql" ] ; then
	exit 0
fi
mysql_libs=`./mysql_config --libs`
if [ $? -ne 0 ] ; then
	echo "-Werror"
	exit 1
fi
case "$1" in
	DARWIN)
	;;
	*)
	pre1="-Xlinker -R -Xlinker"
	echo $mysql_libs | grep rdynamic > /dev/null
	if [ $? -eq 0 ] ; then
		pre2=`echo $mysql_libs|awk '{print $2}'|sed s}-L}}g`
	else
		pre2=`echo $mysql_libs|awk '{print $1}'|sed s}-L}}g`
	fi
	pre="$pre1 $pre2"
esac
echo $pre $mysql_libs
exit 0
