.TH newinclude 1
.SH NAME
newinclude \- create a binary mailing list from an :include: file
.SH SYNOPSIS
.B newinclude
.I list
.SH DESCRIPTION
.B newinclude
reads a
sendmail-style
.B :include:
file,
.IR list ,
and converts it into a binary format in
.I list\fB.bin
for use by
.BR fastforward .

.B newinclude
first writes the mailing list to
.IR list\fB.tmp ,
and then moves it to
.IR list\fB.bin .
If there is any problem creating
.IR list\fB.tmp ,
.B newinclude
leaves
.I list\fB.bin
alone.

.B newinclude
always creates
.I list\fB.bin
world-readable.

.B COMPATIBILITY WARNING:
sendmail
reads
.I list
directly;
.B fastforward
needs
.IR list\fB.bin .
sendmail's strategy is a disaster if you save
.I list
to disk at the same moment that
sendmail
reads it;
the list will be truncated at a random spot,
perhaps in the middle of an address.
Furthermore, if the system crashes while you are writing
.IR list ,
.I list
could be filled with all sorts of garbage.
.SH "LIST FORMAT"
.I list
may contain any number of lines;
each line may contain any number of addresses
or further
.B :include:
files.
See
.BR newaliases (1)
for details on the address format.
Any line in
.I file
beginning with # is ignored.

.B COMPATIBILITY WARNING:
.B newinclude
does not support file or program deliveries in
.B :include:
files.
You can use the secure delivery mechanisms described in
.B dot-qmail(5)
instead.

.B COMPATIBILITY WARNING:
Versions of
sendmail
before V8 did not allow comments in
.B :include:
files.
.SH "SEE ALSO"
fastforward(1),
newaliases(1),
setmaillist(1),
dot-qmail(5)
