.TH "qmailctl" "8" "07 Mar 2010" "Manvendra Bhangui" ""

.SH NAME
qmailctl \- control / query indimail startup / shutdown

.SH SYNOPSIS
.B qmailctl [start|stop|condrestart|restart|flush|reload]

.B qmailctl [stat|queue|pause|cont|cdb|help]

.SH DESCRIPTION
\fBqmailctl\fR(8) is a utility to help with very basic administration of \fBIndiMail\fR(7).
\fBqmailctl\fR(8) can be used if \fBIndiMail\fR(7) services are monitored by \fBsupervise\fR(8).
You can setup services under \fBsupervise\fR(8) using \fBsvctool\fR(8).

.SH OPTIONS
.TP 8
\fBstart\fR
start \fBqmail-smtpd\fR(8) and \fBqmail-send\fR(8)
.EX
 svc -u /service/qmail-smtpd.*
 svc -u /service/qmail-qmtpd.* /service/qmail-qmtpd.*
 svc -u /service/qmail-send.*
.EE
.TP
\fBstop\fR
stop \fBqmail-smtpd\fR(8) and \fBqmail-send\fR(8)
.EX
 svc -d /service/qmail-smtpd.*
 svc -d /service/qmail-qmtpd.* /service/qmail-qmtpd.*
 svc -d /service/qmail-send.*
.EE
.TP
\fBshut\fR
stop \fBsvscan\fR(8) and shut all services configured in services directory
.TP
\fBrestart\fR
stop \fBqmail-stmpd\fR(8), \fBqmail-send\fR(8) and restart \fBqmail-smtpd\fR(8), \fBqmail-send\fR(8)
.EX
 svc -d /service/qmail-smtpd.*
 svc -d /service/qmail-qmtpd.* /service/qmail-qmqpd.*
 svc -d /service/qmail-send.*
 svc -u /service/qmail-smtpd.*
 svc -u /service/qmail-qmtpd.* /service/qmail-qmqpd.*
 svc -d /service/qmail-send.*
.EE
.TP
\fBcondrestart\fR
stop \fBqmail-stmpd\fR(8), send SIGTERM to \fBqmail-send\fR(8) and restart \fBqmail-smtpd\fR(8)
.EX
 svc -d /service/qmail-smtpd.*
 svc -d /service/qmail-qmtpd.* /service/qmail-qmqpd.*
 svc -t /service/qmail-send.*
 svc -u /service/qmail-smtpd.*
 svc -u /service/qmail-qmtpd.* /service/qmail-qmqpd.*
.EE
.TP
\fBflush\fR
Reset qmail tcp timeout table using \fBqmail-tcpok\fR(8) and send SIGALRM to \fBqmail-send\fR(8)
.EX
 svc -a /service/qmail-send.*
.EE
.TP
\fBreload\fR
send SIGHUP to \fBqmail-send\fR(8)
.EX
 svc -h /service/qmail-send.*
.EE
.TP
\fBstatus\fR
check status of \fBsvscan\fR(8) service
.TP
\fBstat\fR
run \fBsvstat\fR(8) on all directories in the service directory
.TP
\fBqueue\fR
run \fBqmail-qstat\fR(8)
.TP
\fBpause\fR
pause \fBqmail-send\fR(8), \fBqmail-smtpd\fR(8). This implies using \fBsvc\fR(8) with -p option.
.EX
 svc -p /service/qmail-send.*
.EE
.TP
\fBcont\fR
continue \fBqmail-send\fR(8), \fBqmail-smtpd\fR(8). This implies using \fBsvc\fR(8) with -c option.
.EX
 svc -c /service/qmail-send.*
.EE
.TP
\fBcdb\fR
rebuild tcp.smtpd.cdb, tcp.imap.cdb, tcp.pop3.cdb and tcp.poppass.cdb using \fBtcprules\fR(1)

.SH "SEE ALSO"
qmail-stmpd(8), qmail-send(8), qmail-qstat(8), qmail-tcpok(8),
tcprules(1), svc(8), svctool(8), initsvc(1) init(8), upstart(8), initctl(8)
