.TH qmail-daned 8
.SH NAME
qmail-daned \- TLSA Record Checker for \fBIndiMail\fR
.SH SYNOPSIS
.B qmail-daned
[\c
.B \-t
.I timeout (days)\c
]\ [\c
.B \-p
.I port\c
]\ [\c
.B -h
.I hash_size
]\ [\c
.B -v
.I verbosity
]\ [\c
.B \-f
.I free_interval (min)\c
]\ [\c
.B \-s
.I save_interval (min)\c
]\ [\c
.B \-w
.IR whitelist_file
[.cdb]
]\ [\c
.B \-T
.IR tlsadomains_file
[.cdb]
]
.I ipaddr contextFile

.SH DESCRIPTION
\fBqmail-daned\fR is a qmail daemon for DANE protocol validation.
”DANE” defines the protocol for storing TLS certificates
in the DNS for a variety of applications using them. DNS-based
Authentication of Named Entities (DANE) is a great feature that uses the
advantages of a DNSSEC signed zone in order to tell the client which TLS
certificate one has to expect when connecting to a secure destination
over HTTPS or SMTPS.

\fBqmail-daned\fR is a DANE verification daemon responding to UDP query
packets, typically sent by a using \fBtlsacheck(3)\fR function in
\fBqmail-remote(8)\fR. The query packet consists of the sending the MX
domain name. If the domain was previously successful for a tlsa check, and
was last queried within \fItimeout_days\fR, the check succeeds. Otherwise
the domain name supplied and the result of DANE verfication is added to a
in memory TLSA database to check against future queries, and the check
fails (meaning \fBqmail-remote(8)\fR will reject the message).

\fBqmail-daned\fR maintains its database in memory. Periodic backups of the
database are made to \fIcontextFile\fR on the disk, to enable
\fBqmail-daned\fR to start with existing tlsa verification data, in case of
restart. To keep the in-memory search as efficient as possible, entries
older than \fItimeout_days\fR are expired during every request. To keep
the in-memory database as small as possible, records older than
\fItimeout_days\fR are periodically removed. The default interval is 5
minutes and can be changed by specifiying the \fB-f\fR option.  You can
force removal of expired records by issuing \fISIGUSR2\fR signal to
\fBqmail-daned\fR.  \fBqmail-daned\fR also backups the in-memory database to
\fIcontextFile\fR on receipt of \fISIGTERM\fR or \fISIGUSR1\fR signal. The
\fIcontextFile\fR and its containing directory should be writeable by the
user with which \fBqmail-daned\fR process runs. At start-up the file
\fIcontextFile\fR is read and all records older than \fItimeout\fR days are
expired. \fBqmail-daned\fR can maintain an internal hash table for fast
domain lookup using the \fBhsearch(3)\fR function.

A control file having the list of domains for which TLSA records needs
to be verified, can be maintained in a control file, specified by the
\fB-T\fR \fIfilename\fR option. If this control file is present, TLSA
verification will be skipped for all domains not in this file. If a file
with the name \fIfilename\fR.\fIcdb\fR exists, \fBqmail-daned\fR will use
\fBcdb(3)\fR lookup, in addition to the normal in-memory search, in a table
of tlsa verification enforced domains. \fBqmail-daned\fR re-reads this list
of domains on receipt of signal \fISIGHUP\fR. This control file is also
used by \fBqmail-remote(8)\fR

A whitelist of domains not subject to tlsa checking can be specified to
\fBqmail-daned\fR by the \fB-w\fR \fIfilename\fR option. If a file with the
name \fIfilename\fR.\fIcdb\fR exists, \fBqmail-daned\fR will use \fBcdb(3)\fR
lookup in addition to the normal in-memory search in a table of whitelisted
domains. \fBqmail-daned\fR re-reads the whitelist on receipt of signal
\fISIGHUP\fR.

\fBqmail-daned\fR listens on IP address \fIipaddr\fR, port 1998 for incoming
UDP queries. 127.0.0.1 (the loopback address) is recommended for
\fIipaddr\fR if \fBqmail-daned\fR is to serve queries on the same machine.
You can specify :: for \fBqmail-daned\fR to listen on wildcard IPV6 address.
Specifiying * for \fIipaddr\fR causes \fBqmail-daned\fR to listen on all
addresses.

\fBqmail-daned\fR uses \fIMSG_PEEK\fR flag in \fBrecvfrom(2)\fR to determine
the length of the packet and then reads the entire packet in one operation.

.SH OPTIONS
.TP
.B -v \fIverbosity
Set verbosity. 0 - minimal, 1 - moderate, 2 - maximum, 3 - include debug messages\fR

.TP
.B -h \fIhash_size
specify the memory for creating a hash using \fBhcreate(3)\fR

.TP
.B -w \fIfilename
specify whitelist of IP ranges not subject to tlsa verification.

.TP
.B -t \fIdays
timeout for known IPs in days; defaults to 7.

.TP
.B -f \fIminutes
periodic interval, in minutes, after which entries older than \fItimeout\fR days are expired; defaults to 5

.TP
.B -s \fIminutes
save interval for context file, in minutes; defaults to 5

.TP
.B -p \fIport
Alternate port to listen instead of the default 1998

.SH "QUERY FORMAT"
Queries to
\fBqmail-daned\fR are UDP packets containing the domain name(as a string) preceded by
.BR D ,
with the record terminated by an ASCII 0 character.

.EX
 Ddomain\\0
.EE

qmail-remote(8) can delegate DANE validation to qmail-daned(8) if the DANE_VERIFICATION is set
to host@port, where host@port represents the IP and port on which qmail-daned(8) is listening.
qmail-remote(8) has the domain name (as a string) in UDP packets preceded by
.BR q ,
.BR S or
.BR F ,
with the record terminated by an ASCII 0 character. In the 'q' mode, qmail-daned(8) just returns
if there is a record of DANE verification for \fIdomain\fR. In the 'S' or 'F' mode, qmail-daned(8)
does not do the actual DANE verification but simply updates its own in memory database with the
result from qmail-remote.  The character q is for verifying the existence of TLSA RR. The
character S, F is for updating the DANE validation as success or failure respectively. By using
these modes, qmail-remote and qmail-daned avoid duplicate DANE verification attempts between themselves.

.SH "CONTROL FILES"
.B qmail-daned
by default looks at @controldir@ for all control files. This path can be changed by defining the
CONTROLDIR environment variable.

.TP 5
.I timeoutconnect
Number of seconds
.B qmail-daned
will wait for the remote SMTP server to accept a connection.
Default: 60.
The kernel normally imposes a 75-second upper limit.

.TP 5
.I timeoutremote
Number of seconds
.B qmail-daned
will wait for each response from the remote SMTP server.
Default: 1200.

.TP 5
.I helohost
Current host name,
for use solely in saying hello to the remote SMTP server.
Default:
.IR me ,
if that is supplied;

.SH "SEE ALSO"
qmail-remote(8), qdane(1), tlsacheck(3), hcreate(3), hsearch(3), hdestroy(3), recvfrom(2).

.SH AUTHORS
.B qmail-daned
is currenty being maintained by Manvendra Bhangui <mbhangui@gmail.com> and
is part of the IndiMail package at http://www.indimail.org
