.TH vadddomain 1
.SH NAME
vadddomain \- Create a virtual domain

.SH SYNOPSYS
.B vadddomain
[
.I options
]
.I virtual_domain
[
\fIpostmaster_password\fR
]

.SH DESCRIPTION

.PP
.B vadddomain
adds a new virtual domain. It creates the necessary \fBqmail\fR control files and
a \fB.qmail-default\fR containing delivery instructions.
It also adds the RFC821 required postmaster account. Carries out the following steps
to create the domain.

.nr step 1 1
.IP \n[step] 3
Create the domains directory (/var/indimail/domains/\fIvirtual_domain\fR)
.IP \n+[step]
Create the \fB.qmail-default\fR file in the domains directory.
.IP \n+[step]
Add the domain to qmail assign file.
.IP \n+[step]
Add the domain to chkrcptdomains ('-C' option).
.IP \n+[step]
Add the domain to rcpthosts, virtualdomains (and etrnhosts for domains with ETRN/AUTOTURN support).
.IP \n+[step]
Create table indimail and indibak if used for the first time.
.IP \n+[step]
Sends SIGHUP to qmail-send.
.IP \n+[step]
Add entry to table dbinfo and mcdfile for a clustered domain ('-D' option).
.IP \n+[step]
Create the postmaster account for a non-clustered domain. For a clustered domain, the \fIpostmaster\fR
account is created on the first host on which the domain is created. Post adding the
\fIpostmaster\fR user, \fBvadddomain\fR adds \fIabuse\fR and \fImailer-daemon\fR, as aliases to the \fIpostmaster\fR account.

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvadddomain\fR executes the program defined by
the POST_HANDLE environment variable, passing \fIvirtual_domain\fR as a parameter. If POST_HANDLE
is not defined, the program/script INDIMAIL/libexec/vadddomain will be executed with \fIvirtual_domain\fR
as a parameter.

.SH OPTIONS
.PP
\fIvirtual_domain\fR is mandatory. Rest are optional. If \fIpostmaster_password\fR is not given, \fBvadddomain\fR
will prompt for the password.
.TP
\fB\-v\fR
make \fBvaddomain\fR be verbose
.TP
\fB\-B\fR \fIbase_path\fR
sets the BASE PATH for user's home directory for users created on this domain. This
overrides the environment variable \fBBASE_PATH\fR and the default base path \fI/home/mail\fR.
You can use this option to assign specific directories/filesystems to users added to a domain.
The base path is maintained in the file INDIMAIL/\fIvirtual_domain\fR/.\fIbase_path\fR
.TP
\fB\-l\fR users_per_level
By default, \fBvadduser\fR uses an adaptive directory structure based on a table dir-control
which is automatically managed by \fBvadduser(1)\fR, \fBvdeluser(1)\fR and \fBvreorg(8).
The basic idea is to break up the user Maildir directories across multiple directories and sub
directories so that there are never more than 100 user directories in a single directory. Use
this option to change the default compile time value of 100 users per directory.
.TP
\fB\-q\fR \fIquota_in_bytes\fR
sets the quota for postmaster account
.TP
\fB\-b\fR
bounces all mail that doesn't match a user, default
.TP
\fB\-e\fR
email_address (forwards all non matching user to this address)
.TP
\fB\-u\fR \fIuser\fR
sets the uid/gid based on a user in /etc/passwd. Default is user \fBindimail\fR
.TP
\fB\-d\fR \fIdir\fR
sets the dir to use for the domain in the file \fIINDIMAIL/users/assign\fR. See \fBdot-qmail(5)\fR.
All configuration files for the domain are placed in this directory.
.TP
\fB\-i\fR \fIuid\fR
sets the uid to use for this domain
.TP
\fB\-g\fR \fIgid\fR
sets the gid to use for this domain
.TP
\fB\-C\fR
Sets RECIPIENT Check for this domain. \fBqmail-smtpd(8)\fR verifies all users in the RCPT TO command.
.TP
\fB\-a\fR
sets the account to use APOP, default is POP
.TP
\fB\-O\fR
optimize adding, for bulk adds set this for all except the last one
.TP
\fB\-f\fR
sets the domain to use vfilter mechanism for mail filtering
.TP
\fB\-t\fR
Enable ETRN support for the domain
.TP
\fB\-T\fR \fIip_address\fR
Enable AUTOTURN Support from the IP ip_address
.TP
\fB\-D\fR \fIdatabase\fR
Adds domain information to dbinfo table. This implies use of the \fB-S\fR, \fB-U\fR, \fB-P\fR, \fB-L\fR
options additionally
.TP
\fB\-S\fR \fISqlServer\fR
IP address or hostname of MySQL(1) server
.TP
\fB\-U\fR \fIUser\fR
User for accessing MySQL Database
.TP
\fB\-P\fR \fIPassword\fR
Password for the user to access the MySQL database
.TP
\fB\-p\fB \fIMySQL Port\fR
Port to connect to for accessing the database
.TP
\fB\-c\fR
Adds a clustered domain.  This implies use of the \fB-S\fR, \fB-U\fR, \fB-P\fR, \fB-L\fR options
.TP
\fIvirtual_domain\fR
Name of the new virtual domain. \fInew_domain\fR can contain alphanumeric characters besides '-' and '.' . However the first and the last character cannot be '-'.
.TP
[\fIpostmaster password\fR]
The password for the RFC required postmaster account. If the password is not supplied on the command line then vadddomain will prompt for the password twice.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic message is printed.

.SH NOTE
.nr step 1 1
.IP \n[step] 3
The virtual domain becomes active after running this program. No additional files need to be modified. A new directory is added under INDIMAIL/domains to house all the .qmail files, configuration files for the new virtual domain. 
.IP \n+[step]
vadddomain has the setuid bit set and runs as root.
.IP \n+[step]
Domain names can contain alphanumeric characters besides '-' and '.' . However the first and the last character cannot be '-'.
.IP \n+[step]
The postmaster account is created as an active account.
.IP \n+[step]
For a clustered domain, the postmaster id is added only for the first domain created as part of a
cluster.

.SH "SEE ALSO"
vaddaliasdomain(1), vmoddomain(1), vadduser(1), vdeldomain(1), valias(1), vdeluser(1), vdominfo(1),
dbinfo(8), qmail-smtpd(8), vdelivermail(8), vatrn(1), dot-qmail(5)
