.TH vatrn 1
.SH NAME
vatrn \- Enable ATRN domain for On Demand Mail Relay (ODMR)

.SH SYNOPSYS
.B vatrn
[
.I options
]
.I email
|
.I domain

.SH DESCRIPTION
.PP
.B vatrn
enables ATRN domains for On Demand Mail Relay (ODMR). ATRN domains can be added by using the
\fB\-t\fR option to
.BR vadddomain .

.SH OPTIONS
.PP
.TP
\fB\-s\fR
Displays domains enabled for the user specified by the email address email or domain domain.
If neither email or domain are specified, all atrn domain access are displayed
.TP
\fB\-d\fR \fIdomain\fR
Deletes domain enabled for the user.
.TP
\fB\-i\fR \fIdomain\fR
Adds a new domain for ODMR access by the user.
.TP
\fB\-u\fR \fIdomain\fR
Renames an existing domain for which the user has access to the domain specified in the \fB\-i\fR
option.
.TP
\fB\-v\fR
Print verbose messages on the screen.
.TP
\fIemail\fR
The name of an existing user in the indimail database. The encrypted passwd of this user
should be used by the ODMR client to authenticate using CRAM-MD5. Users for ODMR can be
created by using vadduser (provided domain has already been created using the vadddomain).
.TP
\fIdomain\fR
Name of an existing ATRN domain. All users having access to download mails using ODMR protocol
are shown.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic
message is printed.

.SH "SEE ALSO"
vadddomain(1)
