.TH vsetuserquota 1
.SH NAME
vsetuserquota \- Set quota for a user in a virtual domain

.SH SYNOPSYS
.B vsetuserquota
[
.I options
]
.I email_address
.I quota_in_bytes

.SH DESCRIPTION
\fBvsetuserquota\fR changes a users hard quota limit. \fB--enable-hardquota=y\fR must be set
during  indimail configuration for this to have any effect. Default configuration sets
hard quota on. \fBvsetuserquota\fR has setuid bit set and must be run as root or indimail user.

.SH OPTIONS
.TP
\fB\-v\fR
Set verbose mode.
.TP
\fIemail_address\fR
The email address of the user. 
.TP
\fIquota_in_bytes\fR
The hard quota limit in bytes. Abbrievations can be used for kilobytes, megabytes and
gigabytes. For example \fBvsetuserquota\fR user@domain 5m will set the quota to 5 mega
bytes. Or \fBvsetuserquota\fR user@domain 2k will set the quota to 2k. \fBvsetuserquota\fR
user@domain NOQUOTA will turn off all quota checking for that user.

.PP
If the domain has domain limits set using vmoddomlimits(1), then domain limits apply. Setting
of quota will not be allowed if permission for modifying quota is disabled in domain limits.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a diagnostic
message is printed.

.SH "SEE ALSO"

vadduser(1), vmoduser(1), resetquota(8), vmoddomlimits(1)
