.TH 822body 1
.SH NAME
822body \- print the body of a mail message
.SH SYNOPSIS
.B 822body
.SH DESCRIPTION
.B 822body
reads an 822-format email message from standard input and prints the
body of the message to standard output.
.B 822body
considers the end of the message or the first line that cannot be part of an
822-format header field to terminate the message headers. A nonblank line that
terminates the headers is part of the message body. If it encounters an error
processing a message, 822body exits 111. Otherwise, 822body exits 0. 
.SH "SEE ALSO"
822header(1)
