.TH 822fields 1
.SH NAME
822fields \- extract 822 field values from email headers.
.SH SYNOPSIS
.B 822fields
.I field ...
.SH DESCRIPTION
.B 822field
reads an 822-format email message from standard input. For each input header
field, 822fields prints one line containing the value of the field to standard
output.

822fields considers the end of the message or the first line that cannot be
part of an 822-format header field to terminate the message message body.

If it encounters an error while processing a message, 822fields exits 111.

If no field appears, 822fields looks for subject. If 822fields finds any
matching headers, it exits 0. Otherwise, 822fields exits 100. 

