#!/bin/sh
# $Log: catChangeLog,v $
# Revision 1.2  2020-10-10 21:19:45+05:30  Cprogrammer
# fixed ChangeLog generation with dates
#
# Revision 1.1  2020-05-24 11:49:25+05:30  Cprogrammer
# Initial revision
#
#
# $Id: catChangeLog,v 1.2 2020-10-10 21:19:45+05:30 Cprogrammer Exp mbhangui $
#
flag=0
if [ $# -eq 1 ] ; then
	file=$1
else
	file=doc/ChangeLog
fi
cat $file |while read line
do
	echo "$line"|grep "^*" > /dev/null
	if [ $? -eq 0 -a $flag -ne 0 ] ; then
		break
	fi
	echo "$line" | grep "^[0-9]*/.*/.*" > /dev/null # skip dates
	if [ $? -eq 0 ] ; then
		continue
	fi
	if [ $flag -eq 0 ] ; then # first line
		echo "* `date +"%a %b %d %Y %H:%M:%S %z"` indimail-mta@indimail.org" @version@-@release@%{?dist}
		flag=1
		continue
	elif [ $flag -eq 1 ] ; then
		echo "$line"
		flag=2
		continue
	fi
	echo "$line" |egrep "^- [0-9]|^[0-9]" > /dev/null
	if [ $? -eq 0 ] ; then
		echo "$line"
	else
		echo "  $line"
	fi
done

