#!/bin/sh
# $Log: catChangeLog,v $
# Revision 2.3  2017-04-24 09:09:51+05:30  Cprogrammer
# fixed changelog date
#
# Revision 2.2  2017-03-08 18:24:24+05:30  Cprogrammer
# added version in changelog generation
#
# Revision 2.1  2014-03-12 08:54:46+05:30  Cprogrammer
# utility to append changelog to indimail.spec
#
#
# $Id: catChangeLog,v 2.3 2017-04-24 09:09:51+05:30 Cprogrammer Exp mbhangui $
#
flag=0
if [ $# -eq 1 ] ; then
	file=$1
else
	file=doc/ChangeLog
fi
cat $file |while read line
do
	echo "$line"|grep "^*" > /dev/null
	if [ $? -eq 0 -a $flag -ne 0 ] ; then
		break
	fi
	echo "$line" | grep "^[0-9]*/.*/.*" > /dev/null # skip dates
	if [ $? -eq 0 ] ; then
		continue
	fi
	if [ $flag -eq 0 ] ; then # first line
		echo "* `date +"%a %b %d %Y %H:%M:%S %z"` indimail-mta@indimail.org" @version@-@release@
		flag=1
		continue
	elif [ $flag -eq 1 ] ; then
		echo "$line"
		flag=2
		continue
	fi
	echo "$line" |grep "^[0-9]" > /dev/null
	if [ $? -eq 0 ] ; then
		echo "$line"
	else
		echo "    $line"
	fi
done

