.TH cdb-database 8
.SH NAME
cdb-database \- prepare cdb assignments for ctrlenv
.SH SYNOPSIS
\fBcdb-database\fR \fIfilename\fR

.SH DESCRIPTION
.B cdb-database
reads the assignments in \fICONTROL/control/filename\fR
and writes them into \fICONTROL/control/filename.cdb\fR in a binary format suited
for quick access by \fBctrlenv\fR.
Extra arguments provided after \fIfilename\fR are silently ignored.

If there is a problem with \fICONTROL/control/filename\fR, \fBcdb-database\fR
complains and leaves \fICONTROL/control/filename.cdb\fR alone.

\fBcdb-database\fR ensures that
\fICONTROL/control/filename.cdb\fR is updated atomically, so
\fBctrlenv\fR never has to wait for \fBcdb-database\fR to finish.
However, \fBcdb-database\fR makes no attempt to protect against two simultaneous updates of
\fICONTROL/control/filename.cdb\fR.

The binary \fICONTROL/control/filename.cdb\fR format is portable across machines.

.B CONTROL/control/filename
is a series of assignments, one per line.
It ends with a line containing a single dot.
Lines must not contain NUL.

Lines in \fICONTROL/control/filename\fR consists of \fIaddress\fR separated by
\fIvalue\fR
.EX
   =joe.shmoe@indimail.org:CONTROL/control/domainkeys/joe:
.EE

When \fBctrlenv\fR is run against this file using address
jome.shmoe@indimail.org, DKIMSIGN will be set to \fICONTROL/control/domainkeys/joe\fR

.SH "SIMPLE ASSIGNMENTS"
A simple assignment is a line of the form

.EX
   =local:value:
.EE

Here \fIlocal\fR is an address;
\fIvalue\fR is the value of environment variable that \fBctrlenv\fR will
set when it finds a match for address \fIlocal\fR.

If there are several assignments for the same
.I local
address,
.B ctrlenv
will use the first one.

.I local
is interpreted without regard to case.

.SH "WILDCARD ASSIGNMENTS"
A wildcard assignment is a line of the form

.EX
   +loc:value:
.EE

This assignment applies to any address beginning with
.IR loc ,
including
.I loc
itself.
It means the same as

.EX
   =locext:value:
.EE

for every string
.IR ext .

A more specific wildcard assignment overrides a less specific
assignment, and a simple assignment overrides any wildcard assignment.
For example:

.EX
   +:CONTROL/control/domainkeys/%/default:
   +joe-:CONTROL/control/domainkeys/indimail.org/joe:
   =joe:CONTROL/control/domainkeys/example.com/joe:
.EE

The address
.B joe
is handled by the third line;
the address
.B joe-direct
is handled by the second line;
the address
.B bill
is handled by the first line.

.SH "SEE ALSO"
ctrlenv(8)
