.TH cdbget 1
.SH NAME
cdbget \- search for records in cdb

.SH SYNOPSIS
\fBcdbget\fR \fIk\fR [\fIs\fR]

.SH DESCRIPTION
\fBcdbget\fR searches for a record with key \fIk\fR in a constant database. The constant
database must be readable (and seekable) on \fBcdbget\fR's standard input.

Normally \fBcdbget\fR prints the data in the first record with key \fIk\fR and exits 0. If
there is no record with the key \fIk\fR, \fBcdbget\fR exits 100 without printing anything.

If \fBcdbget\fR encounters a read error, write error, or database format error, it complains
and exits 111.

Given a numeric \fIs\fR argument, \fBcdbget\fR skips past the first \fIs\fR records with key
\fIk\fR, and prints the data in the next record. 

.SH SEE ALSO
cdbgetm(1), cdbmake(1), cdbdump(1)
