.TH checkdomain 1

.SH NAME
checkdomain - match domain in 822addr output

.SH SYNOPSIS
.B checkdomain
.I dom ...
where
.I dom
is a domain name.

.SH DESCRIPTION
\fBcheckdomain\fR reads email addresses from standard input in the form
output by \fB822addr\fR(1), and compares the domain portion with each
\fIdom\fR without regard to case. If no addr appears, \fBcheckdomain\fR
uses the domain part of the environment variable $RECIPIENT as \fIdom\fR.
If it finds a match, \fBcheckdomain\fR exits 0. Otherwise, it exits 100.

Each address appears as a null-terminated line with an introductory
character. A + character introduces a delivery address, and a ( character
introduces a comment. The introductory characters are not part of the
address. \fBcheckdomain\fR compares its arguments only with delivery
addresses, and ignores comments.

If \fBcheckdomain\fR finds an address matching dom, it exits 0. Otherwise,
it exits 100.

.SH SEE ALSO
822addr(1),
checkaddr(1)
