.TH checkaddr 1

.SH NAME
checkaddr - match address in 822addr output

.SH SYNOPSIS
\fBcheckaddr\fR \fIaddr\fR ...
where \fIaddr\fR is an email header name.

.SH DESCRIPTION
\fBcheckaddr\fR reads addresses from standard input, in the form output by
\fB822addr\fR(1), and compares them with each addr without regard to case.
If no addr appears, \fBcheckaddr\fR uses $RECIPIENT as addr. If it finds a
match, checkaddr exits 0.  Otherwise, checkaddr exits 100.

Each address appears as a null-terminated line with an introductory
character. A + character introduces a delivery address, and a ( character
introduces a comment. The introductory characters are not part of the
address. \fBcheckaddr\fR compares its arguments only with delivery
addresses, and ignores comments.

If \fBcheckaddr\fR finds an address matching addr, it exits 0. Otherwise,
it exits 100.

.SH SEE ALSO
822addr(1),
checkdomain(1)
