.\" vim: tw=75
.TH condredirect 1
.SH NAME
condredirect \- perhaps redirect mail to another address

.SH SYNOPSIS
in
.BR .qmail :
.B |condredirect
[
.B \-r
]
.I newaddress
.I program
[
.I arg ...
]

.SH DESCRIPTION
\fBcondredirect\fR feeds each new mail message to \fIprogram\fR with the
given arguments.

Without the \fB\-r\fR option, if \fIprogram\fR exits 0, \fBcondredirect\fR
forwards the mail message to \fInewaddress\fR, and then exits 99, so
further commands in \fB.qmail\fR are ignored.

With the \fB\-r\fR option \fBcondredirect\fR forwards the mail message to
\fInewaddress\fR when \fIprogram\fR exits non-zero (other than 100 or 111)
and then exits 99, so that further commands in \fB.qmail\fR are ignored.

If \fIprogram\fR exits 111, \fBcondredirect\fR exits 111, so delivery will
be retried later.

If \fIprogram\fR exits 100, \fBcondredirect\fR exits 100, so delivery will
be discarded and mail bounced back to the sender.

Without the \fB\-r\fR option, if \fIprogram\fR exits anything else (or
doesn't exist), \fBcondredirect\fR exits 0, so the rest of \fB.qmail\fR
will be processed as usual.

With the \fB\-r\fR option, if \fIprogram\fR exits anything else (or doesn't
exist), \fBcondredirect\fB forwards the mail message to \fInewaddress\fR
and then exits 99, so further commands in \fB.qmail\fR are ignored. If
\fIprogram\fR exits 0, \fBcondredirect\fR also exits 0, so that the rest of
\fB.qmail\fR will be processed as usual.

Note that it is not safe for \fBprogram\fR to fork a child that reads the
message in the background.

If running as non-root, \fBcondredirect\fR uses environment set according
to files in $HOME/.defaultqueue directory. You can skip $HOME/.defaultqueue
if \fBSKIP_LOCAL_ENVIRONMENT\fR is set. If \fBQUEUE_BASE\fR environment
variable is not set, it additionally uses environment set according to
files in @controldir@/defaultqueue directory (for any uid).

\fBWARNING:\fR If you create a \fB.qmail\fR file to enable
\fBcondredirect\fR, make sure to also add a line specifying delivery to
your normal mailbox.

\fBcondredirect\fR rewrites the sender using Sender Rewriting Scheme if
\fISRS\fB has been configured. See \fBindimail-srs\fR(5) for information on
how to do this.

.SH "SEE ALSO"
uenv(1),
envdir(8),
ifaddr(1),
iftocc(1),
iftoccfrom(1)
bouncesaying(1),
condtomaildir(1),
dot-qmail(5),
filterto(1),
except(1),
dot-forward(1),
fastforward(1),
forward(1),
printforward(1),
setforward(1),
preline(1),
qmail-command(8),
qnotify(1),
qreceipt(1),
replier(1),
rrforward(1),
indimail-srs(5),
qmail-queue(8)
