.\" vim: tw=75
.TH condtomaildir 1
.SH NAME
condtomaildir - feed message to program and perhaps store message

.SH SYNOPSIS
in
\fB.qmail\fR:
\fB|condtomaildir\fR [ -r ] \fIdir\fR \fIprogram\fR [ \fIarg\fR ... ]

where \fIdir\fR is a Maildir-format directory and \fIprogram\fR is one or
more arguments specifying a program to run for each message.

.SH DESCRIPTION
\fBcondtomaildir\fR feeds each new mail message to \fIprogram\fR with the
given arguments.

Without the \fB\-r\fR option, if \fIprogram\fR exits 0, \fBcondtomaildir\fR
writes the email message to \fIdir\fR, and then exits 99, so further
commands in \fB.qmail\fR are ignored.

With the \fB\-r\fR option \fBcondtomaildir\fR writes the email message to
\fIdir\fR when \fIprogram\fR exits non-zero (other than 100 or 111)
and then exits 99, so that further commands in \fB.qmail\fR are ignored.

If \fIprogram\fR exits 111, \fBcondtomaildir\fR exits 111, so delivery will
be retried later.

If \fIprogram\fR exits 100, \fBcondtomaildir\fR exits 100, so delivery will
be discarded and mail bounced back to the sender.

Without the \fB\-\fRr option, if \fIprogram\fR exits anything else (or
doesn't exist), \fBcondtomaildir\fR exits 0, so the rest of \fB.qmail\fR
will be processed as usual.

With the \fB\-r\fR option, if \fIprogram\fR exits anything else (or doesn't
exist), \fBcondtomaildir\fB writes the mail message to \fIdir\fR and then
exits 99, so further commands in \fB.qmail\fR are ignored. If \fIprogram\fR
exits 0, \fBcondtomaildir\fR also exits 0, so that the rest of \fB.qmail\fR
will be processed as usual.

If \fBcondtomaildir\fR encounters a permanent error in handling a message
or writing to \fIdir\fR, or if the maildir quota is exceeded,
\fBcondtomaildir\fR exits 100. If it encounters a temporary error in
handling a message or writing to \fIdir\fR, \fBcondtomaildir\fR exits 111.

If \fBcondtomaildir\fR encounters a permanent error attempting to run prog,
it exits 100. If \fBcondtomaildir\fR encounters a temporary error in
attempting to run prog, it exits 111.

Note that it is not safe for \fIprogram\fR to fork a child that reads the
message in the background.

\fBWARNING:\fR If you create a \fB.qmail\fR file to enable
\fBcondtomaildir\fR, make sure to also add a line specifying delivery to
your normal mailbox.

.SH "SEE ALSO"
ifaddr(1),
iftocc(1),
iftoccfrom(1)
bouncesaying(1),
condredirect(1),
dot-qmail(5),
filterto(1),
except(1),
dot-forward(1),
fastforward(1),
forward(1),
printforward(1),
setforward(1),
preline(1),
qmail-command(8),
qnotify(1),
qreceipt(1),
replier(1),
rrforward(1),
qmail-queue(8)
