#!/bin/sh
# $Log: $
#
# $Id: $
#
curdir=`pwd`
version=$(cat conf-version)
name=indimail-mta
if [ ! -f /etc/arch-release ] ; then
  echo "you can't make arch package on a non Arch Linux system" 1>&2
  exit 1
fi

verbose=0
release=1
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
    ;;
    *) optarg=
    ;;
    esac

    case "$1" in
    --verbose)
    verbose=1
    ;;
    --release=*)
    release=$optarg
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
  copy_src=1
fi

mkdir -p $HOME/stage/arch/$name
STAGE=$HOME/stage/arch/$name-$version
if [ $copy_src -eq 1 ] ; then
  /bin/rm -rf $STAGE
  cp -rp . $STAGE
  /bin/rm -f $STAGE/catChangeLog
  /bin/cp catChangeLog $STAGE/catChangeLog
  cd $STAGE
  make -s PKGBUILD
  if [ $? -ne 0 ] ; then
    echo "make failed" 1>&2
    exit 1
  fi
  cp PKGBUILD $name.changes $HOME/stage/arch/$name
  total=$(grep "#### INSTALL.* ####" PKGBUILD | wc -l)
  if [ $total -eq 1 ] ; then
    sed -n '/#### INSTALL SCRIPTS ####/,$p' PKGBUILD \
        | grep -v "^####" > $HOME/stage/arch/$name/archpkg.install
    if [ ! -s $HOME/stage/arch/$name/archpkg.install ] ; then
      rm -f $HOME/stage/arch/$name/archpkg.install
    fi
  else
    count=1
    while true
    do
      sed -n "/#### INSTALL$count SCRIPTS ####/,\$p" PKGBUILD \
          | grep -v "^####" > $HOME/stage/arch/$name/archpkg$count.install
      if [ ! -s $HOME/stage/arch/$name/archpkg$count.install ] ; then
        rm -f $HOME/stage/arch/$name/archpkg$count.install
      fi
      if [ $count -eq $total ] ; then
          break
      fi
      count=$(expr $count + 1)
    done
  fi
  make -s clean
  make -s distclean

  /bin/rm -rf autom4te.cache .deps
  cd $HOME/stage/arch
  echo "Archiving $name-"$version".tar.gz in `pwd`"
  tar \
    --exclude="$name-$version/.git" \
    --exclude="$name-$version/debian"  \
    --exclude="$name-$version/RCS" \
    -cf - $name-"$version" \
      | gzip -c > $HOME/stage/arch/$name/$name-"$version".tar.gz
  dist=`uname -r |cut -d . -f4`
  /bin/rm -rf $STAGE
fi
echo -n "Build Arch Package for $name-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
  cd $curdir
  tmprel=`cat conf-release 2>/dev/null`
  if [ ! " $tmprel" = " 1.$release" ] ; then
    sed -i -e "s|^pkgrel=.*|pkgrel=1.$release|g" $HOME/stage/arch/$name/PKGBUILD
  fi
  cd $HOME/stage/arch/$name
  makepkg -f --clean
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
  /bin/rm -rf $HOME/stage/arch/$name
fi
