#!/bin/sh
# $Log: create_rpm,v $
# Revision 1.9  2020-07-05 14:14:34+05:30  Cprogrammer
# added command line option to set verbose rpmbuild
#
# Revision 1.8  2020-07-04 23:57:51+05:30  Cprogrammer
# do silent rpm builds
#
# Revision 1.7  2020-07-01 21:35:03+05:30  Cprogrammer
# added option to skip copying source files
#
# Revision 1.6  2020-05-31 10:54:53+05:30  Cprogrammer
# removed version numbers from directory names of libdkim, libsrs2, ucspi-tcp
#
# Revision 1.5  2020-05-27 12:39:18+05:30  Cprogrammer
# build spec file before rpm build
#
# Revision 1.4  2020-05-26 09:38:40+05:30  Cprogrammer
# added option to specify release number on command line
#
# Revision 1.3  2020-05-25 23:12:35+05:30  Cprogrammer
# fixed release number in changelog
#
# Revision 1.2  2020-05-24 23:52:46+05:30  Cprogrammer
# reset release to 1.1 on OS distribution change
#
# Revision 1.1  2020-05-24 11:55:44+05:30  Cprogrammer
# Initial revision
#
#
# $Id: create_rpm,v 1.9 2020-07-05 14:14:34+05:30 Cprogrammer Exp mbhangui $
#
version=$(head -1 conf-version)
libdkim_version=$(cat ../libdkim-x/conf-version)
libsrs2_version=$(cat ../libsrs2-x/conf-version)
ucspitcp_version=$(cat ../ucspi-tcp-x/conf-version)

get_tar_files()
{
(
for i in `grep "^Source" indimail-mta-x/indimail-mta.spec.in | awk '{print $2}' | grep "\.tar"`
do
	i=`basename $i`
	echo $i
done
) | uniq | sed \
	-e 's/%{name}/indimail-mta/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{libdkim_version}/$libdkim_version/g" \
	-e "s/%{libsrs2_version}/$libsrs2_version/g" \
	-e "s/%{ucspitcp_version}/$ucspitcp_version/g"
}

get_non_tar_files()
{
(
for i in `grep "^Source" $1 | grep -v "\.tar" | awk '{print $2}'`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/indimail-mta/g' \
	-e "s/%{version}/$version/g" \
	-e "s/%{libdkim_version}/$libdkim_version/g" \
	-e "s/%{libsrs2_version}/$libsrs2_version/g" \
	-e "s/%{ucspitcp_version}/$ucspitcp_version/g"
}

get_dirname()
{
	echo $1 | sed \
		-e 's}.tar.gz}}g' \
		-e 's}.tar.bz2}}g' \
		-e 's}.tar.xz}}g'
}

if [ -f /etc/debian_version ] ; then
	echo "you can't do rpmbuild on an insane system" 1>&2
	exit 1
fi

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --verbose)
	verbose=1
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

if [ $copy_src -eq 1 ] ; then
make -s indimail-mta.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 1
fi
if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
list=`get_tar_files`
for i in $list
do
	dir=`get_dirname $i`
	case "$dir" in
		indimail-mta-$version)
		if [ ! -d indimail-mta-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Preparing indimail-mta-"$version""
		/bin/cp -rp indimail-mta-x stage/indimail-mta-"$version"
		cd stage/indimail-mta-"$version"
		echo "Cleaning indimail-mta"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ..
		tar \
			--exclude="indimail-mta-$version/.git" \
			--exclude="indimail-mta-$version/debian" \
			--exclude="indimail-mta-$version/RCS" \
			-cf - indimail-mta-"$version" \
			| gzip -c > $rpmbuild/SOURCES/indimail-mta-"$version".tar.gz
		SRC="$rpmbuild/SOURCES/indimail-mta-"$version".tar.gz $SRC"
		cd ..
		continue
		;;
		libdkim-$libdkim_version)
		if [ ! -d libdkim-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Preparing libdkim-"$libdkim_version""
		/bin/cp -rp libdkim-x stage/libdkim-"$libdkim_version"
		cd stage/libdkim-"$libdkim_version"
		echo "Cleaning libdkim-$libdkim_version"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ..
		tar \
			--exclude="libdkim-$libdkim_version/.git" \
			--exclude="libdkim-$libdkim_version/debian" \
			--exclude="libdkim-$libdkim_version/RCS" \
			-cf - libdkim-"$libdkim_version" \
			| gzip -c > $rpmbuild/SOURCES/libdkim-"$libdkim_version".tar.gz
		SRC="$rpmbuild/SOURCES/libdkim-"$libdkim_version".tar.gz $SRC"
		cd ..
		continue
		;;
		libsrs2-$libsrs2_version)
		if [ ! -d libsrs2-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Preparing libsrs2-"$libsrs2_version""
		/bin/cp -rp libsrs2-x stage/libsrs2-"$libsrs2_version"
		cd stage/libsrs2-"$libsrs2_version"
		echo "Cleaning libsrs2-$libsrs2_version"
		make -s clean > /dev/null
		make -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ..
		tar \
			--exclude="libsrs2-$libsrs2_version/.git" \
			--exclude="libsrs2-$libsrs2_version/debian" \
			--exclude="libsrs2-$libsrs2_version/RCS" \
			-cf - libsrs2-"$libsrs2_version" \
			| gzip -c > $rpmbuild/SOURCES/libsrs2-"$libsrs2_version".tar.gz
		SRC="$rpmbuild/SOURCES/libsrs2-"$libsrs2_version".tar.gz $SRC"
		cd ..
		continue
		;;
		ucspi-tcp-$ucspitcp_version)
		if [ ! -d ucspi-tcp-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Preparing ucpsi-tcp-$ucspitcp_version"
		/bin/cp -rp ucspi-tcp-x stage/ucspi-tcp-"$ucspitcp_version"
		cd stage/ucspi-tcp-"$ucspitcp_version"
		echo "Cleaning ucspi-tcp-$ucspitcp_version"
		make -s clean > /dev/null
		cd ..
		tar \
			--exclude="ucspi-tcp-$ucspitcp_version/.git" \
			--exclude="ucspi-tcp-$ucspitcp_version/debian" \
			--exclude="ucspi-tcp-$ucspitcp_version/RCS" \
			-cf - ucspi-tcp-"$ucspitcp_version" \
			| gzip -c > $rpmbuild/SOURCES/ucspi-tcp-"$ucspitcp_version".tar.gz
		SRC="$rpmbuild/SOURCES/ucspi-tcp-$ucspitcp_version.tar.gz $SRC"
		cd ..
		continue
		;;
	esac
done
echo "Copying permissions files and rpmlintrc"
for i in `get_non_tar_files indimail-mta-x/indimail-mta.spec.in`
do
	/bin/cp -p stage/indimail-mta-"$version"/$i $rpmbuild/SOURCES
	SRC="$rpmbuild/SOURCES/$i $SRC"
done
echo "Clearing stage directory"
/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/sbin/qmail-smtpd ] ; then
		idist=$(rpm -qf /usr/sbin/qmail-smtpd|cut -d- -f4|cut -d. -f3)
		if [ " $dist" = " $idist" ] ; then
			iversion=$(rpm -qf /usr/sbin/qmail-smtpd|cut -d- -f3)
			if [ "$iversion" = "$version" ] ; then
				release=$(rpm -qf /usr/sbin/qmail-smtpd | cut -d- -f4 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for indimail-mta-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat indimail-mta-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > indimail-mta-x/conf-release
		cd indimail-mta-x
		make indimail-mta.spec
		cp indimail-mta.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp indimail-mta-x/indimail-mta.spec /tmp
	fi
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba --clean --quiet /tmp/indimail-mta.spec"
		rpmbuild -ba --clean --quiet /tmp/indimail-mta.spec
	else
		echo "rpmbuild -ba --clean /tmp/indimail-mta.spec"
		rpmbuild -ba --clean /tmp/indimail-mta.spec
	fi
	/bin/rm -f /tmp/indimail-mta.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	if [ $? -eq 0 ] ; then
		for i in indimail-mta indimail-mini daemontools ucspi-tcp
		do
			rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
		done
		rpm --addsign $rpmbuild/SRPMS/indimail-mta-"$version"-"1.$release".$dist.src.rpm
		echo -n "RPM lint for indimail-mta-"$version"-1."$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			for i in indimail-mta indimail-mini daemontools ucspi-tcp
			do
				echo $i
				rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
				echo ------------------------
			done
			echo indimail-mta-"$version"-"1.$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/indimail-mta-"$version"-"1.$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	fi
fi
if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		for i in $SRC
		do
			echo "/bin/rm -f $i"
			/bin/rm -f $i
		done
	fi
fi
