.TH ctrlenv 8
.SH NAME
ctrlenv \- runs another program with environment modified, according to a
match in control file having key value pairs, where key can be any address

.SH SYNOPSIS
\fBctrlenv\fR -f \fIfilename\fR -e \fIenv\fR -a \fIaddress\fR \fIchild\fR

.SH DESCRIPTION
\fIchild\fR consists of one or more arguments. 

\fBctrlenv\fR sets environment variable \fIenv\fR according to the first matched
line for address \fIaddress\fR in the file \fICONTROL/control/filename\fR
It then runs \fIchild\fR.

If the matched line contains a line starting wth \fIaddr\fR
whose first word following \fIaddr\fR separated by colon ":" is
\fIt\fR, \fBctrlenv\fR removes an environment variable named
\fIenv\fR if one exists, and then adds an environment variable named
\fIenv\fR with value \fIt\fR.

if \fIenv\fR does not exists, \fBctrlenv\fR adds an environment variable named
\fIenv\fR with value \fIt\fR.

If no matched lines are found, \fBctrlenv\fR runs \fIchild\fR without
modifying any environment variable

.SH EXIT CODES
.B ctrlenv
exits 111 if it has trouble reading \fIfilename\fR,
if it runs out of memory for environment variables, or if it cannot run
.IR child .
Otherwise its exit code is the same as that of
.IR child .
.SH SEE ALSO
supervise(8),
svc(8),
svok(8),
svstat(8),
svscanboot(8),
svscan(8),
readproctitle(8),
fghack(8),
pgrphack(8),
multilog(8),
tai64n(8),
tai64nlocal(8),
setuidgid(8),
envuidgid(8),
softlimit(8),
setlock(8)

http://cr.yp.to/daemontools.html
