.TH dnsfq 1
.SH NAME
dnsfq - retrieve AAAA and A records for a fqdn

.SH SYNOPSIS
.B dnsfq 
.I fqdn

.SH DESCRIPTION
.B dnsfq
takes the given
.I fqdn
for a host and employs a 
.I CNAME 
DNS lookup while finally retrieving the
.I AAAA
and
.I A 
record following the chain of potential alias names. 
On output, the entire chain of nested DNS information 
is displayed together with the retrieved IP(v4|v6) 
addresses.

.SH "SEE ALSO"
dnscname(1),
dnsmxip(1),
dnsptr(1),
dnstxt(1).
