.TH dnsfq 1
.SH NAME
dnsfq - retrieve PTR record for a fqdn

.SH SYNOPSIS
.B dnsfq 
.I fqdn

.SH DESCRIPTION
\fBdnsfq\fR takes the given \fIfqdn\fR for a host and gets the IP, employs
a DNS PTR lookup on the IP and displays the retreived records.

.SH "SEE ALSO"
dnscname(1),
dnsmxip(1),
dnsptr(1),
dnstxt(1).
