.TH dnsptr 1

.SH NAME
dnsptr - do a PTR lookup and display retrieved fqdn

.SH SYNOPSIS
.B dnsptr 
.I IPv4 
or
.IR IPv6 .

.SH DESCRIPTION
\fBdnsptr\fR does a DNS \fIPTR\fR lookup for an IP addressand displays the
retrieved \fIfqdn\fR.

.SH "SEE ALSO"
dnscname(1),
dnsmxip(1),
dnsfq(1),
dnsip(1),
dnstxt(1).
