.TH forward 1.

.SH NAME
forward \- forward new mail to one or more addresses.

.SH SYNOPSIS
in
.BR .qmail :
.B |forward
.I address ....

.SH DESCRIPTION
.B forward
forwards each new mail message to the specified list of addresses.
It is a simple wrapper around
.BR qmail-queue .
It achieves the same results as listing each
.I address
separately in
.BR .qmail ,
but it is more programmable since
.I address
can be constructed on the fly.

.B forward
rewrites the sender using Sender Rewriting Scheme if \fISRS\fB has been configured. see
.B qmail-srs(5)
for information on how to do this.

If running as non-root, \fBforward\fR uses environment set according
to files in $HOME/.defaultqueue directory. If QUEUE_BASE environment
variable is not set, it additionally uses environment set according to
files in @controldir@/defaultqueue directory (for any uid).

.SH "SEE ALSO"
dot-qmail(5),
qmail-srs(5),
qmail-command(8),
qmail-queue(8)
