.\" vim: tw=75
.TH forward 1.

.SH NAME
forward \- forward new mail to one or more addresses.

.SH SYNOPSIS
in
.BR .qmail :
.B |forward
.I address ....

.SH DESCRIPTION
\fBforward\fR forwards each new mail message to the specified list of
addresses. It is a simple wrapper around \fBqmail-queue\fR. It achieves the
same results as listing each \fIaddress\fR separately in \fB.qmail\fR, but
it is more programmable since \fIaddress\fR can be constructed on the fly.

\fBforward\fR uses the \fBDTLINE\fR environment variable set by
\fBqmail-local\fR to insert the \fBDelivered-To\fR header, \fBSENDER\fR
environment variable to set the \fBX-Forwarded-For\fR header. For each
\fIaddress\fR, it inserts the \fBX-Forwarded-To\fR header headers.

\fBforward\fR rewrites the sender using Sender Rewriting Scheme if
\fISRS\fB has been configured. See \fBindimail-srs\fR(5) for information on
how to do this.

If running as non-root, \fBforward\fR uses environment set according
to files in $HOME/.defaultqueue directory. You can skip $HOME/.defaultqueue
if \fBSKIP_LOCAL_ENVIRONMENT\fR is set. If \fBQUEUE_BASE\fR environment
variable is not set, it additionally uses environment set according to
files in @controldir@/defaultqueue directory (for any uid).

.SH "SEE ALSO"
ifaddr(1),
iftocc(1),
iftoccfrom(1)
bouncesaying(1),
condredirect(1),
condtomaildir(1),
dot-qmail(5),
dot-forward(1),
fastforward(1),
printforward(1),
setforward(1),
filterto(1),
except(1),
preline(1),
qmail-command(8),
qnotify(1),
qreceipt(1),
replier(1),
rrforward(1)
indimail-srs(5),
qmail-queue(8)
