.\" vim: tw=75
.TH indimail-environ 5

.SH NAME
indimail-environ \- indimail-mta environment variables

.SH DESCRIPTION

.TP 4
\fIACCESSLIST\fR
Override \fI@sysconfdir@/control/accesslist\fR. Used by
\fBqmail-smtpd\fR(8).

.TP
\fIASSIGNDIR\fR
Override \fI@sysconfdir@/users/assign\fR. Used by \fBqmail-lspawn\fR(8),
\fBqmail-newu\fR(8), \fBqmail-smtpd\fR(8).

.TP
\fIAUTH_ALL\R, \fIREQUIREAUTH\fR
\fBAUTH_ALL\fR enforce authenticated SMTP if relaying. \fBREQUIREAUTH\fR
forces authenticated SMTP for all SMTP transactions before accepting
\fBMAIL FROM\fR.

.TP
\fIAUTHENTICATED\fR
Set by \fBqmail-smtpd\fR(8) on successful auhentication

.TP
\fIAUTHINFO\fR
Set by \fBqmail-smtpd\fR(8) to the authenticated envelope sender address

.TP
\fIALLOW_BARELF\fR
If set, \fBqmail-smtpd\fR(8) converts bare LF into CRLF, even though such
messages violate the SMTP protocol.

.TP
\fIDISABLE_CNAME_LOOKUP\fR
Used by \fBqmail-remote\fR(8) to disable cname lookups when it fails to
find MX record for a host.

.TP
\fIDISABLE_EXTRA_GREET\fR
Used by \fBqmail-smtpd\fR(8) to skip additional lines in the
\fIsmtpgreeting\fR control file.

.TP
\fIAUTHSELF\fR
If set, \fBqmail-lspawn\fR(8) authenticates against local database,
existence of users before delivery, rather than accepting delivery and then
bouncing the mail after discovring that the account doesn't exist

.TP
\fIAUTH_SMTP\fR
If set, \fBqmail-remote\fR(8) will use authenticated SMTP with the remote
host before starting delivery.

.TP
\fIBADEXT\fR
Override \fI@sysconfdir@/control/badext\fR. List of extensions that are
banned to be sent as attachments in emails. Used by \fBqmail-smtpd\fR(8)

.TP
\fIBADEXTPATTERNS\fR
Override \fI@sysconfdir@/control/badextpatterns\fR. List of patterns that
match extensions that are banned to be send as attachments in emails. Used
by \fBqmail-smtpd\fR(8)

.TP
\fIBADHELOCHECK\fR
If set, enfoces bad helo/ehlo check in \fBqmail-smtpd\fR(8).

.TP
\fIBADHOSTCHECK\fR
Enforce badhost check which rejects connections with \fBTCPREMOTEHOST\fR
matching entries in \fI@sysconfdir@/control/badhost\fR. Used by
\fBqmail-smtpd\fR(8)

.TP
\fIBADIPCHECK\fR
Enforce badip check which rejects connections with \fBTCPREMOTEIP\fR
matching entries in \fI@sysconfdir@/control/badip\fR. Used by
\fBqmail-smtpd\fR(8).

.TP
\fIBIGTODO\fR
This is a boolean which enables (1) or disables (0) bigtodo. Used by
\fBqmail-clean\fR(8), \fBqmail-qread\fR(8), \fBqmail-queue\fR(8),
\fBqmail-send\fR(8), \fBqmta-send\fR(8), \fBqscheduler\fR(8),
\fBqueue-fix\fR(8), \fBslowq-send\fR(8), \fBtodo-proc\fR(8). If
\fBBIGTODO\fR is non-zero, these programs will use \fICONFSPLIT\fR
directories in the todo directory of each queue.

.TP
\fIBODYCHECK\fR
Override \fI@sysconfdir@/control/bodycheck\fR control file. Used by
\fBqmail-smtpd\fR(8)

.TP
\fIBOUNCEMAIL\fR
If set, \fBqmail-smtpd\fR(8) bounces mail with value of \fBBOUNCEMAIL\fR
environment variable as the bounce message

.TP
\fIBOUNCEPROCESSOR\fR
If set, \fBqmail-send\fR(8) can execute an external program defined by this
variable when delivery to a recipient fails.

.TP
\fIBOUNCEQUEUE\fR
If set, \fBqmail-send\fR(8) will use this instead of \fBqmail-queue\fR(8)
to queue a bounce mail

.TP
\fICACHELIFETIME\fR
Overrides control file \fI@sysconfdir@/control/cachelifetime\fR. Allows you
to override the 300 seconds default of \fBsurblfilter\fR(8) results in
\fI@sysconfdir@/control/cache\fR directory.

.TP
\fICERTDIR\fR
Used by \fBqmail-smtpd\fR(8), \fBqmail-remote\fR(8), \fBdotls\fR(1),
\fBtcpclient\fR(1), \fBtcpserver\fR(1) to locate openssl certificates

.TP
\fICHECKRECIPIENT\fR
If set, \fBqmail-smtpd\fR(8) checks for recipient status in local passwd(5),
recipients.cdb or indimail-virtualdomain's MySQL database.

.TP
\fICHECKRELAY\fR
If set, \fBqmail-smtpd\fR(8) will check if the user from indimail-virtual
domains is successfully authenticated in the last 30 minutes and allows the
user to relay mails.

.TP
\fICHECKSENDER\fR
If set, \fBqmail-smtpd\fR(8) enforces user to authenticate when
\fBMAIL FROM\fR domain is in \fIrcpthosts\fR control file. It also prevents
user from forging the envelope sender address (\fBMAIL FROM\fR) by ensuring
that the \fBMAIL FROM\fR is the same as the authenticated user unless the
environment variable \fBMASQUERADE\fR is set.

.TP
\fIRELAY_CLEAR_MINUTES\fR
Override the default of 30 minutes within which time an indimail-virtual
domain user has authenticated, relaying will be allowed.

.TP
\fICLIENTCA\fR
A list of Certifying Authority (CA) certificates that are used to verify
the client-presented certificates during a TLS-encrypted session. The
default is \fI@sysconfdir@/certs/clientca.pem\fR. Used by
\fBqmail-smtpd\fR(8).

.TP
\fICLIENTCERT\fR
SSL certificate that is used to authenticate with the remote server during
a TLS session. The default is \fI@sysconfdir@/certs/clientcert.pem\fR. Used
by \fBqmail-remote\fR(8) as the certificate for negotiating a TLS session.

.TP
\fICLIENTCRL\fR
Override the default \fI@sysconfdir@/certs/clientcrl.pem\fR used by
\fBqmail-smtpd\fR(8).

.TP
\fICONFSPLIT\fR
Used by \fBqmail-clean\fR(8), \fBqmail-qread\fR(8), \fBqmail-queue\fR(8),
\fBqmail-rm\fR(1), \fBqmail-send\fR(8), \fBqmail-showctl\fR(8),
\fBtodo-proc\fR(8), \fBqmta-send\fR(8), \fBqueue-fix\fR(8),
\fBslowq-send\fR(8) to set the directory split. Default is \fBDIRSPLIT\fR

.TP
\fICONTROLDIR\fR
The directory to use for control files. The default is
\fI@sysconfdir@/control\fR. This is used by all indimail-mta to locate
various control files. This is a powerful variable and allows indimail-mta
to be configured dynamically.

.TP
\fISYSCONFDIR\fR
Used by indimail-virtualdomains programs if \fBCONTROLDIR\fR environment
variable is not an absolute path

.TP
\fICUGMAIL\fR
If set, \fBqmail-smtpd\fR(8) allows email transaction between hosts listed
in \fI@sysconfdir@/control/locals\fR and
\fI@sysconfdir@/control/virtualdomains\fR.

.TP
\fIDANETIMEOUT\fR
Max time to wait for a response from indimail-mta's DANE verification
daemon. Used by \fBqmail-remote\fR(8), tlsacheck

.TP
\fIDANE_VERIFICATION\fR
Turn on DANE verifiation. Used by \fBqmail-remote\fR(8)

.TP
\fIDATABYTES\fR
Max size of mail allowed to be injected in the queue or accepted from
remote clients. Used by \fBqmail-inject\fR(8), \fBqmail-smtpd\fR(8),
\fBqmail-lspawn\fR(8), \fBqmail-rspawn\fR(8). Overrides the
\fI@sysconfdir@/control/databytes\fR.

.TP
\fIDATABYTES_NOTIFY\fR
If set, \fBqmail-smtpd\fR(8) logs transactions denied when clients exceeed
DATABYTES limit

.TP
\fIDATA_TIMEOUT\fR
Amount of time to wait in seconds for timing out select(2) call in
\fBinotify\fR(1), \fBadminclient\fR(8), \fBproxyimap\fR(8),
\fBproxypop3\fR(8).

.TP
\fIDEATH\fR
Amount of time in seconds to wait before dying. Used by
\fBqmail-nullqueue\fR(8)

.TP
\fIDEBUG\fR
Turns on debug in \fBldap-checkpwd\fR(8), \fBqhpsi\fR(8),
\fBqmail-remote\fR(8), \fBauthindi\fR(7), \fBauthpgsql\fR(7),
\fBvchkpass\fR(8) and other checkpassword modules. This shouldn't be set on
production.

.TP
\fIDEBUG_LOGIN\fR
Logs logins and passwords for \fBldap-checkpwd\fR(8), \fBqhpsi\fR(8),
\fBqmail-remote\fR(8), \fBauthindi\fR(7), \fBauthpgsql\fR(7),
\fBvchkpass\fR(8) and other checkpassword modules. This shouldn't be set on
production. This is dangerous too.

.TP
\fIDEFAULT\fR
Used by \fBqmail-local\fR(8) and \fBfastforward\fR(1) as the default
recipient address. If this is not set, $EXT@$HOST is used.

.TP
\fIDEFAULT_DOMAIN\fR
Used by various indimail-virtual programs and \fBqmail-smtpd\fR(8) when domain
component is missing in addresses.

.TP
\fIDISABLE_AUTH_LOGIN\fR, \fIDISABLE_AUTH_PLAIN\fR, \fIDISABLE_CRAM_MD5\fR, \fIDISABLE_CRAM_RIPEMD\fR,
.TP
\fIDISABLE_CRAM_SHA1\fR, \fIDISABLE_CRAM_SHA224\fR, \fIDISABLE_CRAM_SHA256\fR, \fIDSABLE_CRAM_SHA384\fR,
.TP
\fIDISABLE_CRAM_SHA512\fR, \fIDISABLE_DIGEST_MD5\fR, \fIDISABLE_SCRAM_SHA1\fR, \fIDISABLE_SCRAM_SHA256\fR

If set these variables stop \fBqmail-smtpd\fR(8) from advertising these
authentication mechanisms as response to EHLO command

.TP
\fIDISABLE_PLUGIN\fR
Disables loading of external plugins in \fBqmail-smtpd\fR(8)

.TP
\fIDISPOSITION_HEADER\fR
Overrides the default Disposition-Notification-To header used by \fBqnotify\fR(1)
for sending notifications.

.TP
\fIDKIMEXPIRE\fR
Used by \fBqmail-dkim\fR(8) to set the expire time in seconds for the signature.
This overrides the x option in \fBDKIMSIGNOPTIONS\fR.

.TP
\fIDKIMIDENTITY\fR
Used by \fBqmail-dkim\fR(8) to set the identity for the signature. This overrides
the i option in \fBDKIMSIGNOPTIONS\fR.

.TP
\fIDKIMKEY\fR
When both \fBDKIMSIGN\fR and \fBDKIMVERIFY\fR are not set, this turns on
DKIM signing by \fBqmail-dkim\fR(8), only for authenticated users and
overrides the default DKIM private key
\fI@sysconfdir@/control/domainkeys/default\fR.

.TP
\fIDKIMPRACTICE\fR
\fBqmail-dkim\fR(8) turns on SSP/ADSP signing practice for messages that fail DKIM
verification

.TP
\fISIGN_PRACTICE\fR
\fIUsed by \fBqmail-dkim\fR(8) to set DKIM sign practice as ssp, adsp or local\fR

.TP
\fIDKIMSIGN\fR
Path to DKIM private key. By default \fBqmail-dkim\fR(8) uses
\fI@sysconfdir@/control/domainkeys/default\fR.

.TP
\fIDKIMSIGNOPTIONS\fR
getopt sytle list of DKIM options used by \fBqmail-dkim\fR(8)

.TP
\fIDKIMVERIFY\fR
If set, \fBqmail-dkim\fR(8) performs DKIM verification for messages.

.TP
\fIBOUNCEDOMAIN\fR
\fBqmail-dkim\fR(8) uses the domain found in the Return-Path, Sender, From
headers to set the domain tag. If not it uses the \fBBOUNCEDOMAIN\fR
environment variable. \fBBOUNCEDOMAIN\fR can be set to an email address or
a domain (without the at sign).

.TP
\fIDNSBLLIST\fR
Override \fI@sysconfdir@/control/dnsbllist\fR. A list of dnsbl providers
that \fBqmail-smtpd\fR(8) checks to identify blacklisted ip addresses.

.TP
\fIDNSCACHEIP\fR \fIDNSREWRITEFILE\fR \fILOCALDOMAIN\fR
Set \fBDNSCACHEIP\fR to make \fBtcpserver\fR(1) set the DNS resolver's
IP(s) dynamically irrespectively of settings in \fI/etc/resolv.conf\fR. The
individual IPs are separated by blanks; If the environment variable
\fBLOCALDOMAIN\fR is populated, this name will be appended to unqualified
host names. Additional rewriting of local to public names is facilitated in
case the file \fI/etc/dnsrewrite\fR exists and is populated, or
alternatively, the environment variable \fBDNSREWRITEFILE\fR points to a
different file. See \fBdjbdns\fR(7), \fBqualification\fR(5) for more
details.

.TP
\fIDOMAINBINDINGS\fR
Override control file \fI@sysconfdir@/control/domainbindings\fR which makes
\fBqmail-remote\fR(8) bind specific local ip addresses based on envelope
sender address.

.TP
\fIDOMAIN_MASQUERADE\fR \fIPARANOID\fR
If using hostaccess feature in \fBqmail-smtpd\fR(8),
\fBDOMAIN_MASQUERADE\fR allows other mails from other domains to be
accepted from an IP which has been listed for another domain in the
\fI@sysconfdir@/control/hostaccess\fR control file. Settin \fBPARANOID\fR
allows only specific domain-ip pairs listed in hostaccess control file to
be accepted. Also look at the \fBTCPPARANOID\fR environment variable set by
\fBtcpserver\fR(1).

.TP
\fIHOSTACCESS\fR
Override \fI@sysconfdir@/control/hostaccess\fR used by
\fBqmail-smtpd\fR(8).

.TP
\fIDOVECOT_VERSION\fR \fINATIVE_CHECKPASSWORD\fR
If set, \fBvchkpass\fR(8) checkpassword module Supports dovecot's native
checkpassword authentication mechanism. i.e. \fBvchkpass\fR(8) will run
external prog on successful authentication and exit 1 if password is
unacceptable. Totally opposite of what indimail's checkpassword programs do.

.TP
\fIENABLE_CRAM\fR
If set, \fBvchkpass\fR(8) checkpassword will support the encrypted password
field to be used as the password for CRAM authentication. This variable is
not required if you have used -C, -m option to \fBvpasswd\fR(1),
\fBvmoduser\fR(1), \fBvadddomain\fR(1), \fBvmoddomain\fR(1).

.TP
\fIALLOW_INACTIVE\fR
If set, \fBvchkpass\fR(8) will allow authentication for inactive users 

.TP
\fIDTLINE\fR
Used by \fBautoresponder\fR(1), \fBcondredirect\fR(1),
\fBcondtomaildir\fR(1), \fBdot-forward\fR(1), \fBfastforward\fR(1),
\fBfilterto\fR(1), \fBforward\fR(1), \fBmaildirdeliver\fR(1),
\fBpreline\fR(1), \fBrrforward\fR(1) to get the value of \fBDelivered-To\fR
header. Set by \fBqmail-local\fR(8) and \fBserialcmd\fR(1)

.TP
\fIENFORCE_FQDN_HELO\fR
Used by \fBqmail-smtpd\fR(8) to enforce clients to supply a fully qualified
domain name in helo/ehlo command.

.TP
\fIENVHEADERS\fR
Override control file \fI@sysconfdir@/control/envheaders\fR. List of custom
headers that \fBqmail-queue\fR(8) should pass to \fBqmail-local\fR(8),
\fBqmail-remote\fR(8) in the queue.

.TP
\fIERROR_FD\fR
Override the default stderr fd of 2. \fBqmail-queue\fR(8) clients can pass
on custom error (=bounce) messages back on this file descriptor when they
exit 88. Any \fBqmail-queue\fR(8) client have to write the error message to
STDERR and exit 88 in order to use the custom  message. Used by all
programs that use \fBqmail-queue\fR(8) to queue messages. Setting ERROR_FD
to -1 disables custom error message.

.TP
\fIEXT\fR \fIEXT2\fR \fIEXT3\fR \fIEXT4\fR
Set by \fBqmail-local\fR(8), \fBserialcmd\fR(1)

.TP
\fIEXTRA\fR
Used by checkpassword programs when using dovecot

.TP
\fIEXTRAQUEUE\fR
Override \fI@sysconfdir@/control/extraqueue\fR. If this control file
exists, each line in the content is added as a recipient to the recipient
list by \fBqmail-queue\fR(8)

.TP
\fIFILTERARGS\fR
A filter program with arguments to execute. Used by \fBqmail-multi\fR(8),
\fBspawn-filter\fR(8) to filter mail message through filters. The output of
the filter becomes the modified / delivered message.

.TP
\fIFORCE_TLS\fR
If set, \fBqmail-smtpd\fR(8) forces TLS session with clients.

.TP
\fIUID\fR \fIGID\fR
Used by \fBtcpserver\fR(1) to switch to \fIUID\fR, \fIGID\fR in the child
when passed -U option.

.TP
\fIGREETDELAY\fR
Overrides the control file \fI@sysconfdir@/control/greetdelay\fR used by
\fBqmail-smtpd\fR(8)

.TP
\fIGREYIP\fR
If set, \fBqmail-smtpd\fR(8) enables greylisting against
\fBqmail-greyd\fR(8) running on the IP \fB$GREYIP\fR

.TP
\fISPAMFILTER\fR, \fIHAMEXITCODE\fR, \fISPAMEXITCODE\fR, \fISPAMIGNORE\fR,
.TP
\fISPAMIGNOREPATTERNS\fR, \fISPAMREDIRECT\fR \fIREJECTSPAM\fR,
.TP
\fIUNSUREEXITCODE\fR
Used by \fBqmail-spamfilter\fR(8) when spam filtering is enabled by setting
\fBSPAMFILTER\fR.

.TP
\fIHELOHOSTBYIP\fR
Override \fI@sysconfdir@/control/helohostbyip\fR control file used by
\fBqmail-remote\fR(8).

.TP
\fIHOME\fR
Used by \fBcondredirect\fR(1), \fBdot-forward\fR(1), \fBfastforward\fR(1),
\fBfilterto\fR(1), \fBforward\fR(1), \fBmaildirserial\fR(1),
\fBnew-inject\fR(8), \fBprocess_queue\fR(3), \fBqmail-inject\fR(8),
\fBqmail-qread\fR(8), \fBqmail-showctl\fR(8), \fBqmta-send\fR(8),
\fBqnotify\fR(1), \fBqreceipt\fR(1), \fBqueue-fix\fR(8), \fBreplier\fR(1),
\fBrrforward\fR(1), \fBrrt\fR(1), to load environment variables from
\fI$HOME/.defaultqueue\fR directory

.TP
\fISKIP_LOCAL_ENVIRONMENT\fR
Used by \fBcondredirect\fR(1), \fBdot-forward\fR(1), \fBfastforward\fR(1),
\fBfilterto\fR(1), \fBforward\fR(1) \fBmaildirserial\fR(1),
\fBnew-inject\fR(8), \fBprocess_queue\fR(3), \fBqmail-inject\fR(8),
\fBqmail-qread\fR(8), \fBqmail-showctl\fR(8), \fBqmta-send\fR(8),
\fBqnotify\fR(1), \fBqreceipt\fR(1), \fBqueue-fix\fR(8) \fBreplier\fR(1),
\fBrrforward\fR(1), \fBrrt\fR(1) to skip \fI$HOME/.defaultqueue\fR
directory for environment variables.

.TP
\fIHONOR_BODYLENGTHTAG\fR
If set, \fBqmail-dkim\fR(8) honors body length tag.

.TP
\fIHOST\fR
Set by \fBqmail-local\fR(8), \fBqmail-qfilter\fR(1), \fBserialcmd\fR(1).
Used by \fBautoresponder\fR(1), \fBdot-forward\fR(1), \fBfastforward\fR(1),
\fBqmail-inject\fR(8), \fBqnotify\fR(1), \fBsrsfilter\fR(1)

.TP
\fIHOSTNAME\fR
Used by \fBqmail-queue\fR(8) for putting hosname against TCPREMOTEIP in
Received headers.

.TP
\fIINCLUDE_TRASH\fR
If set, \fBmaildirsize\fR(1) and \fBqmail-smtpd\fR(8) ETRN will include
mails in trash as part of the user's quota (size, count or size+count).

.TP
\fIINITCMD\fR
\fIWAIT_INITCMD\fR
If set, \fBsvscan\fR(8) runs an initialization command defined by this variable
before startup. If \fBWAIT_INITCMD\fR is set, \fBsvscan\fR(8) will wait for the
command to exit.

.TP
\fILDAP_BASE\fR
\fILDAP_BIND_DN\fR
\fILDAP_BIND_PASSWD\fR
\fILDAP_FILTER\fR
\fILDAP_HOST\fR
\fILDAP_PORT\fR
\fILDAP_SCOPE\fR
Used by \fBldap-checkpwd\fR(8) checkpassword authentication module

.TP
\fILEVEL2_TLD\fR
\fILEVEL3_TLD\fR
Set this to override \fBsurblfilter\fR(8) control files \fIlevel2_tld\fR,
\fIlevel3_tld\fR.

.TP
\fILOCAL\fR
Set by \fBqmail-local\fR(8), \fBserialcmd\fR(1). Used by the
\fBreplier\fR(1) program

.TP
\fILOCALDOMAINS\fR
If set, forces \fBqmail-local\fR(8) to treat only those domains in control
file \fI@sysconfdir@/control/localdomains\fR as local. This restrict local
deliveries for users only from certain domains.

.TP
\fILOGFILTER\fR
\fILOGFD\fR
\fBLOGFILTER\fR is used by \fBqmail-smtpd\fR(8) to log SMTP transactions
marked as spam to a fifo created by qmail-logfilter. If this FIFO is
pre-opened, it can be specified in \fBLOGFD\fR.

.TP
\fILOGHEADERS\fR
\fILOGHEADERFD\fR
Override control file \fI@sysconfdir@/control/logheaders\fR used by
\fBqmail-queue\fR(8). If this is set or this control files exists,
\fBqmail-queue\fR(8) will log headers matching lines in this control file
with the value of the header. It will do this by writing to fd equal to
\fBLOGHEADERFD\fR.

.TP
\fILOGLOCK\fR
indimail-mta uses multiple queues with each queue being served by specific
\fBtodo-proc\fR(8), \fBqmail-send\fR(8), \fBqmail-lspawn\fR(8),
\fBqmail-rspawn\fR(8) and \fBqmail-clean\fR(8) processes. The standard
output and errors all go to a single fd (usually setup by
\fBsupervise\fR(8)). The output can get jumbled up. Setting this prevents
log output to be written only with it is a complete line.

.TP
\fILOGNAME\fR
Used by \fBqmail-inject\fR(8), \fBnew-inject\fR(8)

.TP
\fIMAIL\fR
Used by maildir2mbox program

.TP
\fIMAILARCHIVE\fR
Override \fI@sysconfdir@/control/mailarchive\fR control file used by
\fBqmail-queue\fR(8).

.TP
\fIMAILDIR\fR
Used by \fBmaildir2mbox\fR(1), \fBmbox2maildir\fR(1) and
\fBmaildirwatch\fR(1) programs

.TP
\fIMAILDIRSIZE_MAX_AGE\fR
Used by \fBvdelivermail\fR(8) to recalculate quota if the age for
\fImaildirsize\fR(1) exceeds this value.

.TP
\fIMAILDIRSIZE_MAX_SIZE\fR
Used by \fBvdelivermail\fR(8) to recalcuate quota if the size for
\fImaildirsize\fR exceeds this value. Multiple quota lines in
\fImaildirsize\fR is collapsed to a single line containing the
totals.

.TP
\fIMAILHOST\fR
\fINAME\fR
Used by \fBnew-inject\fR(8), \fBqmail-inject\fR(8) and unset by
\fBsendmail\fR(8)

.TP
\fIMAILNAME\fR
Used by \fBnew-inject\fR(8), \fBqmail-inject\fR(8) and set by
\fBsendmail\fR(8)

.TP
\fIMAILTMP\fR
Used by \fBmaildir2mbox\fR(1).

.TP
\fIMAILUSER\fR
Used by \fBnew-inject\fR(8) and \fBqmail-inject\fR(8)

.TP
\fIMAKE_SEEKABLE\fR
Used by \fBqmail-spamfilter\fR(8) and \fBautoresponder\fR(1)

.TP
\fIMASQUERADE\fR
If set, authenticated users will be allowed to use envelope sender
different from that of the authenticated address.

.TP
\fIMAXPERIP\fR
Used by \fBtcpserver\fR(1) to limit connections from one IP.

.TP
\fIMAX_RCPT_ERRCOUNT\fR
Maximum invalid recipients that \fBqmail-smtpd\fR(8) will allow in a single
SMTP transaction.

.TP
\fIMAXRECIPIENTS\fR
Maximum recipients that \fBqmail-smtpd\fR(8) will allow in a single SMTP
transaction.

.TP
\fIMAX_TOLERANCE\fR
\fIMIN_FREE\fR
\fIMIN_PENALTY\fR
Used by \fBqmail-remote\fR(8) when delivery to remote host result in
temporary errors.

.TP
\fIMESSID\fR
Set by \fBqmail-lspawn\fR(1), \fBqmail-rspawn\fR(1) to the message file
path in the queue.

.TP
\fIMORESMTPROUTESCDB\fR
Override \fI@sysconfdir@/control/moresmtproutes.cdb\fR used by
\fBqmail-remote\fR(8)

.TP
\fIMSGQSIZE\fR
Set in services variables to decide POSIX message queue size limit for
qscheduler.

.TP
\fIMYSQL_LIB\fR
Override \fI@sysconfdir@/control/mysql_lib\fR control file used by
\fBqmail-smtpd\fR(8), \fBqmail-lspawn\fR(8), \fBqmail-respawn\fR(8),
\fBqmail-showctl\fR(8), \fBmaildirsize\fR(1), \fBqmail-sql\fR(8),
\fBsql-database\fR(8), \fBctrlenv\fR(8).

.TP
\fIMYSQL_TIMEOUT\fR
Timeout for connecting to MySQL. Used by \fBqmail-smtpd\fR(8),
\fBqmail-sql\fR(8), \fBsql-database\fR(8), \fBctrlenv\fR(1).

.TP
\fINEWSENDER\fR
Used by forward, \fBrrforward\fR(1) and set by \fBqmail-local\fR(8)

.TP
\fINODNSCHECK\fR
If set, \fBqmail-smtpd\fR(8) disables if the envelope sender domain exists
in dns.

.TP
\fINOSIGNATUREDOMAINS\fR
Override control file \fI@sysconfdir@/nosignaturedomains\fR used by
\fBqmail-dkim\fR(8)

.TP
\fINOTLSHOSTS\fR
override \fI@sysconfdir@/control/notlshosts\fR used by
\fBqmail-remote\fR(8).

.TP
\fINULLQUEUE\fR
If set, \fBqmail-nullqueue\fR(8) gets used to drain the message without
putting it in the queue. This overrides \fBQMAILQUEUE\fR environment
variable.

.TP
\fIONFAILURE_REMOTE\fR \fIONSUCCESS_REMOTE\fR \fIONTEMPORARY_REMOTE\fR
Used by \fBqmail-remote\fR(8) to execute external program / scripts after
delivery or after a temporary failure.

.TP
\fIORIGINIPFIELD\fR
Overrides \fI@sysconfdir@/control/originipfield\fR used by
\fBqmail-remote\fR(8).

.TP
\fIOUTGOINGIP\fR
Overrides \fI@sysconfdir@/control/outgoingip\fR used by
\fBqmail-remote\fR(8).

.TP
\fIPASSWORD_COMMAND\fR
The password command to execute by the \fBqmail-poppass\fR(8) daemon.

.TP
\fISMTP_PLUGIN\fR \fISMTP_PLUGIN_SYMB\fR
used by \fBqmail-smtpd\fR(8) to load smtp plugins

.TP
\fISOFT_MEM\fR
Set in services variables to decide soft limit for various services

.TP
\fIPLUGINDIR\fR
Directory to look for plugins by \fBqhpsi\fR(8) and \fBqmail-smtpd\fR(8)

.TP
\fIPORT_QMQP\fR
Override the default port 628 used by \fBqmail-qmqpc\fR(8).

.TP
\fIPOSTAUTH\fR
Program to execute after successful authentication by
\fBsys-checkpwd\fR(8), \fBvchkpass\fR(8), \fBldap-checkpwd\fR(8),
\fBpam-checkpwd\fR(8), \fBauthindi\fR(7), \fBauthpgsql\fR(7)

.TP
\fIPROTO\fR
Set by \fBtcpclient\fR(1), \fBtcpserver\fR(1), \fBsendmail\fR(8),
\fBtcp-env\fR(1)

.TP
\fIPWD\fR
Used by \fBsvscan\fR(8) to get the current working directory.

.TP
\fIQIDENT\fR
queue identifier set by \fBqscheduler\fR(8). Each invocation of
\fBqmail-send\fR(8) uses a queue with a unique identifier. e.g.
\fBQIDENT\fR is 1 for queue1, 2 for queue2 and so on.

.TP
\fIQHPSI\fR \fIQHPSIMAXSIZE\fR \fIQHPSIMINSIZE\fR \fIQHPSIRC\fR
\fIQHPSIRN\fR Used by \fBqhpsi\fR(8)

.TP
\fIQLOCAL\fR, \fIQREMOTE\R
Used by spawn-filter to execute alternet \fBqmail-local\fR(8),
\fBqmail-remote\fR(8) binaries.

.TP
\fIQMAILDEFAULTDOMAIN\fR
\fIQMAILDEFAULTHOST\fR
Used by \fBofmipd\fR(8), \fBnew-inject\fR(8) \fBqmail-inject\fR(8),
\fBnewinclude\fR(1).

.TP
\fIQMAILGETPW\fR
Used by \fBqmail-spawn\fR(8) to execute an alternate \fBqmail-getpw\fR(8).

.TP
\fIQMAILHOST\fR
Used by \fBautoresponder\fR(1), \fBqmail-qfilter\fR(1). Set by
\fBnew-inject\fR(8), \fBqmail-inject\fR(8), \fBsendmail\fR(8)

.TP
\fIQMAILIDHOST\fR
Used by \fBofmipd\fR(8), \fBnew-inject\fR(8), \fBqmail-inject\fR(8)

.TP
\fIQMAILINJECT\fR \fIQMAILINJECT_FORCE_SRS\fR \fIQMAILINJECT_SKIP_SRS\fR
Used by \fBqmail-inject\fR(8)

.TP
\fIQMAILMFTFILE\fR
Used by \fBnew-inject\fR(8), \fBqmail-inject\fR(8)

.TP
\fIQMAILNAME\fR
Used by \fBnew-inject\fR(8), \fBqmail-inject\fR(8). Unset by
\fBautoresponder\fR(1), \fBqmail-qfilter\fR(1), \fBsendmail\fR(8)

.TP
\fIQMAILPLUSDOMAIN\fR
Used by ofmipd, \fBnew-inject\fR(8), \fBqmail-inject\fR(8), newinclude

.TP
\fIQMAILLOCAL\fR
Used by \fBqmail-lspawn\fR(8) to execute an alternate \fBqmail-local\fR(8)
binary.

.TP
\fIQMAILREMOTE\fR
Used by \fBqmail-rspawn\fR(8) to execute an alternate \fBqmail-remote\fR(8)
binary.

.TP
\fIQMAILQUEUE\fR
Used by all \fBqmail-queue\fR(8) clients \fBcondredirect\fR(1),
\fBdot-forward\fR(1), \fBfastforward\fR(1), \fBfilterto\fR(1),
\fBforward\fR(1), \fBmaildirserial\fR(1), \fBnew-inject\fR(8), ofmipd,
\fBqmail-inject\fR(8), \fBqmail-local\fR(8), qmail-qmqpd, qmail-qmtpd,
\fBqmail-queue\fR(8), \fBqmail-send\fR(8), \fBqmta-send\fR(8),
\fBqnotify\fR(1), \fBqreceipt\fR(1), \fBreplier\fR(1),
\fBrrforward\fR(1), \fBrrt\fR(1), \fBslowq-send\fR(8), smtpd,
\fBsrsfilter\fR(1)

.TP
\fIQMAILRCPTS\fR
Used by \fBqmail-qfilter\fR(1), \fBsurblfilter\fR(8).

.TP
\fIQMAILSHOST\fR \fIQMAILSUSER\fR
Used by \fBnew-inject\fR(8), \fBqmail-inject\fR(8)

.TP
\fIQMAILUSER\fR
used by \fBnew-inject\fR(8), \fBqmail-inject\fR(8). Set by
\fBqmail-qfilter\fR(1), \fBsendmail\fR(8). Unset by \fBautoresponder\fR(1)

.TP
\fIQMTPCODE\fR
Used by \fBqmail-remote\fR(8), \fBrrt\fR(1)

.TP
\fIQMTPTEXT\fR
Used by \fBqmail-remote\fR(8)

.TP
\fIQQEH\fR
This can be set before calling \fBqmail-queue\fR(8) to insert extra
headers. Used by \fBcondredirect(1)\fR, \fBcondtomaildir(1)\fR,
\fBfilterit(1)\fR, \fBforward(1)\fR, \fBmaildirdeliver(1)\fR,
\fBpreline(1)\fR, \fBqmail-local(8)\fR, \fBqmail-queue(8)\fR. If set,
qmail-queue passes the value across the queue. Set by \fBqmail-local\fR(8),
\fBfilterit\fR(1) to set the X-Filterit header.

.TP
\fIQREGEX\fR
Used by \fBqmail-smtpd\fR(8), \fBqmail-inject\fR(8), \fBspawn-filter\fR(8),
\fBqmail-send\fR(8), \fBslowq-send\fR(8), \fBdrate\fR(1), \fBuacl\fR(1).

.TP
\fIQUARANTINE\fR
Override \fI@sysconfdir@/control/quarantine\fR control file Used by
\fBqmail-queue\fR(8).

.TP
\fIQUERY_CACHE\fR
Used by \fBqmail-smtpd\fR, \fBqmail-lspawn\fR(8), \fBvchkpas\fR(8) to use
\fBinlookup\fR(8), \fBauthindi\fR(7) password request connection pooling
daemon for authentication and user and password lookups.

.TP
\fIQUEUE_BASE\fR \fIQUEUE_START\fR \fIQUEUE_COUNT\fR \fIQUEUEDIR\fR
Used by drate, \fBqscheduler\fR(8), \fBqmail-qread\fR(8),
\fBqmail-rm\fR(1), \fBqmail-showctl\fR(8), \fBqmail-tcpok\fR(8),
\fBqmail-tcpto\fR(8), \fBqmail-multi\fR(8), \fBspawn-filter\fR(8),
\fBcondredirect\fR(1), \fBdot-forward\fR(1), \fBfastforward\fR(1),
\fBfilterto\fR(1), forward, maildirserial, \fBnew-inject\fR(8),
\fBqmail-inject\fR(8), \fBqmail-qread\fR(8), \fBqmail-showctl\fR(8),
\fBqmta-send\fR(8), \fBqnotify\fR(1), \fBqreceipt\fR(1),
\fBqueue-fix\fR(8), \fBreplier\fR(1), \fBrrforward\fR(1), \fBrrt\fR(1)
to select a queue from indimail's multi queue.

.TP
\fIERROR_INTERVAL\fR
Used by \fBqscheduler\fR(8) when in dynamic mode. Any failure in accessing
message queues, shared memory segments, opening control files
\fBqscheduler\fR sleeps for \fBERROR_INTERVAL\fR seconds before continuing.

.TP
\fIQUEUE_LOAD\fR
Used by \fBqscheduler\fR(8), \fBqmail-send\fR(8) and \fBqmail-qread\fR(8)
as the threshold for maximum queue load. queue load is the average
concurrencies of all the queues. When this is exceeded, \fBqscheduler\fR(8)
creates additional queue and starts \fBtodo-proc\fR(8), \fBqmail-send\fR(8)
instance to reduce the average concurrency.

.TP
\fIQUEUE_MAX\fR
The maximun number of queues \fBqscheduler\fR(8) will create when
\fIQUEUE_LOAD\fR is exceeded.

.TP
\fIQUEUE_PLUGIN_SYMB\fR
Used by \fBqhpsi\fR(8)

.TP
\fIQUEUEPROG\fR
Override the the queue program \fBqmail-queue\fR(8) executed by
\fBqmail-multi\fR(8) to queue the mail.

.TP
\fIRATELIMIT_DIR\fR \fIRATELIMIT_INTERVAL\fR
Used by \fBqmail-send\fR(8), \fBslowq-send\fR(8)

.TP
\fIRBLEHLO\fR \fIRBLGREETING\fR \fIRBLSMTPD\fR
Used by \fBrblsmtpd\fR(1)

.TP
\fIRECIPIENT\fR
Used by \fBautoresponder\fR(1), checkaddr, checkdomain,
\fBfastforward\fR(1), ifaddr, iftocc, iftoccfrom, \fBqnotify\fR(1).
Set by \fBqmail-local\fR(8), \fBserialcmd\fR(1)k

.TP
\fIREJECTVIRUS\fR \fIVIRUSFORWARD\fR
Used by \fBqmail-queue\fR(8). Infected mails will be quarantined to the
email defined by \fBVIRUSFORWARD\fR. This will work only if
\fBREJECTVIRUS\fR is not equal to 1. Setting \fBVIRUSFORWARD\fR sets the
\fBX-Quarantine-ID\fR containing the list of original recipient list is
added.

.TP
\fIRELAYCLIENT\fR
Used by \fBofmipd\fR(8), \fBqmail-dkim\fR(8), \fBqmail-qmtpd\fR(8),
\fBqmail-queue\fR(8), \fBqmail-spamfilter\fR(8), \fBqmail-smtpd\fR(8). Set
by \fBsendimail\fR(1), \fBtcpserver\fR(1).

.TP
\fIRELAYCLIENT_NODKIMVERIFY\fR
used by \fBqmail-dkim\fR(8)

.TP
\fIREMOTEINFO\fR
Used by \fBofmipd\fR(8).

.TP
\fIREMOVEHEADERS\fR
override \fI@sysconfdir@/control/removeheaders\fR used by
\fBqmail-queue\fR(8).

.TP
\fIREQPTR\fR
If the environment variable \fBREQPTR\fR is set and \fBTCPREMOTEHOST\fR is
absent, \fBqmail-smtpd\fR(8) rejects connections from unresolvable IP address
(hosts without reverse DNS). \fBqmail-smtpd\fR(8) returns permanent error
code 553 to the client. \fBTCPREMOTEHOST\fR environment variable is removed by
\fBtcpserver\fR(1) if remote host (\fBTCPREMOTEIP\fR) does not have a reverse
DNS record.

.TP
\fIROUTE_NULL_USER\fR
If set, \fBqmail-lspawn\fR(8) redirects double bounces to a mailbox

.TP
\fIQMTPROUTE\fR \fISMTPROUTE\fR
Used by \fBqmail-remote\fR(8), set by \fBqmail-rspawn\fR(8)
.TP
\fISMTPROUTEFILE\fR \fIQMTPROUTEFILE\fR
Override \fI@sysconfdir@/control/\fR[\fIsmtproutes\fR,\fIqmtproutes\fR]
control file used by \fBqmail-remote\fR(8).
.TP
\fIROUTES\fR
Used by \fBqmail-remote\fR(8)
If set as "smtp", \fBqmail-rspawn\fR(8) sets the \fBSMTPROUTE\fR variable
for a indimail-virtualdomain user. If set as "qmtp", \fBqmail-rspawn\fR(8)
sets the \fBQMTPROUTE\fR variable for a indimail-virtualdomain user.

.TP
\fIRPLINE\fR
Used by \fBcondtomaildir\fR(1), \fBdot-forward\fR(1),
\fBmaildirdeliver\fR(1), \fBpreline\fR(1), \fBqnotify\fR(1) to get the
\fBReturn-Path\fR. Set by \fBqmail-local\fR(8) and \fBserialcmd\fR(1),
\fBvacation\fR(8).

.TP
\fISANITIZE_ENV\R
Used by \fBqmail-local\fR(8) to clear all environment variables other than
\fBUSE_FSYNC\fR, \fBUSE_FDATASYNC\fR, \fBUSE_SYNCDIR\fR. You can set
additional environment variables to preserve by setting \fBSANITIZE_ENV\fR
as a colon ':' separated list of environment variables to preserve.

.TP
\fISCANCMD\fR \fISCANDIR\fR
Used by \fBqscanq-stdin\fR(8), \fBqhpsi\fR(8)

.TP
\fISCANINTERVAL\fR \fISCANLOG\fR
Used by \fBsvscan\fR(8)

.TP
\fISECURE_AUTH\fR
Enforces TLS when doing authenticated SMTP in \fBqmail-smtpd\fR(8). In
\fBqmail-remote\fR(8), authenticated SMTP gets disabled unless TLS is used.

.TP
\fISENDER\fR
Used by \fBautoresponder\fR(1), \fBcondredirect\fR(1),
\fBfastforward\fR(1), \fBfilterto\fR(1), \fBqnotify\fR(1),
\fBqreceipt\fR(1), \fBreplier\fR(1), \fBreplier-config(1),
\fBqmail-smtpd\fR(8), \fBsrsfilter\fR(1), \fBqmail-remote\fR(8),
\fBvacation\fR(1).  Set by \fBqmail-local\fR(8), \fBserialcmd\fR(1)

.TP
\fISERVERCERT\fR
Overrides the default certificate \fI@sysconfdir@/certs/servercert.pem\fR
used by \fBqmail-smtpd\fR(8).

.TP
\fISERVICE_RESPONDER\fR
Used by \fBautoresponder\fR(1)

.TP
\fISETSID\fR
Used by \fBsvscan\fR(8). If set, \fBsvscan\fR(8) calls setsid(2) to make
the child a session leader.

.TP
\fISETPGID\fR
Used by \fBsupervise\fR(8). If set, \fBsupervise\fR(8) calls setpgid(2) to
make the child run in its own process group.

.TP
\fITERMINATE_SESSION\fR
Used by \fBsvscan\fR(8). If set along with \fBSETSID\fR, \fBsvscan\fR(8)
calls kill(0, 15) to terminate all \fBsupervise\fR(8) processes started by
it.

.TP
\fISHUTDOWN\fR
Path to a script / command used by \fBsvscan\fR(8) to execute on -d option
to \fBsvc\fR(1).

.TP
\fISIGNATUREDOMAINS\fR
Override \fI@sysconfdir@/control/signaturedomains\fR control file used by
\fBqmail-dkim\fR(8)

.TP
\fIBATVKEY\fR
Override \fI@sysconfdir@/control/batvkey\fR control file used by
\fBqmail-smtpd\fR(8), \fBqmail-remote\fR(8).

.TP
\fIBATVKEYSTALE\fR
Override \fI@sysconfdir@/control/batvkeystale\fR control file used by
\fBqmail-smtpd\fR(8), \fBqmail-remote\fR(8).

.TP
\fIBATVNOSIGNLOCALS\fR
Override \fI@sysconfdir@/control/batvnosinlocals\fR control file used by
\fBqmail-smtpd\fR(8), \fBqmail-remote\fR(8).

.TP
\fIBATVNOSIGNREMOTE\fR
Override \fI@sysconfdir@/control/batvnosinremote\fR control file used by
\fBqmail-smtpd\fR(8), \fBqmail-remote\fR(8).

.TP
\fISKIPDNSBL\fR
If set, \fBqmail-smtpd\fR(8) skips dnsbl check

.TP
\fISMTPS\fR
If set, \fBqmail-smtpd\fR(8) starts a tls session to support the deprecated
SMTPS protocol.

.TP
\fISMTPUTF8\fR
Enables RFC 5336 SMTP Email  Address Internationalization  support in
\fBqmail-smtpd\fR(8) and \fBqmail-remote\fR(8)

.TP
.nf
\fISRS_DOMAIN\fR, \fISRS_SECRETS\fR, \fISRS_MAXAGE\fR, \fISRS_HASHLENGTH\fR, \fISRS_HASHMIN\fR, \fISRS_ALWAYSREWRITE\fR, \fISRS_SEPARATOR\fR
.fi
These are used for configuring Sender Rewriting Scheme (SRS). Used by 
\fBcondredirect\fR(1), \fBforward\fR(1), \fBqmail-inject\fR(8),
\fBqmail-local\fR(8), \fBqmail-send\fR(8), \fBqmta-send\fR(8),
\fBslowq-send\fR(8), \fBqmail-smtpd\fR(8), \fBsrsfilter\fR(1)

.TP
\fISTART_PLUGIN\fR \fISTART_PLUGIN_SYMB\fR
Enables to load and execute startup plugin in \fBqmail-send\fR(8)

.TP
\fISTARTTLS\fR
If enabled, \fBqmail-smtpd\fR(8) advertizes STARTTLS capability in EHLO
response

.TP
\fISTRIP_DOMAIN\fR
If enabled, \fBsys-checkpwd\fR(8) strips domain component from username

.TP
\fISURBLDOMAINWHITE\fR
Overrides \fI@sysconfdir@/control/surbldomainwhite\fR control file used by
\fBsurblfilter\fR(8)

.TP
\fISURBLRCPT\fR
Overrides \fI@sysconfdir@/control/surblrcpt\fR control file used by
\fBsurblfilter\fR(8)

.TP
\fISV_PWD\fR
Set by \fBsvscan\fR(8) to set the current working dirctory and used by
\fBsupervise\fR(8) to get the current working directory.

.TP
\fITCP6LOCALIP\fR \fITCP6REMOTEIP\fR \fITCPLOCALHOST\fR \fITCPLOCALIP\fR
\fITCPLOCALPORT\fR
.TP
\fITCPREMOTEHOST\fR \fITCPREMOTEINFO\fR \fITCPREMOTEIP\fR
See \fBtcp-env\fR(1)iron(5)

.TP
\fITCPPARANOID\fR
Set by \fBtcpserver\fR(1) host has reverse DNS but IP does not match
remoteip

.TP
\fITLSADOMAINS\fR
Override \fI@sysconfdir@/control/tlsadomains\fR used by \fBqmail-remote\fR(8)

.TP
\fITLS_CERTFILE\fR
Used by \fBsslerator\fR(8).

.TP
\fITLS_CIPHER_LIST\fR \fITLS_CIPHER_SUITE\fR
Used by \fBsslerator\fR(8), \fBqmail-smtpd\fR(8), \fBqmail-remote\fR(8).

.TP
\fITMPDIR\fR
Used as path for creating temporary files by \fBautoresponder\fR(1), qarf,
\fBqmail-dkim\fR(8), \fBqmail-qfilter\fR(1), \fBqmail-multi\fR(8),
\fBqnotify\fR(1), \fBqmail-smtpd\fR(8), \fBspawn-filter\fR(8)

.TP
\fITODO_INTERVAL\fR
Used by \fBtodo-proc\fR(8), \fBslowq-send\fR(8) and \fBqmta-send\fR(8)

.TP
\fITODO_CHUNK_SIZE\fR
Used by \fBtodo-proc\fR(8) to communicate to \fBqmail-send\fR(8) new
messages in chunks instead of transmitting a message as soon as it is seen
in the queue.

.TP
\fICHUNK_WAIT\fR
Max number of seconds to wait for \fBTODO_CHUNK_SIZE\fR messages in the
queue after which \fBtodo-proc\fR(8) communicates to \fBqmail-send\fR(8)
available messages to be scheduled for delivery.

.TP
\fITRY_NEXT_MX_HELO_FAIL\fR
Used by \fBqmail-remote\fR(8). If set, \fBqmail-remote\fR(8) tries the next
mx when ehlo/helo command fails with a temporary error

.TP
\fIUFLINE\fR
used by \fBdot-forward\fR(1), preline. Set by \fBqmail-local\fR(8)

.TP
\fIUNSIGNED_FROM\fR
If set, \fBqmail-dkim\fR(8) allows unsigned From headers in DKIM-Signature

.TP
\fIUNSIGNED_SUBJECT\fR
If set, \fBqmail-dkim\fR(8) allows unsigned Subject headers in
DKIM-Signature

.TP
\fIUSE_DLMOPEN\fR
If set, \fBtcpserver\fR(1) uses dlmopen(3) instead of dlopen(3) to load
\fBtcpserver\fR(1) modules.

.TP
\fIUSE_FNMATCH\fR
If set, \fBqmail-smtpd\fR(8), \fBqmail-inject\fR(8), \fBspawn-filter\fR(8)
uses file pattern matching fnmatch(3) function to match addresses.

.TP
\fIUSE_FSYNC\fR \fIUSE_SYNCDIR\fR
Used by \fBqmail-queue\fR(8) to sync files after queuing.

.TP
\fIUSE_QPWGR\fR
Use internal getpwent, getgrent, getpwnam, getgrnam, getpwuid, getgrgid,
getpwent_r, getgrent_r, getservent, getservbyname, getservbyport,
getservent_r, getservbyname_r, getservbyport_r functions in
\fBqmail-getpw\fR(8), \fBqmail-direct\fR(8), \fBserialcmd\fR(1),
\fBsys-checkpwd\fR(8), \fBqhpsi\fR(8), \fBqscanq\fR(8), \fBcleanq\fR(8),
\fBqmail-lspawn\fR(8), \fBqmail-rspawn\fR(8), \fBqmail-queue\fR(8),
\fBqmta-send\fR(8), \fBqmail-showctl\fR(8), \fBqmail-start\fR(8),
\fBqscheduler\fR(8), \fBslowq-start\fR(8), \fBqueue-fix\fR(8)

.TP
\fIUSER\fR
Used by \fBdot-forward\fR(1), \fBnew-inject\fR(8), \fBqmail-direct\fR(8),
\fBqmail-inject\fR(8). Set by \fBqmail-local\fR(8),
\fBserialcmd\fR(1)

.TP
\fIUSE_SETGROUPS\fR
Used by \fBqmail-start\fR(8), \fBslowq-start\fR(8) to add supplementary
groups for daemons \fBtodo-proc\fR(8), \fBqmail-send\fR(8),
\fBqmail-lspawn\fR(8), \fBqmail-rspawn\fR(8) and \fBqmail-clean\fR(8)

.TP
\fISETUSER_PRIVILEGES\fR
Used by \fBqmail-lspawn\fR to run \fBqmail-local\fR with user's
supplementary groups for local user in the passwd database. Without this,
\fBqmail-local\fR is run with the primary uid, primary gid of the user.

.TP
\fIVIRTUAL_PKG_LIB\fR
Used by \fBqmail-smtpd\fR(8), \fBqmail-lspawn\fR(8), \fBqmail-rspawn\fR(8),
\fBmaildirsize\fR(1), \fBqmail-showctl\fR(8) to load
indimail-virtualdomains library.

.TP
\fIVIRUSCHECK\fR
Used by \fBqmail-smtpd\fR(8), \fBqmail-spamfilter\fR(8) to execute
\fBqscanq\fr(8) for checking if the mail is infected

.TP
\fIADDUSERCMD\fR
Used by \fBproxyimap\fR(8), \fBproxypop3\fR(8) if configured to add users
automatically.

.TP
\fITIMEOUTCONN\fR
Timeout that \fBadminclient\fR(8) uses for connecting to \fBindisrvr\fR(8)

.TP
\fITIMEOUTDATA\fR
Timeout that \fBadminclient\fR(8) uses for data exchange between
\fBindisrvr\fR(8) and itself.

.TP
\fIALLOWCHARS\fR
List of allowed characters in the usernames. Used by \fBvadduser\fR(1)

.TP
\fIAVG_USER_QUOTA\fR
Used by \fBvfstab\fR(8) as the value of average user quota in bytes.

.TP
\fIBASE_PATH\fR
Used by \fBvadddomain\fR(1), \fBvadduser\fR(1), \fBvdominfo\fR(1)

.TP
\fIBULK_MAILDIR\fR
The bulk mail directory. e.g. for indimail.org the bulk
mail directory will be \fI@qmaildir@/indimail.org/$BULK_MAILDIR\fR.

.TP
\fIBULK_HOST\fR
Environment variables to be set when the bulkmail table lies on a remote
MySQL host

.TP
\fIBULK_DATABASE\fR
Database for the 'bulkmail' MySQL

.TP
\fIBULK_USER\fR
User for the 'bulkmail' MySQL

.TP
\fIBULK_PASSWD\fR
Password for the 'bulkmail' MySQL

.TP
\fIBULK_VPORT\fR
Port for the 'bulkmail' MySQL

.TP
\fIBULK_SOCKET\fR
Socket for the 'bulkmail' MySQL

.TP
\fIEDITOR\fR
Used by \fBdbinfo\fR(8) for editing mcdinfo (when passed the -e option)

.TP
\fIELIMINATE_DUPS\fR
used by \fBvdelivermail\fR(8), \fBismaildup\fR(1) to discard duplicate
emails.

.TP
\fIELIMINATE_DUPS_ARGS\fR
used by \fBvdelivermail\fR(8), \fBismaildup\fR(1) to run a program with the
mail as input on stdin. The output of this command is used for md5sum
calcuation to decide if an email is to be discarded or not. If this is not
defined, \fB822header\fR(1) program is used.

.TP
\fIELIMINATE_DUPS_INT\fR
used by \fBvdelivermail\fR(8), ismaildup as the interval within which same email
will be discarded as duplicate

.TP
\fIHARD_QUOTA\fR
Used by \fBvadduser\fR(1) as the default quota to set for a user when
adding users

.TP
\fIHOLDOVERQUOTA\fR
If set, \fBvdelivermail\fR(8) will defer mails when user runs out of quota.
The command defined by \fIOVERQUOTA_CMD\fR environment variable will be
run. However, \fBBOUNCE_FLAG\fR and lastdeliver table will not be updated

.TP
\fIOVERQUOTA_CMD\fR
Command to be run when user becomes overquota. Triggered during mail
delivery or during IMAP/POP3 authentication.

.TP
\fIMAILCOUNT_LIMIT\fR
If set, max deliveries permitted for a user in day by \fBvdelivermail\fR(8)

.TP
\fIMAILSIZE_LIMIT\fR
If set, total size of mail delivery/day for user by \fBvdelivermail\fR(8)

.SH indimail-virtualdomains environment variables

.PP

These variables are mostly used by indimail-virtualdomains. But there can
overlap with indimail-mta

.TS
l l.
Environment variable      |Program       |Purpose
--------------------------|--------------|-------------------------------------
INFIFO                    |inlookup      |Name of FIFO used for communicating with
                          |qmail-smtpd   |inlookup. inlookup pools connections to
                          |authindi      |MySQL and provides the interface between
                          |proxyimap     |IndiMail and MySQL
                          |proxypop3     |
                          |inquerytest   |
FIFODIR                   |              |Directory specifying location of INFIFO
--------------------------|--------------|-------------------------------------
CNTRL_HOST                |inlookup      |Environment variables to be set when a
                          |qmail-rspawn  |domain is extended across multiple
                          |qmail-lspawn  |servers. These variables point to the
                          |vuserinfo     |central database which has the
                          |vserverinfo   |\fIhostcntrl\fR table. If both MASTER_HOST
                          |              |and CNTRL_HOST are defined all updates
                          |              |go to MASTER_HOST adn all queries go
                          |              |to CNTRL_HOST
CNTRL_USER                |              |User for connecting to MySQL database
CNTRL_PASSWD              |              |password for connecting to MySQL
                          |              |database
CNTRL_VPORT               |              |port for connecting to MySQL database
CNTRL_SOCKET              |              |socket for connecting to MySQL database
CNTRL_TABLE               |              |Table for storing user location
                          |              |default is \fIhostcntrl\fR
CNTRL_DATABASE            |              |database on which table \fIhostcntrl\fR is
                          |              |present. default is \fIindimail\fR
MASTER_HOST               |              |Host to which all writes should go to
--------------------------|--------------|-------------------------------------
MYSQL_HOST                |              |MySQL Host to connect for database
                          |              |conection
MYSQL_USER                |              |User for connecting to MySQL database
MYSQL_PASSWD              |              |password for connecting to MySQL
                          |              |database
MYSQL_VPORT               |              |port for connecting to MySQL database
MYSQL_SOCKET              |              |socket for connecting to MySQL database
MYSQL_TABLE               |              |Name of the default indimail
                          |              |authentication table containing active
                          |              |users. If not set, this defaults to
                          |              |\fIindimail\fR
MYSQL_INACTIVE_TABLE      |              |Name of the default indimail
                          |              |authentication table containing inactive
                          |              |users. If not set, this defaults to
                          |              |\fIindibak\fR
ENABLE_MYSQL_ESCAPE       |              |If set, all queries to MySQL will be
                          |              |escaped before sending to mysqld.
MYSQL_INIT_COMMAND        |              |
MYSQL_READ_DEFAULT_FILE   |              |
MYSQL_READ_DEFAULT_GROUP  |              |
MYSQL_OPT_RECONNECT       |any indimail  |Reconnect automatically after failure
MYSQL_OPT_READ_TIMEOUT    |program that  |Read timeout from MySQL
MYSQL_OPT_WRITE_TIMEOUT   |connects to   |Write timeout writing to MySQL
MYSQL_OPT_CONNECT_TIMEOUT |MySQL         |Connect timeout for MySQL
MYSQL_OPT_PROTOCOL        |              |Set unix domain or tcp/ip sockets
MYSQL_SET_CLIENT_IP       |              |Set the client ip when connecting 
CLIENT_COMPRESS           |              |Set client compress flag
CLIENT_INTERACTIVE        |              |Set client interactive flag
MYSQL_OPT_SSL_CA          |              |Certificate Authority (CA) file path
MYSQL_OPT_SSL_CAPATH      |              |directory that contains trusted SSL CA
MYSQL_OPT_SSL_CERT        |              |client public key certificate file
MYSQL_OPT_SSL_CIPHER      |              |permitted cipher list for SSL encryption
MYSQL_OPT_SSL_CRL         |              |certificate revocation lists file
MYSQL_OPT_SSL_CRLPATH     |              |certificate revocation lists directory
MYSQL_OPT_SSL_ENFORCE     |              |Enforce SSL connection
MYSQL_OPT_SSL_VERIFY_CERT |              |Enable verification of the server''s CN 
MYSQL_OPT_SSL_MODE        |              |security state to use for the connection 
                          |              |SSL_MODE_DISABLED, SSL_MODE_PREFERRED,
                          |              |SSL_MODE_REQUIRED, SSL_MODE_VERIFY_CA,
                          |              |SSL_MODE_VERIFY_IDENTITY.
MYSQL_OPT_SSL_KEY         |              |client private key file
MYSQL_OPT_TLS_VERSION     |              |for opessl TLSv1, TLSv1.1, TLSv1.2
                          |              |for yaSSL TLSv1, TLSv1.1 protocols
                          |              |
MAX_FAIL_ATTEMPTS         |              |Max failers after which use delay
                          |              |reconnect till MYSQL_RETRY_INTERVAL
                          |              |has elapsed
MYSQL_RETRY_INTERVAL      |              |Interval before reconnecting
                          |              |after a dropped or failed connection
--------------------------|--------------|--------------------------------------
MCDFILE                   |inlookup      |Mail Control Definition file. Specifies
                          |dbinfo        |the list of all MySQL servers
                          |vuserinfo     |participating in a distributed setup.
                          |vserverinfo   |
--------------------------|--------------|--------------------------------------
MIGRATEUSER               |              |Program to be run once (first time) when
                          |              |the user logs in successfully
                          |              |successful authentication).
MIGRATEFLAG               |              |Zero bytes file created in User's
                          |              |Maildir to figure out if the migration
                          |              |program defined by environment variable
                          |              |MIGRATEUSER has been run.
--------------------------|--------------|--------------------------------------
MIN_LOGIN_INTERVAL        |              |Minimum time permitted between two
                          |              |successful authentication.
                          |              |Authentication requests made before this
                          |              |time elapsed are rejected. To remove
                          |              |this restriction, set this to 0.
NORELAY                   |              |If set, insert to table 'relay'
                          |              |after successful authentication
                          |              |is disabled. This in effect disables
                          |              |relaying (Roaming Users).
TCP_FILE                  |              |File containing list of default tcprules
                          |              |to be applied. Default is
                          |              |@sysconfdir@/tcp/tcp.smtp.
OPEN_SMTP                 |              |File containing list of tcprules for IP
                          |              |addresses of users who have
                          |              |authenticated in the past
                          |              |RELAY_CLEAR_MINUTES. Default
                          |              |is @indimaildir@/tcp/open-smtp
RELAY_CLEAR_MINUTES       |clearopensmtp |No of minutes after which the
                          |inlookup      |authentication request maintained in the
                          |vuserinfo     |relay table is expired. This is used for
                          |authindi      |sites using pop/imap before smtp
                          |vchkpass      |authentication
                          |proxyimap     |
                          |proxypop3     |
--------------------------|--------------|--------------------------------------
RELAY_TABLE               |authindi      |MySQL table name containing user
                          |inlookup      |authentication timestamps for
                          |clearopensmtp |implementing POP/IMAP before SMTP.
--------------------------|--------------|--------------------------------------
AUTHENTICATED             |authindi      |Set by authindi when
                          |              |authentication is successful
--------------------------|--------------|--------------------------------------
.TE

.SH "SEE ALSO"
indimail(7),
tcp-environ(5)
