.TH ipmeprint 8

.SH NAME
ipmeprint

.SH SYNOPSIS
\fBipmeprint\fR

.SH DESCRIPTION
\fBipmeprints\fR(8) displays all \fIIPv4\fR, \fIIPv6\fR addresses for all
local network interfaces. \fBipmeprint\fR(8) uses \fBgetifaddrs\fR(3) to
get local interface addresses.

.SH "SEE ALSO"
ifconfig(8), hostname(1), getifaddrs(3)
