.TH maildirsmtp 1
.SH NAME
maildirsmtp \- send a maildir through SMTP
.SH SYNOPSIS
.B maildirsmtp
.I dir
.I prefix
.I host
.I helohost
.SH DESCRIPTION
.B maildirsmtp
scans a maildir,
.IR dir ,
and sends each message to
.I host
through SMTP.
It removes
.I prefix
from the beginning of each envelope recipient address.
It ignores any message whose recipient address does not begin with
.IR prefix .

.B maildirsmtp
removes messages accepted by
.IR host .
It bounces messages permanently rejected by
.I host
back to the envelope sender,
and then removes them.
It treats temporary rejection as permanent rejection
for messages more than two weeks old.

Note that failure to connect to
.I host
is not temporary rejection.
If
.I host
is never reachable,
.B maildirsmtp
will never remove messages.

.B maildirsmtp
uses
.I helohost
as the local host name for saying hello to the SMTP server.

.B maildirsmtp
uses \fBPORT\fR environment variable as the port for SMTP if set.

.B maildirsmtp
needs
.B tcpclient
in
.BR $PATH .
.SH "SEE ALSO"
maildirserial(1),
serialsmtp(1),
tcpclient(1)
