.\" vim: tw=75
.TH MAILDIRDELIVER 1

.SH NAME
maildirdeliver \- deliver a mail message to a maildir

.SH SYNOPSIS
.B maildirdeliver
.I dir

.SH DESCRIPTION
\fBmaildirdeliver\fR reads a mail message from the standard input, and
stores it in a maildir, \fIdir\fR.

\fBmaildirdeliver\fR exits 0 on a successful delivery.  On a temporary
failure, it exits 111.  On a permanent failure, it exits 100.

Unlike a maildir line in \fB.qmail\fR files, \fBmaildirdeliver does not
prepend a \fBReturn-Path\fR line nor a \fBDelivered-To\fR line to the
incoming message. \fBmaildirdeliver\fR will use \fBRPLINE\fR if set, to
prepend a \fBReturn-Path\fR line to the incoming message.
\fBmaildirdeliver\fR will use \fBDTLINE\fR if set, to prepend a
\fBDelivered-To\fR line to the incoming message. If \fBRPLINE\fR or
\fBDTLINE\fR are not defined and if you use \fBmaildirdeliver\fR in a
program line in a script, you may want to invoke it under \fBpreline\fR.
For example:

.EX
     |preline -f maildirdeliver Maildir
.EE

\fBmaildirdeliver\fR is heavily based on \fBqmail-local.c\fR from D. J. Bernstein's
qmail package.

.SH "SEE ALSO"
dot-qmail(5),
maildir(5),
preline(1)
