it += indimail-mta.fc indimail-mta.spec indimail-mta-permissions.easy \
	indimail-mta-permissions.paranoid indimail-mta-permissions.secure \
	indimail-mta.fc qlocal_upgrade.sh PKGBUILD qmta-send.service

static_option = -Wl,-Bstatic
dynamic_option = -Wl,-Bdynamic

ifeq ($(USE_SQL),1)
it += qmail-sql sql-database
man += qmail-sql.8 sql-database.8
endif
