.\" vim: tw=75
.TH mini-smtpd 8

.SH NAME
mini-smtpd \- receive mail via SMTP

.SH SYNOPSIS
\fBmini-smtpd\fR

.SH DESCRIPTION
\fBmini-smtpd\fR receives mail messages via the Simple Mail Transfer
Protocol (SMTP) and invokes \fBqmail-queue\fR to deposit them into the
outgoing queue. \fBmini-smtpd\fR must be supplied several environment
variables; see \fBtcp-environ(5)\fR.

\fBmini-smtpd\fR is responsible for counting hops. It rejects any message
with 100 or more \fBReceived\fR or \fBDelivered-To\fR header fields.

\fBmini-smtpd supports ESMTP, including the 8BITMIME and PIPELINING options.

\fBmini-smtpd\fR writes \fIReceived:\fR header with details of the SMTP
connection regarding ESMTP, date and time. If the environment variable
\fBHIDE_HOST\fR is set, \fBmini-smtpd\fR does not write hostnames and IP
addresses in the received header.

.SH TRANSPARENCY
\fBmini-smtpd\fR converts the SMTP newline convention into the UNIX newline
convention by converting CR LF into LF.  It returns a temporary error and
drops the connection on bare LFs; see
\fBhttps://cr.yp.to/docs/smtplf.html\fR.

\fBmini-smtpd\fR accepts messages that contain long lines or non-ASCII
characters, even though such messages violate the SMTP protocol.

.SH "CONTROL FILES"
.TP 5
\fIdatabytes\fR
Maximum number of bytes allowed in a message, or 0 for no limit.
Default: 0. If a message exceeds this limit, \fBmini-smtpd\fR returns a
permanent error code to the client; in contrast, if the disk is full or
\fBmini-smtpd\fR hits a resource limit, \fBmini-smtpd\fR returns a
temporary error code.

.TP 5
\fIdatabytes\fR
counts bytes as stored on disk, not as transmitted through the network.
It does not count the \fBmini-smtpd\fR Received line, the \fBqmail-queue\fR
Received line, or the envelope.

If the environment variable
.B DATABYTES
is set, it overrides
.IR databytes .
.TP 5
.I localiphost
Replacement host name for local IP addresses.
Default:
.IR me ,
if that is supplied.
.B mini-smtpd
is responsible for recognizing dotted-decimal addresses for the
current host.
When it sees a recipient address of the form
.IR box@[d.d.d.d] ,
where
.I d.d.d.d
is a local IP address,
it replaces
.IR [d.d.d.d]
with
.IR localiphost .
This is done before
.IR rcpthosts .
.TP 5
.I morercpthosts
Extra allowed RCPT domains.
If
.I rcpthosts
and
.I morercpthosts
both exist,
.I morercpthosts
is effectively appended to
.IR rcpthosts .

You must run \fBqmail-cdb\fR(8) on \fImorercpthosts\fR whenever it changes.

Rule of thumb for large sites:
Put your 50 most commonly used domains into
.IR rcpthosts ,
and the rest into
.IR morercpthosts .
.TP 5
.I rcpthosts
Allowed RCPT domains.
If
.I rcpthosts
is supplied,
.B mini-smtpd
will reject
any envelope recipient address with a domain not listed in
.IR rcpthosts .

Exception:
If the environment variable
.B RELAYCLIENT
is set,
.B mini-smtpd
will ignore
.IR rcpthosts ,
and will append the value of
.B RELAYCLIENT
to each incoming recipient address.

.I rcpthosts
may include wildcards:

.EX
   heaven.af.mil
   .heaven.af.mil
.EE

Envelope recipient addresses without @ signs are
always allowed through.
.TP 5
.I smtpgreeting
SMTP greeting message.
Default:
.IR me ,
if that is supplied;
otherwise
.B mini-smtpd
will refuse to run.
The first word of
.I smtpgreeting
should be the current host's name.
.TP 5
.I timeoutsmtpd
Number of seconds
.B mini-smtpd
will wait for each new buffer of data from the remote SMTP client.
Default: 1200.
.SH "SEE ALSO"
tcp-env(1),
tcp-environ(5),
indimail-control(5),
qmail-inject(8),
qmail-cdb(8),
qmail-queue(8),
qmta-send(8),
qmail-local(8),
qmail-remote(8)
