.TH ofmipd 8
.SH NAME
ofmipd \- accept outgoing mail through OFMIP
.SH SYNOPSIS
.B ofmipd
[
.I name.cdb
]
.SH DESCRIPTION
.B ofmipd
accepts mail messages through the
Old-Fashioned Mail Injection Protocol (OFMIP),
rewrites them according to local rules,
and invokes
.B qmail-queue
to deposit them into the outgoing queue.
.B ofmipd
must be supplied several environment variables;
see
.BR tcp-environ (5).

See
.B http://pobox.com/~djb/proto/ofmip.html
for further information on OFMIP.
.SH "USING OFMIP"
You can use
.B tcpserver
to set up
.B ofmipd
on a free TCP port.
Some sites use port 26.
Some sites use port 25 on an IP address that does not receive incoming mail.

Note that
.B ofmipd
will relay messages to any destination.
It should be invoked
only for connections from preauthorized users.
With
.B tcpserver
you can deny connections
that do not come from preauthorized IP addresses such as 127.0.0.1.

Most MUAs that claim to be ``SMTP clients''
are actually OFMIP clients.
You should point them at
.B ofmipd
rather than
.BR qmail-smtpd .
Some MUAs will use port 26 of 
.I server
if you tell them that the ``SMTP server'' is
.IR server\fB:26 .
.SH "MESSAGE REWRITING"
.B ofmipd
rewrites each message in essentially the same way that
.B new-inject
does.
It transforms each envelope address
as discussed in
.BR rewriting (5);
it cleans up address lists in
.BR To ,
.BR Cc ,
.BR Notice-Requested-Upon-Delivery-To ,
.BR From ,
.BR Sender ,
.BR Reply-To ,
.BR Mail-Reply-To ,
and
.BR Mail-Followup-To ;
it adds
.B Date
and
.BR Message-ID ;
it discards
.BR Bcc ,
.BR Apparently-To ,
.BR Content-Length ,
and
.BR Return-Path ;
and it moves various fields to the top of the message.

.B ofmipd
also transforms envelope sender addresses and
.B From
lines according to
.I name.cdb
if
.I name.cdb
is supplied.
See
.BR ofmipname (8)
for further details.

.B ofmipd
accepts LF and CR LF as line terminators inside messages.

.B ofmipd
does not do hop counting
or local-IP-address recognition.
.SH "SEE ALSO"
new-inject(1),
tcpserver(1),
addresses(5),
tcp-environ(5),
rewriting(5),
indimail-control(5),
qmail-queue(8),
ofmipname(8)
