.TH predate 1
.SH NAME
predate \- Prepend RFC 822 compliant Date header to data

.SH SYNOPSYS
\fBpredate\fR \fIchild\fR

.SH DESCRIPTION
\fBpredate\fR reads the standard input and outputs the data read with RFC 822 compliant \fIDate\fR header
to the \fIchild\fR on the child's standard input.

.SH SEE ALSO
datemail(1)
