.TH printmaillist 1
.SH NAME
printmaillist \- print the contents of a binary mailing list
.SH SYNOPSIS
.B printmaillist
.SH DESCRIPTION
.B printmaillist
reads a binary mailing list from its standard input
and prints all the forwarding instructions
in a format accepted by
.BR setmaillist .
.SH "SEE ALSO"
newinclude(1),
printforward(1),
setmaillist(1)
