.TH qmail-sql 8
.SH NAME
qmail-sql \- prepare data in MySQL for
.BR qmail-smtpd(8) .

.SH SYNOPSIS
.B qmail-sql
[-Sr] [-s \fIdbserver\fR -u \fIuser\fR -p \fIpass\fR -d \fIdbname\fR -t \fItable_name\fR] \fIfilename\fR

.SH DESCRIPTION
\fBqmail-sql\fR does a chdir to @controldir@ and prepares filename.sql control file to enable
\fBqmail-smtpd\fR to access data from MySQL instead of control files. \fBqmail-sql\fR also
prepares data in \fIfilename\fR to be inserted into \fItable_name\fR in MySQL.

The below command will create a file \fIbadmailfrom.sql\fR in @controldir@ and table \fIbmf\fR
in MySQL
.EX
 qmail-sql -s localhost -u indimail -p ssh-1.5- -d indimail -t bmf badmailfrom
.EE

The below command will replace contents of file badmailfrom in @controldir@ into the the table
\fIbmf\fR in MySQL.
.EX
 qmail-sql -r badmailfrom
.EE

The following control files can also be specified in cdb format or
be in MySQL

.IR authdomains ,
.IR badhelo ,
.IR badext ,
.IR badmailfrom ,
.IR badrcptto ,
.IR blackholedsender ,
.IR blackholedrcpt ,
.IR chkrcptdomains ,
.IR goodrcptto ,
.IR relaymailfrom ,
.IR spamignore ,
and
.IR badip .

.SH OPTIONS
.TP
.B -S
Skip creating MySQL table and subsequent inserting of data into MySQL
.TP
.B -r
Replace the content of data in MySQL with the content in \fIfilename\fR
.TP
.B -u \fIuser\fR
MySQL username. A user which has privilege to create, insert, delete in MySQL database \fIdbname\fR.
.TP
.B -p \fIpass\fR
Password for MySQL user \fIusername\fR
.TP
.B -d \fRdbname\fR
Database name in MySQL
.TP
.B -t \fRtable_name\fR
Table in MySQL in which data from plain-text control file will be inserted

.SH SEE ALSO
qmail-cdb(8),
qmail-smtpd(8),
qmail-control(5)
