.TH qmail-getpw 8

.SH NAME
qmail-getpw \- give addresses to users

.SH SYNOPSIS
\fBqmail-getpw\fR \fIlocal\fR

.SH DESCRIPTION
In \fBqmail\fR, each user controls a vast array of local addresses.
\fBqmail-getpw\fR finds the user that controls a particular address,
\fIlocal\fR.  It prints six pieces of information, each terminated by NULL:
\fIuser\fR; \fIuid\fR; \fIgid\fR; \fIhomedir\fR; \fIdash\fR; and \fIext\fR.
The user's account name is \fIuser\fR; the user's uid and gid in decimal are
\fIuid\fR and \fIgid\fR; the user's home directory is \fIhomedir\fR;
and messages to \fIlocal\fR will be handled by \fIhomedir\fR\fB/.qmail\fIdashext\fR.

In case of trouble,\fBqmail-getpw\fR exits nonzero without printing anything.

\fBWARNING\fR:
The operating system's \fBgetpwnam\fR function, which is at the heart of
\fBqmail-getpw\fR, is inherently unreliable: it fails to distinguish
between temporary errors and nonexistent users. Future versions of
\fBgetpwnam\fR should return ETXTBSY to indicate temporary errors and ESRCH
to indicate nonexistent users.

You can set the environment variable \fBUSE_QPWGR\fR environment variable
to use an internal implementation of \fBgetpwnam\fR(3) - \fBqgepwnam\fR(3).
\fBqgetpwnam\fB(3) sets ENOENT for non-existent users and return ETXTBSY.

.SH "RULES"
\fBqmail-getpw\fR considers an account in \fB/etc/passwd\fR to be a user
if
.PP
.EX
(1) the account has a nonzero uid,
(2) the account's home directory exists (and is visible to \fBqmail-getpw\fR), and
(3) the account owns its home directory.
.EE

\fBqmail-getpw\fR ignores account names containing uppercase letters.
\fBqmail-getpw\fR also assumes that all account names are shorter than 32
characters.

\fBqmail-getpw\fR gives each user control over the basic \fIuser\fR address
and all addresses of the form \fIuser\fR\fBBREAK\fR\fIanything\fR. When
\fIlocal\fR is \fIuser\fR, \fIdash\fR and \fIext\fR are both empty. When
\fIlocal\fR is \fIuser\fR\fBBREAK\fR\fIanything\fR, \fIdash\fR is a hyphen
and \fIext\fR is \fIanything\fR. \fIuser\fR may appear in any combination of
uppercase and lowercase letters at the front of \fIlocal\fR.

A catch-all user, \fBalias\fR, controls all other addresses. In this case
\fIext\fR is \fIlocal\fR and \fIdash\fR is a hyphen.

You can override all of \fBqmail-getpw\fR's decisions with the
\fBqmail-users\fR mechanism, which is reliable, highly configurable, and
much faster than \fBqmail-getpw\fR.

.SH "SEE ALSO"
getpwnam(3),
qgetpwnam(3),
qmail-users(5),
qmail-lspawn(8)
