.TH qmail-clean 8

.SH NAME
qmail-clean \- clean up the queue directory

.SH SYNOPSIS
.B qmail-clean

.SH DESCRIPTION
\fBqmail-clean\fR reads a cleanup command from descriptor 0, performs the
cleanup, prints the results to descriptor 1, and repeats. \fBqmail-clean\fR
uses the enivronment \fBCONFSPLIT\fR as the run time directory split value.
If not set it uses the value DIRSPLIT. A value larger than DIRSPLIT for
\fBCONFSPLIT\fR is silently ignored.

\fBqmail-clean\fR can process a queue created with \fItodo\fR, \fIintd\fR
with subdirectory split instead of without split. This can be done by
setting the \fBBIGTODO\fR environment variable.

.SH "SEE ALSO"
qmail-send(8)
qmail-todo(8)
