.\" vim: tw=75
.TH qmail-local 8
.SH NAME
qmail-local \- deliver or forward a mail message
.SH SYNOPSIS
.B qmail-local
[
.B \-nN
]
.I user
.I homedir
.I local
.I dash
.I ext
.I domain
.I sender
.I defaultdelivery
.I qqeh

.SH DESCRIPTION
\fBqmail-local\fR(8) reads a mail message and delivers it to \fIuser\fR by
the procedure described in \fBdot-qmail\fR(5).

The message's envelope recipient is \fIlocal@domain\fR.
\fBqmail-local\fR(8) records \fIlocal@domain\fR in a new \fBDelivered-To\fR
header field. If exactly the same \fBDelivered-To:\fR \fIlocal@domain\fR
already appears in the header, \fBqmail-local\fR(8) bounces the message to
prevent mail forwarding loops. If \fImaxdeliveredto\fR is a value greater
than the number of exact \fIlocal@domain\fR matches, then delivery
progresses. If \fImaxdeliveredto\fR is -1 then this stage goes unchecked.

The message's envelope sender is \fIsender\fR. \fBqmail-local\fR(8) records
\fIsender\fR in a new \fBReturn-Path\fR header field.

\fIhomedir\fR is the user's home directory. It must be an absolute
directory name.

\fIdash\fR and \fIext\fR identify the \fB.qmail\fR\fIdashext\fR file used
by \fBqmail-local\fR(8) ; See \fBdot-qmail\fR(5). Normally \fIdash\fR is
either empty or a lone hyphen. If it is empty, \fBqmail-local\fR(8) treats
a nonexistent \fB.qmail\fR\fIext\fR the same way as an empty
\fB.qmail\fR\fIext\fR : namely, following the delivery instructions in
\fIdefaultdelivery\fR. If \fIext\fR ends with the string literal "default",
then \fBqmail-local\fR(8) sets the environment variable \fBDEFAULT\fR to
the string "default". This environment variable can be used by
\fBfastforward\fR(1) in a \fBdot-qmail\fR(5) file to use the -d flag and
use default@$HOST as the recipient. Without this environment variable set,
\fBfastforward\fR can use $EXT@$HOST as the recipient. Typical use of this
would be use \fB.qmail-default\fR in \fI@qmaildir@/alias\fR directory to
handle default for unknown addresses.

The contents of \fIqqeh\fR is prepended to the message on standard input.
It is used to add extra headers to an existing message.

The standard input for \fBqmail-local\fR(8) must be a seekable file, so
that \fBqmail-local\fR(8) can read it more than once.

\fBqmail-local\fR(8) gets called by \fBqmail-lspawn\fR(8) usually. One can
also configure \fBqmail-lspawn\fR(8) to call \fBspawn-filter\fR(8) before
\fBqmail-local\fR(8). This is done by setting \fBQMALLOCAL\fR environment
variable. \fBspawn-filter\fR(8) can carry out filtering and set few
recipient specific environment variables using envrules. Thus, one can
customize \fBqmail-local\fR(8) behaviour to be recipient specific.

If \fBSender Rewriting Scheme\fR (\fISRS\fR) has been configured, when
forwarding (due to instructions in a \fBdot-qmail\fR(5) file),
\fBqmail-local\fR(8) rewrites the sender. See \fBindimail-srs\fR(5) for
information on how to do this.

If the environment variable \fBUSE_FSYNC\fR or \fBUSE_FDATASYNC\fR is set,
then \fBqmail-local\fR(8) writes all data to disk ("flushes") all modified
in-core data of (i.e., modified buffer cache pages for) the new message to
the disk device (or other permanent storage device) so that all changed
information can be retrieved even if the system crashes or is rebooted.
This includes writing through or flushing a disk cache if present. The call
blocks until the device reports that the transfer has completed. The system
calls fsync(2) or fdatasync(2) are used to flush data to disk. Though
fdatasync(2) is faster than fsync(2), both these calls impose a penalty on
performance.

If the environment variable \fBUSE_SYNCDIR\fR is enabled,
\fBqmail-local\fR(8) forces BSD style directory syncing.

The environment variable \fBUSE_FSYNC\fR, \fBUSE_FDATASYNC\fR,
\fBUSE_SYNCDIR\fR is controlled by \fBqmail-send\fR(8) /
\fBtodo-proc\fR(8).

If the environment variable \fBSANITIZE_ENV\fR is enabled \fBqmail-local\fR
will first clear all environment variables other than \fBMESSID\fR,
\fBUSE_FSYNC\fR, \fBUSE_FDATASYNC\fR, \fBUSE_SYNCDIR\fR. You can set
additional environment variables to preserve by setting SANITIZE_ENV as a
colon ':' separated list of environment variables to retain. The purpose of
\fBSANITIZE_ENV\fR is to ensure programs run using \fBdot-qmail\fR(5) will
run without any environment variable inherited from the startup scripts.

.SH "OPTIONS"
.TP
.B \-n
Instead of reading and delivering the message, print a description of the
delivery instructions.

.TP
.B \-N
(Default.) Read and deliver the message.

.SH "CONTROL FILES"
\fBqmail-local\fR(8) by default looks in \fI@controldir@\fR directory for
all control files. This path can be changed by defining the
\fBCONTROLDIR\fR environment variable.

.TP 5
\fIlocaldomains\fR
List of domains considered as local. If the user's home directory has a
file \fB.localdomains\fR or if the environment variable \fBLOCALDOMAINS\fR,
is defined \fBqmail-local\fR(8) will deliver the mail only if it comes from
any of the domain listed in \fBlocaldomains\fR. This restricts users to
receive local mails only.

.SH "EXIT CODES"
0 if the delivery is completely successful, 5 if out of disk quota;
nonzero if any delivery instruction failed. Exit code 111 indicates
temporary failure.

.SH "SEE ALSO"
dot-qmail(5),
indimail-srs(5),
envelopes(5),
qmail-command(8),
qmail-queue(8),
qmail-send(8),
spawn-filter(8),
qmail-lspawn(8),
fsync(2)
