.\" vim: tw=75
.TH qmail-inject 8
.SH NAME
qmail-inject \- preprocess and send a mail message
.SH SYNOPSIS
.B qmail-inject
[
.B \-nNaAhH
] [
.B \-f\fIsender
] [
.I recip ...
]

.SH DESCRIPTION
\fBqmail-inject\fR reads a mail message from its standard input, adds
appropriate information to the message header, and by default invokes
\fBqmail-queue\fR(8) to send the message to one or more recipients. You can
set \fBQMAILQUEUE\fR environment variable to call any other program that
has the same interface as \fBqmail-queue\fR. \fBQMAILQUEUE\fR can be list
of multiple programs separated by a white space. e.g. you can set
QMAILQUEUE to insert DKIM header as well as filter spam as below.

.EX
  QMAILQUEUE="PREFIX/sbin/qmail-dkim PREFIX/sbin/qmail-spamfilter"
.EE

\fBqmail-inject\fR rewrites the sender using Sender Rewriting Scheme if
\fISRS\fB has been configured. See \fBindimail-srs\fR(5) for information on
how to do this.

See \fBqmail-header\fR(5) for information on how \fBqmail-inject\fR
rewrites header fields.

\fBqmail-inject\fR normally exits 0. It exits 100 if it was invoked
improperly or if there is a severe syntax error in the message.  It exits
111 for temporary errors.

.SH "ENVIRONMENT VARIABLES"
For the convenience of users who do not run \fBqmail-inject\fR directly,
\fBqmail-inject\fR takes many options through environment variables.

The user name in the \fBFrom\fR header field is set by \fBQMAILUSER\fR,
\fBMAILUSER\fR, \fBUSER\fR, or \fBLOGNAME\fR, whichever comes first.

The host name is normally set by the \fIdefaulthost\fR control but can be
overridden with \fBQMAILHOST\fR or \fBMAILHOST\fR.

The personal name is \fBQMAILNAME\fR, \fBMAILNAME\fR, or \fBNAME\fR.

The default envelope sender address is the same as the default \fBFrom\fR
address, but it can be overridden with \fBQMAILSUSER\fR and
\fBQMAILSHOST\fR. It may also be modified by the \fBr\fR and \fBm\fR
letters described below. Bounces will be sent to this address.

If \fBQMAILMFTFILE\fR is set, \fBqmail-inject\fR reads a list of mailing
list addresses, one per line, from that file. If To+Cc includes one of
those addresses (without regard to case), \fBqmail-inject\fR adds a
Mail-Followup-To field with all the To+Cc addresses.  \fBqmail-inject\fR
does not add Mail-Followup-To to a message that already has one.

If \fBQMAILQUEUE\fR environment variable is set to PREFIX/sbin/qmail-multi,
\fBqmail-inject\fR gets the ability to multiplex queues and filter
emails. See qmail-multi(8).

The \fBQMAILINJECT\fR environment variable can contain any of the following
letters:

.TP
.B c
Use address-comment style for the \fBFrom\fR field. Normally
\fBqmail-inject\fR uses name-address style.

.TP
.B s
Do not look at any incoming \fBReturn-Path\fR field. Normally, if
\fBReturn-Path\fR is supplied, it sets the envelope sender address,
overriding all environment variables. \fBReturn-Path\fR is deleted in any
case.

.TP
.B f
Delete any incoming \fBFrom\fR field. Normally, if \fBFrom\fR is supplied,
it overrides the usual \fBFrom\fR field created by \fBqmail-inject\fR.

.TP
.B i
Delete any incoming \fBMessage-ID\fR field. Normally, if \fBMessage-ID\fR
is supplied, it overrides the usual \fBMessage-ID\fR field created by
\fBqmail-inject\fR.

.TP
.B r
Use a per-recipient VERP. \fBqmail-inject\fR will append each recipient
address to the envelope sender of the copy going to that recipient.

.TP
.B m
Use a per-message VERP. \fBqmail-inject\fR will append the current date and
process ID to the envelope sender.

.TP
.B n
Print the message rather than feeding it to

.PP
\fBqmail-inject\fR uses environment set according to files in
$HOME/.defaultqueue directory. You can skip setting environment variables
from $HOME/.defaultqueue by setting \fBSKIP_LOCAL_ENVIRONMENT\fR
environment variable. If \fBQUEUE_BASE\fR environment variable is not
set, it additionally uses environment set according to files in
@controldir@/defaultqueue directory. If the environment variable
\fBFASTQUEUE\fR is set, $HOME/.defaultqueue is not processed.

.SH OPTIONS

.TP
.B \-a
Send the message to all addresses given as \fIrecip\fR arguments; do not
use header recipient addresses.

.TP
.B \-h
Send the message to all header recipient addresses. For non-forwarded
messages, this means the addresses listed under \fBTo\fR, \fBCc\fR,
\fBBcc\fR, \fBApparently-To\fR. For forwarded messages, this means the
addresses listed under \fBResent-To\fR, \fBResent-Cc\fR, \fBResent-Bcc\fR.
Do not use any \fIrecip\fR arguments.

.TP
.B \-A
(Default.)
Send the message to all addresses given as \fIrecip\fR arguments. If no
\fIrecip\fR arguments are supplied, send the message to all header
recipient addresses.

.TP
.B \-H
Send the message to all header recipient addresses, and to all addresses
given as \fIrecip\fR arguments.

.TP
.B \-f\fIsender
Pass \fIsender\fR to \fBqmail-queue\fR as the envelope sender address. This
overrides \fBReturn-Path\fR and all environment variables.

.TP
.B \-N
(Default.)
Feed the resulting message to \fBqmail-queue\fR.

.TP
.B \-n
Print the message rather than feeding it to \fBqmail-queue\fR.

.SH "CONTROL FILES"

.TP 5
.I defaultdomain
Default domain name.
Default:
\fIme\fR, if that is supplied; otherwise the literal name
\fBdefaultdomain\fR, which is probably not what you want.
\fBqmail-inject\fR adds this name to any host name without dots, including
\fIdefaulthost\fR if \fIdefaulthost\fR does not have dots. (Exception: see
\fIplusdomain\fR.)

The \fBQMAILDEFAULTDOMAIN\fR environment variable overrides \fIdefaultdomain\fR.

.TP 5
.I defaulthost
Default host name.
Default: \fIme\fR, if that is supplied; otherwise the literal name
\fBdefaulthost\fR, which is probably not what you want. \fBqmail-inject\fR
adds this name to any address without a host name. \fIdefaulthost\fR need
not be the current host's name. For example, you may prefer that outgoing
mail show just your domain name.

The \fBQMAILDEFAULTHOST\fR environment variable overrides
\fIdefaulthost\fR.

.TP 5
.I idhost
Host name for Message-IDs.
Default: \fIme\fR, if that is supplied; otherwise the literal name
\fBidhost\fR, which is certainly not what you want. \fIidhost\fR need not
be the current host's name. For example, you may prefer to use fake host
names in Message-IDs. However, \fIidhost\fR must be a fully-qualified name
within your domain, and each host in your domain should use a different
\fIidhost\fR.

The \fBQMAILIDHOST\fR environment variable overrides \fIidhost\fR.

.TP 5
.I plusdomain
Plus domain name.
Default: \fIme\fR, if that is supplied; otherwise the literal name
\fBplusdomain\fR, which is probably not what you want. \fBqmail-inject\fR
adds this name to any host name that ends with a plus sign, including
\fIdefaulthost\fR if \fIdefaulthost\fR ends with a plus sign. If a host
name does not have dots but ends with a plus sign, \fBqmail-inject\fR uses
\fIplusdomain\fR, not \fIdefaultdomain\fR.

The \fBQMAILPLUSDOMAIN\fR environment variable overrides \fIplusdomain\fR.

.TP 5
.I maxrecipients 
maxrecipients is the number of RCPT TO:'s \fBqmail-inject\fR will accept.
Default: 0 which means no restriction. The environment variable
\fBMAXRECIPIENTS\fR overrides the value in this control file.

.TP 5
.I domainqueue
Specific queue can be assigned to recipient domains. The format of this
file is of the form

.EX
  domain:QUEUEDIR=queue_dir
.EE

where domain is the recipient domain and queue_dir is any queue which is
part of indimail's queue collection. You could also specify a set of queues
for a domain.

domain:QUEUE_COUNT=5,QUEUE_START=6,QUEUE_BASE=/var/indimail/queue

specifies that any emails to *@domain be queued in
HOME/queue/queue[6,7,8,9,10]. You can use \fIdomainqueue\fR to
queue mails for certain domains into specific domains and specify
individual concurrencies for these queues (see qmail-send(8)). e.g. having

.EX
  yahoo.com:QUEUEDIR=HOME/queue/queue6
.EE

in @controldir@/domainqueue and

.EX
  10
.EE

in @controldir@/concurrencyr.queue6

will set 10 as the remote concurrency for all emails sent to yahoo.com

.TP 5
.I envrules
Specific environment variables can be set for specific senders. The format
of this file is of the form

.EX
  pat:envar1=val,envar2=val,...]
.EE

where pat is a regular expression which matches a sender. envar1, envar2
are list of environment variables to be set.

The name of the control file can be overridden by the environment variable
FROMRULES. The following environment variables used by \fBqmail-queue\fR
can be set by using envrules.

.IR SCANCMD ,
.IR QHPSI ,
.IR QHPSIMINSIZE ,
.IR QHPSIMAXSIZE ,
.IR QHPSIRC ,
.IR EXTRAQUEUE ,
.IR USE_FSYNC ,
.IR QQEH ,
.IR BADEXT ,
.IR BADEXTPATTERNS ,
.IR QREGEX ,
.IR QMAILNAME ,
.IR MAILNAME ,
.IR NAME ,
.IR REMOVEHEADERS ,
.IR ENVHEADERS ,
.IR LOGHEADERS ,
.IR LOGHEADERFD ,
.IR LOGFILTER ,
.IR TMPDIR ,
.IR VIRUSCHECK ,
.IR VIRUSFORWARD ,
.IR QUARANTINE ,
.IR RELAYCLIENT ,
.IR MAKESEEKABLE ,
.IR FILTERARGS ,
.IR QMAILQUEUE ,
.IR QUEUEPROG ,
.IR QUEUEDIR ,
.IR QUEUE_BASE ,
.IR QUEUE_START ,
.IR QUEUE_COUNT ,
.IR QUEUE_PLUGIN ,
.IR PLUGINDIR ,
.IR MIN_FREE ,
.IR ERROR_FD ,
.IR DKSIGN ,
.IR DKVERIFY ,
.IR DKSIGNOPTIONS ,
.IR DKQUEUE ,
.IR DKEXCLUDEHEADERS ,
.IR DKIMSIGN ,
.IR DKIMVERIFY ,
.IR DKIMPRACTICE ,
.IR DKIMIDENTITY ,
.IR DKIMEXPIRE ,
.IR SIGN_PRACTICE
.IR DKIMQUEUE ,
.IR SIGNATUREDOMAINS ,
and
.IR NOSIGNATUREDOMAINS

.SH "SEE ALSO"
uenv(1),
envdir(8),
sendmail(1),
indimail-srs(5),
addresses(5),
rfc-822(5),
indimail-control(5),
qmail-header(5),
qmail-queue(8),
qmail-multi(8)
