.TH qmail-qread 8
.SH NAME
qmail-qread \- list outgoing messages and recipients
.SH SYNOPSIS
.B qmail-qread
.I [-a]
.I [-l]
.I [-r]
.I [-t]
.I [-c]
.I [-s]
.I [-i]
.TP 2
-a List Mails in local, remote and todo
.TP 2
-l List Mails in local
.TP 2
-r List Mails in remote
.TP 2
-t List Mails in todo
.TP 2
-c Display counts only
.TP 2
-s Silent display for option -\fBc\fR
.TP 2
-i Display queue information in shared memory when using dynamic queues

.SH DESCRIPTION
\fBqmail-qread\fR scans the outgoing queue of messages.  For each message
it prints various human-readable information, including the date the
message entered the queue, the number of bytes in the message, the message
sender, the queue id no, and all the recipients still under consideration.

\fBqmail-qread\fR must be run either as \fBroot\fR or with user id
\fBqmails\fR and group id \fBqmail\fR.

\fBqmail-qread\fR uses DIRSPLIT as the directory split. It can be
overriden by environment variable \fICONFSPLIT\fR upto a max of
DIRSPLIT. \fBqmail-qread\fR can process a queue created with \fItodo\fR,
\fIintd\fR with subdirectory split instead of without any split. This
can be done by setting the \fBBIGTODO\fR environment variable.

\fBqmail-qread\fR uses the environment variable QUEUE_BASE or the conrol file \fBqbase\fR if
present to use the queue base. If the environment variables QUEUE_START and QUEUE_COUNT are set,
\fBqmail-qread\fR will process multiple queues present in the queue base.

\fBqmail-qread\fR uses environment set according to files in
$HOME/.defaultqueue directory. If QUEUE_BASE environment variable is not
set, it additionally uses environment set according to files in
@controldir@/defaultqueue directory.

When using dynamic queues (See multi-queue(7)), -i option can be used to
display queue counts, queue load and queue concurrencies.

.SH "SEE ALSO"
qmail-queue(8),
qmail-send(8),
qmail-todo(8),
shm_open(3),
ipcs(1),
mq_overview(7)
