.\" vim: tw=75
.TH qmail-lspawn 8
.SH NAME
qmail-lspawn \- schedule local deliveries
.SH SYNOPSIS
.B qmail-lspawn
.I defaultdelivery

.SH DESCRIPTION
\fBqmail-lspawn\fR reads a series of local delivery commands from
descriptor 0, invokes \fBqmail-local\fR to perform the deliveries, and
prints the results to descriptor 1. It passes \fIdefaultdelivery\fR to
\fBqmail-local\fR as the default delivery instruction.

\fBqmail-lspawn\fR invokes \fBqmail-local\fR asynchronously, so the results
may not be in the same order as the commands. If the environment variable
\fBQMAILLOCAL\fR is defined the executable defined by \fBQMAILLOCAL\fR is
invoked instead.

\fBqmail-lspawn\fR sets the environment variable \fBMESSID\fR pointing
message file in the queue.

For each recipient address, \fBqmail-lspawn\fR finds out which local user
controls that address. It first checks the \fBqmail-users\fR mechanism; if
the address is not listed there, it invokes \fBqmail-getpw\fR.
\fBqmail-lspawn\fR then runs \fBqmail-local\fR under the user's uid and
gid. For address fetched using \fBqmail-getpw\fR, it sets up supplementary
groups for the user if the environment variable \fBSETUSER_PRIVILEGES\fR is
set. \fBqmail-lspawn\fR does not perform deliveries as root.

If the environment variable \fBAUTHSELF\fR is set, \fBqmail-lspawn\fR
connects to MySQL and fetches user records for virtual domains in
\fIvirtualdomains\fR control file. If connecton to MySQL fails,
\fBqmail-lspawn\fR exits with -2. For an empty mailbox name (e.g. double
bounces to virtual domains), mails can be routed to user defined by
\fBROUTE_NULL_USER\fR environment variable. If this variable is set but
empty, \fBqmail-lspawn\fR will treat the empty mailbox name as a trash
address. If the domain portion, belongs to a virtual domain on the host,
the mail will be routed to the mailbox name at the virtual domain. If the
domain portion, doesn't belong to a virtual domain set in IndiMail, the
mail will be silently deliverd to local user, ignoring the domain name
following the '@' sign.

For all other cases not covered by setting \fbAUTHSELF\fR environment
variable, \fBqmail-lspawn\fR treats an empty mailbox name as a trash
address.

.SH Virtual Package Functionality
\fBqmail-lspawn\fR can load an external library to add functionality. The
virtual package can be loaded by setting the environment variable
\fBVIRTUAL_PKG_LIB\fR or by using the control file \fIlibindimail\fR. The
value in \fIlibindimail\fR is set to \fIlibindimail\fR.\fIso\fR by default.
If there is any problem loading the library or loading symbols required,
\fBqmail-lspawn\fR will exit with -3. If the environment \fBAUTHSELF\fR
isn't defined the external library will not be loaded.

Following functions should be provided by the shared library for adding
features to qmail-lspawn - isvirtualdomain(), iopen(), sql_getpw(),
iclose(). If such a library is opened \fBqmail-lspawn\fR connects to
MySQL(1) and sets the environment variable \fBPWSTRUCT\fR having the passwd
structure for the user. The environment variable is set to "No such user"
in case the user is not found in the local MySQL database. This environment
variable can be used by delivery agents without having to read the passwd
file or a database. For a user-cluster domain, if a mail is injected for a
user not found in the local MySQL database, \fBqmail-lspawn\fR will set
PWSTRUCT to "No such user". However, a delivery agent like
\fBvdelivermail(8)\fR reroutes the email to the correct destination host
which has the user account, using \fBqmail-remote\fR.

\fBqmail-lspawn\fR goes ahead without attempting to load external library
if \fBAUTHSELF\fR was not set.

.B qmail-lspawn
runs with uid 0.

.SH "SEE ALSO"
envelopes(5),
qmail-users(5),
qmail-getpw(8),
qscheduler(8),
qmail-start(8),
qmail-send(8),
todo-proc(8),
qmail-local(8)
