.TH qmail-queue 8
.SH NAME
qmail-queue \- queue a mail message for delivery
.SH SYNOPSIS
.B qmail-queue
.SH DESCRIPTION
.B qmail-queue
reads a mail message from descriptor 0.
It then reads envelope information from descriptor 1.
It places the message into the outgoing queue
for future delivery by
.BR qmail-send .
The default outgoing queue is @qmaildir@/queue. This can be changed by setting environment variable QUEUEDIR to
point to a path having a valid qmail queue.

The envelope information is an envelope sender address followed by a list of envelope recipient addresses.
The sender address is preceded by the letter F and terminated by a 0 byte.
Each recipient address is preceded by the letter T and terminated by a 0 byte.
The list of recipient addresses is terminated by an extra 0 byte. If
.B qmail-queue
sees end-of-file before the extra 0 byte, it aborts without placing the message into the queue.
If \fBUSE_FSYNC\fR environment variable is defined \fBqmail-queue\fR uses fsync(2) to sync the message file in
\fIqueue/mess\fR and the envelope in \fIqueue/intd\fR file as well. After creating a link
to the envelope in \fIqueue/todo\fR to \fIqueue/intd\fR, qmail-queue syncs the directory
using the following two methods.
.IP \[bu] 2
.I BSD Style Synchronous Directory
This gets enabled if \fBUSE_SYNCDIR\fR environment variable is defined. This forces directory syncing.
.IP \[bu]
.I Using FSYNC
\fBqmail-queue\fR opens the file in \fBqueue/todo\fR and uses the fsync(2)
call to flush data buffers to the disk

.SH CONTROL FILES
\fBqmail-queue\fR use many control files to provide various features.

.TP
.B extraqueue
If this control file exists, each line in the content is added as a recipient to the 
recipient list. The environment variable
.B EXTRAQUEUE
also does the same thing. The value of the environment variable overrides the value in the
control file. Also the environment variable can be just one recipient. There is a potential
for loops in case the recipient is local and the local delivery has any kind of forwarding
rule which results in qmail-queue being invoked.

.TP
.B mailarchive
if this control file exists, its content can be used for rule based archival. The environment
variable
.B MAILARCHIVE
overrides the name of the \fImailarchive\fR control file. A line in this control file
can be of the form

.EX
 type:regexp:dest_mailbox
.EE

where \fItype\fR is \fBF\fR  or \fBT\fR. If \fItype\fR is \fBF\fR, rule is appled on the sender.
If \fItype\fR is \fBT\fR, the rule is applied on the recipient. \fItype\fR can be omitted to
match all recipients. \fIregexp\fR is an expression to match the address (sender or recipient
as specfied by \fItype\fR) and \fIdest_mailbox\fR is a valid email address. \fIregexp\fR can be
omitted to match any address. A \fB%\fR in \fIdest_mailbox\fR followed by u, d or e gets
replaced as below

.EX
 %u - user component in address without the '@' sign
 %d - domain component in address
 %e - email address
.EE

As stated above, the address used for matching \fIregexp\fR is the sender in case type is
\fBF\fR. For bounces, you can use <> to match a null sender. e.g.

.EX
 F:<>:bounce_archive@example.com
.EE

When a rule matches a sender or any one of the recipients, the \fIdest_mailbox\fR address after
expansion will be added to the existing recipient list. When a rule matches multiple recipients,
only one email address will be added to recipient list to avoid duplicates.

The below will make a copy all mails for domain \fIyourdomain\fR to \fIarchyourdomain\fR

.EX
::%u@arch%d
.EE

.TP
.B originipfield
If this control file is set or if the environment variable 
.B ORIGINIPFIELD
is set, a "X-Originating-IP" header will be added to every relayed mail. The environment
variable 
.B ORIGINIPFIELD
overrides the control file 
.BR originipfield .

.TP
.B quarantine
If this control file exists, recipient list is replaced with its content. The environment
variable
.B QUARANTINE
also does the same thing. The value of the environment variable overrides the value in the
control file. Additionally, comma separated list of original recipient list is added to the
header \fBX-Quarantine-ID\fR.

.TP
.B removeheaders
If this control file
exists, \fBqmail-queue\fR removes all headers listed in the control file from the mail message
on descriptor 0 before writing it to the disk. The environment variable \fBREMOVEHEADERS\fR can
be set to use a different name for this control file.

Every envelope recipient address should contain a username, an @ sign, and a fully qualified domain name.

.B qmail-queue
always adds a
.B Received
line to the top of the message.
.B qmail-queue
keeps a copy of the
.B QQEH
environment variable (if set), and passes it into the queue.
.B qmail-local
and
.B qmail-remote
will prepend it to the headers of the email when it is delivered.

.TP
.B envheaders
If this control file exists, \fBqmail-queue\fR passes all headers listed in the control file
to the queue along with the value. \fBqmail-local\fR and \fBqmail-remote\fR will set
environment variables corresponding to the headers with the values. An optional length,
separated by a ':', can be appended to the name of the header. If length is specified, the
environment variable will be set only if the actual length of the header value is less than
or equal to this value. This will prevent emails with extra long headers or malicious headers
to exploit memory allocation on the system. The environment variable \fBENVHEADERS\fR can be
set to use a different name for this control file.

.TP
.B logheaders
If this control file exists, \fBqmail-queue\fR writes all headers (along with values) listed in
the control file to file descriptor defined by \fBLOGHEADERFD\fR environment variable. The file
descriptor needs to be open for write. You can open the file descriptor in the startup scripts
for \fBqmail-smtpd\fR, for example.

.EX
 touch /tmp/header.log
 exec 45 >/tmp/header.log
 LOGHEADERFD=45
.EE

If the file descriptor is not open, logging of header will be silently ignored. Logging of headers
can be useful for debugging or logging specific headers in log files. The environment
variable \fBLOGHEADERS\fR can be set to use a different name for this control file.

.B qmail-queue
does not inspect the message and does not enforce any restrictions on its contents.
However, the recipients probably expect to see a proper header, as described in
.BR qmail-header(5) .

Programs included with qmail which invoke
.B qmail-queue
will invoke the contents of
.B $QMAILQUEUE
instead, if that environment variable is set.

.SH "FILESYSTEM RESTRICTIONS"
.B qmail-queue
imposes two constraints on the queue structure:
each
.B mess
subdirectory must be in the same filesystem as the
.B pid
directory; and each
.B todo
subdirectory must be in the same filesystem as the
.B intd
directory.

.SH "Qmail High Performance Scanner Interface"
A large fraction of today's emails is infected by a virus
or a worm. It is necessary to recognize those malicious
emails as soon as possible -- already in the DATA phase
of the SMTP conversation and to reject them.

Typically, this is facilitated my means of
.BR AMaViS , 
.BR qmail-scanner ,
or
.B qscanq
which facilitate as "wrapper" of
the original qmail-queue program invoked by means 
of QMAILQUEUE path (
.BR qmail-multi ).

However -- in case of virus attacks -- those umbrella
programs become part of the problem itself due to their
resource requirements.

Today's virus scanner -- in particluar Clam AV -- work in 
resource efficient client/server mode (clamd/clamdscan)
and include the feature to detect virii/worms in the base64
encoded data stream. Thus, there is no necessity to call
additional programs (like reformime or ripmime) except 
for the virus scanner itself.

The QHPSI extension for qmail-queue allows to call an arbitary virus scanner directly,
scanning the incoming data-stream on STDIN or it allows plugins to be loaded from
the @prefix@/lib/indimail/plugins directory. This directory can be changed by defining
\fBPLUGINDIR\fR environment variable. QHPSI can be advised to pass
multiple arguments to the virus scanner for customization. To run external scanner
or load scanner plugins, \fBqmail-queue\fR calls \fBqhpsi\fR, a program setuid to \fIqscand\fR.
By default, \fBqhpsi\fR looks for the symbol \fIvirusscan\fR to invoke the scanner.
The symbol can be changed by setting the environment variable \fBQUEUE_PLUGIN_SYMB\fR to the
desired symbol.

In order to use the QHPSI, the virus scanner has to have
the following qualifications:

a) Correct interpretation of the base64 and perhaps the
   uudecoded data in order to detect the virii/worms therein.

b) Results have to be made available on stderr/stdout.

And perhaps:

c) Suppression of 'negative' scan results. 

Details on setting the virus scanner interface is given below.

.B QHPSI
can be set either to the full path of a scanner or to a list of plugins.

.LP
.nr step 1 1
.IP \n[step] 2
is set to full path of the virus scanner, i.e. QHPSI=@prefix@/bin/clamdscan.
If full path is not specified,
.B qmail-queue
will use execvp(2) to run the scanner. Else it uses execv(2).
Setting QHPSI environment variable turns on the QHPSI interface. 
The Qmail High Performance Scanner interface QHPSI also allows
.B qmail-queue
to read command line arguments taken from the
.B QHPSI
environment to be used as a call-interface for an external virus scanner:

.EX
 QHPSI="clamdscan %s --quiet --no-summary"
.EE

Any \fB'%s'\fR in the \fBQHPSI\fR gets replaced with
the message filename in the queue's '\fImess\fR' directory.

.IP \n+[step]
is set to list of plugins starting with a keyword 'plugin:'.

.EX
 QHPSI="plugin: clamd.so fsecure.so symantec.so"
.EE

Sets \fBqmail-queue\fR to load three plugins clamd, fsecure and symantec from
@prefix@/lib/indimail/plugins directory.

You can also use the plugin generic.so. generic.so plugin can use any scanner defined
by the \fBSCANCMD\fR environment variable.

.EX
 QHPSI="plugin: generic.so"
 SCANCMD="clamdscan %s --quiet --no-summary"
.EE

Any \fB'%s'\fR in the \fBSCANCMD\fR gets replaced with
the message filename in the queue's '\fImess\fR' directory.

.LP

.TP
.B QHPSIRC
To specify the return code of the virus scanner in case of an infection; default is 1.
.TP
.B QHPSIRN
To specify the return code of the virus scanner in case of no infection; default is 0.
.TP
.B REJECTVIRUS
If set to 1, infected mails will be bounced to sender. If set to 2, infected mails will
be blackholed. If set to 0, infected mails will be accepted. Blackholing does not work if VIRUSFORWARD or
QUARANTINE is defined. Setting to a value > 2 will bounce infected mails to sender
.TP
.B VIRUSFORWARD
Infected mails will be quarantined to the email defined by VIRUSFORWARD. This will work only if
.B REJECTVIRUS
is not equal to 1. Setting VIRUSFORWARD sets the \fBX-Quarantine-ID\fR containing the
list of original recipient list is added.
.TP
.B QHPSIMINSIZE
The minimal size of the message to invoke the virus scanner; default is 0.
A typical choice would be QHPSIMISIZE=10000 (~10k).
.TP
.B QHPSIMAXSIZE
The maximal size of the message to invoke the virus scanner; default is unrestricted.
A typical choice would be QHPPIMAXSIZE=1000000 (~1M).

When QHPSI is enabled \fBqmail-queue\fR adds the header X-QHPSI, the value of which
is either 'infected' or 'clean' (depending on whether the mail as identifed as infected
or not).

.SH "EXIT CODES"
.B qmail-queue
does not print diagnostics.
It exits
0 if
it has successfully queued the message.
It exits between 1 and 99 if
it has failed to queue the message.

All
.B qmail-queue
error codes between 11 and 40 indicate permanent errors:
.TP 5
.B 11
Address too long.
.TP
.B 31
Mail server permanently refuses to send the message to any recipients. (Not used by
.BR qmail-queue ,
but can be used by programs offering the same interface.)
.TP
.B 32
Spam or Junk Mail threshold exceeded. This is returned when a spam filter like
.B bogofilter
is used (SPAMFILTER is defined) and the mail is identified as spam.
.TP
.B 33
Message contains a virus.
.TP
.B 34
Message contains banned attachments
.TP
.B 88
Custom error (=bounce) messages. You have to write the error message to STDERR
and exit 88, in order to use the custom message. Format of the message:

Dthis is a custom fatal error message

Zthis is a custom temporary failure message

.PP
All other
.B qmail-queue
error codes indicate temporary errors:
.TP 5
.B 51
Out of memory.
.TP
.B 52
Timeout.
.TP
.B 53
Write error; e.g., disk full.
.TP
.B 54
Unable to read the message or envelope.
.TP
.B 55
Unable to read a configuration file.
.TP
.B 56
Problem making a network connection from this host. (Not used by
.BR qmail-queue .)
.TP
.B 61
Problem with the qmail home directory.
.TP
.B 62
Problem with the queue directory.
.TP
.B 63
Problem with queue/pid.
.TP
.B 64
Problem with queue/mess.
.TP
.B 65
Problem with queue/intd.
.TP
.B 66
Problem with queue/todo.
.TP
.B 67
Problem with uids/gids.
.TP
.B 71
Mail server temporarily refuses to send the message to any recipients.
(Not used by
.BR qmail-queue .)
.TP
.B 72
Connection to mail server timed out.
(Not used by
.BR qmail-queue .)
.TP
.B 73
Connection to mail server rejected.
(Not used by
.BR qmail-queue .)
.TP
.B 74
Connection to mail server succeeded, but communication failed. (Not used by
.BR qmail-queue .)
.TP
.B 79
Envelope format error.
.TP
.B 81
Internal bug; e.g., segmentation fault.

.SH Notes

Samples with clamd/clamdscan:

Here is a typical sample how to customize QHPSI together
with Clam AV (clamd/clamdscan) for a tcpserver tcp.smtpd file:

 :allow,QHPSI='@prefix@/bin/clamdscan %s --quiet --no-summary'

Comments:

 - The path of 'clamdscan' can be omitted, because it is in 
   the standard path (@prefix@/bin).
 - In the configuration file clamav.conf, the option
  'ScanMail' has to be enabled; clamd has to run as 'root'.
 - The argument QHPSI='@prefix@/bin/clamdscan %s --quiet --no-summary'
   tells Clam AV to just provide the return status and print nothing
   on the stdout.
 - The argument QHPSIRC is not necessary, because
   'clamdscan' return with 'RC=1' (the default) in 
   case a virus infection is recognized.

Sample with McAfee's uvscan:

 :allow,QHPSI='/usr/bin/uvscan --secure',QHPSIMAXSIZE='9000000',QHPSIRC='13'

Comments:

 - The path of 'uvscan' is '/usr/local/bin' and can be ommitted.
 - 'uvscan' returns with RC=13 in case a virus is found,
   therefore, QHPSIRC has to provide this value.
 - The virus scanning is omitted, if the size of the message
   exceeds 9.000.000 byte, ~ 8.5MB.

You can also set these variables outside tcp.smtp. e.g.
  # echo @prefix@/bin/clamdscan %s --quiet --no-summary \\
     > @servicedir@/qmail.smtpd.25/variables/QHPSI

.SH Compliance
.TP
\fBBasel II\fR \fIInternational\fR
Affects - International Banking

Basel II is an international banking accord that replaces the original Basel agreement of 1988. The
accord brings in a major shift in the way that financial institutions assess and manage risk in relation to
investments.

Given that the emphasis is in the main risk assessment, the impact on emails is likely to be the
requirement to retain all emails relating to a trade for a period of not less than 5 years, starting from
January 2003. Financial institutions must ensure that data and communication is secure, accessible
and accurate.

.TP
\fBCanadian Privacy Act\fR \fICanada\fR
Affects - This policy is applicable to anyone who is storing any personal data.

The Privacy Act was established to protect the personal information of individuals collected by the
government. It also gives these individuals the right to access this information. It is a law governing how
private sector organizations collect, use and disclose personal information in the course of commercial
business.

In order to comply with the Canadian Privacy Act, a law which guarantees individuals access to public
records kept by government agencies, an efficient archiving system for compliance is a must. Email is a
public record, just like any other document, it is vital that a system is in place to control the increasing
amount of email data - in addition to the ability to quickly respond to compliance requests.

.TP
\fBData Proection Act 1988\fR \fIEU\fR
Affects - This policy is applicable to anyone who is storing any personal data.

The purpose of the act is to protect the individual rights and freedoms of persons; especially their right
to privacy with respect to the processing of personal data.

Given that email is a major medium for exchange and storage of personal information, principles 5 & 7
effectively rule out all current mail server platforms as effective means for storing personal data. Only a
purpose built archiving system can meet these requirements. Furthermore, given the individuals right to
issue “Subject Access Request”, SAR’s, detailed search capabilities are required within an archive
repository to support these requirements in a cost effective manner. A standard mail server platform
does not meet these requirements.

.TP
\fBEU Data Protection Directive 95/46/FC\fR \fIAll organizations, members of EU member states\fI
Affects - All organizations, members of EU member states

The European Union adopted a Directive 95/46/EC on the protection of individuals with regard to the
processing of personal data and on the free movement of such data ("data protection directive"). A key
objective of the data protection Directive was to allow the free flow of personal data between Member
States by harmonizing the level of adequate protection granted to individuals. Similar to the UK Data
Protection Act the principles of security and retention of data for only as long as is required are
common.

The need for a comprehensive email archiving solution is clear. The Data Controller must implement
appropriate technical and organizational measures to protect personal data against accidental or
unlawful destruction or accidental loss, alteration, unauthorized disclosure or access – such elements
cannot be provided by generic mail servers as already indicated by compliance with the UK Data
Protection Act.

.TP
\fBFederal Information Security Management Act (FISMA)\fR \fIUSA\fR
Affects - United States Federal, State & Local Government

Federal Information Security Management Act (FISMA) places the onus squarely on agencies and their
partners to develop information security risk assessments and mitigation strategies. It defines three
security objectives for information and information systems (Confidentiality, Integrity and Availability)
and requires every government agency to secure the information and information systems that support
its operations and assets, including those provided or managed by another agency, contractor, or
other source. As part of FISMA compliance, agencies and departments should implement ways to track
the contents of all outgoing emails.

Email is a prime medium for exchange and storage of company records. Storage in the mail-server
does not protect against falsification, nor does it protect against accidental loss or malicious removal. A
purpose built email archive system will ensure that relevant data can be maintained for the desired
retention period and maintain integrity of the records through tamper-proof mechanisms. Furthermore,
the system will provide easy search access to recover data if required by an external auditor.

.TP
\fBFederal Rules of Civil Procedure (FRCP)\fR \fIUSA\fR
Affects - Any organization in any industry that has the potential of being involved in litigation in the U.S. Federal
Court system.

The amendments, which went into effect on December 1, 2006, mandate that companies be prepared
for electronic discovery. The organization must know where their data is, how to retrieve it, how to meet
data requests and they must determine what data will not be subject to search.

Organizations that do not have an automated system in place to help them effectively store, search
and retrieve email data in real-time face paying high costs for “rush job” discovery requests. In some
instances, failure to produce the requested data in a timely fashion may even lead to the loss of a
lawsuit.

.TP
\fBFinancial Services Act 198, regulated by FSA\fR \fIUK\fR
Affects - Financial Services Industry Sector

The Financial Services Act was passed to consolidate the regulatory authority of numerous agencies in
the United Kingdom. The FSA (Financial Services Authority) was created, which is an agency with broad
regulatory powers to govern the financial industry. Whilst the act itself is not specific with regard to
email retention, the FSA has imposed some guidance in relation to records retention. For example, in
relation to guidance on Money Laundering, records relating to transactions, reports and “information
not acted on” must be retained for a period of 5 years.

Financial organizations need to review their compliance with FSA guidance in relation to the email.
Given the need to retain records for varying numbers of years, a dedicated email archive store is
required to ensure that that these requirements are met.

.TP
\fBFreedom of Information Act (FOIA)\fR \fIUSA\fR
Affects - United States Federal, State & Local Government

Freedom of Information Act requires that federal agencies disclose their records to anyone making a
written request. The speed and economy of email often makes it the preferred means of delivery,
carrying risks that the wrong information might be sent or the wrong recipient addressed. Because
email has become so prevalent for interdepartmental communications, security of communications has
become a serious concern.

In order to comply with the FOI, a law guaranteeing individuals access to public records kept by
government agencies, an efficient archiving system for compliance is a must. Email is a public record,
just like any other document, it is vital that a system is in place to control the increasing amount of
email data. In addition to the ability to quickly respond to compliance requests

.TP
\fBFreedom of Information Act (in force January 2005)\fR \fIUK\fR
Affects - All UK Government Organizations

The Freedom of information Act gives anyone the right to request information from a government
organization (including central and local government, the health sector, police and armed forces, the
education sector and other public bodies), about any subject that they are interested in.

It is clear that organizations reliant upon existing email technology will not be able to adequately meet
the SAR (Subject Access Requests) in a timely and cost-effective manner. A centralized email archive
store will address all these issues, ensuring that those covered by the FOI can meet their obligations.

.TP
\fBThe Gramm-Leach-Bliley Act (GLB)\fR \fIUS Financial Institutions\fR
Affects - US Financial Institutions

The GLB Act applies to “financial institutions” – businesses that offer financial products or services to
individuals to be used primarily for their personal, family, or household purposes. Financial institutions
include, for example, banks, securities firms and insurance companies; such entities are covered by the
SEC (Securities and Exchange Commission). Businesses that provide many other types of financial
products and services to consumers fall under jurisdiction of the FTC (Federal Trade Commission) for the
purposes of enforcing GLB.

Violation of GLBA may result in a civil action brought by the U.S. Attorney General. The penalties include
those for the financial institution of up to $100,000 for each violation. In addition, “the officers and
directors of the financial institution shall be subject to, and shall be personally liable for, a civil penalty
of not more than $10,000 for each such violation”. Criminal penalties may include up to 5 years in
prison.

Today, the vast majority of organizations use email to communicate internally and as a vehicle for the
exchange of documents and correspondence between businesses and consumers. Since personal
financial information can be transmitted by and retained in electronic formats, it is critical to ensure that
the management of such records complies with GLB.

.TP
\fBHealth Insurance Portability & Accountability Act (HIPAA)\fR \fIUSA\fR
Affects - Virtually all organizations that deal with electronic patient healthcare information are affected.

All patient information, authorizations, policies, procedures and contracts with business associates
must be retained for at least 6 years. Information must be stored in robust data centers that provide
minimum guarantees uptime and very high security. Anyone who obtains and discloses information
with the intent to sell, transfer or use it for commercial gain or malicious harm can face penalties of up
to $250K in fines and 10 years in jail.

All patient information, authorizations, policies, procedures and contracts with business associates
must be retained for at least 6 years.

.TP
\fBIRS Circular 230\fR \fIUSA\fR
Affects - All Financial Services Organizations/Departments

The new Circular 230 regulations issued by the Treasury Department were effective on June 20,
2005 in response to some situations in which tax professionals issued tax advice or opinions to clients
so that the clients would have penalty protection, even though the advice or opinions were based upon
facts, assumptions, or representations that were not reasonable. These new regulations established
very high standards that a tax advisor must meet if he or she wishes to provide a client with written tax
advice that may be relied upon for tax penalty protection. Circular 230 prescribes standards of practice
for lawyers and accountants before the Internal Revenue Service, including ethical and professional
responsibilities.

The need for Disclaimers - As a result of the Circular 230 regulations, any written tax advice (including tax advice included in an
email or other form of electronic written communication) must include a prominent disclaimer. The
disclaimer must be near the top of an opinion in a typeface the same size or larger than the typeface of
the tax advice. Exclaimer Mail Utilities helps ensure regulation compliance. For example, Circular 230
requires that the disclaimer must be inserted prior to the body of the email, and at a larger font size.
Exclaimer Mail Utilities handles this requirement with ease.

.TP
\fBMiFID (Markets in Financial Instruments Directives)\fR \fIEU\fR
Affects - EU financial markets - Investment banks, Portfolio Managers, Stockbrokers, Broker Dealers, Corporate
Finance Firms

MiFID – the Markets in Financial Instruments Directive – comes into effect on 1 November 2007, when it
will replace the existing Investment Services Directive (ISD). MiFID extends the coverage of the current
ISD and introduces new and more extensive requirements that firms will have to adapt to, in particular
for their conduct of business and internal organization.

Email is a prime medium for exchange and storage of company records. Storage in the mail-server
does not protect against falsification, nor does it protect against accidental loss or malicious removal. A
purpose built email archive system will ensure that relevant data can be maintained for the desired
retention period and maintain integrity of the records through tamper-proof mechanisms. Furthermore,
the system will provide easy search access to recover data if required by an external auditor.

.TP
\fBPIPEDA (Personal Information Protection and Electronic Documents Act)\fR \fICanada\fR
Affects - This policy is applicable to anyone who is storing any personal data.

The Personal Information Protection and Electronic Documents Act is a Canadian law designed to
ensure that personal information collected by businesses will be kept secure and will only be collected,
used and given out under a strict set of circumstances. The Act, based on ten privacy principles was
developed by the Canadian Standards Association.

In order to comply with the PIPEDA an effective archiving system for compliance is a must. Email is a
public record, just like any other document, it is vital that a system is in place to control the increasing
amount of email data. In addition to the ability to quickly respond to compliance requests

.TP
\fBThe Public Information Act, Texas State\fR \fIUSA, Texas State\fR
Affects - Anyone who is storing public records kept by government agencies.

Texas Government Code, Chapter 552, gives anyone the right to access government records; and an
officer for public information and the officer's agent may not ask why you want them. All government
information is presumed to be available to the public. Certain exceptions may apply to the disclosure of
the information. Governmental bodies shall promptly release requested information that is not
confidential by law, either constitutional, statutory, or by judicial decision, or information for which an
exception to disclosure has not been sought.

In order to comply with the Public Information Act, a law guaranteeing individuals access to public
records kept by government agencies, an efficient archiving system for compliance is a must. Email is a
public record, just like any other document, it is vital that a system is in place to control the increasing
amount of email data. In addition to the ability to quickly respond to compliance requests

.TP
\fBSarbanes-Oxley 2002\fR \fIUSA\fR
Affects - All US public companies and many private organizations, and any UK companies trading on US stock
exchange.

Sarbanes Oxley is all about corporate governance. It came as a result of the large corporate financial
scandals involving Enron, WorldCom, Global Crossing and Arthur Andersen. Effective in 2004, all
publicly-traded companies are required to submit an annual report of the effectiveness of their internal
accounting controls to the US Securities and Exchange Commission (SEC). Essentially, SOX legislates
what used to be IT security best practices. The major provisions of the Sarbanes Oxley Act (SOX) include
criminal and civil penalties. Anyone who knowingly alters, falsifies, destroys, or otherwise tampers with
a document or record can be fined and/or imprisoned for up to 20 years.

Specifically all relevant audit-related documentation must be retained for a period of at least seven
years. This includes contracts, policies, authorizations, verifications, recommendations, performance
reviews and financial data. SOX also addresses the need for companies to effectively manage risk in all
its forms—including ensuring that data residing on corporate computers is adequately archived and
protected from damage or tampering. To comply with these needs, an effective archiving system is

.TP
\fBSEC Rule 17a-4/ NASD 3010 (Securities Exchange Act 1934)\fR \fIUS, UK\fR
Affects - All US Financial institutions and UK organizations trading on the NYSE

Among the most visible record keeping regulations are those imposed by SEC and related exchanges
on communication between securities traders/brokers and the public.
SEC rules 17a-3 and 17a-4 require broker-dealers to create, and preserve in an accessible manner, a
comprehensive record of each securities transaction they effect and of their securities business in
general.

The US Financial Services market is perhaps one of the most heavily regulated markets in the world
when it comes to document and email archiving. All US financial organizations and any UK
organizations that trade on the NYSE are required to meet these regulations.
The member, broker, or dealer must have in place an audit system providing for accountability
regarding inputting of records required to be maintained and preserved pursuant to Rule 17a-3 and
Rule 17a-4 to electronic storage media and inputting of any changes made to every original and
duplicate record maintained and preserved thereby.
a) At all times, a member, broker, or dealer must be able to have the results of such audit system
available for examination by the staffs of the Commission and the self-regulatory organizations of
which the broker or dealer is a member.
b) The audit results must be preserved for the time required for the audited records.
The need to guarantee capture, store and maintain messages in a non-erasable manner is a key
requirement that mail servers or indeed home grown archive systems cannot deliver. Speed of retrieval
is also a key factor when dealing with Legal Discovery orders. Noncompliance is not an option with
huge fines in the region of several million dollars being leveled at organizations.

.TP
\fBUK Companies Act 1985\fR \fIUK\fR
Affects - All private and public companies

Every company must keep accounting records which sufficiently show and explain the company’s
transactions that (a) disclose with reasonable accuracy, at any time, the financial position of the
company at that time, and (b) enable the directors to ensure that any balance sheet and profit and loss
account prepared under this Part complies with the requirements of this Act. A company’s accounting
records shall be kept at its registered office or such other place as the directors think fit, and shall at all
times be open to inspection by the company’s officers. From the date on which the record is made,
private companies must retain this information for 3 years and public companies must retain it for 6
years.

Email is a prime medium for exchange and storage of company records. Storage in the mail-server
does not protect against falsification, nor does it protect against accidental loss or malicious removal. A
purpose built email archive system will ensure that relevant data can be maintained for the desired
retention period and maintain integrity of the records through tamper-proof mechanisms. Furthermore,
the system will provide easy search access to recover data if required by an external auditor.

.TP
\fBUK Companies Act 2006 (amended 2007)\fR \fIUK\fR
Affects - All private and public companies

In addition to the requirements of the UK Companies Act 1985, every company should list its company
registration number, place of registration and registered office address on its website as a result of an
update to the legislation of 1985. The information, which must be in legible characters, should also
appear on order forms and in emails. Such information is already required on 'business letters' but the
duty is being extended to websites, order forms and electronic documents.

Need for Disclaimer - If your business is a private or public limited company or a Limited Liability Partnership, the Companies
Act 1985 requires all of your business emails (and your letterhead and order forms) to include the
following details in legible characters:

 o Your company registration number;
 o Your place of registration (e.g. Scotland or England & Wales)
 o Your registered office address

This information should also appear on your company's website. Failure to comply with these
requirements puts a company at risk of a fine of up to £1000.

.SH "SEE ALSO"
addresses(5),
envelopes(5),
qmail-header(5),
qmail-inject(8),
qmail-control(5),
queue-fix(8),
qmail-rm(1),
qmail-qread(8),
qmail-qmqpc(8),
qmail-send(8),
qmail-smtpd(8),
qmail-internals(8),
qmail-multi(8).
qmail-nullqueue(8).
qmail-direct(8)
