.TH qmail-qread 8
.SH NAME
qmail-qread \- list outgoing messages and recipients
.SH SYNOPSIS
.B qmail-qread
.I [-a]
.I [-l]
.I [-r]
.I [-t]
.I [-c]
.TP 2
-a List Mails in local, remote and todo
.TP 2
-l List Mails in local
.TP 2
-r List Mails in remote
.TP 2
-t List Mails in todo
.TP 2
-c Display counts only

.SH DESCRIPTION
.B qmail-qread
scans the outgoing queue of messages.
For each message it prints various human-readable information,
including the date the message entered the queue,
the number of bytes in the message,
the message sender, the queue id no,
and all the recipients still under consideration.

.B qmail-qread
must be run either as 
.B root
or with user id
.B qmails
and group id
.BR qmail .

\fBqmail-qread\fR uses DIRSPLIT as the directory split. It can be
overriden by environment variable \fICONFSPLIT\fR upto a max of
DIRSPLIT

\fBqmail-qread\fR uses the environment variable QUEUE_BASE or the conrol file \fBqbase\fR if
present to use the queue base. If the environment variables QUEUE_START and QUEUE_COUNT are set,
\fBqmail-qread\fR will process multiple queues present in the queue base.

\fBqmail-qread\fR uses environment set according to files in
$HOME/.defaultqueue directory. If QUEUE_BASE environment variable is not
set, it additionally uses environment set according to files in
@controldir@/defaultqueue directory.

.SH "SEE ALSO"
qmail-send(8)
