.\" vim: tw=75
.TH qmail-cdb 8
.SH NAME
qmail-cdb \- prepare data in cdb format for
.BR qmail .

.SH SYNOPSIS
.PP
.B qmail-cdb
\fB\-r\fR
[
\fB\-m\fR
]
[
.I filename
]

.PP
or
.PP
.B qmail-cdb
[
\fB\-m\fR
]
.I filename

.SH DESCRIPTION
With the -\fIr\fR option, \fBqmail-cdb\fR does a chdir to
\fI@sysconfdir@\fR directory option and proceeds to read
\fIusers/filename\fR. You can override \fI@sysconfdir@\fR directory by
setting \fBSYSCONFDIR\fR environment variable. \fIfilename\fR can be
omitted to use a default of \fIuser/recipients\fR for the -\fIr\fR option.

Without the -\fIr\fR option, \fBqmail-cdb\fR does a chdir to
\fI@controldir@\fR directory and proceeds to read \fIfilename\fR. You can
override \fI@controldir@\fR directory by setting \fBCONTROLDIR\fR
environment variable.

\fBqmail-cdb\fR then reads the addresses provided in \fIfilename\fR (or
\fIusers/filename\fR for -r option), converts them into lowercase, and
writes them into \fIfilename.cdb\fR in a binary format suited for quick
access by \fBqmail-smtpd\fR, \fBspawn-filter\fR and many other programs.
Each line in \fIfilename\fR should be a local email address.
\fIfilename.cdb\fR is compatible with \fBsetforward\fR(1)'s generated
\'fastforward\' cdbs and it's format is portable across machines. If there
is a problem with \fIfilename\fR, \fBqmail-cdb\fR complains and leaves
\fIfilename.cdb\fR alone. \fIfilename.cdb\fR is created in the same
directory as \fIfilename\fR.

\fBqmail-cdb\fR ensures that \fIfilename.cdb\fR is updated atomically, so
\fBqmail-smtpd\fR or \fBspawn-filter\fR never has to wait for
\fBqmail-cdb\fR to finish. However, \fBqmail-cdb\fR makes no attempt to
protect against two simultaneous updates of \fBfilename.cdb\fR.

The \fI\-m\fR option moves \fIfilename\fR to \fIfilename.bak\fR after a
successfull conversion to cdb.

The following control files can also be converted to cdb format using
\fBqmail-cdb\fR(8).

.IR authdomains ,
.IR badhelo ,
.IR badext ,
.IR badmailfrom ,
.IR badrcptto ,
.IR blackholedsender ,
.IR blackholedrcpt ,
.IR chkrcptdomains ,
.IR goodrcptto ,
.IR relaymailfrom ,
.IR spamignore ,
.IR greylist.white ,
.IR tlsa.white ,
.IR tlsadomains ,
.IR morercpthosts ,
.IR badip ,
and
.IR recipients .

.SH "SEE ALSO"
qmail-sql(8), cdb-database(8), qmail-smtpd(8), spawn-filter(8), setforward(1),
fastforward(1), qmail-multi(8), make-recipients(8), test-recipients(8)
