.\" vim: tw=75
.TH qmail-command 8

.SH NAME
qmail-command \- user-specified mail delivery program

.SH SYNOPSIS
in
.BR .qmail\fIext :
.B |\fIcommand

.SH DESCRIPTION
\fBqmail-local\fR will, upon your request, feed each incoming mail message
through a program of your choice.

When a mail message arrives, \fBqmail-local\fR runs \fBsh -c\fR
\fIcommand\fR in your home directory. It makes the message available on
\fRcommand\fI 's standard input.

\fBWARNING:\fR The mail message does not begin with \fBqmail-local\fR 's
usual \fBReturn-Path\fR and \fBDelivered-To\fR lines.

Note that \fBqmail-local\fR uses the same file descriptor for every
delivery in your \fB.qmail\fR file, so it is not safe for \fIcommand\fR
to fork a child that reads the message in the background while the parent exits.

.SH "EXIT CODES"
\fIcommand\fR 's exit codes are interpreted as follows: 0 means that the
delivery was successful; 99 means that the delivery was successful, but
that \fBqmail-local\fR should ignore all further delivery instructions; 100
means that the delivery failed permanently (hard error); 111 means that the
delivery failed but should be tried again in a little while (soft error).

Currently 64, 65, 70, 76, 77, 78, and 112 are considered hard errors, and
all other codes are considered soft errors, but \fIcommand\fR should avoid
relying on this.

.SH "ENVIRONMENT VARIABLES"
\fBqmail-local\fR supplies several useful environment variables to
\fRcommand\fR.

\fBWARNING:\fR These environment variables are not quoted. They may contain
special characters. They are under the control of a possibly malicious
remote user.

\fBSENDER\fR is the envelope sender address.
\fBNEWSENDER\fR is the forwarding envelope sender address,
as described in
\fBdot-qmail(5)\fR.
\fBRECIPIENT is the envelope recipient address, \fIlocal@domain\fR.
\fBUSER\fR is \fIuser\fR.
\fBHOME\fR is your home directory, \fIhomedir\fR.
\fBHOST\fR is the \fIdomain\fR part of the recipient address.
\fBLOCAL\fR is the \fIlocal\fR part.
\fBEXT\fR is the address extension, \fIext\fR.

\fBHOST2\fR is the portion of \fBHOST\fR preceding the last dot;
\fBHOST3\fR is the portion of \fBHOST\fR preceding the second-to-last dot;
\fBHOST4\fR is the portion of \fBHOST\fR preceding the third-to-last dot.

\fBEXT2\fR is the portion of \fBEXT\fR following the first dash;
\fBEXT3\fR is the portion following the second dash;
\fBEXT4\fR is the portion following the third dash.
\fBDEFAULT\fR is the portion corresponding to the \fBdefault\fR part of the
\fB.qmail\fR\- ...  file name; \fBDEFAULT\fR is not set if the file name
does not end with \fBdefault\fR.

\fBDTLINE\fR and \fBRPLINE\fR are the usual \fBDelivered-To and
\fBReturn-Path lines, including newlines. \fBUFLINE is the UUCP-style
\fBFrom_\fR line that \fBqmail-local\fR adds to \fImbox\fR -format files.

\fBQQEH\fR is the same QQEH that was set when \fBqmail-queue\fR
was invoked for this email.

.SH "SEE ALSO"
envelopes(5),
qmail-local(8)
ifaddr(1),
iftocc(1),
iftoccfrom(1)
bouncesaying(1),
condredirect(1),
condtomaildir(1),
dot-qmail(5),
dot-forward(1),
fastforward(1),
forward(1),
printforward(1),
setforward(1),
filterto(1),
except(1),
preline(1),
qnotify(1),
qreceipt(1),
replier(1),
filterit(1),
rrforward(1)
