.TH qmail-qmqpc 8
.SH NAME
qmail-qmqpc \- queue a mail message via QMQP
.SH SYNOPSIS
.B qmail-qmqpc
[
.I server
[...] ]
.SH DESCRIPTION
.B qmail-qmqpc
offers the same interface as
.BR qmail-queue ,
but it gives the message to a QMQP server
instead of storing it locally.

In a
.B mini-qmail
installation,
.B qmail-queue
is replaced with a symbolic link to
.BR qmail-qmqpc .

If one or more server IP addresses 
are specified on the command line,
.B qmail-qmqpc
will ignore the control files and instead use the QMQP servers specified on the
command line.

The default QMQP port 628 used by \fBqmail-qmqpc\fR can be overriden by
setting PORT_QMQP environment variable.
 
.SH "CONTROL FILES"
.TP 5
.I qmqpservers
IP addresses of QMQP servers, one address per line.
.B qmail-qmqpc
will try each address in turn until it establishes a QMQP connection
or runs out of addresses. If control file \fIqmqpservers\fR has the sticky bit set,
\fBqmail-qmqpc\fR will use the modulus of current
time in seconds and the number of servers in \fIqmqpservers\fR file to select just one
address. If this address fails, \fBqmail-qmqpc\fR will revert to the traditional method where
it tries each address till it establishes a QMQP connection. This allows one to distribute
the load across multiple QMQP servers.
.TP 5
.I timeoutconnect
Number of seconds
.B qmail-qmqpc
will wait for the remote QMQP server to accept a connection.
Default: 10.
The kernel normally imposes a 75-second upper limit.

.TP 5
.I timeoutremote
Number of seconds
.B qmail-qmqpc
will wait for each response (read or write) from the remote QMQP server.
Default: 60.

.TP 5
.I outgoingip
IP address to be used on outgoing connections.
Default: system-defined.
The value
.IR 0.0.0.0
is equivalent to the system default. The IP address can also be configured
by setting the environment variable \fBOUTGOINGIP\fR. \fBOUTGOINGIP\fR overrides the control
file \fIoutgoingip\fR. You can have multiple IP addresses one per line, one per line
for each IP. \fBqmail-remote\fR will use the modulus operator with the current time
to pick a single IP address.


.SH "SEE ALSO"
qmail-control(5),
qmail-queue(8),
qmail-qmqpd(8)
