.TH qmail-newmrh 8
.SH NAME
qmail-newmrh \- prepare morercpthosts for qmail-smtpd

.SH SYNOPSIS
.B qmail-newmrh

.SH DESCRIPTION
\fBqmail-newmrh\fR does a chdir to @controldir@ and reads the instructions in
.B @controldir@/morercpthosts
and writes them into
.B @controldir@/morercpthosts.cdb
in a binary format suited
for quick access by
.BR qmail-smtpd .

If there is a problem with
.BR @controldir@/morercpthosts ,
.B qmail-newmrh
complains and leaves
.B @controldir@/morercpthosts.cdb
alone.

.B qmail-newmrh
ensures that
.B @controldir@/morercpthosts.cdb
is updated atomically,
so
.B qmail-smtpd
never has to wait for
.B qmail-newmrh
to finish.
However,
.B qmail-newmrh
makes no attempt to protect against two simultaneous updates of
.BR @controldir@/morercpthosts.cdb .

The binary
.B @controldir@/morercpthosts.cdb
format is portable across machines.
.SH "SEE ALSO"
qmail-cdb(8),
qmail-smtpd(8)
