.TH qmaildirwatch 1
.SH NAME
qmaildirwatch \- look for new mail in a maildir
.SH SYNOPSIS
.B qmaildirwatch
.SH DESCRIPTION
.B qmaildirwatch
watches your
.I maildir
for new mail.
You must supply a
.B MAILDIR
environment variable
with the name of your
.I maildir
directory.

.B qmaildirwatch
prints a new mail summary twice per minute.
It is designed to run inside a (VT100-compatible) window;
it clears the window before each summary.
.SH "SEE ALSO"
maildir(5)
