.TH qmonitor 8
.SH NAME
qmonitor \- Monitor queue loads and increase it dynamically

.SH SYNOPSIS
\fBqmonitor\fR [-t \fIthreshold\fR [-i \fIinterval\fR] [-n]

.SH DESCRIPTION
\fBqmonitor\fR monitors the queue load when indimail-mta is running in IPC
mode (see qscheduler(8)). If it crosses the threshold defined by the
QUEUE_LOAD environment variable, it instruct qscheduler to increase the
queue count. The queue count will be increased if it is below the value of
the QUEUE_MAX environment variable.

.SH SEE ALSO
qscheduler(8),
setqload(8),
qtop(1),
multi-queue(8)


