.TH qreceipt 1
.SH NAME
qreceipt \- respond to delivery notice requests
.SH SYNOPSIS
in
.BR .qmail :
.B |qreceipt
.I youraddress
.SH DESCRIPTION
When a mail message arrives with 
.I youraddress
listed in a
.B Notice-Requested-Upon-Delivery-To
header field,
.B qreceipt
sends a success notice back to the envelope sender.

.B WARNING:
If you create a
.B .qmail
file to enable
.BR qreceipt ,
make sure to also add a line specifying delivery to your normal mailbox.
For example:

.EX
     /home/joe/Mailbox
.br
     |qreceipt joe@nowhere.mil
.EE

If running as non-root, \fBqreceipt\fR uses environment set according
to files in $HOME/.defaultqueue directory. You can skip $HOME/.defaultqueue
if \fBSKIP_LOCAL_ENVIRONMENT\fR is set. If \fBQUEUE_BASE\fR environment
variable is not set, it additionally uses environment set according to
files in @controldir@/defaultqueue directory (for any uid).

.SH "SEE ALSO"
uenv(1),
envdir(8),
envelopes(5)
ifaddr(1),
iftocc(1),
iftoccfrom(1)
bouncesaying(1),
condredirect(1),
condtomaildir(1),
dot-qmail(5),
dot-forward(1),
fastforward(1),
forward(1),
printforward(1),
setforward(1),
filterto(1),
except(1),
preline(1),
qmail-command(8),
qnotify(1),
replier(1),
rrforward(1)
