.TH qscanq 8
.SH NAME
qscanq \- qmail virus scanner
.SH SYNOPSIS
.B qscanq
[
.I prog
.I arg1
.I arg2
.IR arg3 ...
]

.SH DESCRIPTION
.B qscanq
replaces
\fBqmail-multi\fR / \fBqmail-queue\fR.  It initiates a scan on an incoming email,
and returns the exit status of the scanner or of \fBqmail-multi\fR / \fBqmail-queue\fR to the caller.

.B qscanq
needs no arguments. It may be called with optional arguments, which will then be treated as a
program to be called instead of
.BR qmail-multi .
The arguments will be passed on to
.BR qscanq-stdin ,
which actually calls
.B qmail-multi
or
.BR qmail-queue ,
if no arguments are given.

.B qscanq
runs setuid to the
.I qscand
user. When invoked, it changes to the spool directory and creates a working directory based on a
timestamp, the PID, and a counter, with the sticky bit set. It then changes to that directory and
invokes
.B qscanq-stdin.
The spool directory is defined during compile time by the file
.BR conf-scandir .
This can be overriden at run time by the environment variable
.BR SCANDIR.

After 
.B qscanq-stdin
returns, 
.B qscanq
unsets the sticky bit on its working directory, invokes
.B run-cleanq
and then returns the exit status of
.B qscanq-stdin
without waiting for
.B run-cleanq
to return.
.B qscanq
generates no output. The return codes are interpreted by the caller, which in
turn generates any user output.

.SH Environment Variables

.B qscanq
sets no environment variables. It does pass its environment to
.BR qscanq-stdin ,
which in turn passes them to 
.B qmail-multi
(or \fIprog\fR, if supplied instead). This means that any qmail-queue wrapper called by
.B qscanq
must be able to handle its environment safely.

If the DEBUG environment variable is set to any value whatsoever, then
.B qscanq
will print diagnostic messages to stderr whenever an error occurs. This is for use in debugging a
new configuration, and should never be used to capture "extra log information" during runtime.

The default scanner to be called is set during compilation in conf-scancmd. This can
be overriden at run time by the environment variable SCANCMD. See qscanq-stdin(8)

.SH Return Codes

.B qscanq
can return any code returned by
.BR qmail-queue .
In addition, it returns 71 (temporary refusal) if any runtime error occurs. The caller may also
receive exit status 31 from
.BR qscanq-stdin ,
which is called by
.BR qscanq .

.SH NOTES

In a default install, the
.B clamscan
configuration file will be found at @sysconfdir@/clamav.conf.
Edit the file and follow the contained instructions, making sure that the following entries are set
in their appropriate places:

 * LogFile stderr
 * StreamSaveToDisk
 * User Gqscanq
 * Foreground
 * FixStaleSocket

The FixStaleSocket setting is intended to address a problem with
.BR clamdscan :

if the daemon crashes,
it can leave a stale communications socket lying around. When launched, it detects this socket and
refuses to start. When this happens, email will be deferred because scanning will fail; if it is
not corrected in time, messages will start to bounce. The startup script supplied below also checks
for this condition.

Make sure you are running
.B freshclam
in order to get the latest virus definitions in a timely way.

It is recommended that
.B clamd
be run as a daemontools service. If clamav was installed in the default manner, there should be a
.I qscand
user. You should not proceed until that user exists. Stop right now and install qscanq, or
at least create the necessary users, and then come back to this step.

That should be it. This daemon will be running as qscand, and will be logging to
@logdir@/clamd.

.SH "SEE ALSO"
cleanq(8),
run-cleanq(8),
qscanq-stdin(8),
qmail-queue(8),
qmail-multi(8),
clamd(8),
clamav.conf(5),
clamdscan(1),
clamscan(1)
