.TH queue-fix 8
.SH NAME
queue-fix \- Create or Repair a qmail queue structure
.SH SYNOPSIS
\fBqueue-fix\fR [-\fBi\fR -\fBN\fR -\fBr\fR -\fBv\fR] [-s \fIsplit\fR] \fIqueue_dir\fR

.SH DESCRIPTION
\fBqueue-fix\fR is a small utility for checking and repairing the qmail queue
structure. It will fix uid/gid settings and permissions. It will rename the
message files to match their inodes. It will even create missing directories
and files. You can even create a queue from scratch). It will
also print warnings for any files it finds that should not exist.

\fBqueue-fix\fR(1) uses environment set according to files in
$HOME/.defaultqueue and @controldir@/defaultqueue if the environment
variable QUEUE_BASE is not set. This can be used for setting default value
of \fBCONFSPLIT\fR environment variable for your setup.

\fBqueue-fix\fR uses the uids \fIqmailq\fR, \fIqmailr\fR and \fIqmails\fR
to set permissions for various directories.

.SH OPTIONS
.TP
\fB\-i\fR
Interactive mode

.TP
\fB\-N\fR
Test mode. This option will report inconsistencies in the queue and 
not make any changes.

.TP
\fB\-s\fR \fIsplit\fR
specify the queue subdirectory split (default DIRSPLIT). You can also set
this by setting the environment variable \fBCONFSPLIT\fR. Any value above
DIRSPLIT is silently ignored.

.TP
\fB\-r\fR
create ratelimit subdirectory for rate controlled delivery. See
slowq-send(8)

.TP
\fB\-m\fR
Set permissions for qmta-send where qmta-send qill run as \fIqmailq\fR user.

.TP
\fB\-v\fR
Verbose mode

.TP
\fIqueue_dir\fR
Directory where the qmail queue stucture is created. This directory has the subdirectories
bounce, info, intd, local, lock, mess, pid, remote, todo, trash, ratelimit.

.SH "SEE ALSO"
qmail-rm(1), svctool(8), qmail-queue(8), qmail-multi(8), slowq-send(8)

.SH Original AUTHOR
Eric Huss
