.TH replier 1
.SH NAME
replier - In dot-qmail, run a program to reply to an address

.SH SYNOPSIS
in
.BR .qmail :

.B |replier
.I dir
.I address
.I program
[
.I arg ...
]

where 
.I dir
is a directory, 
.I address
is an email address, and
.I program
is one or more arguments
specifying a program to run.

For each email message it processes,
.B replier
changes the working directory to
.IR dir ,
executes
.I program
with the same message on standard input, and forwards the standard output from
.I program
to
.IR address .

.B replier
adds a Mailing-List field to the message headers with the contents of 
\fBdir/mailinglist\fR.
It rejects the message if there is already a Mailing-List field.

.B replier
adds to the message all fields listed in 
\fBdir/headeradd\fR,
followed by an appropriate Delivered-To line.
.B replier
deletes from the message any fields with names listed in
\fBdir/headerremove\fR.
.B replier
performs its header editing on the output from
\fIprogram\fR.

If
.I program
exits 0, then
.B replier
forwards the message to 
.I address
and exits 99, so that further commands in 
.B .qmail
are ignored. If
.I program
exits 111,
.B replier
exits 111, so that delivery is retried later. If
.I program
exits anything else, or does not exist,
.B replier
exits 0, so the rest of .qmail is processed. If it encounters a permanent error in handling a
message,
.B replier
exits 100. If it encounters a temporary error a message,
.B replier
exits 111.
.B replier
does not distribute bounce messages: if the environment variable $SENDER is set, and is either
empty or #@[], then
.B replier
rejects the message.

To create a replier that handles email sent to an address, use
.BR replier-config .

.SH "Environment variables"
.B replier
supplies several environment variables to
.IR program .
The recipient address that caused message processing by
.B replier
has one of two forms:
inlocal-request@domain, where inlocal matches the first line of
.BR dir/inlocal ,
or request@domain, when
.B dir/inlocal
has an empty first line. In either case,
.B replier
sets the following environment variables:


$REQUEST is request in the recipient address.

$REQUEST2 is the portion of request in the recipient address that follows the first hyphen.

$REQUEST3 is the portion of request in the recipient address that follows the second hyphen.

$REQUEST4 is the portion of request in the recipient address that follows the third hyphen. 

NB: These environment variables are not quoted. They are under the control of the sender.

If running as non-root, \fBreplier\fR uses environment set according
to files in $HOME/.defaultqueue directory. If QUEUE_BASE environment
variable is not set, it additionally uses environment set according to
files in @controldir@/defaultqueue directory (for any uid).

.SH "SEE ALSO"
bouncesaying(1),
condredirect(1),
filterto(1),
except(1),
dot-qmail(5),
qmail-command(8),
qmail-queue(8)
