.TH rrforward 1
.SH NAME
rrforward \- round-robin message delivery
.SH SYNOPSIS
in
.BR .qmail :
.B |rrforward
.I .qmailrr[-extension]
.I address ...

.SH DESCRIPTION
.B rrforward
forwards each message to one address choosed from specified list of addresses.
When local address extension part match
.IR extension ,
it read a sequence number from the
.I .qmailrr-extension
file.
Then
.B rrforward
forwards message to the next
.I address
in sequence and update the sequence number in
.I .qmailrr-extension
file.
If
.I extension
is empty, sequence number
is read from
.I .qmailrr
file.

If running as non-root, \fBrrforward\fR uses environment set according
to files in $HOME/.defaultqueue directory. You can skip $HOME/.defaultqueue
if \fBSKIP_LOCAL_ENVIRONMENT\fR is set. If \fBQUEUE_BASE\fR environment
variable is not set, it additionally uses environment set according to
files in @controldir@/defaultqueue directory (for any uid).

.SH "EXIT CODES"
0 if local address part does not match
.IR extension ;
99 if the delivery is completely successful;
nonzero if any delivery instruction failed.
Exit code 111 indicates temporary failure.

.SH "SEE ALSO"
ifaddr(1),
iftocc(1),
iftoccfrom(1)
bouncesaying(1),
condredirect(1),
condtomaildir(1),
dot-qmail(5),
dot-forward(1),
fastforward(1),
forward(1),
printforward(1),
setforward(1),
filterto(1),
except(1),
preline(1),
qmail-command(8),
qnotify(1),
qreceipt(1),
replier(1),
qmail-queue(8)
