.TH run-cleanq 8
.SH NAME
run-cleanq \- request cleanq to be run
.SH SYNOPSIS
.B run-cleanq

.SH DESCRIPTION
.B run-cleanq
runs with group
.I qscand
privilege to request that the
.B cleanq
process be run once, to clean temporary files used in scanning an email for viruses. It does this
by invoking the following daemontools  command:

@prefix@/bin/svc -o @servicedir@/qscanq

Any user can invoke
.BR run-cleanq ,
which takes no arguments, ignores its environment and any file descriptors. Multiple invocations
are ignored by the supervise process while
.B cleanq
is running. By default, each invocation of
.B cleanq
pauses for 10 seconds, so nothing interesting is to be gained by a local attacker trying to invoke
.B run-cleanq
repeatedly or rapidly.

.SH "SEE ALSO"
qscanq(8),
qscanq-stdin(8),
cleanq(8)
