.TH slowq-start 8

.SH NAME
slowq-start \- turn on mail delivery

.SH SYNOPSIS
.B slowq-start
[
.I defaultdelivery
[
.I logger arg ...
]
]

.SH DESCRIPTION
.B slowq-start
invokes
.BR qmail-send ,
.BR qmail-todo ,
.BR qmail-lspawn ,
.BR qmail-rspawn ,
and
.BR qmail-clean ,
under the proper uids and gids for a queue defined by the environment
variable \fBQUEUEDIR\fR. These five daemons cooperate to deliver messages
from the queue. The uids and gids are obtained from the passwd(5) database
using standard glibc getpwent(3), getgrent(3) calls which are inherently
unreliable. You can switch to internal qgetpwent(3), qgetgrent(3) funtions
by setting the environment variable \fBUSE_QPWGR\fR.

\fBslowq-start\fR borrows most of it's code from \fBqmail-start\fR.

.B slowq-start
arranges for
.BR slowq-send 's
activity record to be sent to
.BR slowq-start 's
output. See
.B qmail-log(5)
for the format of the activity record.
Other than this,
.B slowq-start
does not print anything, even on failure.

If
.I defaultdelivery
is supplied,
.B slowq-start
passes it to
.BR qmail-lspawn .

The default indimail installation, creates a supervised service in
@servicedir@/slowq. The output goes to @logdir@/slowq/current. The default
mailbox type is picked up from the \fBdefaultdelivery\fR control file. The
table below outlines the choices for \fBdefaultdelivery\fR control file

.TS
l l.
Mailbox | Name  | Location       | defaultdelivery | Comments
Format  |       |                |                 |
_

mbox    |Mailbox | $HOME         | ./Mailbox       | most common, works with 
        |        |               |                 | most MUA's
_
maildir |Maildir | $HOME         | ./Maildir/      | more reliable, less
        |        |               |                 | MUA support
_
mbox    |username|/var/spool/mail| See INSTALL.vsm | traditional mailbox
_

.TE


If
.I logger
is supplied,
.B slowq-start
invokes
.I logger
with the given arguments, and feeds
.BR slowq-send 's
activity record through
.IR logger .

Environment variables given to
.B slowq-start
will eventually be passed on to
.BR qmail-local ,
so make sure to clean up the environment if you run
.B slowq-start
manually:

.EX
   # env - PATH="PREFIX/sbin:$PATH"
.br
   slowq-start ./Mailbox splogger qmail &
.br
   (all on one line)
.EE

Resource limits, controlling ttys, et al. are also passed from
.B slowq-start
to
.BR qmail-local .

Note that
.B slowq-send
normally juggles several simultaneous deliveries. To reduce
.BR slowq-send 's
impact on other programs, you can run
.B slowq-start
with a low priority.

.SH Supplementary Groups
If you set the environment variable \fBUSE_SETGROUPS\fR, \fBqmail-start\fR
can set supplementary groups (if defined in /etc/group) for qmail-send
(for qmails user), qmail-rspawn (for qmailr user), qmail-clean (qmailq user)
and any logger specified on command line (qmaill user). See group(5) to
learn how to set supplementary groups.

.SH "SEE ALSO"
logger(1),
splogger(1),
nice(1),
qmail-log(5),
qmail-local(8),
qmail-clean(8),
qmail-lspawn(8),
qmail-rspawn(8),
qmail-start(8),
qmail-send(8),
slowq-send(8),
qmail-todo(8),
qmail-multi(8),
initsvc(1),
svscan(8),
supervise(8),
getpwent(3),
getgrent(3),
qgetpwent(3),
qgetgrent(3),
passwd(5),
group(5),
IndiMail(7)
