.\" vim: tw=75
.TH spfquery 1
.SH NAME
spfquery - SPF query tool

.SH SYNOPSIS
spfquery
.I sender-ip 
.I sender-helo/ehlo
.I envelope-from
[
.I local_rules
.I guess_rules
.I spfexp
]

.SH DESCRIPTION
\fBspfquery\fR is a tool that can be used for checking if a \fIsender-ip\fR
is authorized to send emails for the domain in \fIenvelope-from\fR.

.SH OPTIONS
.TP 3
\fIsender-ip\fR
The IP address to verify if it is authorized to send emails for domain
specfied in \fIenvelope-from\fR.

.TP 3
\fIsender-helo\fR
Substitute the domain used in the most recent SMTP HELO or EHLO with
\fIsender-helo\fR in case there is a SPF expansion

.TP 3
\fIenvelope-from\fR
Use domain from \fIenvelope_from\fR

.TP 3
\fIlocal_rules\fR
Rules that are executed before the real SPF rules for a domain would fail
(fail, softfail, neutral). This can be used to always allow certain
machines to send certain mails.

.TP 3
\fIguess_rules\fR
SPF rules that will be checked if a sender domain doesn't have a SPF
record. The local spfrules are always executed afterwards.

.TP 3
\fIspfexp\fR
Use spfexp as explanation in case of a reject

.SH "EXIT STATUS"
\fBspfquery\fR exits with a code depicting success or failure as below.

.EX
0  - SPF_OK       IP is authorized to send email for the domain
1  - SPF_NONE     No SPF records found for the domain
2  - SPF_UNKNOWN  Unknown SPF failure
3  - SPF_NEUTRAL  happens when the domain owner doesn’t want to assert
                  that the sending IP addresses are authorized.
4  - SPF_SOFTFAIL The sender is either authorized or not authorized to
                  send email from the domain.
5  - SPF Failure  sending IP address is NOT authorized to send from the
                  domain.
6  - SPF_ERROR    Temporary error in getting SPF records from DNS
7  - SPF_NOMEM    Out of memory failure
.EE

.SH "SEE ALSO"
qmail-smtpd(8)
