.TH srsfilter 1

.SH NAME
srsfilter - in dot-qmail filter messages using SRS

.SH SYNOPSIS
in
.BR .qmail-srs-default :

.B |/bin/srsfilter

.SH DESCRIPTION
For each email message it processes, \fBsrsfilter\fR validates the address
in sender before sending it to a mail delivery agent like qmail-inject(8),
sendmail(1). \fBsrsfilter\fR uses Sender Rewriting Scheme (SRS) to reject
(or filter) any incoming bounce messages which are not legitimate
responses. The criteria is simply: any incoming messages with an empty
envelope sender which go to my main email address must be spam. Real
bounces will go to an SRS address instead, and will then be forwarded to a
real address. \fBsrsfilter\fR rewrites To header with the SRS decoded
address. It only accepts messages from null-sender, Return-Path:<>. It also
rejects messages without body.

.SH "SEE ALSO"
srs(1), qmail-inject(8), sendmail(1), qmail-srs(5),
