.\" vim: tw=75
.TH test-recipients 8
.SH NAME
test-recipients \- Test Recipients in MySQL or via RECIPIENTS extension.

.SH SYNOPSIS
.B test-recipients
\-\fBr\fR
|
\-\fBs\fR
[
\-\fBt\fR
\fItimeout\fR
]
.I addr

.SH DESCRIPTION
\fBtest-recipients\fR(1) tests recipients by checking it in in indimail's
MySQL database or by using the recipients extension. The recipients
extension in indimail-mta is an adaptation of the recipients extension
from s/qmail at https://www.fehcom.de/sqmail/sqmail.html.

The \-\fBr\fR option makes \fBtest-recipients\fR do chdir to
\fI@sysconfdir@\fR directory. It then opens the control/recipients. If
there are any rules to open a cdb database in the \fIrecipients\fI control
file, it will be opened relative to the current working directory of
\fBqmail-cdb\fR which will be \fIsysconfdir\fR. You can override
\fI@sysconfdir@\fR by setting \fBSYSCONFDIR\fR environment variable and
override \fI@controldir@\fR by setting \fBCONTROLDIR\fR environment
variable.

The \-\fBs\fR option makes \fBtest-recipients\fR loads the indimail.so
shared library. This enables submittig query to \fBinlookup\fR(8) daemon
using the \fBinquery\fR(3) function. The default timeout used to get result
from \fBinlookup\fR(8) daemon is 60 seconds and can be changed by
specifying the \-\fBt\fR \fItimeout\fR argument. Note that to submit query
to \fBinlookup\fR daemon, you will require access to
\fIrun/indimail/inlookup\fR directory owned by \fBindimail:qmail\fR with
\fB0770\fR permissions. You will also require write access to FIFOs in this
directory owned by \fBqmaild:indimail\fR with \fB0660\fR permissions.

\fBqmail-smtpd\fR(8) checks recipients in RCPT TO dialog when the
environment variable \fBCHECKRECIPIENT\fR is set and rejects email when the
recipient is missing. Rejecting emails during SMTP session enables
rejecting emails immediately rather than accepting it and bouncing it
later.

\fBtest-recipient\fR(1) is located in @libexecdir@ directory.

.SH NOTES

The inlookup daemon creates named pipes that can be accessed by
\fBqmaild\fR user. To test users in MySQL it is neccessary to execute it
with the privileges of the user \fBqmaild\fR

In \fIrun/indiail/inlookup\fR, \fIrun\fR refers to \fI/run\fR or
\fI/var/run\fR depending on the OS.

.EX
$ sudo bash
# setuidgid -g qmail qmaild test-recipients -s testuser01@example.com
# setuidgid -g indimail indimail env FIFO_MODE=0666 \\
  test-recipients -s testuser01@example.com
.EE

.SH "SEE ALSO"
qmail-smtpd(8),
inlookup(8),
inquery(3),
qmail-cdb(8),
make-recipients(1)
