.TH docker-entrypoint 8
.SH NAME
docker-entrypoint \- entry point for indimail docker/podman images

.SH SYNOPSYS
.B docker-entrypoint
[
.I options
]

.SH DESCRIPTION
docker-entrypoint(8) is the entrypoint for indimail, indimail-mta runtime
docker(1) / podman(1) images. It gets automatically invoked when you start
a docker/podman image. Depending on the image (indimail-mta, indimail or
indimail image with Roundcube Mail), it is passed specific options on the
command line. Normally, it is not meant to be executed by the user, but you
can pass options and other arguments as part of the \fIcommand\fR argument
to podman(1) / docker(1) command.

By default the entrypoint will execute \fBsvscan\fR(8). You can bypass this
behaviour by passing a program of your choice. This may be required if you
want to do some maintenance modification of the image. Options passed to
entrypoint are actually program/options to be executed in the container and
is passed by the podman(1) or docker(1) command. Few program names passed
have special meaning. If you want to execute a program with command line
arguments, separate them with two hypens i.e. \fB--\fR.

The below command will run ls -l /tmp in the container and delete the
container after execution.

.EX
podman run -ti --rm e716bf178990 -- ls -l /tmp
.EE

docker-entrypoint(8) uses the hostname to reconfigures qmail control files.
This can be set by passing the -h argument to podman(1) / docker(1). The
hostname set by podman(1) or docker(1) can be overriden by the -d argument.
The command 

.EX
\fBsvctool\fR --default-domain=\fIdomain\fR --config=recontrol
.EE

is used to reset control files for domain \fIdomain\fR. The below command
will run the container with domain as indimail.org.

.EX
podman run -d e716bf178990 -d indimail.org
.EE

The below will run an emergency shell
.EX
podman run -ti --rm e716bf178990 -r
.EE

.SH OPTIONS
.TP
\fBindimail\fR or \fBindimail-mta\fR or \fBsvscan\fR
.lf
Start svscan(1) in @servicedir@ directory and create a link /etc/mnttab to
/proc/mounts.

.TP
.B webmail
Start svscan(1) in @servicedir@ directory and create a link /etc/mnttab
to /proc/mounts. ALso starts the httpd and php-fpm service.

.TP
-r or --repair
Drop to shell prompt. This doesn't start svscan(1) command, allowing you to
execute maintenance, repairs without starting the indimail/indimail-mta
services.

.TP
-d \fIdomain\fR or --domain \fIdomain\fR
By default the hostname argument passed to podman or docker command is used
as the domain name. This option overrides that value.

.SH "SEE ALSO"
docker(1), podman(1), svscan(8), svstat(8), svc(8), supervise(8),
runpod(1)
