.TH envdir 8
.SH NAME
envdir \- runs another program with environment modified according to files
in a specified directory.

.SH SYNOPSIS
\fBenvdir\fR [ -c ] \fId\fR \fIchild\fR

.SH DESCRIPTION
\fId\fR is a single argument. \fIchild\fR consists of one or more
arguments. If you pass the -\fBc\fR argument, all existing environment is
cleared before modifying any environment variables.

\fBenvdir\fR sets various environment variables as specified by files in
the directory named \fId\fR. It then runs \fIchild\R.

If \fId\fR contains a file named \fIs\fR whose first line is \fIt\fR,
\fBenvdir\fR removes an environment variable named \fIs\fR if one exists,
and then adds an environment variable named \fIs\fR with value \fIt\fR. The
name \fIs\fR must not contain =. Spaces and tabs at the end of \fIt\fR are
removed. Nulls in \fIt\fR are changed to newlines in the environment
variable. 

If the file \fIs\fR is completely empty (0 bytes long), \fBenvdir\fR
removes an environment variable named \fIs\fR if one exists, without adding
a new variable.

If \fBenvdir\fR finds a link named .\fIdir\fR pointing to a directory, or a
directory named .\fIdir\fR, it enters that directory and modifies
environment variables according to files in .\fIdir\fR. \fBenvdir\fR avoids
infinite recursive loops, by storing the inode number of directories
visited and checking against the list. Files in .\fIdir\fR are read first
to prevent. This prevents .\fIdir\fR from overrideing or deleting
environment variables set in \fId\fR. Apart from .\fIdir\fR, \fBenvdir\fR
skips all files/directories starting with the '.' dot character.

.SH EXIT CODES
\fBenvdir\fR exits 111 if it has trouble reading \fId\fR, if it runs out of
memory for environment variables, or if it cannot run \fIchild\fR.
Otherwise its exit code is the same as that of \fIchild\fR.

.SH SEE ALSO
supervise(8),
svc(8),
svok(8),
svstat(8),
svscanboot(8),
svscan(8),
readproctitle(8),
fghack(8),
pgrphack(8),
multilog(8),
tai64n(8),
tai64nlocal(8),
setuidgid(8),
envuidgid(8),
softlimit(8),
setlock(8)
