.TH logselect 8
.SH NAME
\fBlogselect\fR - select parts of logs created by \fBmultilog\fR(8)

.SH SYNOPSYS
under \fBtcpserver\fR xargs -e EOF logselect

.SH DESCRIPTION
To use \fBlogselect\fR you can create a service whose run file looks like this:
 #!/bin/sh
 QMAILDUID=`id -u qmaill`
 NOFILESGID=`id -g qmaill`
 exec softlimit -m 2000000 \
 tcpserver -p -x cdb -u QMAILDUID -g $NOFILESGID 0 642 \\
   /usr/bin/xargs -e EOF @prefix@/bin/logselect
.PP
In addition, the service directory should have symlinks pointing to
the log files you wish to make accessible.

Then, to fetch logs, you make a connection to port 642, and stuff four
lines down the TCP connection.  The first line contains the name of
the symlink you created. The second contains a TAI64N for the start
of the period of interest. The third contains a TAI64N for the stop
of the period of interest. The fourth contains the literal string
"EOF".  All lines in the log file after the start but before the stop
will be returned.

.SH SEE ALSO
tcpserver(1), qlogselect(1), multilog(8)
