.TH minisvc 8
.SH NAME
minisvc \- daemontools mini Service Configuration Tool

.SH SYNOPSYS
.B minisvc
[
.I options
]

.SH DESCRIPTION

\fBminisvc\fR is a shell frontend for configuring supervise(8) services
under svscan(8). For every service created, it also creates a supervised
log service, that uses multilog(8), in @logdir@ direcotry. You can install
\fBsvscan(8)\fR to be started by the system using the command

.EX
\fBminisvc --config=add-boot\fR.
.EE

Similarly, you can remove \fBsvscan(8)\fR from startup by using the command

.EX
\fBminisvc --config=rm-boot\fR.
.EE

\fBminisvc\fR offers tiny subset of indimail-mta's svctool(8) config tool features.

\fBsvctool\fR can be used to dump the entire configuration of indimail
on stdout

.EX
minisvc --servicedir=@servicedir@ --dumpconfig --cntrldir=@sysconfdir@/control
.EE

\fBminisvc\fR requires root privilege to run.

.SH Services & Environment variables

\fBsvctool\fR primary function is for creating supervised services in
@servicedir@. You can change the location of the service directory by
specifying \fB--servicedir\fR option.

When you create any service, \fBsvctool\fR stores the entire command line
invocation wth arguments in @servicedir@/\fIname\fR/variables/.options.
This allows svctool to recreate entire configuration for a service when
you use the --refreshsvc option. Using envdir(8), supervise(8) services can
be run with set of environment variables or a set of variables removed from
the environment. The environment variables are those needed by applications
run by supervise(8). These environment variables are stored as files in
@servicedir@/\fIname\fR/variables directory. \fBsvctool\fR can store all
environment variables set for a service
in @servicedir@/\fIname\fR/variables/.variables. This file can be created
by running the command

.EX
svctool --servicedir=@servicedir@ --save-variables --force
.EE

Once you have saved all environment variables as key=value lines in a file,
\fBsvctool\fR can restore all environment variables to original state by
running the command

.EX
svctool --servicedir=@servicedir@ --restore-all-variables --force
.EE

\fIname\fR refers to a supervised service name. See svscan(8), supervise(8).

.SH OPTIONS

.EX
Usage: minisvc [OPTION]

Known values for OPTION are:

--svscanlog --servicedir=service_path [--initcmd=cmmd --scanint=n --resolvconf]

  service_path - Path where supervise service will be installed
  cmmd         - Program/Script to run instead of .svscan/run
  n            - Scan interval for svscan command
  --resolvconf - mount /etc/indimail/resolv.conf as /etc/resolv.conf
                 Use if you have dnscache installed in $servicedir/dnscache

--unshare
  Use unshare to mount private /etc/resolv.conf for using local dns

--down
  Create supervisor services in down state

--rmsvc=service_name

  Disable supervise scripts for service
  service_name   - name of service with full path
                   e.g. (@servicedir@/qmail-smtpd.25)
                   (give multiple services enclosed in double quotes)
                   "@servicedir@/qmail-smtpd.25 @servicedir@/qmail-imapd.143"

--ensvc=service_name

  Enable supervise scripts for service
  service_name   - name of service with full path
                   e.g. (@servicedir@/qmail-smtpd.25)
                   (give multiple services enclosed in double quotes)
                   "@servicedir@/qmail-smtpd.25 @servicedir@/qmail-imapd.143"

--refreshsvc=service_name
  [--run-file-only] [--force]

  Enable supervise scripts for service
  service_name   - name of service with full path
                   e.g. (@servicedir@/qmail-smtpd.25)
                   (give multiple services enclosed in double quotes)
                   "@servicedir@/qmail-smtpd.25 @servicedir@/qmail-imapd.143"
                   service_name can be "all" to act on all services
  run-file-only  - Recreate run files but not variables
  force          - Recreate service even if it has norefreshsvc flag
  NOTE: if the file .norefreshsvc is present in the variable or the config
  directory, refresh is skipped

--autorefresh="0|1 service_name"

  Disable/Enable auto refresh of supervise scripts for service
  0              - Disable autorefresh (create .norefreshsvc in variables directory)
  1              - Enable  autorefresh (delete .norefreshsvc in variables directory)
  service_name   - name of service with full path
                   e.g. (@servicedir@/qmail-smtpd.25)
                   service_name can be "all" to act on all services

--config=add-boot|rm-boot|users|rmusers

  add-boot       - Add startup scripts for IndiMail to get started during boot
  rm-boot        - Remove Startup scripts to prevent IndiMail to get started after boot
  users          - Create Internal System Users needed by svscan
  rmusers        - Delete Internal System Users needed by svscan

--set-variable=n --variable-value=v
  --servicedir=service_path
  --service-name=service_name
  [--force]

  Set a new variable for a supervise service
  n              - variable name
  v              - variable value
  service_path   - Path where supervise service will be installed
  service_name   - Service name
  force          - Overwrite variable if it exists

--modify-variable=n --variable-value=v
  --servicedir=service_path
  --service-name=service_name
  [--force]

  Modify an existing variable for a supervise service
  n              - variable name
  v              - variable value
  service_path   - Path where supervise service will be installed
  service_name   - Service name
  force          - Set the variable even if does not exist

--unset-variable=n
  --servicedir=service_path
  --service-name=service_name

  Unset any existing environment variable named 'n'
  n              - variable name
  service_name   - Service name

--remove-variable=n
  --servicedir=service_path
  --service-name=service_name

  Remove an existing variable for a supervise service
  n              - variable name
  service_path   - Path where supervise service will be installed
  service_name   - Service name

--restore-variables
  --servicedir=service_path
  --service-name=service_name

  Clean and Restore all variables to original state from
  servicedir/service_name/variables/.variables file
  service_path   - Path where supervise service will be installed
  service_name   - name of supervise service without path
                   e.g. (qmail-smtpd.25)

--import-variables=file
  --servicedir=service_path
  --service-name=service_name
  [--force]

  Import new environment variables from a file having one more multiple
  key=value pairs
  file           - File from which to import key=value environment variables
  service_path   - Path where supervise service will be installed
  service_name   - name of supervise service without path
                   e.g. (qmail-smtpd.25)
  force          - Set the variable if variable already exists

--export-variables=file
  --servicedir=service_path
  --service-name=service_name
  [--force]

  Export existing environment variables to a file
  file           - File in which to save key=value environment variables
  service_path   - Path where supervise service will be installed
  service_name   - name of supervise service without path
                   e.g. (qmail-smtpd.25)
  force          - overwrite service_path/service_name/variables/.variables

--save-variables
  --servicedir=service_path

  Export variables for all service in @servicedir@ and
  @qsysconfdir@/control/defaultqueue
  service_path   - Path where supervise service will be installed

--restore-all-variables
  --servicedir=service_path

  Restore all variables to orignal state for all service in
  @servicedir@ and @qsysconfdir@/control/defaultqueue
  service_path   - Path where supervise service will be installed

--print-variables
  --servicedir=service_path
  --service-name=service_name

  Print environment variables for a service
  service_path   - Path where supervise service will be installed
  service_name   - name of supervise service without path
                   e.g. (qmail-smtpd.25)

--print-all-variables
  --servicedir=service_path

  Print environment variables all services
  service_path   - Path where supervise service will be installed

--dumpconfig --servicedir=service_path --cntrldir=cntrl_path

  Dumps all service configuration for Supervise Scripts, control files and software information
  service_path - Path where supervise service will be installed
  cntrl_path   - Path where Qmail control files are stored

--help

  display this help and exit

--version

  output version information
.EE

.SH RETURN VALUE
\fBsvctool\fR returns non-zero status on error.

.SH "SEE ALSO"
IndiMail(7), initsvc(1), svscan(8), svstat(8), svc(8), supervise(8), multilog(8)
