.TH multipipe 1
.SH NAME
multipipe \- supervise a pipeline of commands
.SH SYNOPSIS
\fBmultipipe\fR [ \fIdirectory\fR ]

.SH DESCRIPTION
\fBmultipipe\fR starts one supervise process for each subdirectory of the
current directory. \fBmultipipe\fR skips subdirectory names starting with
dots.  Each supervised processes is piped a copy of standard input sent to
\fBmultipipe\fR.

.P
Every five seconds, \fBmultipipe\fR checks for subdirectories again. If it
sees a new subdirectory, it starts a new supervise process. If a
subdirectory is removed, it closes the pipe to that supervise process.
Directory named \fIsupervise\fR or with names starting with a period are ignored.

.P
If
\fBmultipipe\fR is given a command-line argument, it switches to that
directory when it starts.

.P
If \fBmultipipe\fR is sent either the \fBINT\fR, \fBQUIT\fR, or the
\fBTERM\fR signal, or it reaches end of file on standard input, it runs
\fBsvc -dx\fR on each command to shut it down, and waits for it to exit.

.SH RETURN VALUE
Exits 0 when all the commands are shut down.

.SH SEE ALSO
supervise, svscan
