.TH qlogselect 1
.SH NAME
qlogselect \- selectively copy entries from a qmail log file
.SH SYNOPSIS
.B qlogselect
.I [from PATTERN]
.I [start TIME]
.I [end TIME]
.I [stripstatus]
.I [addstatus]
.SH DESCRIPTION
This program selectively copies entries from a qmail log file on
standard input to standard output.

All times must be expressed either as year-month-day,
or as the number of seconds since the Unix epoch (January 1, 1970).
.SH OPTIONS
.TP
.I from PATTERN
Only output messages that have a envelope sender address that matches
.IR PATTERN .
.TP
.I start TIME
Only output lines that are stamped with a time that is on or after the
named time.
.TP
.I end TIME
Only output lines that are stamped with a time that is before the
named time.
.TP
.I stripstatus
Strip all the status lines from the input.
.TP
.I addstatus
Recalculate and insert status lines.
.SH EXAMPLES
To show all the messages sent from the mailing list owner at
vger.rutgers.edu:

.EX
qlogselect from owner-.*-outgoing@vger.rutgers.edu
.EE
.SH SEE ALSO
logselect(1),
qmail(7),
splogger(8)
