.\" vim: tw=75
.TH runpod 1
.SH NAME
runpod \- Run indimail podman / docker image using podman / docker

.SH SYNOPSIS
\fBrunpod\fR [\fIOPTIONS\fR] \fIprog\fR \fIarg\fR \fIarg\fR ...

.SH DESCRIPTION
\fBrunpod\fR is a frontend for \fBpodman\fR(1) / \fBdocker\fR(1) to help
execute indimail containers. indimail containers can be downloaded from

.nf
https://hub.docker.com/u/cprogrammer
or
https://github.com/mbhangui?tab=packages
.fi

\fIprog\fR is usually the binary to be executed on startup. \fIprog\fR also
can have a special meaning. if \fIprog\fR is indimail, indimail-mta,
svscan, webmail, runpod will let \fBdocker-entrypoint\fR(8) execute
\fBsvscan\fR(8) in the container. This will start an services configured in
the \fB/service\fR directory of the container image. If you don't want
this, you can set \fBname\fR to execute something else instead of
\fBsvscan\fR. If \fIname\fR is \fBtest\fR or \fBdevel\fR, bash will be
executed with a controlling terminal and also remove the container on exit.
If \fIname\fR is \fBsvscan\fR, bash will be executed with a controlling
terminal, but the container will not be removed on exit. If \fIprog\fR is
\fBauto\fR, systemd will be loaded for debian, ubuntu, fedora, centos,
almalinux, oraclelinux, opensuse images. For alpine linux bash will be
loaded with a controlling terminal. If systemd is empty, the default entry
point for the container will be used. If \fIprog\fR is set as auto, then
\fBrunpod\fR will instruct podman or docker to execute \fBsystemd\fR(1) if
the image supports systemd or execute /sbin/init for alpine and gentoo
images.

If you need to pass any command line switches to \fBprog\fR, use \-\- to
prevent the options getting passed to \fBrunpod\fR instead of \fBprog\fR.

e.g. The below passes the timezone parameter to indimail's
\fBdocker-entrypoint\fR(8).

.EX
runpod --id=2a13c928f3aa --name=svscan \-\- -t UTC
.EE

.SH OPTIONS
.TP 2
\fB\-\-id\fR=\fIimageID\fR | -i \fIimageID\fR
Use this option to specify image id

.TP
\fB\-\-name\fR=\fIname\fR | -\fBn\fR \fIname\fR
Use this option to specify name for the running image. \fIname\fR has
special significance if name is either of \fBindimail\fR,
\fBindimail-mta\fR, \fBwebmail\fR which causes following ports to be mapped

.EX
2025 -> 25, 2106 -> 106, 2110 -> 110  2143 -> 143, 2209 -> 209,
2366 -> 366, 2465 -> 465, 2587 -> 587 2628 -> 628, 2993 -> 993,
2995 -> 995, 3110 -> 4110 3143 -> 4143, 5110 -> 9110, 5143 -> 9143,
8080 -> 80
.EE

\fIname\fR is what you see in the \fBpodman\fR ps or the \fBdocker\fR ps
command.

.TP
\fB\-\-args\fR=\fIextra_args\fR | -\fBa\fR \fIextra_args\fR
Pass extra arguments to podman or docker command. You need use this for
every extra arg that you need to supply to the podman or docker command.

.TP
\fB\-\-capability\fR=\fIcap\fR | -\fBC\fR \fIcap\fR
Use this option to add capabilities like SYS_PTRACE, SYS_ADMIN, IPC_LOCK,
SYS_RESOURCE. You can specify this option multiple times.

.TP
\fB\-\-host\fR=\fIhost\fR | -\fBh\fR \fIhost\fR
Specify hostname for the container.

.TP
\fB\-\-port\fR=\fIlport\fR:\fIrport\fR -\fBp\fR \fIlport\fR:\fIrport\fR
Map local port \fIlport\fR to remote port \fIrport\fR in the container. You
can specify this option multiple times.

.TP
\fB\-\-command\fR=\fIdocker\fR|\fIpodman\fR | -\fBc\fR \fIdocker\fR|\fIpodman\fR
Use \fBdocker\fR(1) or \fBpodman\fR(1) to run the container. Default is
\fBpodman\fR(1).

.TP
\fB\-\-volume\fR=\fIlocal_dir\fR:\fIremote_dir\fR | \fB\-v\fR
\fIlocal_dir\fR:\fIremote_dir\fR mount \fIlocal_dir\fR as \fIremote_dir\fR
in the container. You can specify this option multiple times.

.TP
\fB\-\-cgroup\fR=\fIgroup\fR | -\fBg\fR \fIgroup\fR
Specify \fIgroup\fR for cgroups. You can specify this option multiple
times.

.SH SEE ALSO
docker(1),
podman(1)
