.\" vim: tw=75
.TH supervise 8

.SH NAME
supervise \- start and monitor a service.

.SH SYNOPSIS
\fBsupervise\fR \fIdir\fR [\fIparent_ident\fR]

.SH DESCRIPTION
\fBsupervise\fR(8) switches to the directory named \fIdir\fR. It checks for
the file \fIdown\fR. If this file exists, \fBsupervise\fR doesn't start the
service. If the directory \fIrun/svscan\fR exists, \fBsupervise\fR creates
the directory \fIdir/supervise\fR in \fIrun/svscan\fR where \fIrun\fR is
either \fI/run\fR or \fI/var/run\fR tmpfs filesystem (depending on your
operating system). You can disable the creation and use of this tmpfs
filesystem by setting \fBDISABLE_RUN\fR environment variable. From now
onwards, we will refer to \fI/var/run\fR as \fI/run\fR. \fBsvscan\fR
also opens \fI/run/svscan/dir/supervise/lock\fR in exclusive mode (1) to
prevent multiple copies of supervise running for the same service. It exits
100 if it cannot open \fI/run/svscan/dir/supervise/lock\fR. The directory
\fI/run/svscan/dir\fR must be writable for \fBsupervise\fR. This directory
is used to maintain status information in binary format and also create few
named pipes or \fBfifo\fR(7). The status information can be read by
\fBsvstat\fR(8). The format of the status file is described in another
section below. If \fBDISABLE_RUN\fR is set, or if your system doesn't
have the \fI/run\fR, \fIdir/supervise\fR will be created in \fIorig/dir\fR
directory where \fIorig\fR is the directory in which \fIdir\fR is present.
\fIorig\fR is usually \fI/service\fR on most systems. The use of \fI/run\fR
tmpfs filesystem allows \fBsupervise\fR to be used on systems where the
root filesystem is read-only. So,
\fI/run/svscan\fR/\fIdir\fR/\fIsupervise\fR is equivalent to
\fIdir/supervise\fR when \fBrun\fR tmpfs filesystem is present.

\fBsupervise\fR then executes \fI./init\fR if it exists. In case
\fI./init\fR exits with non-zero status, it pauses for 60 seconds before
restarting \fI./init\fR. The pause is required so that \fBsupervise\fR
doesn't loop too quickly causing high CPU usage. \fIdir\fR has to be
relative to the current working directory and cannot start with the dot
(\fB.\fR) or the slash (\fB/\fR) character. \fIparent_ident\fR is passed as
a command line argument by \fBsvscan\fR(8) when starting supervise log
process when \fIdir/log\fR exists. This is useful when listing supervised
log processes using the \fBps\fR(1) command (See also the \fBsvps\fR(1)
command).

After \fI./init\fR exits with zero exit status, \fBsupervise\fR starts
\fI./run\fR. It restarts \fI./run\fR if \fI./run\fR exits. In case
\fI./run\fR exits with non-zero status, it pauses for a second after
restarting \fI./run\fR. The sleep avoids supervise from looping quickly
when \fI./run\fR has a problem. \fBsupervise\fR expects \fI./run\fR to
remain in the foreground. Sometimes daemon fork themselves into background,
which some consider bad software design. If you want to monitor
such a daemon, set the sticky bit on \fI./run\fR. This makes
\fBsupervise\fR go into \fBsubreaper\fR mode using \fBprctl\fR(2)
\fBPR_SET_CHILD_SUBREAPER\fR on Linux or \fBprocctl\fR(2)
\fBPROC_REAP_ACQUIRE\fR on FreeBSD. In subpreaper mode or when the
environment variable \fBSETPGID\fR is set, the command started by
\fI./run\fR will have it's process Group ID set to the value of it's PID.
Setting the process Group ID is required to monitor \fI./run\fR reliably
when \fI./run\fR has a command which forks in the background. It is also
required in such cases to make \fBsvc\fR(8) command operate and control
\fBsupervise\fR reliably for such forked daemon/commands in \fI./run\fR.
You can also prefix such commands in \fI./run\fR with \fBfghack\fR(1)
instead of setting the sticky bit on \fI./run\fR. \fBsupervise\fR uses the
selfpipe trick (2) to handle all SIGCHLD events reliably. This requires the
use of two file descriptors for the selfpipe. \fI./run\fR is passed two
command line arguments with \fIdir\fR as argv[1] and \fIhow\fR as argv[2]
(\fIhow\fR is explained later in this document).

If the directory \fI./variables\fR exists, \fBsupervise\fR sets
environment variables before calling \fI./run\fR using \fIenvdir\fR(8).
Files in \fI./variables\fR directory must be compatible for
\fBenvdir\fR. If the directory \fI./variables\fR doesn't have execute
permissions for \fBothers\fR group, all existing environment variables will
be cleared before setting environment variables for \fI./run\fR.

\fBsupervise\fR uses \fI/run/svscan\fR/\fIdir\fR/\fIsupervise/control\fR
named pipe to read commands from \fBsvc\fR. You can use \fBsvc\fR give
commands to \fBsupervise\fR. You can give commands to \fBsupervise\fR
even if the file \fIdir\fR/down exists.

On receipt of \fBSIGTERM\fR, \fBsupervise\fR sends \fBSIGTERM\fR followed
by \fBSIGCONT\fR to its child. If running in subreaper mode or when
\fBSETPGID\fR is set, \fBsupervise\fR uses \fBkillpg\fR(3) to send the
signals, else \fBkill\fR(2) is used to send signals.

if the file \fIdir\fR/shutdown exists \fBsupervise\fR executes
\fIshutdown\fR when asked to exit or on receipt of \fBSIGTERM\fR. \fIdir\fR
is passed as the first argument and the pid of the process that exited is
passed as the second argument to \fIshutdown\fR.

if the file \fIdir\fR/alert exists \fBsupervise\fR executes \fIalert\fR
whenever \fI./run\fR exits. \fIdir\fR is passed as the first argument, the
pid of the process that exited is passed as the second argument, the exit
value or signal (if killed by signal) is passed as the third argument to
\fIalert\fR. The fourth argument is either of the strings \fIexited\fR or
\fIstopped\fR / \fIsignalled\fR.

\fBsupervise\fR may exit immediately after startup if it cannot find the
files it needs in \fIdir\fR or if another copy of \fBsupervise\fR is
already running in \fIdir\fR. Once \fBsupervise\fR is successfully running,
it will not exit unless it is killed or specifically asked to exit. On a
successful startup \fBsupervise\fR opens the named pipe
\fI/run/svscan\fR/\fIdir\fR/\fIsupervise\fR/\fIok\fR in O_RDONLY|O_NDELAY
mode. You can use \fBsvok\fR(8) to check whether \fBsupervise\fR is
successfully running. You can use \fBsvscan\fR to reliably start a
collection of \fBsupervise\fR processes. \fBsvscan\fR mirrors the service
directory in \fI/run\fR or \fI/var/run\fR directory (whichever is found
first). So \fI/run/svscan\fR/\fIdir\fR will be analogous to
/service/\fIdir\fR. If started by \fBsvscan\fR, error messages printed by
\fBsupervise\fR will go the standard error output of \fBsvscan\fR process.
In such a case it will be the log file \fI/var/log/svc/svscan/current\fR.

\fBsupervise\fR creates and opens the following named pipes / FIFOs with
\fBO_RDONLY|O_NDELAY\fR mode. \fBsupervise\fR will exit if it has trouble
creating and opening these named pipes. See \fBopen\fR(2) for description
of \fBO_RDONLY\fR, \fBO_WRONLY\fR, \fBO_NDELAY\fR.

.IP \[bu] 2
\fIdir\fR/\fIsupervise\fR/\fIcontrol\fR - for reading commands from clients
like \fBsvc\fR.
.IP \[bu] 2
\fIdir\fR/\fIsupervise\fR/\fIok\fR - clients can open this in write mode
(O_WRONLY) to test if \fBsupervise\fR is running in \fIdir\fR. If write
returns, it means \fBsupervise\fR is running.
.IP \[bu] 2
\fIdir\fR/\fIsupervise\fR/\fIup\fR - clients can open this in write mode
(O_WRONLY) to test if service in \fIdir\fR is up. Any client that opens
this named pipe in O_WRONLY mode, will block until the service \fIdir\fR is
up. If write returns, it means service in \fIdir\fR has executed
\fIdir\fR/\fIrun\fR. \fBsvc\fR is one such client (-w option) that can be
used to check if a service is up.
.IP \[bu] 2
\fIdir\fR/\fIsupervise\fR/\fIdn\fR - clients can open this in write mode to
test if service in \fIdir\fR is down. This works like exactly like
\fIdir\fR/\fIsupervise\fR/\fIup\fR. \fBsvc\fR (-W option) can be used to
check if a service is down.

\fIsupervise\fR opens \fI/run/svscan\fR/\fIdir\fR/\fIsupervise\fR/\fIup\fR
in read mode just after it executes \fI./run\fR. Hence, if service \fIw\fR
is up, write on \fI/run/svscan\fR/\fIw\fR/\fIsupervise\fR/\fIup\fR returns
immediately. If service \fIw\fR is down, the write will block until \fIw\fR
is up and running. If service \fIw\fR doesn't have \fBsupervise\fR running,
\fBsupervise\fR will wait for 60 seconds before attempting to open the file
\fIw\fR/\fIsupervise\fR/\fIup\fR again in read mode. The default value of
60 seconds gets overriden by the \fBSCANINTERVAL\fR environment variable
used by \fBsvscan\fR. If service \fIw\fR doesn't exist,
\fIdir\fR/\fIwait\fR will be ignored.

\fIsupervise\fR opens \fI/run/svscan\fR/\fIdir\fR/\fIsupervise\fR/\fIdn\fR
named pipe in read mode, when asked to bring down a service, using
\fBsvc\fR (-d or -r option). It opens this named pipe after issuing the
TERM, CONT signal to the service. Hence, if service\fIw\fR is down, write
on \fIw\fR/\fIsupervise\fR/\fIdn\fR returns immediately. if service \fIw\fR is
up, the write will block until \fIw\fR is down.

.PP
\fBsupervise\fR can wait for another service by having a file named
\fIdir\fR/\fIwait\fR. This file has two lines. The first line is time
\fIt\fR in seconds and the second line is a directory \fIw\fR for another
supervise service. If \fIw\fR does not begin with '/', then it is assumed
that the service for which supervise needs to wait is represented by
\fI..\fR/\fIw\fR. If \fIw\fR begins with '/', then it represents a
supervise service in a different base directory, probably being managed by
another \fBsvscan\fR process. By having \fIdir\fR/\fIwait\fR file, the
supervise service for \fIdir\fR will wait \fIt\fR seconds after supervise
service for \fIw\fR starts up successfully. The amount of time \fIt\fR is
limited to a max of 32767 secs. Any value above this value will be limited
to 60 secs. When \fIw\fR doesn't start with '/', the wait for another
service is implemented by opening the named pipe
\fI..\fR/\fIw\fR/\fIsupervise\fR/\fIup\fR in \fBO_WRONLY\fR mode. When
\fIw\fR starts with '/', then supervise will open the named pipe
\fIw\fR/\fIsupervise\fR/\fIup\fR in \fBO_WRONLY\fR mode. When using the
wait feature, you can make supervise use a named pipe other than \fIup\fR
by setting the environment variable \fBUPFIFO\fR. This allows supervise to
wait for a non-supervise service, where the named fifo is opened by an
external application.

\fBsupervise\fR logs informational, warning and error messages to
descriptor 2. Informational messages can be turned on by setting the
environment variable \fBVERBOSE\fR. Warning messages can be turned off by
setting the environment variable \fBSILENT\fR. If you are using
\fBsvscan\fR for service startup (as setup for indimail-mta), you can set
environment variables for \fBsupervise\fR in
\fI/service/.svscan/variables\fR directory.

\fBsupervise\fR passes arguments to the \fIrun\fR, \fIalert\fR and the
\fIshutdown\fR scripts. This allows you to handle various events in the
three scripts. The table below shows the arguments passed. The script
\fI@libexecdir@/svalert\fR uses these arguments to send alerts on port
3001. See \fBsvalert\fR(8).

To call svalert in your \fIrun\fR, \fIalert\fR, \fIshutdown\fR scripts just
include this line as the first call.

.EX
  [ -x @libexecdir@/svalert ] && @libexecdir@/svalert $@
.EE

If you don't have your own \fIalert\fR or \fIshutdown\fR scripts, you can
link those scripts to \fI@libexecdir@/svalert\fR.

.EX
  ln -s @libexecdir@/svalert \fIdir\fR/alert
  ln -s @libexecdir@/svalert \fIdir\fR/shutdown
.EE

where \fIdir\fR is your service directory.

When called in \fIrun\fR invoked with $@ as the argument, \fBsvalert\fR is
passed two command line arguments with \fIdir\fR as argv[1] and \fIhow\fR
as argv[2]. The value of \fIhow\fR is as below in the table

.TS
l l.
how              Description
_
abnormal startup When ./run exits on its own
system failure   When supervise is unable to fork to execute ./run
manual restart   When svc -u or -r is used to start the service
one-time startup When svc -o is used to start the service
auto startup     Normal startup after supervise is run by svscan or
                 manually
.TE

When called in \fIalert\fR or as \fBalert\fR, \fBsvalert\fR is passed four
command line arguments with \fIdir\fR as argv[1], \fIpid\fR as argv[2]. The
exit value or signal (if killed by signal) is passed as the third argument.
The fourth argument is either of the strings \fIexited\fR, \fIstopped\fR or
\fIsignalled\fR.

When called in \fIshutdown\fR or as \fBshutdown\fR with \fB$@\fR as the
argmument, \fBsvalert\fR is passed two arguments. \fIdir\fR is passed as
the first argument and the pid of the process that exited is passed as the
second argument.

\fBsupervise\fR sets \fBPPID\fR environment variable as its PID (process
ID) for all it's children.

.SH STATUS FILE FORMAT

The file \fIsupervise/status\fR is used by \fBsupervise\fR to write it's
PID and status information. This file can be read by \fBsvstat\fR to
display a human readable status of \fBsupervise\fR and the service it is
running.

.TS
l l.
Byte             Description
_
0-12  TAI64N label
12-15 PID of the supervise or service
16    If service is paused (1 - paused, 0 - not paused)
17    Wants to be up or down ('u' - up, 'd' - down)
18-19 Short integer for wait interval when waiting for another service.
      (> 0 - wait interval, < -1 - wait indefinitely)
20    Up or Down (0 - down, 1 - up)
.TE

.SH EXIT VALUE
\fBsupervise\fR is designed to run forever after startup. However, it will
exit 100 during startup, if it fails to open \fIdir/supervise/lock\fR, or
exit 111, if it a encounters a system error.

.SH NOTES
.EX
1. The file \fIdir/supervise/lock\fR is opened in exclusive mode using
   \fBlock(fd, LOCK_EX | LOCK_NB)\fR or \fBlockf(fd, F_TLOCK, 0)\fR.
2. The Self Pipe Trick - https://cr.yp.to/docs/selfpipe.html
.EE

.SH SEE ALSO
envdir(8),
envuidgid(8),
fghack(8),
minisvc(8),
multilog(8),
open(2),
mkfifo(3),
fifo(7),
pipe(7),
pgrphack(8),
readproctitle(8),
setlock(8),
setuidgid(8),
softlimit(8),
svalert(8),
svc(8),
svctool(8),
svok(8),
svps(1),
svscan(8),
svscanboot(8),
svstat(8),
tai64n(8),
tai64nlocal(8)

http://cr.yp.to/daemontools.html
