.\" vim: tw=75
.TH svps 1
.SH NAME
svps \- prints the status of all services started by \fBsvscan\fR

.SH SYNOPSIS
.B svps
[--\fIall\fR | -a] [--\fImain\fR | -m] [--\fIlogs\fR | -l]
  [--\fIhup\fR | -h | ] [--\fIterm\fR | -t | ] [--no-pager | -n]

.SH DESCRIPTION
\fBsvps\fR prints one human-readable line for all supervise services
started by \fIsvscan\fR(8). It prints human readable information for each
directory where \fBsupervise\fR(8) is successfully running and reporting
the status information maintained by \fBsupervise\fR(8).

Typical output of svps on a fully configured IndiMail system will be like
below. If a service is up, svps displays the PID of the service. If the
service is down, the PID of the \fBsupervise\fR(8) process is displayed.

.EX
------------ svscan ---------------
/usr/sbin/svscan /service          up         3 secs  pid   74847

------------ main -----------------
/service/fetchmail                 down       3 secs spid   74909
/service/qmail-qmqpd.628           down       3 secs spid   74852
/service/inlookup.infifo           wait       3 secs  pid   74922 remaining      27 seconds
/service/pwdlookup                 wait       3 secs  pid   74913 remaining      27 seconds
/service/dnscache                  up         3 secs  pid   74992
/service/greylist.1999             up         3 secs  pid   74980
/service/indisrvr.4000             up         3 secs  pid   74938
/service/mrtg                      up         3 secs  pid   74946
/service/mysql.3306                up         3 secs  pid   74981
/service/proxy-imapd.4143          up         3 secs  pid   74941
/service/proxy-imapd-ssl.9143      up         3 secs  pid   74953
/service/proxy-pop3d.4110          up         3 secs  pid   74989
/service/proxy-pop3d-ssl.9110      up         3 secs  pid   74990
/service/qmail-daned.1998          up         3 secs  pid   74916
/service/qmail-imapd.143           up         3 secs  pid   74901
/service/qmail-imapd-ssl.993       up         3 secs  pid   74907
/service/qmail-logfifo             up         3 secs  pid   74967
/service/qmail-pop3d.110           up         3 secs  pid   74932
/service/qmail-pop3d-ssl.995       up         3 secs  pid   74903
/service/qmail-poppass.106         up         3 secs  pid   74945
/service/qmail-qmtpd.209           up         3 secs  pid   74929
/service/qmail-send.25             up         3 secs  pid   74937
/service/qmail-smtpd.25            up         3 secs  pid   74944
/service/qmail-smtpd.366           up         3 secs  pid   74960
/service/qmail-smtpd.465           up         3 secs  pid   74956
/service/qmail-smtpd.587           up         3 secs  pid   74959
/service/qscanq                    up         3 secs  pid   74940
/service/udplogger.3000            up         3 secs  pid   74954

------------ logs -----------------
/service/.svscan/log               up         3 secs  pid   74867
/service/dnscache/log              up         3 secs  pid   74987
/service/fetchmail/log             up         3 secs  pid   74975
/service/greylist.1999/log         up         3 secs  pid   74991
/service/indisrvr.4000/log         up         3 secs  pid   74962
/service/inlookup.infifo/log       up         3 secs  pid   74983
/service/mrtg/log                  up         3 secs  pid   74939
/service/mysql.3306/log            up         3 secs  pid   74963
/service/proxy-imapd.4143/log      up         3 secs  pid   74996
/service/proxy-imapd-ssl.9143/log  up         3 secs  pid   74988
/service/proxy-pop3d.4110/log      up         3 secs  pid   74972
/service/proxy-pop3d-ssl.9110/log  up         3 secs  pid   74985
/service/pwdlookup/log             up         3 secs  pid   74970
/service/qmail-daned.1998/log      up         3 secs  pid   74936
/service/qmail-imapd.143/log       up         3 secs  pid   74934
/service/qmail-imapd-ssl.993/log   up         3 secs  pid   74899
/service/qmail-logfifo/log         up         3 secs  pid   74933
/service/qmail-pop3d.110/log       up         3 secs  pid   74930
/service/qmail-pop3d-ssl.995/log   up         3 secs  pid   74905
/service/qmail-poppass.106/log     up         3 secs  pid   74906
/service/qmail-qmqpd.628/log       up         3 secs  pid   74869
/service/qmail-qmtpd.209/log       up         3 secs  pid   74942
/service/qmail-send.25/log         up         3 secs  pid   74943
/service/qmail-smtpd.25/log        up         3 secs  pid   74931
/service/qmail-smtpd.366/log       up         3 secs  pid   74900
/service/qmail-smtpd.465/log       up         3 secs  pid   74984
/service/qmail-smtpd.587/log       up         3 secs  pid   74976
/service/qscanq/log                up         3 secs  pid   74965
/service/udplogger.3000/log        up         3 secs  pid   74993
.EE

Status can be down, wait or up. When service is in wait status, svps will
display the number of seconds supervise will wait before starting it up.
The process id can be of the service (pid) or the supervise process (spid)

.SH OPTIONS
.TP
\-\-\fIall\fR or -a

Print status for both main and log processes

.TP
.B \-\-main or -m

Print status for main processes

.TP
\-\-\fIhup\fR or -h

Send HUP signal to svscan

.TP
\-\-\fIterm\fR or -t

Send TERM signal to svscan

.TP
.B \-\-logs or -l

Print status for log processes

.TP
.B \-\-days or -d

Print uptime/downtime in days, hours, minutes and seconds.

.TP
.B \-\-no-pager or -n

Do not use print output through a pager

.SH SEE ALSO
svstat(8),
supervise(8),
qmailctl(8),
svc(8),
svok(8),
svscan(8),
svscanboot(8),
indimail-services(7)
