.TH svstats 1
.SH NAME
svstats \- prints the status of all services started by \fBsvscan\fR

.SH SYNOPSIS
.B svstats

.SH DESCRIPTION
.B svstats
prints one human-readable line for all supervise services started by
\fIsvscan\fR(8). It prints human readable information for all
directories where
.BR supervise (8)
is successfully running in that directory, and reporting the status
information maintained by
.BR supervise (8).

.SH SEE ALSO
svstat(8),
supervise(8),
svc(8),
svok(8),
svscan(8),
svscanboot(8)
