#!/bin/sh
#$Id: testsuite,v 1.1 1999/06/02 00:29:49 mrsam Exp $

rm -f testbdb.dat

./testbdb testbdb.dat foo bar
./testbdb testbdb.dat foo baz
./testbdb testbdb.dat bar foo
./testbdb testbdb.dat foo
./testbdb testbdb.dat bar
./testbdb testbdb.dat
./testbdb testbdb.dat -foo
./testbdb testbdb.dat
