#!/bin/sh
# $Log: $
#
# $Id: $
#
curdir=`pwd`
version=$(cat conf-version)

if [ -f /etc/debian_version ] ; then
	echo "you can't do rpmbuild on an insane system" 1>&2
	exit 1
fi

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --verbose)
	verbose=1
    ;;
    --release=*)
	release=$optarg
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s libsrs2.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 1
fi

if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
if [ $copy_src -eq 1 ] ; then
cd ..
/bin/rm -rf stage/libsrs2-"$version"
cp -rp libsrs2-x stage/libsrs2-"$version"
/bin/rm -f stage/libsrs2-"$version"/catChangeLog
/bin/cp libsrs2-x/catChangeLog stage/libsrs2-"$version"
cd stage/libsrs2-"$version"
make -s clean
make -s distclean

/bin/rm -rf autom4te.cache .deps
cd ..
echo "Archiving libsrs2-"$version".tar.gz in `pwd`"
tar \
	--exclude="libsrs2-$version/.git" \
	--exclude="libsrs2-$version/debian"  \
	--exclude="libsrs2-$version/RCS" \
	-cf - libsrs2-"$version" \
	| gzip -c > $rpmbuild/SOURCES/libsrs2-"$version".tar.gz
dist=`uname -r |cut -d . -f4`
if [ -z "$release" ] ; then
	if [ -d /usr/include/srs2 ] ; then
		qdist=$(rpm -qf /usr/include/srs2|cut -d- -f4|cut -d. -f3)
		if [ " $dist" = " $qdist" ] ; then
			qversion=$(rpm -qf /usr/include/srs2|cut -d- -f3)
			if [ "$qversion" = "$version" ] ; then
				release=$(rpm -qf /usr/include/srs2 | cut -d- -f4 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
cd ..
/bin/cp -p stage/libsrs2-"$version"/libsrs2-rpmlintrc $rpmbuild/SOURCES
else
	cd ..
fi
echo -n "Build RPM for libsrs2-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	cp stage/libsrs2-"$version"/libsrs2.spec /tmp
	sed -i -e "s|^Release: .*|Release: 1.$release%{?dist}|g" /tmp/libsrs2.spec
	/bin/rm -rf /tmp/libsrs2-"$version"
	cd $curdir
	if [ $? -eq 0 ] ; then
		tmprel=`cat conf-release 2>/dev/null`
		if [ ! " $tmprel" = " 1.$release" ] ; then
			echo 1.$release > conf-release
			make -s libsrs2.spec
			cp libsrs2.spec /tmp
			cd debian
			make -s
			cd ..
		fi
	fi
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba --clean --quiet /tmp/libsrs2.spec"
		rpmbuild -ba --clean --quiet /tmp/libsrs2.spec
	else
		echo "rpmbuild -ba --clean /tmp/libsrs2.spec"
		rpmbuild -ba --clean /tmp/libsrs2.spec
	fi
	if [ $? -eq 0 ] ; then
		/bin/rm /tmp/libsrs2.spec
		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
		rpm --addsign $rpmbuild/RPMS/$build_arch/libsrs2-"$version"-"1.$release".$dist.$build_arch.rpm
		echo -n "RPM lint for libsrs2-"$version"-1."$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			echo libsrs2
			rpmlint $rpmbuild/RPMS/$build_arch/libsrs2-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
			echo libsrs2-devel
			rpmlint $rpmbuild/RPMS/$build_arch/libsrs2-devel-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
			echo libsrs2-"$version"-"1.$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/libsrs2-"$version"-"1.$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	else
		/bin/rm /tmp/libsrs2.spec
	fi
else
	/bin/rm -rf /tmp/libsrs2-"$version"
fi
echo -n "Remove Source (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	/bin/rm -f $rpmbuild/SOURCES/libsrs2-"$version".tar.gz $rpmbuild/SOURCES/libsrs2-rpmlintrc
fi
