.LL 8i
.TH vmoduser 1
.SH NAME
vmoduser \- Modify virtual user attributes

.SH SYNOPSYS
\fBvmoduser\fI [\fIoptions\fR] \fIemail_addr\fR

.SH DESCRIPTION
.PP
.B vmoduser
modifies attributes of an email account by modifying fields in the authentication tables
indimail or indibak. \fBvmoduser\fR has the setuid bit set to root and must be run as
root or indimail user.

.SH OPTIONS
.PP
.TP
\fB\-v\fR
Sets verbose mode

.TP
\fB\-n\fR
Toggles between Inactive and Active state for the user
i.e. Moves the user between indimail and indibak

.TP
\fB\-q\fR \fIquota\fR
Changes the quota for the user. Changes the field pw_shell in indimail or indibak.
You can also use +\fIquota\fR to increase the existing quota by amount specified by
\fIquota\fR. You can also use -\fIquota\fR to decrease the existing quota by amount
specified by \fIquota\fR. You can use k/K, m/M, g/G for kilobytes, megabytes and
gigabytes respectively, when specifying a value for \fIquota\fR.

If the domain has domain limits set using vmoddomlimits(1), then domain limits apply. Also,
this option will not be allowed if permission for modifying quota is disabled in domain limits.

.TP
\fB\-c\fR \fIcomment\fR
Changes the gecos (comment) field for the user. Changes the field pw_gecos in indimail or
indibak.

.TP
\fB\-P\fR \fIclear_text\fR
Changes the password for the user after encrypting the clear text password given on the
command line. Changes the field pw_passwd in indimail or indibak.

.TP
\fB\-e\fR \fIencrypted_passwd\fR
Changes the encrypted password for the user as given after '\fB\-e\fR' argument (without performing
any encryption). It is expected to supply a crypted password using crypt(3) library call.
Changes the field pw_passwd in indimail or indibak.

.TP
\fB\-D\fR \fIdate_format\fR
Delivery to a date folder instead of Maildir (Inbox) as per format specification \fIdate_format\fR. 
\fBvdelivermail\fR(8) uses \fBstrftime\fR(3) to process the date format. This format is maintained
in the file \fIfolder.dateformat\fR in user's Maildir.

.EX
The format %b-%Y will cause emails to be delivered to Apr-2014 if the delivery date happens to
be anytime in Apr 2014
.EE

.TP
\fB\-l\fR \fIvacation_messsage_file\fR
Sets up autoresponder for the user. It creates .qmail file in user's homedir containing
path to the autoresponder program vacation. If vacation_message_file is specified
as '\fB-\fR', autoresponder is removed. If it is specified as '\fB+\fR', the text for autoresponder
is taken from STDIN. Any other value is taken as a file containing text for the autoresponder.
.PP
The following options are bit flags in the gid int field. (pw_gid in indimail or indibak)

.TP
\fB\-t\fR
Toggle the bit flags in the gid int field

.TP
\fB\-u\fR
Set no dialup flag.

.TP
\fB\-d\fR
Set no password changing flag for the user

.TP
\fB\-p\fR
Set no POP3 access flag.

.TP
\fB\-w\fR
Set no web mail access flag.

.TP
\fB\-i\fR
Set no IMAP4 access flag.

.TP
\fB\-b\fR
Set bounce mail flag.

.TP
\fB\-r\fR
Set no external relay flag.

.TP
\fB\-a\fR
Grant administrator privileges.

.TP
\fB\-0\fR
Reserved for future use.

.TP
\fB\-1\fR
Reserved for future use.

.TP
\fB\-2\fR
Reserved for future use.

.TP
\fB\-3\fR
Reserved for future use.

.TP
\fB\-x \fR
Clear all flags
.PP
The values of pw_gid corresponding to the above options are as below.

.RS
.nf
.ta 5c 10c
Option        	Value
--------------	-----------

NO_PASSWD_CHNG	| 0x01
NO_POP	| 0x02
NO_WEBMAIL	| 0x04
NO_IMAP	| 0x08
BOUNCE_MAIL	| 0x10
NO_RELAY	| 0x20
NO_DIALUP	| 0x40
QA_ADMIN	| 0x80
V_USER0	| 0x100
V_USER1	| 0x200
V_USER2	| 0x400
V_USER3	| 0x800
V_USER4	| 0x2000
V_USER6	| 0x8000
.fi
.RE

.SH RETURN VALUES
0 in case of success and non-zero in case of any failure.

.SH "SEE ALSO"
vsetuserquota(1), vpasswd(1), vmoddomlimits(1), resetquota(8), vdelivermail(8), strftime(3)
