#!/bin/sh

rm -f testgdbm.dat

./testgdbm testgdbm.dat foo bar
./testgdbm testgdbm.dat foo baz
./testgdbm testgdbm.dat bar foo
./testgdbm testgdbm.dat foo
./testgdbm testgdbm.dat bar
./testgdbm testgdbm.dat
./testgdbm testgdbm.dat -foo
./testgdbm testgdbm.dat

rm -f testgdbm.dat
