#
# system.module	-	Stephen Fegan 26 September 1996
#
#                           Main Menu for the UCD
#    _ _  _ ___ ____ ____ _  _ ____ ___    ____ ____ ____ _ ____ ___ _   _ 
#    | |\ |  |  |___ |__/ |\ | |___  |     [__  |  | |    | |___  |   \_/  
#    | | \|  |  |___ |  \ | \| |___  |     ___] |__| |___ | |___  |    |    
#

Module background interval 60 preload
system.bg.Netsoc.3;@0,30
system.bg.Netsoc.4;@0,30
#system.bg.agm;@0,35b:system.bg.election;@12,1
EndModule

# Turn on the Bar Clock
Module internal barclock

# Turn on Mail Check
Module internal mailcheck

#Module internal countdown2000

#Module countdown 26/11/1997 21:0:0
#The Fireball is on at 9pm on
# Wednesday in Break for the 
#Border. Only @@@@@@ seconds!
#EndModule
