'\" t
.\"<!-- Copyright 2003-2009 Double Precision, Inc.  See COPYING for -->
.\"<!-- distribution information. -->
.\"     Title: maildirkw
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/24/2017
.\"    Manual: Double Precision, Inc.
.\"    Source: Courier Mail Server
.\"  Language: English
.\"
.TH "MAILDIRKW" "1" "07/24/2017" "Courier Mail Server" "Double Precision, Inc\&."
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
maildirkw \- set maildir message keywords
.SH "SYNOPSIS"
.HP \w'\fBmaildirkw\fR\ 'u
\fBmaildirkw\fR [\-c] [\-l] [\-a] [\-r] {\fImaildir\fR} {\fImessage\fR} [\fIkeyword\fR...]
.HP \w'\fBmaildirkw\fR\ 'u
\fBmaildirkw\fR [\-c] {\-L} {\fImaildir\fR}
.SH "DESCRIPTION"
.PP
\fBmaildirkw\fR
modifies the
Courier
IMAP server compatible maildir message keywords\&. This command allows an easy way to set or clear custom IMAP keywords associated with a particular message\&.
\fImaildir\fR
is the pathname to a maildir, or a maildir folder\&. The
\fB\-L\fR
option lists all messages in the maildir, and their associated keywords\&.
\fImessage\fR
specified which message\*(Aqs keywords should be set\&. One or more
\fIkeyword\fRs specifies a list of keywords to be set for this message\&. The specified list of
\fIkeyword\fRs replaces any keywords presently set for the
\fImessage\fR, unless the
\fB\-a\fR
or the
\fB\-r\fR
option is specified\&.
.PP
The
\fB\-a\fR
option adds the
\fIkeyword\fR
to existing keywords that are set for
\fImessage\fR\&. The
\fB\-r\fR
removes
\fIkeyword\fRs from
\fImessage\fR, leaving any remaining keywords set in place\&.
.PP
The
\fB\-l\fR
should be used if the
Courier
IMAP server\*(Aqs configuration file has the
IMAP_USELOCKS
option set\&.
\fB\-l\fR
enables a compatible locking mechanism to update the message\*(Aqs keywords\&.
.PP
\fB\-c\fR
enables case\-sensitive keywords\&. IMAP keywords are normally case insensitive\&.
\fB\-c\fR
needs to be used if the
\m[blue]\fBSMAP1\fR\m[]\&\s-2\u[1]\d\s+2
protocol extension is used, which uses case sensitive keywords\&.
.SH "SEE ALSO"
.PP
\m[blue]\fB\fBmaildiracl\fR(1)\fR\m[]\&\s-2\u[2]\d\s+2,
\m[blue]\fB\fBmaildirmake\fR(1)\fR\m[]\&\s-2\u[3]\d\s+2\&.
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
Author
.RE
.SH "NOTES"
.IP " 1." 4
SMAP1
.RS 4
\%http://www.courier-mta.org/cone/smap1.html
.RE
.IP " 2." 4
\fBmaildiracl\fR(1)
.RS 4
\%http://www.courier-mta.org/maildiracl.html
.RE
.IP " 3." 4
\fBmaildirmake\fR(1)
.RS 4
\%http://www.courier-mta.org/maildirmake.html
.RE
