.TH clearopensmtp 8
.SH NAME
.PP
clearopensmtp \- remove stale IP's authorized for pop before SMTP
.PP
updaterules \- Rebuild tcp.smtp.cdb with list of static ip stored in tcprules

.SH SYNOPSYS
.PP
.B clearopensmtp
.PP
.B updaterules

.SH DESCRIPTION
\fBclearopensmtp\fR removes old IP's added after pop authentication. These IP's are maintained
in the table relay by default. IndiMail can be configured to allow POP3/IMAP users IP's to be
added to the list of IP's which are allowed to relay through the smtp server. This is done
with the --enable-roaming-users=y option while configuring IndiMail before compilation. With
this option, users IP's who authenticate via POP3/IMAP are added to the list of IP's which can
relay through the smtp server. \fBqmail-smtpd(8)\fR must be run with \fBtcpserver(1)\fR
\fB\-x\fR option. If the host is a clustered domain, \fBclearopensmtp\fR uses the DBINFO
structure to cycle through all the mailstores and clear the relay tables.

\fBupdaterules\fR rebuilds the cdb (tcp.smtp.cdb) file with the list of static IP's stored in
tcprules (\fBtcp.smtp\fR) file and the list of IP's in \fBopen-smtp\fR or relay table. This
rebuilding is needed only if IndiMail's \fBqmail-smtpd(8)\fR has not been installed, and one is
running some other version of smtpd daemon. \fBupdaterules\fR may also be needed if one is
running a version of smtpd on some foreign hosts (e.g. Relay servers) which do not have access
to IndiMail's authentication databases. IndiMail's \fBqmail-smtpd(8)\fR gets the authenticated
user list at run time from the \fBrelay\fR table and hence does not require the IP's in the
\fBtcp.smtp.cdb\fR file.

Each authenticated pop users IP is added with a time stamp. Every time \fBclearopensmtp\fR is
run, this list is checked for time stamps which are older than the 
\fB\-\-enable\-relay\-clear\-minutes\fR option. The default is 30 minutes. Any IP with a time
stamp older than this number are removed from the list. 

.SH OPTIONS
.PP
These options are for \fBclearopensmtp\fR only.
.TP
\fB\-C\fR
Connect to cluster. Allows \fBclearopensmtp\fR to operate on all hosts defined
in \fBdbinfo\fR Mail Cluster Definition (MCD) File. This option causes \fIrelay\fR table
to be cleared on all hosts defined in the MCD file.

.TP
\fB\-t\fR
Rebuild the cdb only.

.TP
\fB\-s\fR
Clear the table \fIrelay\fB in MySQL only.

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise.
