#!/bin/sh
oPrefix=/var/indimail
sysconfdir=/etc
prefix=/usr

restore_old()
{
	if [ $1 -eq 0 ] ; then
		echo "Migration data for IndiMail 2.x was SUCCESSFUL"
		echo "Creating links to original IndiMail 1.x directories"
		for i in sbin bin libexec users control etc
		do
			echo "Linking $oPrefix/$i to $oPrefix/"$i".o"
			ln -rsf $oPrefix/"$i".o $oPrefix/"$i"
		done
		echo "After this script complets, you need to uninstall IndiMail and install IndiMail 2.x"
		echo "After insallation of IndiMail 2.x, remove the following directories"
		for i in sbin bin libexec users control etc
		do
			echo "$oPrefix/$i.o"
		done
		return 0
	else
		echo "Migration data for IndiMail 2.x FAILED"
		read key
	fi
	echo "Will Restore and Start IndiMail service after 5 seconds"
	sleep 5
	echo "Restoring indimail to original state"
	status=$1
	for i in sbin bin libexec users
	do
		if [ -d $oPrefix/$i.o ] ; then
			echo "Restoring $i.o to $i"
			/bin/mv $oPrefix/"$i".o $oPrefix/$i
			if [ $? -ne 0 ] ; then
				status=1
			fi
		fi
	done
	if [ $status -eq 0 ] ; then
		for i in control etc
		do
			ln -s $oPrefix/"$i".o $oPrefix/$i
		done
	fi
	echo "Starting IndiMail service"
    $oPrefix/sbin/initsvc -on
    $oPrefix/sbin/initsvc -status
	exit $status
}

ID=$(id -u)
if [ $ID -ne 0 ] ; then
  echo "You are not root" 1>&2
  exit 1
fi
if [ -d /etc/indimail ] ; then
	echo "/etc/indimail exists!!!. Aborting"
	exit 1
fi
echo "Initiating Migration. This script will make temporary changes to IndiMail to make a copy for IndiMail 2.x"
echo -n "Do you want to continue - (YES/No) - "
read key
if [ ! " $key" = " YES" ] ; then
	echo "No Changes Made and No Migration Performed"
	exit 0
fi
if [ -d $oPrefix -a -d /service ] ; then
  if [ -f $oPrefix/sbin/initsvc ] ; then
    $oPrefix/sbin/initsvc -status
  fi

  if test -f $sysconfdir/init/svscan.conf
  then
    echo "Giving IndiMail exactly 5 seconds to exit nicely"
    /sbin/initctl emit qmailstop > /dev/null 2>&1
  elif test -f $sysconfdir/event.d/svscan
  then
    echo "Giving IndiMail exactly 5 seconds to exit nicely"
    /sbin/initctl emit qmailstop > /dev/null 2>&1
  elif test -f $sysconfdir/systemd/system/multi-user.target.wants/svscan.service
  then
    echo "Giving IndiMail exactly 5 seconds to exit nicely"
    /bin/systemctl stop indimail > /dev/null 2>&1
  elif test -x $oPrefix/sbin/initsvc
  then
    echo "Giving IndiMail exactly 5 seconds to exit nicely"
    $oPrefix/sbin/initsvc -off
  fi
  sleep 5
fi
for i in sbin bin control libexec users etc
do
	if [ -d $oPrefix/$i -a ! -L $oPrefix/$i ] ; then
		echo "Renaming $oPrefix/$i to $oPrefix/$i.o"
		/bin/mv $oPrefix/"$i" $oPrefix/"$i".o
		if [ $? -ne 0 ] ; then
			restore_old 1
		fi
	fi
done
mkdir -p /etc/indimail/etc
if [ -d $oPrefix/control.o ] ; then
	echo "Migrating tcp config files"
	mkdir -p /etc/indimail/tcp
	if [ $? -eq 0 ] ; then
		chown indimail:qmail /etc/indimail/tcp
		chmod 2775 /etc/indimail/tcp
		cp $oPrefix/control.o/*.tcp /etc/indimail/tcp
		echo "Migrated tcp config files from $oPrefix/control to /etc/indimail/tcp"
	else
		restore_old 1
	fi
	echo "Migrating certs"
	mkdir -p /etc/indimail/certs
	if [ $? -eq 0 ] ; then
		chown indimail:qmail /etc/indimail/certs
		chmod 2775 /etc/indimail/certs
	else
		cp -p $oPrefix/control.o/servercert.pem /etc/indimail/certs
		cd /etc/indimail/certs
		ln -s servercert.pem clientcert.pem
		cp -p $oPrefix/control.o/*.cnf /etc/indimail/certs
		cp -p $oPrefix/control.o/couriersslcache /etc/indimail/certs
		echo "Migrated certs from $oPrefix/control to /etc/indimail/certs"
	fi
fi
for i in control users
do
	if [ -d $oPrefix/$i.o ] ; then
		echo "Copying $oPrefix/$i to /etc/indimail/$i"
		/bin/cp -rpf $oPrefix/"$i".o /etc/indimail/"$i"
		if [ $? -ne 0 ] ; then
			restore_old 1
		fi
	fi
done
if [ -d $oPrefix/etc.o ] ; then
	echo "Copying $oPrefix/etc/* to /etc/indimail/"
	cp -rpf $oPrefix/etc.o/* /etc/indimail
	if [ $? -ne 0 ] ; then
		restore_old 1
	fi
	/bin/mv /etc/indimail/leapsecs.* /etc/indimail/etc
	restore_old $?
fi
mkdir -p $prefix/libexec/indimail/imapmodules
echo "Migrating imap, pop3 auth modules"
if [ -d $oPrefix/libexec/authlib ] ; then
	echo "Migrated $oPrefix/libexec/authlib to $prefix/libexec/indimail/imapmodules"
	cp $oPrefix/libexec/authlib/* $prefix/libexec/indimail/imapmodules
fi
for i in `/bin/ls -d /service/*imapd* /service/*pop3d*`
do
	echo migrating $i/run to use authmodules in $prefix/libexec/indimail/imapmodules
	sed s{libexec/authlib{libexec/indimail/imapmodules{g $i/run > $i/run.tmp
	diff $i/run $i/run.tmp > /dev/null
	if [ $? -ne 0 ] ; then
		mv $i/run.tmp $i/run
		chmod +x $i/run
		echo "Migrated $i/run"
	else
		/bin/rm -f $i/run.tmp
	fi
done
exit 0
