.TH vgroup 1
.SH NAME
vgroup \- create distribution groups for set of users in a virtual domain

.SH SYNOPSYS
.PP
\fBvgroup\fR \fB\-a\fR [\fB\-h\fR] [\fB\-c\fR][\fBq\fR] [\fB\-v\fR] \fIgroupAddress\fR [\fIpassword\fR]
.PP
\fBvgroup\fR [\fB\-i\fR \fIaliasLine\fR] [\fB\-d\fR \fIaliasLine\fR] [\fB\-u\fR \fInewaliasLine\fR  \fB\-o\fR \fIoldaliasLine\fR] [\fB\-v\fR] \fIgroupAddress\fR

.SH DESCRIPTION
\fBvgroup\fR implements groups functionality in IndiMail. It is a utility to add groups.
On an existing group, vgroup can be used to add, modify and delete members.

The first form of usage is used for creating a new group. Subsequently normal IndiMail programs
(\fBvuserinfo\fR, \fBvdeluser\fR, \fBvmoduser\fR, \fBvpasswd\fR, \fBvsetuserquota\fR) can be
used to operate on a group exactly like on virtual users. In fact, a group in IndiMail is
a virtual user.

The second form of usage is used to add, modify, delete aliases to the group. It uses the
\fBvalias\fR to do this. The most comman usage of vgroup is to add forwardings. 
i.e. All mails sent to the group will be forwarded to members. In this case address will
be of the form '&email_address'.

The implementation of groups in IndiMail is actually a normal email account with aliases.
Hence a group can also be created using \fBvadduser\fR in conjunction with \fBvalias\fR with
the restriction that the gecos starts with the word 'MailGroup' (see option \fB\-c\fR below for
more explanation). vgroup has been written for user convenience alone.

.SH OPTIONS
.PP
Common Options
.TP
\fB\-v\fR
Sets verbose mode while vgroup is operating
.TP
\fIgroupAddress\fR
Email address for the group.

.PP
Options for adding a New Group.
.TP
\fIpasswd\fR
Passwd for the user. If not given, user will be prompted.
.TP
\fB\-a\fR
Add a new group.
.TP
\fB\-h\fR \fIhostid\fR
For a clustered domain, this option can be used to create the user on a specific host having
\fIhostid\fR as the hostid.
.TP
\fB\-m\fR \fImdahost\fR
For a clustered domain, this option can be used to create the user on a specific cluster
having Mail Delivery Host as \fImdahost\fR.
.TP
\fB\-c\fR
Comment field (gecos) for the group account. Internally the comment starts with the
word 'IndiGroup'. This will be shown if you use the command vuserinfo on the group address.
It is advisable not to change this by external programs such as vmoduser. IndiMail figures
out difference between a normal email account and a group account by checking if gecos
field starts with the word 'IndiGroup'.
.TP
\fB\-q\fR
Sets the Quota for the group. This should be set in case the group will also function as a
normal user and receive mails.
.TP
\fB\-I\fR
Ignore requirement of groupAddress to be a local address on the node where vgroup is
being run (option valid for clustered domain only)

.PP
Options for an Existing Group
.TP
\fB\-i\fR \fIaliasLine\fR
Insert alias line \fIaliasLine\fR in the group. An alias line has one of the 3 forms.
See \fBdot-qmail(5)\fR for more details.

.EX
 1. &\fIemail\fR       - Forward mails to \fIemail\fR
 2. Maildir      - copy mails to a Maildir with path \fIMaildir\fR
 3. | Command    - pipe the mail through command \fICommand\fR
.EE
.TP
\fB\-d\fR \fIaliasLine\fR
delete aliasLine from the group. See valias for more details
.TP
\fB\-u\fR \fInewaliasLine\fR \fB\-o\fR \fIoldaliasLine\fR
Modify oldaliasLine to newaliasLine alias in the group. See valias for more details

.SH RETURN VALUE
0 if all steps were successful, non-zero otherwise. If any of the steps fail, a
diagnostic message is printed.

.SH "SEE ALSO"
dot-qmail(5), valias(1), vcalias(8), vadduser(1), vdelivermail(8), vrenamedomain(1), vreorg(8)
