.TH vsmtp 8
.SH NAME
vsmtp \- Setup artificial routes for qmail-remote

.SH SYNOPSYS
.B vsmtp
[
.I options
.I hostid@domain_name
\fB\-m\fR \fImta\fR
|
\fB\-s\fR \fIdomain_name\fR
]

.SH DESCRIPTION
.PP
\fBvsmtp\fR sets up artificial routes for \fBqmail-remote(8)\fR to be able to deliver mails to the
mailstore on host \fIhostid\fR and domain \fIdomain_name\fR. This route is used by \fBqmail-remote(8)\fR
to send mails using SMTP or QMTP for clustered domains. For all other domains the control/smtproutes or
control/qmtproutes is consulted. This routing information is stored in MySQL on a host which by nomenclature
is called the \fBcontrol host\fR.

.PP
The \fIcontrol host\fR is defined by the control files \fIhost.master\fR / \fIhost.cntrl\fR or the environment
variables \fBCNTRL_HOST\fR, \fBCNTRL_USER\fR, \fBCNTRL_PASS\fR, \fBCNTRL_VPORT\fR or \fBCNTRL_SOCKET\fB.

.SH OPTIONS
.PP
.TP
\fB\-v\fR
Sets Verbose option.
.TP
\fB\-s\fR
Show smtp ports for a virtual domain or SMTP Route between a MTA host and a mailstore having
the domain \fIdomain_name\fR
.TP
\fB\-d\fR
Delete SMTP Route between a MTA host and a mailstore.
.TP
\fB\-i\fR \fIport\fR
Add SMTP Route between a MTA host and a mailstore
.TP
\fB\-u\fR \fIport\fR
Change SMTP Route between a MTA host and a mailstore
.TP
\fB\-m\fR \fImta_ipaddress\fR
The ip address of the MTA which needs a SMTP route to the mailstore.
.TP
\fIhostid@domain\fR
The mailstore hostid followed by '@' sign and the domain_name.
.TP
\fIdomain_name\fR
The name of the virtual domain.

.SH RETURN VALUES
0 for success, 1 for any failure.

.SH "SEE ALSO"
qmail-remote(8), hostcntrl(8), vhostid(8), dbinfo(8)
