.LL 8i
.TH inquerytest 8
.SH NAME
inquerytest \- Test InLookup Queries

.SH SYNOPSYS
.B inquerytest
.I query_type
.I infifo
.I email
[
.I ip_address
]

.SH DESCRIPTION
\fBinquerytest\fR is a utility to test the inquery() function and its interaction with
\fBInLookup(8)\fR. This function is meant to be used by qualified IndiMail administrators.

.SH OPTIONS
.TP
\fIquery_type\fR
Type of query to be tested as given below

 1 – User Query
     This displays the status of the user, whether the id has
     all service enabled or is absent, inactive or over quota
 2 – Relay Query
     Tells whether the user has authenticated and the entry is
     present in the relay table and has not expired (used for
     POP before SMTP).
 3 – Password Query
     Displays the passwd structure for the email address.
 4 – Host Query
     Displays the SMTPROUTE for the address. i.e. To which host
     should the mails for this address be delivered.
 5 – Alias Query
     Displays all the aliases, forwarding, vacation entries for
     the address.
 7 – Local Password Query
     Similar to (3) except that the email address is checked only
     on the local MDA..
.TP
\fIinfifo\fR
Path of the fifo to be used for communication with InLookup. A null
string (“”) makes inquerytest to use INFIFO environment variable
if defined or the default INFIFO file and use an existing running InLookup. If a fifo path is given, inquerytest will invoke a new InLookup on the given fifo, run the test, terminate InLookup and delete the fifo after the test. Hence, do not give a path to a fifo on which an existing InLookup is running.
.TP
\fIemail\fR
Fully qualified email address.
.TP
\fIip_address\fR
IP address (TCPREMOTEIP) recorded in relay table after successful authentication through IMAP/POP3 for the email address email. This option is valid for the Host Query type.

.SH RETURN VALUE
0 for success, 1 for any failure. Prints diagnostics on stdout and failures on stderr.

.SH "SEE ALSO"
inlookup(8)
