#!/bin/sh
# $Log: create_rpm,v $
# Revision 1.1  2024-05-09 22:58:41+05:30  Cprogrammer
# Initial revision
#
#
# $Id: create_rpm,v 1.1 2024-05-09 22:58:41+05:30 Cprogrammer Exp mbhangui $
#
version=$(head -1 conf-version)
ucspitcp_version=$(cat ../ucspi-tcp-x/conf-version)

get_tar_files()
{
(
for i in `grep "^Source" ucspi-tcp-x/ucspi-tcp.spec.in | awk '{print $2}' | grep "\.tar"`
do
	i=`basename $i`
	echo $i
done
) | uniq | sed \
	-e 's/%{name}/ucspi-tcp/g' \
	-e "s/%{version}/$version/g"
}

get_non_tar_files()
{
(
for i in `grep "^Source" $1 | grep -v "\.tar" | awk '{print $2}'`
do
	i=`basename $i`
	echo $i
done
) | sort -u | sed \
	-e 's/%{name}/ucspi-tcp/g' \
	-e "s/%{version}/$version/g"
}

get_dirname()
{
	echo $1 | sed \
		-e 's}.tar.gz}}g' \
		-e 's}.tar.bz2}}g' \
		-e 's}.tar.xz}}g'
}

if [ -f /etc/debian_version ] ; then
	echo "you can't do rpmbuild on an insane system" 1>&2
	exit 1
fi

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --verbose)
	verbose=1
    ;;
    --clean)
    clean="--clean"
    ;;
    --release=*)
	release=$optarg
    ;;
    *)
    echo "invalid option [$1]"
    read key
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

SYSTEM=`uname -s | tr "[:lower:]" "[:upper:]"`
if [ $copy_src -eq 1 ] ; then
make SYSTEM=$SYSTEM -s ucspi-tcp.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 1
fi
if [ -d ../stage ] ; then
	/bin/rm -rf ../stage
fi
mkdir ../stage
cd ..
list=`get_tar_files`
for i in $list
do
	dir=`get_dirname $i`
	case "$dir" in
		ucspi-tcp-$version)
		if [ ! -d ucspi-tcp-x ] ; then
			echo "$i: No such file or directory" 1>&2
			exit 1
		fi
		echo "Preparing ucspi-tcp-"$version""
		/bin/cp -rp ucspi-tcp-x stage/ucspi-tcp-"$version"
		/bin/rm -f stage/ucspi-tcp-"$version"/catChangeLog
		/bin/cp ucspi-tcp-x/catChangeLog stage/ucspi-tcp-"$version"
		cd stage/ucspi-tcp-"$version"
		echo "Cleaning ucspi-tcp"
		make SYSTEM=$SYSTEM -s clean > /dev/null
		make SYSTEM=$SYSTEM -s distclean > /dev/null
		/bin/rm -rf autom4te.cache .deps
		cd ..
		tar \
			--exclude="ucspi-tcp-$version/.git" \
			--exclude="ucspi-tcp-$version/debian" \
			--exclude="ucspi-tcp-$version/RCS" \
			-cf - ucspi-tcp-"$version" \
			| gzip -c > $rpmbuild/SOURCES/ucspi-tcp-"$version".tar.gz
		SRC="$rpmbuild/SOURCES/ucspi-tcp-"$version".tar.gz $SRC"
		cd ..
		continue
		;;
	esac
done
echo "Copying permissions files and rpmlintrc"
for i in `get_non_tar_files ucspi-tcp-x/ucspi-tcp.spec.in`
do
	/bin/cp -p stage/ucspi-tcp-"$version"/$i $rpmbuild/SOURCES
	SRC="$rpmbuild/SOURCES/$i $SRC"
done
echo "Clearing stage directory"
/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ -z "$release" ] ; then
	if [ -f /usr/bin/tcpserver ] ; then
		uversion=$(rpm -qf /usr/bin/tcpserver|cut -d- -f3)
		if [ "$uversion" = "$version" ] ; then
			t1=$(rpm -qf /usr/bin/tcpserver | cut -d- -f4 | cut -d. -f1)
			t2=$(rpm -qf /usr/bin/tcpserver | cut -d- -f4 | cut -d. -f2)
			t2=$(expr $t2 + 1)
			release="$t1.$t2"
		else
			release=0.1
		fi
	else
		release=0.1
	fi
fi
echo -n "Build RPM for ucspi-tcp-"$version"-"$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat ucspi-tcp-x/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " $release" ] ; then
		echo $release > ucspi-tcp-x/conf-release
		cd ucspi-tcp-x
		make SYSTEM=$SYSTEM ucspi-tcp.spec
		cp ucspi-tcp.spec /tmp
		cd debian
		make
		cd ../..
	else
		cp ucspi-tcp-x/ucspi-tcp.spec /tmp
	fi
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba $clean --quiet /tmp/ucspi-tcp.spec"
		rpmbuild -ba $clean --quiet /tmp/ucspi-tcp.spec
	else
		echo "rpmbuild -ba $clean /tmp/ucspi-tcp.spec"
		rpmbuild -ba $clean /tmp/ucspi-tcp.spec
	fi
	if [ $? -eq 0 ] ; then
		/bin/rm -f /tmp/ucspi-tcp.spec
		rpm --addsign $rpmbuild/RPMS/$build_arch/ucspi-tcp-"$version"-"$release".$dist.$build_arch.rpm
		rpm --addsign $rpmbuild/SRPMS/ucspi-tcp-"$version"-"$release".$dist.src.rpm
		echo -n "RPM lint for ucspi-tcp-"$version"-"$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			echo ucspi-tcp-"$version"-"$release".$dist.rpm
			rpmlint $rpmbuild/RPMS/$build_arch/ucspi-tcp-"$version"-"$release".$dist.$build_arch.rpm
			echo ------------------------
			echo ucspi-tcp-"$version"-"$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/ucspi-tcp-"$version"-"$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	else
		/bin/rm -f /tmp/ucspi-tcp.spec
	fi
fi
if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		for i in $SRC
		do
			echo "/bin/rm -f $i"
			/bin/rm -f $i
		done
	fi
fi
