.TH "dotls" "1" "06 Mar 2010" "Manvendra Bhangui" ""

.SH NAME
dotls \- Generic TLS/SSL protocol wrapper for non-TLS programs
.SH SYNOPSIS

\fBdotls\fR [-nftCT ] [-s smtp|pop3] \fB\fIprog\fB\fR \fB\fIarg\fB\fR\fI ...\fR

.SH "DESCRIPTION"
.PP
The \fBdotls\fR program is used by applications to encrypt a
network connection using SSL/TLS, without having the application
deal with the gory details of SSL/TLS.

.PP
\fBdotls\fR is not usually run directly from the command line.
An application typically creates a network connection, then runs
\fBdotls\fR with appropriate options to encrypt the network
connection with SSL/TLS. \fBdotls\fR can also do opportunistic
SSL/TLS (or delayed encryption) for smtp in server mode.

\fBdotls\fR can be run under \fBtcpserver\fR(1) to provide SSL/TLS or
opportunistic TLS for qmail-smtpd, qmail-pop3d. This is known as
\fBserver mode\fR.

\fBdotls\fR can be run under \fBtcpclient\fR(1) to connect to any SSL/TLS
enabled server. This is known is \fBclient mode\fR. This gets enabled
when you use \fB\-T\fR or the \fB\-C\fR options.

\fBdotls\fR is not needed by indimail-mta, as all features offered by
\fBdotls\fR are built-in tcpserver(1) and tcpclient(1), provided by
ucspi-tcp package from indimail-mta git repo at,
https://github.com/mbhangui/indimail-mta/tree/master/ucspi-tcp-x

\fBdotls\fR intercepts client commands for the \fBEHLO\fR, \fBCAPA\fR,
\fBSTARTTLS\fR, \fBSTLS\fR, \fBQUIT\fR requests. For the \fBEHLO\fR and
\fBCAPA\fR requests, it offers \fBSTARTTLS\fR and \fBSTLS\fR capability on
behalf of \fIprog\fR. All other commands are passed unaltered to
\fIprog\fR.

.SH "OPTIONS"
.TP
-\fBn\fR \fIcertfile\fR
Use \fIcertfile\fR as the certificate
The certificate to use and is required for SSL/TLS servers.
\fIcertfile\fR must not be world-readable. This option overrides
environment variable TLS_CERTFILE. If this is not provided, the file
@qsysconfdir@/certs/clientcert.pem will be used.

.TP
-\fBf\fR \fIcipher_list\fR
Use ciphers listed in \fIcipher_list\fR. Without this \fBdotls\fR uses
TLS_CIPHER_LIST environment variable if set or system configured
PROFILE=SYSTEM ciphers.

.TP
-\fBt\fR \fItimeout\fR
Timeout after \fItimeout\fR seconds if no data is received

.TP
-\fBs\fR \fIstartlsType\fR
Specify smtp or pop3 for \fIstarttlsType\fR. In this mode,
\fBdotls\fR will offer STARTTLS extension. It will initiate SSL/TLS
negotation only when it receives \fBSTARTTLS\fR command from client.
Currently, \fBsmtp\fR and \fBpop3\fR are supported. If this is not
provided, \fBdotls\fR will directly initiate a TLS session.

.TP
.B \-C
\fBclient\fR mode. In this mode, \fBdotls\fR acts as a tls client,
reading fd 0 for input and using fd 1 for output.

.TP
.B \-T
\fBtcpclient\fR mode. In this mode, \fBdotls\fR acts as a tls client,
reading fd 6 for input and using fd 7 for output. Use this if \fIprog\fR has
been specifically written for tcpclient(1).

.SH "ENVIRONMENT VARIABLES"
.PP
\fBdotls\fR reads the following environment variables in
order to configure the SSL/TLS protocol:
.TP
.B CERTDIR
Directory having servercert.pem.
Default is @qsysconfdir@/certs.

.TP
.B TLS_CERTFILE
client ssl certificate. This can be overriden by the -n option.
Default is clientcert.pem

.TP
\fBTLS_CIPHER_LIST=\fIcipherList\fB\fR
A set of OpenSSL cipher strings. Multiple ciphers contained in a string
should be separated by a colon. This can be overriden by the -f option.

.SH EXAMPLES
.EX
1. Add STARTTLS extension for qmail-smtpd
   tcpserver 0 25 /usr/bin/dotls -s smtp /var/qmail/bin/qmail-smtpd

2. Provide SMTPS service on port 465 for qmail-smtpd
   tcpserver 0 465 /usr/bin/dotls /var/qmail/bin/qmail-smtpd

3. Add STLS extension for qmail-pop3d
   tcpserver 0 110 /usr/bin/dotls -s pop3 qmail-popup host \\
     checkpassword qmail-pop3d Maildir

4. Provide POP3S service on port 993 for qmail-pop3d
   tcpserver 0 993 /usr/bin/dotls qmail-popup host checkpassword \\
     qmail-pop3d Maildir

5. Run a script under tcpclient that connects to a SSL server on port 5555
   read from fd 0 reads from network & write to fd 1 writes to network
   tcpclient 0 555 /usr/bin/dotls -C /usr/bin/myscript

6. Run a script under tcpclient that connects to a SSL server on port 5555
   read from fd 6 reads from network & write to fd 7 writes to network
   tcpclient 0 555 /usr/bin/dotls -CT /usr/bin/myscript
.EE

.SH "SEE ALSO"
.PP
\fBtcpclient\fR(1),
\fBtcpserver\fR(1),
\fBqmail-smtpd\fR(8),
\fBqmail-pop3d\fR(8)
