.TH tcpclientrw 1
.SH NAME
tcpclientrw \- Prog for tcpclient
.SH SYNOPSIS
.B tcpclientrw [-t \fItimeout\fR]

.SH DESCRIPTION
\fBtcpclientrw\fR is a program that can run under \fBtcpclient(1)\fR. It
reads fd \fI0\fR (stdin) and writes to fd \fI7\fR. It reads fd \fI6\fR and
writes to fd \fI1\fR (stdout). \fBtcpclientrw\fR times out and exits with
non-zero status.

.SH RETURN VALUE
.EX
1   - write failure
2   - write timeout
3   - read failure
4   - read timeout
111 - system error
100 - wrong usage
0   - success
.EE

.SH SEE ALSO
tcpclient(1),
tcpserver(1),
openssl(1)
