.LL 8i
.TH ipchange 8
.SH NAME
ipchange \- Modify IP Address records in IndiMail Database

.SH SYNOPSYS
\fBipchange\fR [\fIoptions\fR] \fItable_name\fR

.SH DESCRIPTION
\fBipchange\fR is meant for modifying IP address records in the IndiMail tables when the IP
address of a host running various IndiMail services is changed. Following tables get impacted
when IP address of a host gets changed.

.RS
.nf
.ta 5c 10c
Table	Column
--------	----------

host_table	ipaddr
dbinfo	server, mdahost
ip_alias_map	ipaddr
.fi

.RE
The control file localiphost on the host whose IP address is changed, gets impacted.
The control file smtproutes on all relay servers acting as a relay for the host
gets impacted.

.EX
e.g. You can use the following command to set things right in the table dbinfo

ipchange -o 202.144.76.7 -n 202.144.76.8 -c server -m dbinfo
ipchange -o 202.144.76.7 -n 202.144.76.8 -c mdahost -m dbinfo
ipchange -o 202.144.76.7 -n 202.144.76.8 -c ipaddr ip_alias_map
.EE

Please Note that ipchange changes only the logical IP address in the IndiMail's database. For the actual/physical IP address change, you will have to use the appropriate
OS utility (i.e. ifconfig).

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose operation
.TP
\fB\-o\fR
Existing IP address.
.TP
\fB\-n\fR
New IP address to be set on the host.
.TP
\fB\-c\fR
Column name of the IP address record.
.TP
\fB\-m\fR
Modifies the table on hostcntrl.
.TP
\fItable_name\fR
The name of the table.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
IndiMail(5)
