.LL 8i
.TH logmonitor 8
.SH NAME
logmonitor - generic live log monitor

.SH SYNOPSYS
.B logmonitor
[
.I options
]

.SH DESCRIPTION
\fBlogmonitor\fR is a utility for monitoring specific values in any log file being generated
continuously by applications. It feeds the items to another utility called \fBhashtable\fR and
\fBdisplaytop\fR.

\fBhashtable\fR creates a hash table of all lines fed to it and displays count of occurrences
of each item feed to it.

\fBdisplaytop\fR sorts the entries and displays the entries on the screen with the entries
having the maximum occurrences at the top.

.SH OPTIONS
.PP
\fB\-\-logfile\fR
Path of log file to monitor
.TP
\fB\-\-display_size\fR
Maximum number of entries to display on screen.
.TP
\fB\-\-format\fR
Type of format of the log file. i.e qmail-send or qmail-smtpd log file
.TP
\fB\-\-threshold\fR
Minimum no of occurrences of an item above which the item should be reported
.TP
\fB\-\-follow\fR
Continuously monitor the log file (like tail -f)
.TP
\fB\-\-batchmode\fR
Set this if the output is not a terminal.

.SH RETURN VALUE
0 for success, 1 for any failure.
