.LL 8i
.TH vmoveuser 1
.SH NAME
vmoveuser \- move homedir of a virtual user to a new path

.SH SYNOPSYS
\fBvmoveuser\fR \fIemail_addr\fR \fInew_homedir\fR

.SH DESCRIPTION
\fBvmoveuser\fR changes the current homedir path to \fInew_homedir\fR, moving all existing
files to the new path. \fBvmoveuser\fR has setuid bit to root and can be run by the
root or indimail user.

.SH POST HANDLE
If the environment variable POST_HANDLE is set, \fBvmoveuser\fR executes the program defined by
the POST_HANDLE environment variable, passing \fIemail_addr\fR, \fIold_homedir\fR and \fInew_homedir\fR
as parameters. If POST_HANDLE is not defined, the program/script INDIMAIL/libexec/vmoveuser will
be executed with \fIemail_addr\fR, \fIold_homedir\fR and \fInew_homedir\fR as parameters.

.SH OPTIONS
.TP
\fIemail_addr\fR
Fully qualified email address (username + virtual domain component).
.TP
\fInew_homedir\fR
Path to which the homedir of the user needs to be assigned to

.SH RETURN VALUES
0 for success, 1 for any failure.

.SH "SEE ALSO"
vrenameuser(1)
