.TH indiversion 8
.SH NAME
.PP
indiversion - display version information for indimail programs
.PP
versioninfo - display version information for indimail programs

.SH SYNOPSYS
.PP
indiversion
.PP
versioninfo

.SH DESCRIPTION
\fBindiversion\fR and \fBversioninfo\fR display the version numbers and rcs(1) information for
all modules and source files comprising the IndiMail system. \fBindiversion\fR also displays
the configuration options set by the configure(1) program  before compiling IndiMail.

.SH OPTIONS
None

.SH RETURN VALUE
Return value does not have any importance.
