.TH vpriv 8
.SH NAME
vpriv \- Set privilege for admin user to run IndiMail commands

.SH SYNOPSYS
\fBvpriv\fR [\fIoptions\fR] \fIuser\fR \fICommandLineSwitches\fR

.SH DESCRIPTION
\fBvpriv\fR sets privileges for users to run IndiMail programs with a set of command line
options. The users can be created with the \fBmgmtpass(8)\fR program. This allows access
control on programs run by \fBadminclient(8)\fR.

.SH OPTIONS
.TP
\fB\-s\fR
Shows all allowed programs and command line switches enabled for the user 'user'.
.TP
\fB\-d\fR \fIprogram\fR
Removes all access to program 'program' for user 'user'
.TP
\fB\-i\fR \fIprogram\fR
Adds the program 'program' in the access control list for the given user. Further access is
given by the CommandLineSwitches argument.
.TP
\fB\-m\fR \fIprogram\fR
Modifies the  command line switches for the program 'program'
.TP
\fB\-D\fR
Removes all access to all programs for the user 'user'
.TP
\fB\-a\fR
Adds all IndiMail programs to the access control list of the user 'user' with all possible
command line arguments.

.PP
Access control list applies only to programs run through the \fBadminclient(8)\fR program. The
access control list is checked by the indisrvr program after successful authentication.

.SH RETURN VALUE
0 for success and 1 for failure in which case all diagnostics are printed on stdout.

.SH "SEE ALSO"
adminclient(8), indisrvr(8), mgmtpass(8)
