catch {global hostname}
catch {global actdate}
catch {global addedon}
catch {global adminhost}
catch {global adminpass}
catch {global adminport}
catch {global adminuser}
catch {global firstname}
catch {global lastname}
catch {global phone1}
catch {global phone2}
catch {global dept}
catch {global authenticated}
catch {global bounce}
catch {global bounceaddr}
catch {global daysinact}
catch {global debug_flag}
catch {global search}
catch {global domain}
catch {global default_domain}
catch {global domaindir}
catch {global domain_list}
catch {global is_distributed}
catch {global cluster}
catch {global etrn}
catch {global etrnaddr}
catch {global fsbalance}
catch {global gecos}
catch {global gid}
catch {global inactdate}
catch {global lastauth}
catch {global lastimap}
catch {global lastpass}
catch {global lastpop3}
catch {global maildir}
catch {global mailstore}
catch {global mailstoreid}
catch {global mailstoreip}
catch {global passwdtyp}
catch {global password}
catch {global pwgen}
catch {global quota}
catch {global relayon}
catch {global result}
catch {global server}
catch {global server_list}
catch {global sqlserver_list}
catch {global aliasdomain_list}
catch {global sqlserver}
catch {global status}
catch {global tablename}
catch {global uid}
catch {global usage}
catch {global user}
catch {global username}
catch {global var_quota}
catch {global var_quota1}
catch {global vfilter}
catch {global w}
catch {global dwin}
catch {global lwin}
catch {global rwin}
catch {global inactive_flag}
catch {global isinactive}
catch {global no_dialup}
catch {global no_pass}
catch {global no_pop3}
catch {global no_imap}
catch {global no_smtp}
catch {global no_limits}
catch {global no_web}
catch {global no_mail}
catch {global no_relay}
catch {global admin_priv}
catch {global allpriv}
catch {global returnstatus}
catch {global mysql_host}
catch {global mysql_port}
catch {global mysql_database}
catch {global mysql_user}
catch {global mysql_pass}
catch {global configs}
catch {global servicedir}
catch {global controldir}
catch {global help_url}
catch {global initialdir}
catch {global bgColor}
catch {global menubarcolor}
catch {global Description}
catch {global mailcheck}
catch {global textcolor}
catch {global userList1}
catch {global userList2}
catch {global userLimit}
