#!/bin/sh
set -x
rcsflag=0
make clean
make distclean
ver=1.05
if [ -d RCS ] ; then
	rcsflag=1
	mv RCS ../RCStinydnssec
fi
cd ..
tar cf - tinydnssec-$ver |gzip -c > /usr/local/src/indimail/rpmbuild/SOURCES/tinydnssec-$ver.tar.gz
cd tinydnssec-$ver
if [ $rcsflag -eq 1 ] ; then
	mv ../RCStinydnssec ./RCS
fi
rpmbuild -bb tinydnssec.spec
