.TH dnsgetroot

.SH NAME
dnsgetroot

.SH SYNOPSIS
\fBdnsgetroot\fR


.SH DESCRIPTION
\fBdnscache\fR(8) begins searching from the top of the Domain Name System, with the DNS root servers.
These root servers (there are presently 13 of them) are sort of like the root node of a B-Tree database,
pointing to other DNS servers, which in turn point to still others, until a DNS server authoritative for
the domain of interest is found.

\fBdnscache\fR(8) maintains a list of the root servers it queries in the file named /service/dnscache/root/servers/@.
This file is created by \fBdnscache\-conf\fR(8), and incorporates whatever IP addresses it finds at the time in the
two files /etc/dnsroots.local and /etc/dnsroot.global.

.EX
198.41.0.4
128.9.0.107
192.33.4.12
128.8.10.90
192.203.230.10
192.5.5.241
192.112.36.4
128.63.2.53
192.36.148.17
198.41.0.10
193.0.14.129
198.32.64.12
202.12.27.33
.EE

Internet root servers are not static, however. They do change from time to time, and the root servers installed by
the tinydnssec distribution may no longer be current. dnscache will still work, because --so far-- the old servers are
running in parallel with the new servers. But this won't continue indefinitely, and it is a good idea to update the
root servers to the current set. dnsgetroot(1) updates the file /etc/indimail/dnsroots.global. It also updates
/service/dnscache/root/servers/@ with the contents of /etc/indiail/dnsroots.local and /etc/indimail/dnsroots.global

For a current listing of DNS root servers, you can also ftp the file named.root from InterNIC:

.EX
 $ ftp ftp://ftp.internic.net/domain/named.root
.EE

.SH See Also
dnscache(8),
dnscache-conf(8)
