.TH pickdns-data 8

.SH NAME
pickdns-data \- Data tool for pickdns

.SH DESCRIPTION

pickdns-data reads local IP addresses from a file named \fIdata\fR in the current directory.It creates \fIdata.cdb\fR in a
binary format designed for fast access by pickdns(8).It may also create some other files with names beginning with \fIdata\fR.

pickdns-data updates \fIdata.cdb\fR atomically, so you can use it safely while pickdns(8) is running. If anything goes
wrong with the creation of \fIdata.cdb\fR, pickdns-data stops and leaves the old \fIdata.cdb\fR in place.

.SH Data Format

+\fIfqdn\fR:\fIip\fR

The domain name \fIfqdn\fR has IP address \fIip\fR. You can list as many as 128 IP addresses for the same name.

-\fIfqdn\fR:\fIip\fR

This type of line is used by programs that automatically edit data to temporarily exclude addresses of overloaded or
dead machines.The line is ignored.

#\fIcomment\fR

Comment line. The line is ignored.

.SH SEE ALSO
pickdns(8)

http://cr.yp.to/djbdns.html
