.TH random-ip 1

.SH NAME
random-ip \- generate random IP addresses


.SH SYNOPSIS
\fBrandom\-ip\fR [\fIcount\fR] [\fIi1\fR] [\fIi2\fR] [\fIi3\fR] [\fIi4\fR]

.SH DESCRIPTION
\fBrandomip\fR(1) is a simple tool to generate specified number of random IP addresses.
By default it generates 10,000 of them. One can specify how many IP addresses to
generate followed by the first, second and third byte of the IP address. If you
specify the fourth byte, it will just print the single IP address

.EX
$ random-ip 10 15 12 6
15.12.6.134
15.12.6.67
15.12.6.179
15.12.6.58
15.12.6.55
15.12.6.88
15.12.6.139
15.12.6.114
15.12.6.167
15.12.6.180

$ random-ip 10 15 12 6 1
15.12.6.1
.EE

