.TH cdbgetm 1
.SH NAME
cdbgetm \- search for multiple records matching a key in cdb

.SH SYNOPSIS
\fBcdbgetm\fR \fIk\fR

.SH DESCRIPTION
\fBcdbgetm\fR searches for all records with key \fIk\fR in a constant database. The constant
database must be readable (and seekable) on \fBcdbgetm\fR's standard input.

Normally \fBcdbgetm\fR prints the data in the first record with key \fIk\fR and exits 0. If
there is no record with the key \fIk\fR, \fBcdbgetm\fR exits 100 without printing anything.

If \fBcdbgetm\fR encounters a read error, write error, or database format error, it complains
and exits 111.

.SH SEE ALSO
cdbget(1), cdbmake(1), cdbdump(1)
