.TH greylist 3
.SH NAME
greylist \- query \fBqmail-greyd\fR for greylisted records
.SH SYNTAX
.B #include <tlsacheck.h>

int  \fBgreylist\fP(char *\fIip\fR, char *\fIclient_ip\fR, char *\fIfrom\fR, char *\fItolist\fR, int \fIlen\fR, void (*\fItimeoutfn\fR)(), void (*\fIerrfn\fR)());

.SH DESCRIPTION
\fBgreylist()\fR connects to \fBqmail-greyd\fR(8) - greylisting daemon
to query, on the IP address \fIip\fR, to query greylisting records for emails
from IP address \fIclient_ip\fR. It uses the triplets of
IP address / sender / recepient sender.
It uses UDP to send the triplet and expects a two byte response. Clients
like \fBqmail-smtpd\fR(8) can use this function to enforce greylisting
protocol. The default port to which \fIgreylist\fR() connects is 1999.
IP address can also be of the form \fIip\fR@\fIport\fR, to specify an
alternate port.

The arguments \fItimeoutfn\fR should be a user defined function to handle
timeouts. The default timeout is 10 seconds, but can be changed by setting
the GREYTIMEOUT environment variable.

.SH "RETURN VALUE"
\fBgreylist\fR returns 1 if the sender triplet records have been
greylisted / whitelisted, 0 if greylisting verification fails

.SH "SEE ALSO"

qmail-smtpd(8), qmail-greyd(8), greydaemon(8)
