.TH rot 1
.SH NAME
rot \- Encruypt/Decrypt using rot13

.SH SYNOPSIS
.BR rot

.SH DESCRIPTION
.B rot

(Accept standard input)

.SH DESCRIPTION
rot performs ROT13 encryption/decryptin from the standard input into the standard
output. Note that it only handles ASCII properly.

.SH OPTIONS
All options are ignored

.SH SEE ALSO
fortune(1), strfile(1), unstr(1), randstr(1)
