'\" t
.\"     Title: unicode::iconvert::tou
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 03/11/2017
.\"    Manual: Courier Unicode Library
.\"    Source: Courier Unicode Library
.\"  Language: English
.\"
.TH "UNICODE::ICONVERT::T" "3" "03/11/2017" "Courier Unicode Library" "Courier Unicode Library"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
unicode::iconvert::tou \- template for converting text sequence to unicode
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <courier\-unicode\&.h>
.fi
.ft
.HP \w'output_iter_t\ convert('u
.BI "output_iter_t convert(input_iter_t\ " "beg_iter" ", input_iter_t\ " "end_iter" ", const\ std::string\ &" "charset" ", bool\ &" "errflag" ", output_iter_t\ " "output_iter" ");"
.HP \w'bool\ convert('u
.BI "bool convert(input_iter_t\ " "beg_iter" ", input_iter_t\ " "end_iter" ", const\ std::string\ &" "charset" ", std::u32string\ &" "out_buf" ");"
.HP \w'std::pair<std::u32string,\ bool>\ convert('u
.BI "std::pair<std::u32string, bool> convert(const\ std::string\ &" "text" ", const\ std::string\ &" "charset" ");"
.SH "DESCRIPTION"
.PP
These template functions convert text in a given character set to unicode characters\&.
\fIbeg_iter\fR
and
\fIend_iter\fR
define an input sequence of
chars in the
\fIcharset\fR
character set\&. They get converted to unicode characters\&.
\fIoutput_iter\fR
is an output iterator that
\fBconvert\fR() iterates over
char32_ts\&.
\fBconvert\fR() returns the value of the output iterator after iterating over the converted character sequence\&.
\fIerrflag\fR, passed by reference, gets set to
true
if some character could not be converted to unicode, from the specified character set, and
false
if the conversion completed without errors\&.
.PP
An overloaded
\fBconvert\fR() puts the unicode character sequence into a vector of
char32_ts, instead of an output sequence, and returned the error flag\&. Finally, a single
std::string
specifies the character string, instead of a beginning and an ending iterator, and returns a
std::pair
with the converted unicode text in a vector, and the error flag\&.
.SH "SEE ALSO"
.PP
\fBcourier-unicode\fR(7),
\fBunicode::convert::convert\fR(3),
\fBunicode_convert\fR(3),
\m[blue]\fB\fBiconv\fR(3)\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
Author
.RE
.SH "NOTES"
.IP " 1." 4

	      \fBiconv\fR(3)
.RS 4
\%http://manpages.courier-mta.org/htmlman3/iconv.3.html
.RE
