.TH 822print 1
.SH NAME
822print \- print a mail message
.SH SYNOPSIS
.B 822print
.SH DESCRIPTION
.B 822print
reads an 822-format mail message from its standard input,
and converts the header to an easier-to-read format.
It uses the standard
.B nroff
codes for boldface and underline.
.SH "SEE ALSO"
822field(1),
822date(1),
822received(1),
less(1)
