.TH printforward 1
.SH NAME
printforward \- print the instructions in a forwarding database
.SH SYNOPSIS
.B printforward
.SH DESCRIPTION
.B printforward
reads a forwarding database from its standard input
and prints all the forwarding instructions
in a format accepted by
.BR setforward .
.SH "SEE ALSO"
fastforward(1),
newaliases(1),
printmaillist(1),
setforward(1)
