.TH BASE64 "1" "User Commands"
.SH NAME
qbase64 \- base64 encode/decode data and print to standard output
.SH SYNOPSIS
.B qbase64
[\fIOPTION\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
Base64 encode or decode standard input, to standard output.
.TP
\fB\-d\fR
Decode data.
.TP
\fB\-i\fR
When encoding, ignore line terminating newline character.
.PP
The data are encoded as described for the base64 alphabet in RFC 3548.
When decoding, the input may contain newlines in addition to the bytes of
the formal base64 alphabet.  Use \fB\-i\fR to ignore the new line terminator
in the encoded stream.
.SH AUTHOR
Written by Manvendra Bhangui.
.SH "REPORTING BUGS"
Report qbase64 bugs to indimail\-support@lists.sourceforge.net
.br
IndiMail home page: <http://www.indimail.org/>
