.TH queue-fix 8
.SH NAME
queue-fix \- Create or Repair a qmail queue structure
.SH SYNOPSIS
.B queue-fix
.I [-i]
.I [-N]
.I [-v]
.I queue_dir

.SH DESCRIPTION
\fBqueue-fix\fR is a small utility for checking and repairing the qmail queue
structure.  It will fix uid/gid settings and permissions. It will
rename the message files to match their inodes. It will even create
directories and files that don't exist that should be there (you can
even create a queue from scratch). It will also print warnings for
any files it finds that should not exist.

.SH OPTIONS
.TP
\fB-i\fR
Interactive mode
.TP
\fB-N\fR
Test mode
.TP
\fB-v\fR
Verbose mode
.TP
\fBqueue_dir\fR
Directory where the qmail queue stucture is created. This directory has the subdirectories
bounce, info, intd, local, lock, mess, pid, remote, todo, yanked.

.SH "SEE ALSO"
svctool(8), qmail-queue(8), qmail-multi(8)

.SH AUTHOR
Eric Huss
