.TH spipe 1
.SH NAME
spipe \- supervise an pipeline of commands
.SH SYNOPSIS
.B spipe
.I dir1 dir2 ...
.SH DESCRIPTION
.B spipe
is designed for the purpose of allowing supervise to manage a complete
pipeline of commands.
.B spipe
executes supervise on all of the named directories, inserting a pipe
between each pair of supervised processes.
The supervise processes are started from last to first, to ensure that
each producer of output has a consumer to pipe its data to.
If
.B spipe
is sent either the
.IR INT ,
.IR QUIT ,
or the
.I TERM
signal, it runs
.B svc -dx
on each command to shut it down, and waits for it to exit.
The processes are shut down from first to last, to ensure that each
producer stops writing its output before shutting down the corresponding
consumer.
.SH RETURN VALUE
Exits 0 when all the commands are shut down.
If a fatal error is encountered, it exits.
.SH SEE ALSO
supervise, svscan
