.TH xqp 1
.SH NAME
xqp \- locate a message given its qp
.SH SYNTAX
.B xqp
.I qp
.SH DESCRIPTION
.B xqp
reads message lines and delivery lines printed by
.BR matchup .
It prints the lines that involve messages with long-term queue identifier
.IR qp .

Long-term queue identifiers are not permanent identifiers.
They are based on process IDs;
15-bit process IDs can easily wrap around in less than an hour on a busy system.
.SH "SEE ALSO"
matchup(1)
