.TH xrecipient 1
.SH NAME
xrecipient \- locate all deliveries to one recipient
.SH SYNTAX
.B xrecipient
.I channel.recipient
.SH DESCRIPTION
.B xrecipient
reads message lines and delivery lines printed by
.BR matchup .
It prints the delivery lines that involve messages sent to
.IR channel.recipient .
.SH "SEE ALSO"
matchup(1)
