.TH iftoccfrom 1
.SH NAME
iftoccfrom \- 
.SH SYNOPSIS
.B iftoccfrom
[ 
.I addr ...
] where
.I addr
is an email address
.SH DESCRIPTION
.B iftoccfrom
reads an 822-format message from standard input and exits 0 if $RECIPIENT is listed in a
To, Cc, or From field, and exits 100 otherwise. If one or more addr is present, then 
.B iftoccfrom
ignores $RECIPIENT, and uses each 
.I addr
instead.

If it encounters a temporary error while reading input, 
.B iftoccfrom
exits 111.

For example, the .qmail line

   | condtomaildir dir iftoccfrom afriend

writes correspondence with afriend to dir. 
