#!/bin/sh
set -x
rcsflag=0
make clean
make distclean
ver=1.0
if [ -d RCS ] ; then
	rcsflag=1
	mv RCS ../RCSdanetlsa
fi
cd ..
tar cf - danetlsa-$ver |gzip -c > /usr/local/src/indimail/rpmbuild/SOURCES/danetlsa-$ver.tar.gz
cd danetlsa-$ver
if [ $rcsflag -eq 1 ] ; then
	mv ../RCSdanetlsa ./RCS
fi
rpmbuild -bb danetlsa.spec
