.LL 8i
.TH vserverinfo 1
.SH NAME
vserverinfo \- Display server info of a node in a IndiMail cluster

.SH SYNOPSYS
\fBvserverinfo\fR [\fIoptions\fR] | [\fIemail_addr\fR]

.SH DESCRIPTION
\fBvserverinfo\fR can display server information for a node in an extended IndiMail cluster.
In one form of usage of \fBvserverinfo\fR, one can either provide the domain and - either the
mailstore \fIhost\fR or MySQL \fIserver\fR. In the second form of usage, one can provide an
email address of a user present in the node in a extended IndiMail cluster.
.PP
\fBvserverinfo\fR displays following information for a user specified by email \fIemail_addr\fR.
.TS
l l.
Field    | Description
_
domain   | domain name
server   | MySQL server holding user records
mdahost  | Mailstore for the user
user     | user's name
password | user's password
port     | MySQL port
database | MySQL database
.TE

\fBvserverinfo\fR can be run only by \fIroot\fR or \fIindimail\fR user.

.SH OPTIONS
\fBvserverinfo\fR can be used in two forms. In the first form, you can specify the domain
and the mailstore (or MySQL server). In the second form, if you specify an email id, and
\fBvserverinfo\fR will display the mailstore on which the user's Maildir is located and
also display the corresponding MySQL server.
.PP
.TP 4
\fB\-a\fR
Display all fields, this is the default
.TP 4
\fB\-u\fR
Display the user name
.TP 4
\fB\-p\fR
Display the user password
.TP 4
\fB\-P\fR
Display the MySQL port
.TP 4
\fB\-s\fR
Display the MySQL server
.TP 4
\fB\-m\fR
Display the user mailstore
.TP 4
\fB\-d\fR
Display the MySQL database
.TP 4
\fB\-D\fR \fIdomain\fR
specify the domain name
.TP 4
\fB\-M\fR \fImdahost\fR
specify the mailstore
.TP 4
\fB\-S\fR \fIserver\fR
specify the MySQL server

.SH RETURN VALUE
0 in case of success, 1 in case of any failure retrieving server information.

.SH "SEE ALSO"
vdominfo(1),
vuserinfo(1),
printdir(1)
