.LL 8i
.TH hostcntrl 8
.SH NAME
hostcntrl \- add, modify, delete hostcntrl entries

.SH SYNOPSYS
\fBhostcntrl\fR [\fIoptions\fR] \fIEmailID\fR

.SH DESCRIPTION
\fBhostcntrl\fR is meant for listing, adding, deleting, modifying user records in the
hostcntrl table for a clustered setup. This is especially useful when you may move a user
from one host to another host in a clustered setup.

.SH OPTIONS
.TP
\fB\-v\fR
Sets verbose operation
.TP
\fB\-s\fR
Shows records pertaining to EmailID in the hostcntrl table.
.TP
\fB\-i\fR
Inserts records in the hostcntrl database. Additional argument hostid has to be given to the -i option.
.TP
\fB\-m\fR
Modifies the hostid field for the given EmailID.
.TP
\fB\-d\fR
Deletes the record for the given EmailID.
.TP
\fIEmailID\fR
The Email ID for the user.

.SH RETURN VALUE
0 for success, 1 for any failure.

.SH "SEE ALSO"
vsmtp(8), vhostid(8), dbinfo(8), IndiMail(7)
