.LL 8i
.TH vacation 8
.SH NAME
vacation - auto responder for virtual domain user

.SH SYNOPSYS
\fBvacation\fR [\fIemail_addr\fR] [\fIvacation_mesg_file\fR]

.SH DESCRIPTION
.PP
\fBvacation\fR implements auto reply for virtual domain users. Without any arguments, the
only usage is in .qmail files or as a valias with valias_line as 

 '| /var/indimail/bin/vacation'

When arguments \fIemail_addr\fR and \fIvacation_mesg_file\fR is specified, autoresponder
is setup for user specified by \fIemail_addr\fR in the user's .\fIqmail\fR (dot-qmail) file.

\fBvacation\fR uses the environment variable CHARSET to set the charset.

.SH OPTIONS
.PP
.TP
\fIemail_addr\fR
Fully qualified email address for a virtual domain user.
.TP
\fIvacation_mesg_file\fR
A file containing the text for auto reply. If the filename is '-' (hyphen), any existing auto-reply is removed for the user. If the filename is '+' (plus sign), the text for auto-reply is taken from STDIN.

.SH RETURN VALUE
0 if successful, non-zero for any failure. Diagnostics are printed on STDOUT.

.SH "SEE ALSO"
autoresponder(1), vmoduser(1), vdelivermail(8), dot-qmail(5)
