.LL 8i
.TH chowkidar 8
.SH NAME
chowkidar \- SPAM Guard for IndiMail

.SH SYNOPSYS
.PP
badmailfrom usage
 \fBchowkidar\fR [\fB\-V\fR] [\fB\-f\fR \fIfilename\fR] [\fB\-b\fR \fIbadmailfrom\fR] [\fB\-B\fR] -n\fR \fIcount\fR
 \fBchowkidar\fR [\fB\-r\fR] [\fB\-V\fR] [\fB\-v\fR] \fB\-q\fR [\fB\-b\fR \fIbadmailfrom\fR]
.PP
badrcptto usage
 \fBchowkidar [\fB\-V\fR] [\fB\-f\fR \fIfilename\fR] [\fB\-t\fR \fIbadrcptto\fR] [\fB\-T] \fB\-n\fR \fIcount\fR
 \fBchowkidar [\fB\-r\fR] [\fB\-V\fR] [\fB\-v\fR] \fB\-q\fR [\fB\-t\fR \fIbadrcptto\fR]
.PP
spamdb usage
 \fBchowkidar\fR [\fB-V\fR] [\fB-f\fR \fIfilename\fR] [\fB-s\fR \fIspamdb\fR] [\fB-S\fR] \fB-n\fR \fIcount\fR
 \fBchowkidar\fR [\fB-r\fR] [\fB-V\fR] [\fB-v\fR] \fB-q\fR [\fB-s\fR \fIspamdb\fR]

.SH DESCRIPTION
\fBchowkidar\fR is a utility to help detect potential spammers by counting senders or
recipients in \fBqmail-send\fR's deliver log file. The name is derived from the language Hindi,
which means 'guard'. It looks for either of the following two entries in the \fBqmail-send\fR's
log file.

 @400000003d95f1d71571b154 info msg 181462: bytes 403 from <root@indimail.org> qp 8087 uid 0
 @400000003d95f1d71571b155 starting delivery 145: msg 523306 to local manny@technology.indimail.org

chowkidar has two modes of operation

.nr step 1 1
.IP \n[step] 3
build mode – The first form of usage in synopsis shown above.
.IP \n+[step]
synchronize mode – The second form of usage in synopsis shown above.
.PP
In build mode, chowkidar maintains a hash table and keeps on incrementing the count against
each sender found in the log file. After reading the log file completely, it prints out on
stderr, the spammer's email id and count of mails received from the spammer. The default output
file is the control file 'badmailfrom'.  This can be either changed by the BADMAILFROM
environment variable or by the '-b' option. The '-b' option overrides the environment variable.
If the output file is the qmail's badmailfrom control file, it appends the spammer's email id
to the file. If the output file is anything other than 'badmailfrom', the count of emails
against the spammer is also appended to the file. Entries already present in the control
files 'badmailfrom' and 'spamignore' are ignored and not maintained in the hash table.
The entries in 'spamignore' can have shell wild cards for pattern matching.  If an entry starts
with a '@' sign, all emails from the domain following the '@' sign will be ignored and not be
treated as spammers. The hash table has a fixed compile time size of 5000, which can be changed
by defining the ENVIRONMENT variable MAXADDR.
.PP
In synchronize mode, chowkidar synchronizes the contents of the badmailfrom file with a master
copy maintained on hostcntrl. It updates the master copy with entries  which are more recent
in the badmailfrom file. It also updates the badmailfrom file with entries which are more
recent in the master copy. The master copy is the table 'badmailfrom' if the filename is
badmailfrom; and the table 'spam' if the filename is anything other than badmailfrom.
The default badmailfrom file is "badmailfrom" which can be changed by setting the '-b'
option. This mode allows multiple hosts to synchronize their copies of badmailfrom with a
central master copy and also replicate changes across all participating hosts running
chowkidar.
.PP
The same logic applies to badrcptto control file. Except that '-b' gets replaced with '-t'
and '-B' gets replaced with '-T'. In this case, count is done against the recipients. The
default file 'badrcptto' can be changed by the '-t' option. 
.PP
The same logic applies to spamdb control file. Except that '-b' gets replaced with '-s'
and '-B' gets replaced with '-S'. In this case, count is done against the recipients. The
default file 'spamdb' can be changed by setting the  '-s' option.

Administrators can set up chowkidar in cron(1) to undertake automated anti-spam measures.
Depending on the qmail-send's log file generation rate, the frequency can be every 30 min
for a light system, every 2 hours for a medium system and every 4-6 hours for a heavy system.
For a heavy system, remember to set the MAXADDR environment variable appropriately before
running chowkidar. i.e. If the incoming rate is around 1 million mails/day and you are running
chowkidar every 6 hrs, set MAXADDR to 250000 (mail_count_per_day * frequency / 24). The tool
is especially useful if you are running multiple hosts and you want a spammer detected on any
one of the hosts to be reflected on all hosts (synchronize mode of operation).

.SH OPTIONS 
.PP
.TP
\fB\-v\fR
Sets verbose option
.TP
\fB\-V\fR
Display Version Number\fR
.TP
\fB\-f\fR \fIfilename\fR
The qmail SMTP/deliver log file. If not given, the file defaults to stdin.
.TP
\fB\-b\fR \fIoutput_file\fR
file in badmailfrom format. If not given, the environment variable BADMAILFROM is used. If the
environment variable is also not defined, the badmailfrom file defaults to the qmail control
file 'badmailfrom'. Input should be qmail-send log file.
.TP
\fB\-B\fR
If '-b' option is not used, this can be set to indicate badmailfrom format. Additionaly
\fBchowkidar\fR will cd to qmail's control directory.
.TP
\fB\-t\fR \fIoutput_file\fR
file in badrcptto format. If not given, the environment variable BADRCPTTO is used. If the
environment variable is also not defined, the badrcptto file defaults to the qmail control
file 'badrcptto'. Input should be qmail-send log file.
.TP
\fB\-T\fR
If '-t' option is not used, this can be set to indicate badrcptto format. i.e. recipients are
to be blocked (spammers generally get lot of bounces). A socially responsible ISP for example
can use this option to prevent their own users from spamming. Additionaly
\fBchowkidar\fR will cd to qmail's control directory.
.TP
\fB\-s\fR \fIoutput_file\fR
Input should be qmail-smtpd log file. The output file will be spamdb. Additionally, qmail-cdb
will be run to create spamdb.cdb.
.TP
\fB\-S\fR
If '-s' option is not used, this can be set to indicate spamdb format. In this option,
\fBchowkidar\fR does cd to qmail's control directory.
.TP
\fB\-n\fR \fIcount\fR
Mail count from senders - above which the sender should be treated as a spammer.
.TP
\fB\-r\fR
Synchronize mode of operation. This mode synchronizes local badmailfrom/badrcptto/spamdb file with a master copy maintained on hostcntrl.
.TP
\fB\-q\fR
quiet mode. This mode will not display the list of spammers on stderr.

RETURN VALUE
Returns 0 for success, 1 for any failure.
