name: Ubuntu, Mac OSX CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main

    - name: install_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
      
    - name: Darwin
      run: if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl; brew link --force openssl; ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
      env:
        OS: ${{ matrix.host }}

    - name: configure_qmail
      run: cd libqmail;./default.configure; make; sudo make install-strip

    - name: configure_indimail-mta
      run: cd main/indimail-mta-x; ./default.configure; ./qmake
    - name: configure_ucspi-tcp
      run: cd main/indimail-ucspi-tcp; ./default.configure; ./qmake
    - name: configure_daemontools
      run: cd main/indimail-daemontools; ./default.configure; ./qmake
