name: daemontools FreeBSD CI

on:
  push:
    paths:
      - '**/daemontools-x/**'
      - .github/workflows/daemontools-freebsd.yml
      - '!**/daemontools-x/debian/*'
      - '!**/daemontools-x/daemontools.spec.in'
      - '!**/daemontools-x/*.9'
      - '!**/daemontools-x/*.8'
      - '!**/daemontools-x/*.1'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build daemontools
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y automake autoconf libtool pkgconf libidn2
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/daemontools-x; ./default.configure; ./qmake
