name: daemontools obs CI

on:
  push:
    branches:
      - master
    paths:
      - '**/daemontools-x/**'
      - .github/workflows/daemontools-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/*.freebsd.yml'
      - '!**/*.c-cpp.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_main
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; ./prepare_obs daemontools
    - uses: actions/upload-artifact@v2
      with:
        name: daemontools
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.daemontools_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
