name: FreeBSD

on: [push]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: install indimail-mta
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/libdkim-x; ./default.configure; make; make install-strip
          cd ../libsrs2-x; ./default.configure; make; make install-strip
          cd ../ucspi-tcp-x; ./default.configure; make; make install
          cd ../daemontools-x; ./default.configure; make; make install
          cd ../indimail-mta-x; ./default.configure; make; make install
