name: indimail-mta FreeBSD CI

on:
  push:
    paths:
      - '**/indimail-mta-x/**'
      - '**/libdkim-x/**'
      - '**/libsrs2-x/**'
      - .github/workflows/indimail-mta-freebsd.yml
      - '!**/indimail-mta-x/indimail-mta.spec.in'
      - '!**/libdkim-x/libdkim.spec.in'
      - '!**/libdkim-x/libsrs2.spec.in'
      - '!**/indimail-mta-x/debian/*'
      - '!**/libdkim-x/debian/*'
      - '!**/libsrs2-x/debian/*'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build indimail-mta
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf libidn2 mysql80-client openldap24-client
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/libdkim-x; ./default.configure; make; make install-strip
          cd ../libsrs2-x; ./default.configure; make; make install-strip
          cd ../indimail-mta-x; ./default.configure; ./qmake
