name: indimail-mta obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/indimail-mta-x/**'
      - .github/workflows/indimail-mta-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/*.freebsd.yml'
      - '!**/*.c-cpp.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_indimail-mta
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; cd indimail-mta-x; ./prepare_obs indimail-mta
    - uses: actions/upload-artifact@v2
      with:
        name: indimail-mta
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.indimail_mta_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
