name: indimail-mta NetBSD CI

on:
  push:
    paths:
      - '**/indimail-mta-x/**'
      - '**/libdkim2-x/**'
      - '**/libsrs2-x/**'
      - .github/workflows/indimail-mta-freebsd.yml
      - '!**/indimail-mta-x/indimail-mta.spec.in'
      - '!**/libdkim2-x/libdkim2.spec.in'
      - '!**/libsrs2-x/libsrs2.spec.in'
      - '!**/indimail-mta-x/qmail-perf/*'
      - '!**/indimail-mta-x/tests/*'
      - '!**/indimail-mta-x/debian/*'
      - '!**/libdkim2-x/debian/*'
      - '!**/libsrs2-x/debian/*'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: OpenBSD
    steps:
    - uses: actions/checkout@v3
      with:
        path: main
    - uses: actions/checkout@v3
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build indimail-mta
      id: OpenBSD
      uses: cross-platform-actions/action@v0.20.0
      with:
        operating_system: netbsd
        architecture: x86-64
        version: '9.3'
        host: ubuntu-latest
        run: |
          sudo pkg install -y curl automake autoconf libtool pkgconf libidn2 mysql80-client openldap26-client libgsasl base64
          cd libqmail; ./default.configure; make; sudo make install-strip
          cd ../main/libdkim2-x; ./default.configure; make; sudo make install-strip
          cd ../libsrs2-x; ./default.configure; make; sudo make install-strip
          cd ../indimail-mta-x; ./default.configure; ./qmake
