name: indimail-mta Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/indimail-mta-x/**'
      - '**/libdkim2-x/**'
      - '**/libsrs2-x/**'
      - .github/workflows/indimail-mta-c-cpp.yml
      - '!**/indimail-mta-x/indimail-mta.spec.in'
      - '!**/libdkim2-x/libdkim2.spec.in'
      - '!**/libsrs2-x/libsrs2.spec.in'
      - '!**/indimail-mta-x/qmail-perf/*'
      - '!**/indimail-mta-x/tests/*'
      - '!**/indimail-mta-x/debian/*'
      - '!**/libdkim2-x/debian/*'
      - '!**/libsrs2-x/debian/*'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install libmysqlclient-dev libc6 libc6-dev libgsasl7-dev; fi
        if [ "${OS}" = "ubuntu-22.04" ] ; then sudo apt-get install libmysqlclient-dev libc6 libc6-dev libgsasl-dev; fi
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig openssl mysql gsasl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_indimail-mta
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" make; sudo make install-strip
    - name: install_libdkim2
      run: cd main/libdkim2-x; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" make; sudo make install-strip
    - name: install_libsrs2
      run: cd main/libsrs2-x; ./default.configure; make; sudo make install-strip
    - name: build_indimail-mta
      run: cd main/indimail-mta-x; env CFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" ./default.configure; env CFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.1/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.1/lib" ./qmake
