name: indimail-mta Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/indimail-mta-x/**'
      - '**/libdkim-x/**'
      - '**/libsrs2-x/**'
      - .github/workflows/indimail-mta-c-cpp.yml
      - '!**/indimail-mta-x/indimail-mta.spec.in'
      - '!**/libdkim-x/libdkim.spec.in'
      - '!**/libdkim-x/libsrs2.spec.in'
      - '!**/indimail-mta-x/debian/*'
      - '!**/libdkim-x/debian/*'
      - '!**/libsrs2-x/debian/*'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macOS-10.15]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install libc6 libc6-dev; fi
        if [ "${OS}" = "macOS-10.15" ] ; then brew install automake autoconf libtool pkgconfig openssl; fi
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_indimail-mta
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make; sudo make install-strip
    - name: install_libdkim
      run: cd main/libdkim-x; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make; sudo make install-strip
    - name: install_libsrs2
      run: cd main/libsrs2-x; ./default.configure; make; sudo make install-strip
    - name: build_indimail-mta
      run: cd main/indimail-mta-x; env CFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./qmake
