name: indimail-mta FreeBSD CI

on:
  push:
    paths:
      - '**/indimail-mta-x/**'
      - '**/libdkim2-x/**'
      - '**/libsrs2-x/**'
      - .github/workflows/indimail-mta-freebsd.yml
      - '!**/indimail-mta-x/indimail-mta.spec.in'
      - '!**/libdkim2-x/libdkim2.spec.in'
      - '!**/libsrs2-x/libsrs2.spec.in'
      - '!**/indimail-mta-x/qmail-perf/*'
      - '!**/indimail-mta-x/tests/*'
      - '!**/indimail-mta-x/debian/*'
      - '!**/libdkim2-x/debian/*'
      - '!**/libsrs2-x/debian/*'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    timeout-minutes: 60 # randomly bootloops https://github.com/vmactions/freebsd-vm/issues/74
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build indimail-mta
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf libidn2 mysql80-client openldap26-client libgsasl base64
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/libdkim2-x; ./default.configure; make; make install-strip
          cd ../libsrs2-x; ./default.configure; make; make install-strip
          cd ../indimail-mta-x; ./default.configure; ./qmake
