name: libdkim Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/libdkim-x/**'
      - .github/workflows/libdkim-c-cpp.yml
      - '!**/libdkim-x/debian/*'
      - '!**/libdkim-x/libdkim.spec.in'
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: extra_packages
      run: if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_libdkim
      uses: actions/checkout@v2
      
    - name: build_libdkim
      run: cd libdkim-x; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make
