name: libdkim FreeBSD CI

on:
  push:
    paths:
      - '**/libdkim-x/**'
      - .github/workflows/libdkim-freebsd.yml
      - '!**/libdkim-x/debian/*'
      - '!**/libdkim-x/libdkim.spec.in'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: build libdkim
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf libidn2
        run: cd libdkim-x; ./default.configure; make
