name: libdkim FreeBSD CI

on:
  push:
    branches:
      - master
    paths:
      - '**/libdkim-x/**'
      - .github/workflows/libdkim-freebsd.yml
      - '!**/libdkim-x/debian/*'
      - '!**/libdkim-x/libdkim.spec.in'
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: build libdkim
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf libidn2
        run: cd libdkim-x; ./default.configure; make
