name: libdkim2 Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/libdkim2-x/**'
      - .github/workflows/libdkim2-c-cpp.yml
      - '!**/libdkim2-x/debian/*'
      - '!**/libdkim2-x/libdkim2.spec.in'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_libdkim2
      uses: actions/checkout@v4

    - name: build_libdkim2
      run: cd libdkim2-x; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.6.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.6.0/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.6.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.6.0/lib" make
