name: libdkim obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/libdkim-x/**'
      - .github/workflows/libdkim-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/*.freebsd.yml'
      - '!**/*.c-cpp.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_libdkim
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; cd libdkim-x; ./prepare_obs libdkim
    - uses: actions/upload-artifact@v2
      with:
        name: libdkim
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.libdkim_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
