name: libsrs2 FreeBSD CI

on:
  push:
    paths:
      - '**/libsrs2-x/**'
      - .github/workflows/libsrs2-freebsd.yml
      - '!**/libsrs2-x/debian/*'
      - '!**/libsrs2-x/libsrs2.spec.in'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: build libsrs2
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf libidn2
        run: cd libsrs2-x; ./default.configure; make
