name: libsrs2 obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/libsrs2-x/**'
      - .github/workflows/libsrs2-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/*.freebsd.yml'
      - '!**/*.c-cpp.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_libsrs2
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; cd libsrs2-x; ./prepare_obs libsrs2
    - uses: actions/upload-artifact@v2
      with:
        name: libsrs2
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.libsrs2_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
