name: libsrs2 Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/libsrs2-x/**'
      - .github/workflows/libsrs2-c-cpp.yml
      - '!**/libsrs2-x/debian/*'
      - '!**/libsrs2-x/libsrs2.spec.in'
      - '!**/doc/*'
      - '!**.md'

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: extra_packages
      run: if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_libsrs2
      uses: actions/checkout@v2
      
    - name: build_libsrs2
      run: cd libsrs2-x; ./default.configure; make
