name: ucspi-tcp FreeBSD CI

on:
  push:
    branches:
      - master
    paths:
      - '**/ucspi-tcp-x/**'
      - .github/workflows/ucspi-tcp-freebsd.yml
      - '!**/ucspi-tcp-x/debian/*'
      - '!**/ucspi-tcp-x/ucspi-tcp.spec.in'
      - '!**/doc/*'
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build ucspi-tcp
      id: FreeBSD
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf libidn2
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/ucspi-tcp-x; ./default.configure; ./qmake
