name: ucspi-tcp Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/ucspi-tcp-x/**'
      - .github/workflows/ucspi-tcp-c-cpp.yml
      - '!**/ucspi-tcp-x/debian/*'
      - '!**/ucspi-tcp-x/ucspi-tcp.spec.in'
      - '!**/ucspi-tcp-x/*.1'
      - '!**/ucspi-tcp-x/*.9'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install libmysqlclient-dev libssl-dev; fi
        if [ "${OS}" = "macos-latest" ] ; then brew install automake autoconf libtool pkgconfig mysql openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_ucspi-tcp
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib" make; sudo make install-strip
    - name: build_ucspi-tcp
      run: cd main/ucspi-tcp-x;env CFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib" ./default.configure;env CFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib" ./qmake
