name: ucspi-tcp Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/ucspi-tcp-x/**'
      - .github/workflows/ucspi-tcp-c-cpp.yml
      - '!**/ucspi-tcp-x/debian/*'
      - '!**/ucspi-tcp-x/ucspi-tcp.spec.in'
      - '!**/ucspi-tcp-x/*.1'
      - '!**/ucspi-tcp-x/*.9'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "ubuntu-latest" ] ; then
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev libssl-dev
        fi
        if [ "${OS}" = "macos-latest" ] ; then
          brew install automake autoconf libtool pkgconfig mysql openssl
        fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_ucspi-tcp
      uses: actions/checkout@v4
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        if [ "${OS}" = "macos-latest" ] ; then
          # Dynamically fetch base paths for Homebrew dependencies
          OPENSSL_PREFIX=$(brew --prefix openssl@3)

          # Combine both paths cleanly into your compilation flags
          export CPPFLAGS="-I${OPENSSL_PREFIX}/include"
          export LDFLAGS="-L${OPENSSL_PREFIX}/lib"
        else
          # Standard flags for Ubuntu environment
          export CPPFLAGS="-I/usr/include/tirpc"
          export LDFLAGS=""
        fi
        cd libqmail
        ./default.configure
        make
        sudo make install-strip
      env:
        OS: ${{ matrix.host }}

    - name: build_ucspi-tcp
      run: |
        if [ "${OS}" = "macos-latest" ] ; then
          # Dynamically fetch base paths for Homebrew dependencies
          OPENSSL_PREFIX=$(brew --prefix openssl@3)

          # Combine both paths cleanly into your compilation flags
          export CPPFLAGS="-I${OPENSSL_PREFIX}/include"
          export LDFLAGS="-L${OPENSSL_PREFIX}/lib"
        else
          # Standard flags for Ubuntu environment
          export CPPFLAGS=""
          export LDFLAGS=""
        fi
        cd main/ucspi-tcp-x
        ./default.configure
        ./qmake
      env:
        OS: ${{ matrix.host }}
