name: ucspi-tcp obs trigger

on:
  push:
    branches:
      - master
    paths:
      - '**/ucspi-tcp-x/**'
      - .github/workflows/ucspi-tcp-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/*.freebsd.yml'
      - '!**/*.c-cpp.yml'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_ucspi-tcp
      uses: actions/checkout@v2

    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install curl; cd ucspi-tcp-x; ./prepare_obs ucspi-tcp
    - uses: actions/upload-artifact@v2
      with:
        name: ucspi-tcp
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        curl -H "Authorization: Token ${{secrets.ucspi_tcp_obs_token_value}}" -X POST https://build.opensuse.org/trigger/runservice
